### ISSUE TITLE
[Bug?] Parsing Issue - block of diamond < diamond block

### ISSUE THREAD

**Issue by MovesLikeJaeger** [SkriptLang/Skript#3683] opened 2021-01-09 05:08 UTC
**Description:**
Not sure if this is more related to SkBee - probably not
This is very easy to work around obviously, and I'm guessing it's probably already well known.
Code pretty much sums it up.

**Steps to Reproduce:**
```
on load:

#Crashes server:
#    register new shaped recipe for block of diamond using block of diamond, block of diamond, block of diamond, block of diamond, block of diamond, block of diamond, block of diamond, block of diamond and block of diamond with id "test" 

#Loads very fast:
    register new shaped recipe for diamond block using diamond block, diamond block, diamond block, diamond block, diamond block, diamond block, diamond block, diamond block and diamond block with id "test" 
```

**Errors / Screenshots:**
https://pastebin.com/BDKJXiWd

**Server Information:**
Paper 1.16.4
Skript 2.5.3
SkBee 1.9.1

**Comment by TPGamesNL** [comment] 2021-02-21 11:27
I recommend not making such long lines, the Skript parser is known to have issues with long lines of code. You could, for example, set a list variable to the ingredients of the recipe and use that in the recipe registration effect. Closing as a duplicate of https://github.com/SkriptLang/Skript/issues/3470

**Closed by TPGamesNL** 2021-02-21 11:27 UTC
