### ISSUE TITLE
Stacktrace when saving visual effects

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4719] opened 2022-04-08 10:25 UTC
### Skript/Server Version

```markdown
[06:23:40 INFO]: [Skript] Server Version: git-Purpur-1609 (MC: 1.18.2)
[06:23:40 INFO]: [Skript] Skript Version: 2.6.1
[06:23:40 INFO]: [Skript] Installed Skript Addons:
[06:23:40 INFO]: [Skript]  - skript-placeholders v1.5.2-nightly-2cc7f3f (https://github.com/APickledWalrus/skript-placeholders)
[06:23:40 INFO]: [Skript]  - skript-gui v1.3-beta2-nightly-e646705 (https://github.com/APickledWalrus/skript-gui)
[06:23:40 INFO]: [Skript]  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
[06:23:40 INFO]: [Skript]  - DiSky v4.0-alpha13
[06:23:40 INFO]: [Skript]  - skript-yaml v1.4
[06:23:40 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[06:23:40 INFO]: [Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[06:23:40 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[06:23:40 INFO]: [Skript] Installed dependencies:
[06:23:40 INFO]: [Skript]  - Vault v1.7.3-b131
```
```


### Bug Description

Throwing stacktrace to console when trying to save a visual effect.

### Expected Behavior

not to get stacktrace

### Steps to Reproduce

`!set {heart} to "heart" parsed as visual effect`
see console

### Errors or Screenshots

```
[06:05:00] [Server thread/ERROR]: #!#! Thread: Server thread
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Language: english
[06:05:00] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! End of Error.
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[06:05:00] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:05:00] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[06:05:00] [Server thread/ERROR]: #!#! Here is full list of them:
[06:05:00] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2-nightly-2cc7f3f (https://github.com/APickledWalrus/skript-placeholders) skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) skript-gui v1.3-beta2-nightly-e646705 (https://github.com/APickledWalrus/skript-gui) DiSky v4.0-alpha13 skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo) SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.4 BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK) 
[06:05:00] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[06:05:00] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[06:05:00] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[06:05:00] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[06:05:00] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[06:05:00] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Stack trace:
[06:05:00] [Server thread/ERROR]: #!#! java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:174)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:199)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:723)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:545)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:539)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:549)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:382)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:373)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Variable.set(Variable.java:463)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Variable.change(Variable.java:519)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:281)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53)
[06:05:00] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71)
[06:05:00] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[06:05:00] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[06:05:00] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.c(PlayerConnection.java:320)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.network.NetworkManager.a(NetworkManager.java:576)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1648)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:522)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1482)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1246)
[06:05:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[06:05:00] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Version Information:
[06:05:00] [Server thread/ERROR]: #!#!   Skript: 2.6.1 (latest)
[06:05:00] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[06:05:00] [Server thread/ERROR]: #!#!     Date: 22:18:42.554713200
[06:05:00] [Server thread/ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[06:05:00] [Server thread/ERROR]: #!#!   Minecraft: 1.18.2
[06:05:00] [Server thread/ERROR]: #!#!   Java: 17 (OpenJDK 64-Bit Server VM 17+35-2724)
[06:05:00] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-1160.el7.x86_64
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Server platform: Paper
[06:05:00] [Server thread/ERROR]: #!#! 
[06:05:00] [Server thread/ERROR]: #!#! Current node: null
[06:05:00] [Server thread/ERROR]: #!#! Current item: null
[06:05:00] [Server thread/ERROR]: #!#! 
```

### Other

_No response_

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-04-08 12:25
Duplicate of #4196

**Closed by AyhamAl-Ali** 2022-04-08 12:25 UTC
Labels: bug, priority: medium
