### ISSUE TITLE
Internal error while trying to execute this command.

### ISSUE THREAD

**Issue by oHeckGage** [SkriptLang/Skript#3198] opened 2020-07-23 22:05 UTC
### Description

I tried to make a /sell command and I got the error on multiple servers including my localhost test server and a Minehut server. I got the error on both servers, and I tried disabling my addons and still didn't work.

### Steps to Reproduce

https://pastebin.com/e5DVvhjP (Code)

### Expected Behavior

I wanted it to sell all the ores in the player's inventory by setting variables to the amount of that item in the player's inventory. Then, it would add them all together and add them to the temp. variable {_made} so I can send how much they made and then add that temp. variable to {m::%player%} (their balance's variable)

### Errors / Screenshots

https://prnt.sc/tniv8x

Console: https://gist.github.com/oHeckGage/9132dda272a506d5e410005e3172fed8

### Server Information

I've used a test server and Minehut:

MH: 1.16 TS: 1.16
MH Skript Version: 2.4.1MH (Idrk if that's the "real" version) TS Skript Version: 2.5-alpha6(rev1) and 2.4.1
(2.4.1 is the latest stable version)

**Comment by ShaneBeee** [comment] 2020-07-23 23:43
Duplicate of #2752

**Comment by ShaneBeee** [comment] 2020-07-23 23:43
err wait, I was thinking something wrong here.

**Comment by ShaneBeee** [comment] 2020-07-23 23:45
Please provide test results from our fork of Skript, not another persons fork.

**Comment by oHeckGage** [comment] 2020-07-24 01:05
Dunno what you mean, I got Skript.jar from github.com/SkriptLang/Skript/releases I think, am I supposed to download it from somewhere else?

**Comment by APickledWalrus** [comment] 2020-07-24 01:10
He meant if you could send the error report that you get using THIS fork, instead of Minehut’s.

**Comment by oHeckGage** [comment] 2020-07-24 01:22
Oh sure

**Comment by oHeckGage** [comment] 2020-07-24 01:25
https://gist.github.com/oHeckGage/4c763a6d740ce3400ffe1fa09dab1cc0

**Comment by APickledWalrus** [comment] 2020-07-24 01:31
Thanks! Your code should error, but for some reason it isn’t. I’m assuming you’re trying to find the total amount of those materials, so you should add them together instead of putting them in a list.

e.g. `set {_made} to {_iron} + {_gold} + ...`

I believe this is what you are trying to do 🙂

We will keep this issue open for now though since it is technically a bug

**Comment by oHeckGage** [comment] 2020-07-24 01:38
Yes it is what I wanted, I will see if that fixes it and see if there are errors!

**Comment by oHeckGage** [comment] 2020-07-24 01:43
Thanks! It works!

**Closed** 2020-10-22 23:22 UTC
Labels: bug, completed, priority: low
