### ISSUE TITLE
TPS drops in server.

### ISSUE THREAD

**Issue by NCSV** [SkriptLang/Skript#4526] opened 2022-01-26 04:06 UTC
### Skript/Server Version

```
Replace this text with your output from the command.
```
[13:02:57] [Server thread/INFO]: [Skript] 서버 버전: git-Purpur-1486 (MC: 1.18.1)
[13:02:57] [Server thread/INFO]: [Skript] Skript 버전: 2.6
[13:02:57] [Server thread/INFO]: [Skript] 설치??? Skript 애드온:
[13:02:57] [Server thread/INFO]: [Skript]  - Skellett v2.0.2 (https://forums.skunity.com/resources/skellett.24/)
[13:02:57] [Server thread/INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[13:02:57] [Server thread/INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[13:02:57] [Server thread/INFO]: [Skript]  - SkQuery v4.1.5
[13:02:57] [Server thread/INFO]: [Skript]  - ItemsAdder v2.5.5 (devs.beer)

### Bug Description

TPS drops 20 to 7 every minute for a moment,

### Expected Behavior

i think when skript send message to console, this problems was happend.

[12:58:56] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Purpur-1486 (MC: 1.18.1) ---
[12:58:56] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[12:58:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[12:58:56] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[12:58:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[12:58:56] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[12:58:56] [Paper Watchdog Thread/ERROR]: 	PID: 40 | Suspended: false | Native: false | State: WAITING
[12:58:56] [Paper Watchdog Thread/ERROR]: 	Stack:
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:938)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.concurrent.locks.ReentrantLock$Sync.lock(ReentrantLock.java:153)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:322)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.players.GameProfileCache.get(GameProfileCache.java:173)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_18_R1.CraftServer.getOfflinePlayer(CraftServer.java:1838)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1169)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:856)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:846)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.registrations.Classes.parseSimple(Classes.java:445)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.registrations.Classes.parse(Classes.java:474)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:579)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:795)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1414)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1337)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1410)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1337)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.lang.SkriptParser.parseArguments(SkriptParser.java:1023)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:271)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		Skript.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		GlobalExecute [Client].jar//me.ayushdev.globalexecute.GEClient.lambda$onMessage$0(GEClient.java:29)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		GlobalExecute [Client].jar//me.ayushdev.globalexecute.GEClient$$Lambda$10427/0x00000008021373c8.call(Unknown Source)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.run(CraftFuture.java:88)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1572)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:517)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1495)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$3992/0x0000000801482028.run(Unknown Source)
[12:58:56] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
[12:58:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[12:58:56] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[12:58:56] [Paper Watchdog Thread/ERROR]: ------------------------------

### Steps to Reproduce

			if arg 1 is "추천":
				if arg 2 is set:
					set {접속보상.추천.%arg 2%} to true
					send "&d%arg 2%&f님의 추천 변수가 적용되었습니다." to console

this is code related with TPS drops

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```
![1](https://user-images.githubusercontent.com/25452835/151102232-64dda0df-766a-4908-9214-edcf4f36b998.PNG)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by ZConnorZ** [comment] 2022-01-26 05:04
Maybe arg 2 is offline player? I also had problems with offline players in teams.

**Comment by TPGamesNL** [comment] 2022-01-26 11:41
Duplicate of https://github.com/SkriptLang/Skript/issues/4254

**Closed by TPGamesNL** 2022-01-26 11:41 UTC
