### ISSUE TITLE
Functions in Functions returning <none>

### ISSUE THREAD

**Issue by PrecedingxD** [SkriptLang/Skript#2275] opened 2019-07-21 01:48 UTC
Hello, I try to create a function in a function, when I try to create it, this is the code (sample skript which I know doesn't work; tried):

```
command /test [<text>]:
    trigger:
        test(player , arg 1)

function test(p: player, t: text):
    test2({_p}, {_t})

function test2(player: player , text: text):
    broadcast "%{_text}%"
```

When I use %{_text}%, it returns none.

![image](https://user-images.githubusercontent.com/49699421/61586004-a9acd680-ab2f-11e9-9e5a-77252485ca0f.png)

**Yes, I added an argument in the command.**

![image](https://user-images.githubusercontent.com/49699421/61586044-630bac00-ab30-11e9-83e0-2cc0c9ff5dbb.png)

![image](https://user-images.githubusercontent.com/49699421/61586048-74ed4f00-ab30-11e9-8cd3-9a6ff63a4940.png)

**Comment by bensku** [comment] 2019-07-21 11:54
Use latest release for testing. Can't reproduce with it.

**Comment by NebuSensei** [comment] 2019-07-21 15:06
it's working like that (2.4 skript)(1.4.4 minecraft {paper})
```
function test2(player: player , text: text):
    broadcast "%{_text}%"

function test(p: player, t: text):
    test2({_p}, {_t})

command /test [<text>]:
    trigger:
        test(player , arg-1)
```

**Comment by michal12sk** [comment] 2019-07-21 16:37
I'm having the same issues on 2.4-beta3.
If I run a command with the same lines(ofc edited for a function) as a function, it returns what I'm expecting but a function returns <none>.

**Comment by Wealthyturtle** [comment] 2019-09-23 11:11
Unable to replicate with 2.4-beta3 and 2.4-beta7... if anything, it's probably fixed by the latest function changes

**Comment by Wealthyturtle** [comment] 2019-11-17 13:14
I can replicate what @michal12sk is saying by using
```
command /test [<text>]:
    trigger:
        test(player , arg 1)

function test(p: player, t: text):
    test2({_p}, {_t})

function test2(player: player , text: text):
    broadcast {_text} #If text is <none>, it will print nothing in this case
```
But I am still otherwise unable to replicate this issue, so I'm closing it.

**Closed by Wealthyturtle** 2019-11-17 13:14 UTC
Labels: needs-testing
