### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Carvane** [SkriptLang/Skript#1910] opened 2019-02-20 22:29 UTC
Console spam:
https://pastebin.com/EkpeT1YB

Server version: PaperSpigot #1598
Skript version: 2.3.5 (latest)

**Comment by ShaneBeee** [comment] 2019-02-21 04:01
You will get better support if you fill out the [BUG REPORT](
https://github.com/SkriptLang/Skript/issues/new?template=bug-report.md) you clearly deleted

**Comment by bensku** [comment] 2019-02-23 12:50
Duplicate of #1902.

**Closed by bensku** 2019-02-23 12:50 UTC
