### ISSUE TITLE
Color Codes format in 1.16.1 versions ERROR

### ISSUE THREAD

**Issue by Scarlet2031** [SkriptLang/Skript#3099] opened 2020-07-04 08:58 UTC
### Description
Color Codes format in 1.16.1 versions all error

### Steps to Reproduce
set {_DGI.magicdust.%player%} to amount of brown dye named "&dMagic &6Dust" in player's inventory

### Expected Behavior
I think this is because the 1.16.1 update is the RGB update

### Errors / Screenshots
No error

### Server Information
1.16.1 paper
2.5-alpha5

### Additional Context
I just updated the server version from 1.15.2 to 1.16.1, at 1.15.2 everything went without a hitch, but when I updated to 1.16.1 everything related to the color code all errors

**Comment by Wealthyturtle** [comment] 2020-07-05 10:31
You say that "everything related to the color code all errors" but you also don't provide any error?

**Comment by Wealthyturtle** [comment] 2020-08-16 10:56
Closing this issue since this was likely caused by the lack of hex color support previously, which has now been properly added into Skript after this issue was created.

**Closed by Wealthyturtle** 2020-08-16 10:56 UTC
Labels: waiting for reply
