### ISSUE TITLE
Rightclick event can't handle checking for name of the item if item doesn't have name

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#4179] opened 2021-07-11 11:09 UTC
### Skript/Server Version

[13:05:42] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:05:42] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[13:05:42] [Server thread/INFO]: [Skript] Server Version: git-Paper-90 (MC: 1.17.1)
[13:05:42] [Server thread/INFO]: [Skript] Skript Version: 2.6-beta2
[13:05:42] [Server thread/INFO]: [Skript] Installed Skript Addons:

### Bug Description

When I'm right-clicking with item and checking for its name - code runs even when it shouldn't

### Expected Behavior

Code shouldn't run when it shouldn't

### Steps to Reproduce

create skript
```
on rightclick:
	if player is holding bone meal named "&eHehe" with lore "&eXD":
		send "&cIt's not possible!"
```
and right-click with unnamed bone meal (with named bone meal problem doesn't exist)

When you have bone meal named &eHehe - there's still problem because it's not checking for lore

### Errors or Screenshots

There's no errors

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-07-11 11:12
Duplicate of https://github.com/SkriptLang/Skript/issues/4163

**Closed by TPGamesNL** 2021-07-11 11:12 UTC
