### ISSUE TITLE
Priority for event

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#2904] opened 2020-04-04 10:49 UTC
May add a priority event? E.g
on rightclick:
    priority is 1:
        spawn zombie

on rightclick:
    priority is 2:
        spawn ender dragon

Ender dragon should spawn not zombie because priority is higher.

**Comment by ShaneBeee** [comment] 2020-04-04 10:53
Even if we had even priorities, both events would still fire, therefor both entities would still spawn.

**Comment by Wealthyturtle** [comment] 2020-04-04 11:40
> Even if we had add event priorities, both events would still fire, therefor both entities would still spawn. I don't think you understand how event priorities work.

^
Also, duplicate of #197

**Closed by Wealthyturtle** 2020-04-04 11:40 UTC

**Comment by Misio12320** [comment] 2020-04-04 13:14
Why its "invalid" not duplicate??
