### ISSUE TITLE
Get the Name of (Item saved in a var) Returns <none>

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#3420] opened 2020-09-30 19:09 UTC
### What happened?
Get the Name of (Item saved in a var) Returns none

### Steps to Reproduce
Following codes were used to set the var, and get the name of item in the var
**set {test} to player's tool
send "%name of {test}%"**

### Expected Behavior
The expression should return the name of the item set in the var.

### Errors / Screenshots
Debugging was done to confirm the variable is set properly:
![image](https://user-images.githubusercontent.com/72163224/94728753-49e8c700-0393-11eb-89ab-10f60a125e4d.png)

### Server Information
Server Version: Paper-207 1.16.3
Skript Version: 2.5 stable

**Comment by APickledWalrus** [comment] 2020-09-30 19:27
I am unable to reproduce this issue. Do you have anything (e.g. addons) that you think may be causing some sort of conflict?
Here's the test I ran below:
![image](https://user-images.githubusercontent.com/29044720/94730177-d31ae200-0330-11eb-8414-ce15287e1e17.png)

**Comment by ShaneBeee** [comment] 2020-10-04 23:54
I also code not replicate this:

<img width="436" alt="Screen Shot 2020-10-04 at 4 49 38 PM" src="https://user-images.githubusercontent.com/20008482/95030077-c6b0c500-0661-11eb-8d85-5b9932a12092.png">

I also did a server restart, same result:
<img width="436" alt="Screen Shot 2020-10-04 at 4 50 44 PM" src="https://user-images.githubusercontent.com/20008482/95030080-cdd7d300-0661-11eb-9ead-4b82843dae30.png">

**Comment by APickledWalrus** [comment] 2020-10-04 23:58
I’m going to say this might be a conflict with an addon. Regardless, we can’t reproduce this issue so I’m going to close it.

**Closed by APickledWalrus** 2020-10-04 23:58 UTC
