### ISSUE TITLE
Fake errors shown if reloading with different cap-formatting

### ISSUE THREAD

**Issue by AntikoreHD** [SkriptLang/Skript#3061] opened 2020-06-20 09:41 UTC
I found a bug where if you reload a script using a different caps-formatting, if you have any function it will show errors that it shouldn't

I'm doing a LobbySk for me and if I do /skript reload lobbysk, all functions give me an error, but if I do /skript reload LobbySk works fine

Seems that the reload command ignores the caps but the repeated function error doesn't

I were using Skript 2.5-alpha3 as long with Minecraft 1.12.2
![image](https://user-images.githubusercontent.com/60967974/85198687-fcb47e00-b2ea-11ea-8bd9-42ceb59d9881.png)

**Comment by APickledWalrus** [comment] 2020-06-20 20:35
I might be wrong, but I believe the name in script reloading is case sensitive. From that, it seems like you have two scripts: LobbySk and lobbysk

**Comment by AntikoreHD** [comment] 2020-06-20 20:51
Nope. I dont have two different and I think its actually impossible to have two same named files in the same folder even with different caps

**Comment by HYPExMon5ter** [comment] 2020-06-20 20:53
It is case sensitive and yes it is possible and it’s exactly what it looks like. Try restarting server or reloading all scripts and see if it still occurs.

**Comment by AntikoreHD** [comment] 2020-06-21 11:55
I literally turn off the computer and turn on the next day, and the bug still happens, and I also reloaded all scripts but the bug still persists.

**Comment by ham1255** [comment] 2020-06-22 18:52
on windows if use SkriptFile.sk or skriptfile.sk it will work since windows doesn't allow files named same but case sentive but in linux  
you can have many files with same name but like this SkriptFile.sk SkRiPTfIle.sk

**Comment by AntikoreHD** [comment] 2020-06-22 19:07
I have windows

**Comment by APickledWalrus** [comment] 2020-06-22 21:37
Are you hosting the server yourself? If so, Windows has ways that you can enable case sensitive file naming (so you can have Script.sk and script.sk). If possible, could you enable that and see if that resolves the issue here?

**Comment by ShaneBeee** [comment] 2020-10-02 05:50
Closing.
We are already aware that Skript has issue when reloading files with the wrong case. I just dont know where the issue is.

That said, dont reload scripts by typing the name in the wrong case.

**Closed by ShaneBeee** 2020-10-02 05:50 UTC
