### ISSUE TITLE
Loop Issue

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#4672] opened 2022-03-17 13:44 UTC
### Skript/Server Version

```markdown
[21:34:25 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:34:25 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[21:34:25 INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[21:34:25 INFO]: [Skript] Skript Version: 2.6.1
[21:34:25 INFO]: [Skript] Installed Skript Addons:
[21:34:25 INFO]: [Skript]  - Repuska v2.8.8
[21:34:25 INFO]: [Skript] Installed dependencies:
[21:34:25 INFO]: [Skript]  - Vault v1.7.3-b131
[21:34:25 INFO]: [Skript]  - WorldGuard v7.0.5+3827266
```

### Bug Description

Here is my code of looping:
```
command /tx:
    trigger:
        set {_x} to "123"
        set {_y} to "234"
        loop {_x} and {_y}:
            send loop-value to console
```
the output should be "123" and "234"
but the actual console output is:
![image](https://user-images.githubusercontent.com/43756134/158820224-11c5476a-8ef7-406f-9c68-ff80bf041776.png)

### Expected Behavior

Times of looping multiple variables should be equal to the index of variables not "index of variables^2"

### Steps to Reproduce

```
command /tx:
    trigger:
        set {_x} to "123"
        set {_y} to "234"
        set {_z} to "345"
        loop {_x}, {_y} and {_z}:
            send loop-value to console
```
output screenshot:
![image](https://user-images.githubusercontent.com/43756134/158821826-797f7881-24f8-4f91-ba1f-f12622af5244.png)

```
command /tx:
    trigger:
        set {_x} to "123"
        set {_y} to "234"
        loop {_x} and {_y}:
            send loop-value to console
```
output screenshot:
![Uploading image.png…]()

### Errors or Screenshots

None

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-03-17 20:49
Caused by this 
https://github.com/SkriptLang/Skript/blob/31bc6c4d5b73fd055535b937e2698c10a086f37d/src/main/java/ch/njol/skript/lang/Variable.java#L402
More in-details by this 
https://github.com/SkriptLang/Skript/blob/31bc6c4d5b73fd055535b937e2698c10a086f37d/src/main/java/ch/njol/util/StringUtils.java#L161

the variable is only 1 character and returning a substring from 0 to -1 will give an empty string which will make `name + "*"` return `*` and grab all the variables

**Comment by AyhamAl-Ali** [comment] 2022-03-17 21:03
Will be fixed in #4627

**Comment by Pikachu920** [comment] 2022-03-18 02:00
> Will be fixed in #4627

can we add a test for this too? should probably have one for all common looping cases.

**Comment by AyhamAl-Ali** [comment] 2022-03-18 13:28
> can we add a test for this too? should probably have one for all common looping cases.

Sounds good. Is that within the scope of your PR @TPGamesNL?

**Comment by TPGamesNL** [comment] 2022-03-19 23:37
Yea I'll do that in the PR

**Comment by TUCAOEVER** [comment] 2022-05-21 21:42
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed** 2022-05-21 21:42 UTC
Labels: bug, priority: high, completed
