### ISSUE TITLE
no idea what the issue is

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2027] opened 2019-04-25 23:55 UTC
```
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[23:53:37] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:53:37] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:53:37] [Server thread/ERROR]: #!#! Here is full list of them:
[23:53:37] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) Vixio (http://vixio.space) TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery 
[23:53:37] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:53:37] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:53:37] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:53:37] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:53:37] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:53:37] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Stack trace:
[23:53:37] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:314)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:1)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:387)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Direction$1.get(Direction.java:1)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:78)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.regions.expressions.ExprRegionsAt.get(ExprRegionsAt.java:1)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.regions.expressions.ExprBlocksInRegion.iterator(ExprBlocksInRegion.java:83)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:79)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:298)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:255)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:200)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:655)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.dispatchCommand(Skript.java:1317)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:280)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:213)
[23:53:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$3$1.call(Commands.java:1)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftFuture.run(CraftFuture.java:85)
[23:53:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[23:53:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[23:53:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[23:53:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[23:53:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[23:53:37] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Version Information:
[23:53:37] [Server thread/ERROR]: #!#!   Skript: 2.3.6 (latest)
[23:53:37] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[23:53:37] [Server thread/ERROR]: #!#!     Date: 2019-03-03
[23:53:37] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[23:53:37] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[23:53:37] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (OpenJDK 64-Bit Server VM 25.191-b12)
[23:53:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-1032-aws
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Server platform: Spigot
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Current node: null
[23:53:37] [Server thread/ERROR]: #!#! Current item: loop all blocks in the regions at at location([[long:0]], [[long:25]], [[long:0]], the world)
[23:53:37] [Server thread/ERROR]: #!#! Current trigger: command /reset (simple event) (reset.sk, line -1)
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Thread: Server thread
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! Language: english
[23:53:37] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/ERROR]: #!#! End of Error.
[23:53:37] [Server thread/ERROR]: #!#! 
[23:53:37] [Server thread/INFO]: An internal error occurred while attempting to perform this command.
``` 
you can tell, `loop all blocks in the regions at at location([[long:0]], [[long:25]], [[long:0]], the world)` is not working properly, this issue only shows in console if console is executing the command, it works if the player runs the command, the actual line is `loop all blocks in region region at location(0, 25, 0, world):`, when I try running this sequence out of a command, I get a separate error 
```
Numeric ids are not supported anymore. (commands/reset.sk, line 6: loop all blocks in region region at location(0, 25, 0, world):')
```

**Comment by TPGamesNL** [comment] 2019-04-26 06:35
Could it be that `world` isn't set when console runs the command?

**Comment by Blueyescat** [comment] 2019-04-27 07:30
Yay the pointless function breaks something, use **`location 0, 25, 0 in world`** or **`location 0, 25, 0`**

**Comment by MrScopes** [comment] 2019-04-27 19:37
> Yay the pointless function breaks something, use **`location 0, 25, 0 in world`** or **`location 0, 25, 0`**

how is the function pointless? I can't use console to reset the mine because skript is retarded so the only solution I have is a function

**Comment by Blueyescat** [comment] 2019-04-27 19:51
> > Yay the pointless function breaks something, use **`location 0, 25, 0 in world`** or **`location 0, 25, 0`**
> 
> how is the function pointless? I can't use console to reset the mine because skript is retarded so the only solution I have is a function

The function doesn't make sense when there is the expression. And the expression doesn't give error if the world is undefined.

You can't use it from the console like that because  **`world`** means world of the executor and the console is not in a world. You can change it to `"worldName"` like `location 0, 25, 0 in "worldName"`.

**Comment by bensku** [comment] 2019-04-29 09:32
Duplicate of #1767. This is caused by misuse of the function, but Skript should not give an error like this.

**Closed by bensku** 2019-04-29 09:32 UTC
