### ISSUE TITLE
Some skript load A LOT LONGER on latest skript

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#4025] opened 2021-05-24 17:05 UTC
### Description

Some skript are loading very long

### Steps to Reproduce

Create new skript, for example:
```
command /setit:
	trigger:
		set {alfabet2::*} to "A" and "B" and "C" and "D" and "E" and "F" and "G" and "H" and "I" and "J" and "K" and "L" and "M" and "N" and "O" and "P" and "R" and "S" and "T" and "U" and "W" and "Y" and "Z" and "Ą" and "Ć" and "Ś" and "Ń" and "Ę" and "Ż" and "Ź" and "Ó" and "Ł" and "V" and "X" and "Q"
```

### Expected Behavior

It should compile instantly like on 2.5.3

### Errors / Screenshots

https://pastebin.com/PiXwQVFg

### Server Information
* **Server version/platform:** git-Paper-727
* **Skript version:** 2.6-alpha1

**Comment by FranKusmiruk** [comment] 2021-05-24 19:35
This was due to #3749, and sadly enough, this can't really be helped due to the way the fix and that specific part of the parsing code works, without changing how strings are parsed drastically at least. We often do not encourage such long lines for that reason anyways, I'd recommend something like the following instead:
```vb
set {_alphabet::*} to "ABCDEFGHIJKLMNOPQRSTUVWXYZ" split at ""
```
As a workaround if you ultimately need the line to be that long for whatever reason, is to group parts of the list with parenthesis, like this:
```vb
set {alfabet2::*} to "A" and "B" and "C" and "D" and "E" and "F" and ("G" and "H" and "I" and "J" and "K" and "L" and "M" and "N") and ("O" and "P" and "R" and "S" and "T" and "U" and "W" and "Y" and "Z" and "Ą" and "Ć" and "Ś") and ("Ń" and "Ę" and "Ż" and "Ź" and "Ó" and "Ł" and "V" and "X" and "Q")
```
That being said, I'll close this as it can be declared as intended behavior for now, but we'll hopefully find ways to parse strings or overall literals with set delimiters more effectively in the future.

**Closed by FranKusmiruk** 2021-05-24 19:35 UTC
