### ISSUE TITLE
umm... can you help me?

### ISSUE THREAD

**Issue by MangoTangoMan12** [SkriptLang/Skript#2996] opened 2020-05-19 11:31 UTC
So... I'm new to GitHub and I don't even know if this question belongs here, but hopefully im not stupid. Anyways, here is an error my friend had with his server.

[Tue, 19. May 2020 09:47:01 GMT ERROR] ------------------------------
[Tue, 19. May 2020 09:47:06 GMT ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-224 (MC: 1.15.2) ---
[Tue, 19. May 2020 09:47:06 GMT ERROR] The server has not responded for 30 seconds! Creating thread dump
[Tue, 19. May 2020 09:47:06 GMT ERROR] ------------------------------
[Tue, 19. May 2020 09:47:06 GMT ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[Tue, 19. May 2020 09:47:06 GMT ERROR] ------------------------------
[Tue, 19. May 2020 09:47:06 GMT ERROR] Current Thread: Server thread
[Tue, 19. May 2020 09:47:06 GMT ERROR]     PID: 17 | Suspended: false | Native: false | State: RUNNABLE
[Tue, 19. May 2020 09:47:06 GMT ERROR]     Stack:
[Tue, 19. May 2020 09:47:06 GMT ERROR]         java.util.LinkedList.indexOf(LinkedList.java:604)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         java.util.LinkedList.contains(LinkedList.java:317)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.log.HandlerList.contains(HandlerList.java:50)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.log.SkriptLogger.removeHandler(SkriptLogger.java:107)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.log.LogHandler.stop(LogHandler.java:43)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1639)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1499)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1499)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:840)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:502)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:900)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1569)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Statement.parse(Statement.java:59)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1010)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1097)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1097)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional$1.<init>(Conditional.java:72)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:72)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1070)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1097)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1097)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.command.Commands.loadCommand(Commands.java:490)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:652)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader$$Lambda$3798/648420252.run(Unknown Source)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader$$Lambda$3784/1647820416.run(Unknown Source)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         ch.njol.skript.Skript$2.run(Skript.java:592)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[Tue, 19. May 2020 09:47:06 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Tue, 19. May 2020 09:47:06 GMT ERROR] ------------------------------
[Tue, 19. May 2020 09:47:06 GMT ERROR] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[Tue, 19. May 2020 09:47:06 GMT ERROR] ------------------------------

If you know what this means and/or you know how to fix it, let me know. Thanks!

**Comment by ShaneBeee** [comment] 2020-05-19 11:33
Duplicate of #2945

**Closed by ShaneBeee** 2020-05-19 11:33 UTC

**Comment by MangoTangoMan12** [comment] 2020-05-19 11:57
ok whats wrong with you shanebeee its literally 2 different things
i watched it and they are different
so pls dont close it and answer

**Comment by Pikachu920** [comment] 2020-05-19 13:20
what are you seeing that's different? they both seem to be watchdog issues

**Comment by ShaneBeee** [comment] 2020-05-19 19:20
I agree with Pikachu. 
Looking at them side by side, they're the same issue. 
If you read the other issue, you will see this issue was caused by paper. 
As stated in the other issue, update your version of Paper since you're 77 versions behind.
