### ISSUE TITLE
[Skript] Severe Error:................ 

### ISSUE THREAD

**Issue by FerriW** [SkriptLang/Skript#2524] opened 2019-10-05 14:52 UTC
I disabled all the addons and still says this, i cant rly tell whats wrong, or if it have any effect on game, but it says i should report it
```
[Skript] Enabling Skript v2.4-beta8
[16:44:14] [ForkJoinPool.commonPool-worker-9/INFO]: [Skript] You're currently running the latest stable version of Skript.
[16:44:19] [Server thread/INFO]: [Skript] Loaded 114161 aliases in 6068ms
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:44:20] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:44:20] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[16:44:20] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Stack trace:
[16:44:20] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
[16:44:20] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[16:44:20] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[16:44:20] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Version Information:
[16:44:20] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[16:44:20] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[16:44:20] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[16:44:20] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[16:44:20] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[16:44:20] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[16:44:20] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.0.0-25-generic
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Server platform: Paper
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Current node: null
[16:44:20] [Server thread/ERROR]: #!#! Current item: null
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Thread: Server thread
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Language: english
[16:44:20] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! End of Error.
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:44:20] [Server thread/ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:44:20] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:44:20] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[16:44:20] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Stack trace:
[16:44:20] [Server thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[16:44:20] [Server thread/ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1546)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1414)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
[16:44:20] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[16:44:20] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[16:44:20] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[16:44:20] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:44:20] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Version Information:
[16:44:20] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[16:44:20] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[16:44:20] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[16:44:20] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[16:44:20] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[16:44:20] [Server thread/ERROR]: #!#!   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[16:44:20] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.0.0-25-generic
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Server platform: Paper
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Current node: null
[16:44:20] [Server thread/ERROR]: #!#! Current item: null
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Thread: Server thread
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! Language: english
[16:44:20] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/ERROR]: #!#! End of Error.
[16:44:20] [Server thread/ERROR]: #!#! 
[16:44:20] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
```

**Comment by JRoy** [comment] 2019-10-05 15:04
Duplicate of #2487

**Closed** 2019-10-05 16:28 UTC
