### ISSUE TITLE
"On region enter" Not recognized

### ISSUE THREAD

**Issue by mmaalex22112** [SkriptLang/Skript#3257] opened 2020-08-02 08:19 UTC
### Description
Created a new skript file. Made a simple region statement. It comes up as can't understand this event. Maybe I'm missing something simple. 

### Steps to Reproduce
Make a simple file. This is the code I used
`on region enter:
	message "hello"`

### Expected Behavior
The player should be messaged when entering a region. No errors on skript loading.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/8296257/89118785-62089c80-d45d-11ea-8961-8b06400fa65e.png)

### Server Information
* **Server version/platform:** Spigot 1.16.1-R0.1-SNAPSHOT
* **Skript version:** 2.5-alpha6

### Additional Context
I may be just fundamentally misunderstanding something but this should work I think?

**Comment by Runakai1** [comment] 2020-08-02 08:25
No errors? I see one. Be sure your indentation is correct and use the right syntax

**Comment by mmaalex22112** [comment] 2020-08-02 08:41
Copying even the direct example syntax from the skriptlang documentation doesn't work. 
![image](https://user-images.githubusercontent.com/8296257/89119200-240d7780-d461-11ea-847d-40f09601c9bd.png)

```
on region exit:
    message "Leaving %region%."
```

**Comment by Wafffidooe** [comment] 2020-08-02 09:38
You sure you have WorldGuard (or some kind of region-plugin) installed for your server version?

**Comment by mmaalex22112** [comment] 2020-08-02 19:17
Worldguard-bukkit-7.0.4-beta1

**Comment by ShaneBeee** [comment] 2020-08-03 11:15
I can not replicate this issue:

<img width="1141" alt="Screen Shot 2020-08-03 at 4 14 54 AM" src="https://user-images.githubusercontent.com/20008482/89177284-eb909b00-d53f-11ea-8f6e-2bcab9d360db.png">

**Comment by mmaalex22112** [comment] 2020-08-03 16:14
I'm currently running FastAsyncWorldEdit-1.16-309.jar. Maybe it has to do with that? They typically are interchangeable.

**Comment by Romitou** [comment] 2020-08-03 16:24
Seems related to #2674.

**Comment by mmaalex22112** [comment] 2020-08-03 16:42
Okay. So it seems FAWE is just not compatible with Skript?

**Comment by Baezor1** [comment] 2020-08-07 12:13
I don't think fawe works with skript. Try using regular world edit and world guard. You could also try using SkBee's Bounds.

**Comment by ShaneBeee** [comment] 2020-08-11 10:29
Closing as duplicate of #2674

**Closed by ShaneBeee** 2020-08-11 10:29 UTC
Labels: waiting for reply
