### ISSUE TITLE
FAWE incompatibility

### ISSUE THREAD

**Issue by Darkweasam** [SkriptLang/Skript#3382] opened 2020-09-16 09:38 UTC
### Description
`on enter region` commands are not triggering when using FAWE instead of original worldedit
( https://intellectualsites.github.io/download/fawe.html )

### Steps to Reproduce
Install both Skript and FAWE, versions doesnt matter

### Expected Behavior
FAWE is a replacement for WE, should regions trigger aswell

### Errors / Screenshots
There are no console errors

If you have console errors, copy them to a paste service which won't delete them.
DON'T use Hastebin!
--->

### Server Information
* **Server version/platform: 1.16.3** 
* **Skript version: 2.5-beta3**

**Comment by ShaneBeee** [comment] 2020-09-16 18:42
Duplicate of #2674

**Closed by ShaneBeee** 2020-09-16 18:42 UTC

**Comment by Darkweasam** [comment] 2020-09-16 21:09
#2674 is marked completed, meanwhile its an open issue

**Comment by ShaneBeee** [comment] 2020-09-16 21:10
completed = we have fixed it
still open = we haven't released it
