### ISSUE TITLE
Former/Past world in a teleport event (TimeStates)

### ISSUE THREAD

**Issue by Lemrigue** [SkriptLang/Skript#3641] opened 2020-12-16 03:02 UTC
### Description
I tried using "former world" in a teleport event, but return "world" value instead

### Steps to Reproduce
Create a file.sk with
`on teleport:
    send "%former world% / %world%"`

### Expected Behavior
former world should return the world the player was in before the teleportation, but return the world he is in after the teleportation (https://skriptlang.github.io/Skript/expressions.html#ExprTimeState)

### Errors / Screenshots
No errors (but if the event is "on world change" instead : "the world does not have a past state")

### Server Information
* **Server version/platform:** paper-319
* **Skript version:** 2.5.3

### Additional Context
I think it worked when I used skQuery, but since it's a Skript feature I reported it

**Comment by ShaneBeee** [comment] 2020-12-25 11:55
Marking this as an enhancement since its technically not a bug, its just not written anywhere in Skript to hold states for locations/worlds in TP events.

**Closed** 2021-05-23 18:15 UTC
Labels: completed, enhancement, priority: lowest
