### ISSUE TITLE
Cancelling on inventory click not consistent

### ISSUE THREAD

**Issue by ghost** [SkriptLang/Skript#2691] opened 2019-12-13 16:59 UTC
### Description
Placing an item into a slot that is set to be cancelled will eventually place the item where it shouldn't go. The does not seem to happen if an item already exists there.

### Steps to Reproduce
```
on inventory click:
    if clicked slot is 5:
        cancel event
```
### Expected Behavior
Cancel consistently

### Errors / Screenshots
https://gyazo.com/a80d2695b485264b5722e4aff00ce0b7

### Tested on
Minecraft: 1.14.4
Spigot: git-Spigot-56f8471-6567017 (MC: 1.14.4)
PaperMC: 234
Skript: 2.4 Stable

**Comment by Jayderp** [comment] 2019-12-14 14:26
Hmm...

**Comment by ThePumpkin5822** [comment] 2019-12-14 19:12
@Jayderp [Github doesn't like you](https://imgur.com/a/PY40iVp).

**Comment by bensku** [comment] 2019-12-14 19:56
I have marked a few short comments that do not add any value here as spam. Please stop cluttering the issue tracker.

**Comment by TPGamesNL** [comment] 2021-06-12 14:15
Duplicate of https://github.com/SkriptLang/Skript/issues/3744. 
Inventory drag events are called instead of inventory click events when the item is being dragged, and an item being dragged across 2 pixels in the same slot already counts as dragging, which doesn't call the inventory click event.

**Closed by TPGamesNL** 2021-06-12 14:15 UTC
Labels: needs testing
