### ISSUE TITLE
Problems with quartz blocks: cannot parse as item, weird value when parsed as item type

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4697] opened 2022-03-25 00:52 UTC
### Skript/Server Version

```markdown
[01:35:25 Server thread/INFO] [Skript] Server Version: git-Paper-"aab1f8a" (MC: 1.18.2)
[01:35:25 Server thread/INFO] [Skript] Skript Version: 2.6.1
[01:35:25 Server thread/INFO] [Skript] Installed Skript Addons: 
[01:35:25 Server thread/INFO] [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[01:35:25 Server thread/INFO] [Skript]  - skript-yaml v1.4
[01:35:25 Server thread/INFO] [Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[01:35:25 Server thread/INFO] [Skript] Installed dependencies: 
[01:35:25 Server thread/INFO] [Skript]  - Vault v1.7.3-b131
[01:35:25 Server thread/INFO] [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Skript can't parse "quartz block" as item. When parsed as item type and converted to string, it's giving a strange result: 

```
nether quartz block, nether quartz block or nether quartz block
```

### Expected Behavior

The same as in the various other block in the example below.

### Steps to Reproduce

```
command /test:
  trigger:
    set {_item} to "64 clay blocks" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 clay blocks" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "64 terracotta" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 terracotta" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "64 sand" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 sand" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "64 dark oak wood" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 dark oak wood" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "64 quartz blocks" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 quartz blocks" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "64 blocks of quartz" parsed as item
    message "item: %{_item}%"
    set {_item} to "64 blocks of quartz" parsed as item type
    message "item type: %{_item}%"

    set {_item} to "quartz block" parsed as item
    message "item: %{_item}%"
    set {_item} to "quartz block" parsed as item type
    message "item type: %{_item}%"
```

Everything here would parse fine, except for quartz blocks:

```
[01:49:42 Server thread/INFO] item: 64 clay blocks
[01:49:42 Server thread/INFO] item type: 64 clay blocks
[01:49:42 Server thread/INFO] item: 64 undyed hardened clay blocks
[01:49:42 Server thread/INFO] item type: 64 undyed hardened clay blocks
[01:49:42 Server thread/INFO] item: 64 sand blocks
[01:49:42 Server thread/INFO] item type: 64 sand blocks
[01:49:42 Server thread/INFO] item: 64 dark oak wood blocks
[01:49:42 Server thread/INFO] item type: 64 dark oak wood blocks
[01:49:42 Server thread/INFO] item: <none>
[01:49:42 Server thread/INFO] item type: 64 nether quartz blocks, nether quartz blocks or nether quartz blocks
[01:49:42 Server thread/INFO] item: <none>
[01:49:42 Server thread/INFO] item type: nether quartz block, nether quartz block or nether quartz block
[01:49:42 Server thread/INFO] item: <none>
[01:49:42 Server thread/INFO] item type: 64 nether quartz blocks, nether quartz blocks or nether quartz blocks
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-03-25 12:47
Duplicate of #4514

**Closed by AyhamAl-Ali** 2022-03-25 12:47 UTC
