### ISSUE TITLE
suggestion: add events for irl time

### ISSUE THREAD

**Issue by Wqrld** [SkriptLang/Skript#879] opened 2017-09-20 18:32 UTC
for example:
```vb
at 23:59 irl:
```

**Comment by Pikachu920** [comment] 2017-09-21 02:33
This is currently possible with the now expression if you need it now

**Comment by Misio12320** [comment] 2021-04-02 16:07
Duplicate of #3378?

**Comment by TPGamesNL** [comment] 2021-04-02 16:31
Duplicate of #3378

**Closed by TPGamesNL** 2021-04-02 16:31 UTC
Labels: enhancement
