### ISSUE TITLE
Number of chickens is invalid?

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#1630] opened 2018-10-25 10:43 UTC
For some reason Skript can't grab the amount of all chickens in the world.
```
broadcast "%number of all chickens%"
```
But yet 
```
broadcast "%all chickens%"
```
works...

Also every other entity works, super weird. It's like the EntityData doesn't exist.

Also I went into more depth about this issue and it appears that Mirre encountered the same issue.

https://github.com/Mirreski/Skript/issues/37

I was like wait wut. lol Poor chickens.

**Comment by Snow-Pyon** [comment] 2018-10-28 01:05
Ended up being a duplicate of #1631.

**Closed by Snow-Pyon** 2018-10-28 01:05 UTC
