### ISSUE TITLE
Function parameter (Function)

### ISSUE THREAD

**Issue by LeoStoch** [SkriptLang/Skript#2631] opened 2019-11-09 02:23 UTC
My suggestion is for functions in general. It would be nice if you are able to five a function another function as parameter instead of only text/numbers... that can be then executed within the function.

**Comment by Wealthyturtle** [comment] 2019-11-09 03:19
What do you mean? Do you want something like
```
function f(func: function):
    func()
```

**Comment by LeoStoch** [comment] 2019-11-09 03:30
Yes, exactly.

**Comment by Wealthyturtle** [comment] 2019-11-09 03:32
Duplicate of #1265

**Closed by Wealthyturtle** 2019-11-09 03:32 UTC
