### ISSUE TITLE
Taking items out of gui (WORKS ON ANY SERVER THAT HAS VANILLA SKRIPT GUIS)

### ISSUE THREAD

**Issue by manduXD** [SkriptLang/Skript#5342] opened 2023-01-12 13:09 UTC
### Skript/Server Version

```markdown
[13:08:56 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:08:56 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[13:08:56 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[13:08:56 INFO]: [Skript] Server Version: git-Paper-215 (MC: 1.19.2)
[13:08:56 INFO]: [Skript] Skript Version: 2.6.3
[13:08:56 INFO]: [Skript] Installed Skript Addons: 
[13:08:56 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[13:08:56 INFO]: [Skript] Installed dependencies: 
[13:08:56 INFO]: [Skript]  - Vault v1.7.3-b131
[13:08:56 INFO]: [Skript]  - WorldGuard v7.0.7-SNAPSHOT+2173-3cb4abd

also this works on the latest versions too
```

### Bug Description

Taking out Items from a gui (This is not a problem with my code, works on any server that uses vanilla skript guis, and has not patched it)

### Expected Behavior

It was suppose to not let the player take the item

### Steps to Reproduce

1) Get a friend
2) person 1 opens a gui
3) person 1, 2 count 
4) and when they counting ends person 1 shift left clicks on the gui item they wanna take out exactly when person 2 hits them

### Errors or Screenshots

No errors

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2023-01-12 13:15
Can you provide a code to test the issue?
Provide a video possibly?

**Comment by TheLimeGlass** [comment] 2023-01-12 17:17
Show your coding that cancels the inventory click event.

**Comment by manduXD** [comment] 2023-01-12 21:57
here's a glimpse of the code

on inventory click:
	if name of event-inventory is "&9&lSERVER SHOP":
		cancel event
		if index of event-slot = 23:
			send "&8&m------------------------------"
			send ""
			send " &7Click <tooltip:&7Click to open our store website><link:https://lifestealtop.tebex.io/package/5452519>&b&nhere&7 to buy  <##7B89FF>&lDRAGON <##7B89FF>Rank"
			send ""
			send "&8&m------------------------------"
			close player's inventory

**Comment by manduXD** [comment] 2023-01-12 21:57
Yea, i can provide a vid too
gimme a few minutes

**Comment by manduXD** [comment] 2023-01-12 22:01
github messed up the indent btw

**Comment by ShaneBeee** [comment] 2023-01-18 23:13
`[13:08:56 INFO]: [Skript] Skript Version: 2.6.3` <-- when reporting issues, Please make sure to be using the latest version of Skript

That said, I can confirm this issue... sorta.

I can steal slot 23, BUT its only client side, as soon as I try to interact with the stolen item, it vanishes.
This is due to the player's inventory not updating when closing!


simple fix for now... wait 1 tick before closing the inventory

**Closed** 2023-03-11 04:07 UTC
Labels: bug, priority: low, completed
