### ISSUE TITLE
Long numbers in list variable index are not working as expected

### ISSUE THREAD

**Issue by CreepahGIT** [SkriptLang/Skript#4729] opened 2022-04-15 09:15 UTC
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[Skript] Skript Version: 2.6.1
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

Two list variables in the form `{var::%{index1}%::*}` and `{var::%{index2}%::*}` are treated the same if `{index1}` and `{index2}` are large numbers. This occurs around 20 characters of digits, but I suspect that it is not a problem with the index string length being too large as the variables are distinct when the indexes are not numbers.

### Expected Behavior

The variables `{var::%{index1}%::*}` and `{var::%{index2}%::*}` should always be different when `{_index1}` and `{_index2}` are not the same. In the tests, changing `{var::%{index2}%::*}` should not change `{var::%{index1}%::*}`

### Steps to Reproduce

1. Load the following script:
```
on load:
	set {digits::*} to "0123456789" split at ""
	set {letters::*} to "abcdefghijklmnopqrstuvwxyz" split at ""
	remove "" from {digits::*}
	remove "" from {letters::*}

function random_str(chars_addr: string, len: number) :: string:
	loop {_len} times:
		add random element of {%{_chars_addr}%::*} to {_str::*}
	return concat {_str::*}

function check(index1: string, index2: string) :: boolean:
	{_index1} != {_index2}
	delete {var::*}
	set {var::%{_index1}%::*} to 1
	set {var::%{_index2}%::*} to 2
	# {var::%{_index1}%::*} must not change because {_index1} != {_index2}
	return true if {var::%{_index1}%::*} = 1 else false

function test(chars_addr: string, len: number):
	set {_index1} to random_str({_chars_addr}, {_len})
	do while {_index2} = {_index1}:
		set {_index2} to random_str({_chars_addr}, {_len})
	set {_msg} to "works" if check({_index1}, {_index2}) = true else "broken!"
	broadcast "%{_chars_addr}%, %{_len}%: %{_msg}% (%{_index1}%; %{_index2}%)"

function test_all(chars_addr: string, len: numbers):
	loop {_len::*}:
		test({_chars_addr}, loop-value)
```
2. Use the test functions:
```
test_all("digits", (numbers from 1 to 30))
test_all("letter", (numbers from 1 to 30))
```
3. The "digits" test should fail at 20+ characters.

### Errors or Screenshots

Output:
![image](https://user-images.githubusercontent.com/67305470/163551650-d5a3c8d8-5e47-4be2-abe8-483b819eb4c7.png)
![image](https://user-images.githubusercontent.com/67305470/163551695-4fc64ee8-550b-4735-a10f-43f576919e27.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-04-15 09:53
Caused by long parsing, which allows max ~19 digits (`log_10(2^63-1)=18.96`):
https://github.com/SkriptLang/Skript/blob/d7119f207d0e06f4b51a473205fb2931c03c28d3/src/main/java/ch/njol/skript/variables/VariablesMap.java#L57-L58
https://github.com/SkriptLang/Skript/blob/d7119f207d0e06f4b51a473205fb2931c03c28d3/src/main/java/ch/njol/skript/util/Utils.java#L679-L683
Utils.parseLong will return `Long.MAX_VALUE` for both numbers, therefore Skript will think them as equal.

Can be fixed by making variableNameComparator not rely on number parsing, instead doing the comparison by comparing things such as sign, length and digits

**Closed** 2022-11-22 00:27 UTC
Labels: bug, priority: medium, completed
