### ISSUE TITLE
Something went terribly wrong with Skript (only on startup)

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#2527] opened 2019-10-06 09:29 UTC
### Description

On startup i get this error message:
[latest.log](https://github.com/SkriptLang/Skript/files/3694176/latest.log)

### Steps to Reproduce
Update to latest skript version and install skquery and skrayfall

### Errors / Screenshots
`[09:18:01] [ForkJoinPool.commonPool-worker-3/INFO]: [Skript] You're currently running the latest stable version of Skript.
[09:18:04] [Server thread/INFO]: [Skript] Loaded 114161 aliases in 3821ms
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[09:18:04] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:18:04] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:18:04] [Server thread/ERROR]: #!#! Here is full list of them:
[09:18:04] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) SkQuery 
[09:18:04] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:18:04] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:18:04] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:18:04] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:18:04] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:18:04] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Stack trace:
[09:18:04] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
[09:18:04] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[09:18:04] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:398)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[09:18:04] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Version Information:
[09:18:04] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[09:18:04] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[09:18:04] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[09:18:04] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[09:18:04] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[09:18:04] [Server thread/ERROR]: #!#!   Java: 11.0.4 (OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu219.04)
[09:18:04] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.0.0-25-generic
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Server platform: Paper
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Current node: null
[09:18:04] [Server thread/ERROR]: #!#! Current item: null
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Thread: Server thread
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Language: english
[09:18:04] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! End of Error.
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:18:04] [Server thread/ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[09:18:04] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[09:18:04] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[09:18:04] [Server thread/ERROR]: #!#! Here is full list of them:
[09:18:04] [Server thread/ERROR]: #!#! skRayFall (https://sk.rayfall.net/) SkQuery 
[09:18:04] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[09:18:04] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[09:18:04] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[09:18:04] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[09:18:04] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[09:18:04] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Stack trace:
[09:18:04] [Server thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[09:18:04] [Server thread/ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1546)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1414)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
[09:18:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[09:18:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[09:18:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[09:18:04] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[09:18:04] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Version Information:
[09:18:04] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[09:18:04] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[09:18:04] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[09:18:04] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[09:18:04] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[09:18:04] [Server thread/ERROR]: #!#!   Java: 11.0.4 (OpenJDK 64-Bit Server VM 11.0.4+11-post-Ubuntu-1ubuntu219.04)
[09:18:04] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.0.0-25-generic
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Server platform: Paper
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Current node: null
[09:18:04] [Server thread/ERROR]: #!#! Current item: null
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Thread: Server thread
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! Language: english
[09:18:04] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/ERROR]: #!#! End of Error.
[09:18:04] [Server thread/ERROR]: #!#! 
[09:18:04] [Server thread/INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~`

### Server Information
* **Server version/platform:**  Paper version git-Paper-209 (MC: 1.14.4)
* **Skript version:**   Skript version 2.4-beta8

### Additional Context
skRayFall+v1.9.18
SkQuery-4.1.1

Error happens only on startup, then the scripts work fine from what i have seen.

**Comment by ShaneBeee** [comment] 2019-10-06 09:30
duplicate of #2487

**Closed** 2019-10-06 15:38 UTC
