### ISSUE TITLE
Entity target not set when experience orbs target player

### ISSUE THREAD

**Issue by staridiot** [SkriptLang/Skript#3659] opened 2020-12-25 18:33 UTC
```
Minecraft: 1.16.4
Paper: 288
Skript: 2.5.3
SkBee: 1.9.1
```

```
on entity target:
	broadcast "%entity% > %target of entity%"
	if target is a player:
		broadcast "definitely a player"
		cancel event
```

You can see in this video the experience orb doesn't have a target, so I can't filter it and cancel it if I want to. However the creeper does have a target, and I can cancel that.

https://user-images.githubusercontent.com/61654758/103140512-5a1ff200-46b5-11eb-9749-5b8aa8d57cf7.mp4

**Comment by ShaneBeee** [comment] 2020-12-25 20:00
According to Spigot API javadocs:
`Called when a creature targets or untargets another entity` 

Since an orb is not a creature, Im assuming that is why.

**Comment by ShaneBeee** [comment] 2021-01-11 13:41
Closing as this appears to be expected behaviour of Bukkit

**Closed by ShaneBeee** 2021-01-11 13:41 UTC
