### ISSUE TITLE
Quit message

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#1467] opened 2018-08-13 10:32 UTC
When a player gets kicked instead of manually disconnecting and the quit message is handled by a skript, it is sent two times

**Comment by Nicofisi** [comment] 2018-08-13 10:47
Duplicate of #1423 (@Matocolotoe could you also, as LimeGlass suggested there, try without skQuery? and please let us know whether it still occurs in the discussion of #1423)

**Closed** 2018-08-13 10:47 UTC
Labels: duplicate
