### ISSUE TITLE
if u use an uncolored string the char "<" or ">" gets deleted

### ISSUE THREAD

**Issue by Eyalcfish** [SkriptLang/Skript#4498] opened 2022-01-12 17:33 UTC
### Skript/Server Version

```
Replace this text with your output from the command.
```

### Bug Description

if i write a code for example
set {item} to uncolored "&3<e>"
it will set {item} to "e"

### Expected Behavior

so if i write
set {item} to uncolored "&3<e>"
it will set {item} to "<e>"

### Steps to Reproduce

i used 
set {item} to uncolored "&3<e>"

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-01-12 17:57
Duplicate of #3787

**Closed** 2022-01-12 17:58 UTC
