### ISSUE TITLE
Skript Issue

### ISSUE THREAD

**Issue by ODGTR** [SkriptLang/Skript#3840] opened 2021-03-21 16:38 UTC
Hello i have this error when i reload my skript it gives me:

[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:32:19] [Server thread/ERROR]: #!#! Could not load mute.sk
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[16:32:19] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:32:19] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[16:32:19] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Stack trace:
[16:32:19] [Server thread/ERROR]: #!#! java.lang.ClassCastException: class ch.njol.skript.lang.Conditional$1 cannot be cast to class ch.njol.skript.lang.Conditional (ch.njol.skript.lang.Conditional$1 and ch.njol.skript.lang.Conditional are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7b0f3a0)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:68)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:68)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1090)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:985)
[16:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:163)
[16:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[16:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[16:32:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Version Information:
[16:32:19] [Server thread/ERROR]: #!#!   Skript: 2.5.3-MH (custom version)
[16:32:19] [Server thread/ERROR]: #!#!     Flavor: selfbuilt-unknown
[16:32:19] [Server thread/ERROR]: #!#!     Date: unknown
[16:32:19] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[16:32:19] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[16:32:19] [Server thread/ERROR]: #!#!   Java: 11.0.9.1 (OpenJDK 64-Bit Server VM 11.0.9.1+1)
[16:32:19] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.8.0-41-generic
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Server platform: Paper
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Current node: else: (mute.sk, line 37)
[16:32:19] [Server thread/ERROR]: #!#! Current item: null
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Thread: Server thread
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! Language: english
[16:32:19] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[16:32:19] [Server thread/ERROR]: #!#! 
[16:32:19] [Server thread/ERROR]: #!#! End of Error.
[16:32:19] [Server thread/ERROR]: #!#!

**Comment by Romitou** [comment] 2021-03-21 16:41
Can you attach your script so that we can try to reproduce it?

**Comment by ODGTR** [comment] 2021-03-21 16:43
[mute.sk.txt](https://github.com/SkriptLang/Skript/files/6177897/mute.sk.txt)

Here it is

**Comment by TPGamesNL** [comment] 2021-03-21 17:06
Duplicate of https://github.com/SkriptLang/Skript/issues/1412
You have a double else section on the same level.

**Closed by TPGamesNL** 2021-03-21 17:06 UTC
