### ISSUE TITLE
on spawn doesnt seem to work

### ISSUE THREAD

**Issue by cookie9kftw** [SkriptLang/Skript#4430] opened 2021-11-20 03:32 UTC
### Skript/Server Version

[04:17:03 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[04:17:03 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[04:17:03 INFO]: [Skript] Server Version: git-Airplane-58 (MC: 1.17.1)
[04:17:03 INFO]: [Skript] Skript Version: 2.6
[04:17:03 INFO]: [Skript] Installed Skript Addons:
[04:17:03 INFO]: [Skript] - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[04:17:03 INFO]: [Skript] - SkBee v1.12.3 (https://github.com/ShaneBeee/SkBee)

### Bug Description

Checking the event-entity type in a on spawn event doesn't seem to work. The bug still appears despite removing the said addons causing the problem.

### Expected Behavior

The event-entity should have a different name and have some equipment and a debug message should appear(removed this at the latest variation of the script)

### Steps to Reproduce

To reproduce it just use _on spawn_ and _if event-entity is zombie(can be any mob)_

### Errors or Screenshots

https://gist.github.com/cookie9kftw/33cf2bf5eab6e52150e0af3b23a254c3

### Other

I've tried removing and updating the addons and reuploading skript and also changed the script multiple times.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-11-22 00:32
This is intended behavior afaik, you need to use `a` like `a zombie` check the examples below
```v
on spawn:
	if event-entity is zombie:
		broadcast "1"
	if event-entity is a zombie:
		broadcast "2" # works

	if type of event-entity is zombie:
		broadcast "3"
	if type of event-entity is a zombie:
		broadcast "4" # works
```
without using `a` it means you're referring to a real existent entity which isn't

**Comment by TPGamesNL** [comment] 2021-11-22 17:29
Duplicate of https://github.com/SkriptLang/Skript/issues/3499

**Closed by TPGamesNL** 2021-11-22 17:29 UTC
