### ISSUE TITLE
Entity type comparison

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#2213] opened 2019-06-29 18:52 UTC
### Description
when you use the code from below and shoot a snowball it returns "no"

### Steps to Reproduce
```
on projectile hit:
	if event-projectile is snowball:
		broadcast "yes %event-projectile%"
	else:
		broadcast "no, %event-projectile%"
```

### Errors / Screenshots
none

### Server Information
* **Server version/platform:**      spigot 1.13.2
* **Skript version:**                v2.4-alpha4

**Comment by ShaneBeee** [comment] 2019-06-29 19:49
if you do `if type of event-projectile is snowball` it works fine

**Comment by TheBentoBox** [comment] 2019-07-08 13:18
I imagine this is indicative of other entity comparison issues? We should investigate further.

Will note that we do have the relatedEntity set up properly for the snowball item alias [here](https://github.com/SkriptLang/skript-aliases/blob/master/misc.sk#L72) so this shouldn't be due to the alias overlapping.

**Comment by diamondpumpkin** [comment] 2019-07-18 08:19
Similar thing with looped items;

`loop all dropped items:
    if item of loop-entity is a gold ingot:
        if name of item of loop-entity contains "Gold":`

that is the only way to get information of the entity itself, not just 'dropped item'. It's a bit confusing.

**Comment by SiebeDW** [comment] 2019-08-06 10:23
I can reproduce this. So i think the needs-testing can be removed.
With type of event-projectile it works fine.

**Comment by ShaneBeee** [comment] 2019-11-09 23:48
Closing this in favour of #2637 
There are many issues on the tracker all stemming from this one big issue, so I wanted to condense this into one larger issue.

**Closed by ShaneBeee** 2019-11-09 23:48 UTC
Labels: bug, needs-testing, priority: medium
