### ISSUE TITLE
Odd Skript error while loading a script

### ISSUE THREAD

**Issue by foxyplush64** [SkriptLang/Skript#4827] opened 2022-06-20 21:51 UTC
### Skript/Server Version

```markdown
[17:42:27] [Render thread/INFO]: [CHAT] [Skript] Server Version: git-Paper-411 (MC: 1.17.1)
[17:42:27] [Render thread/INFO]: [CHAT] [Skript] Skript Version: 2.6.2
[17:42:27] [Render thread/INFO]: [CHAT] [Skript] Installed Skript Addons: 
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - Vixio v2.0.9-pre4 (http://vixio.space)
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - SkQuery v4.1.6
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - SkBee v1.15.1 (https://github.com/ShaneBeee/SkBee)
[17:42:27] [Render thread/INFO]: [CHAT] [Skript] Installed dependencies: 
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - Vault v1.7.3-b131
[17:42:27] [Render thread/INFO]: [CHAT] [Skript]  - WorldGuard v7.0.7-SNAPSHOT+2173-3cb4abd
```

### Bug Description

Whenever I load a dupe script, it just stops the server, I'm not sure why, and I'm not quite sure what to do to fix it.

### Expected Behavior

The script is for a dupe function (executing /dupe dupes the item in your mainhand).

### Steps to Reproduce

I wasn't always in control of the server, so I'm not sure how long this has been happening, but all I know is that you add the skript, and load it, then the errors appear, and the server stops.

Script:
```
command dupe:
    permission: dupe
    trigger:
        event-world is "faction" or "faction_nether" or "faction_the_end"
        loop player's inventory:
            if type of player's held item is a spawn egg:
                stop
            if player's held item's name is "&bWater Transformer" or "&bInfinite &8Void Harvester" or "&5&lAnti Blind Wand &6&l[&3&lTier 1&6&l]" or "&c&lBurned Wood" or "&8&lBlind Core" or "&8Void Ingot" or "&bInfinity Ingot" or "&bInfinite Machine Core" or "&bInfinite &6Machine Circuit" or "&bInfinity Panel" or "&bInfinity Reactor" or "&bInfinity Disenchanter" or "&bInfinity Enchanter" or "&6Infinity Workbench" or "&cAdvanced Anvil" or "&8Void Dust" or "&8Void Bit" or "&bEnder Dragon Data Card" or "&c&lShrooms" or "&8&lMeth" or "&f&lCocaine" or "&2&lAlcohol" or "&a&lCannabis" or "<##D2691E>&lTobacco" or "&8Mob Simulation Chamber" or "&8Mob Data Infuser" or "&bVein Miner Rune":
                send "&eCertain slimefun items cannot be duped."
                stop
            if type of player's held item is a shulker box named "anything":
                stop
            else:
                if type of player's held item is a player head or shulker box or a netherite chestplate or netherite leggings or a netherite helmet or netherite boots or a enchanted golden apple or an enchanted book or a netherite pickaxe or a netherite sword or a netherite axe or a netherite shovel or purple stained glass or tripwire hook or a end portal frame or dragon egg or dragon head or bedrock or barrier or potion or bucket of tropical fish or bucket of axolotl or bucket of pufferfish or bucket of salmon or bucket of cod or minecart or minecart with chest or minecart with hopper or minecart with tnt or minecart with furnace or armor stand or oak boat or spruce boat or birch boat or jungle boat or acacia boat or dark oak boat or written book or white shulker box or orange shulker box or blue shulker box  or pink shulker box or lime shulker box or black shulker box or gray shulker box or magenta shulker box or red shulker box or cyan shulker box or light blue shulker box or light gray shulker box or brown shulker box or green shulker box or yellow shulker box or purple shulker box or a cookie or item frame or armor stand or creeper spawn egg or wither skeleton skull or name tag or spawner or sunflower or saddle or oak sapling or oxidized copper or waxed oxidized copper or exposed copper or waxed exposed copper or weathered Copper or waxed weathered copper:
                    send "&eThis item cannot be duped."
                    stop
            if player's held item is a light block named "&6Foxy's &e&lLightBulb&6 of Ideas":
                send ">++++++[<+++++++++++++>-]<.>[-]+++++++[<++++>-]<+++++."
                stop
            else:
                set {_dupe} to player's held item
                give player {_dupe}
                stop
```

### Errors or Screenshots

https://pastebin.com/sU0d5BRS

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-06-21 13:56
Duplicate of #4463

**Closed by AyhamAl-Ali** 2022-06-21 13:56 UTC
