### ISSUE TITLE
[Suggestion] Sidebar support

### ISSUE THREAD

**Issue by andrei923** [SkriptLang/Skript#2008] opened 2019-04-16 16:10 UTC
I would like to suggest adding sidebar("scoreboard") support in skript.

**Comment by SiebeDW** [comment] 2019-04-16 18:14
Format.exe does not response

**Comment by ShaneBeee** [comment] 2019-04-16 20:37
This has already been suggested in #1824

**Comment by FranKusmiruk** [comment] 2019-04-17 02:01
Duplicate of #1824 as said above.

Also, this is likely not coming soon due to the complexity of scoreboards, implementing them in an intuitive way that also is broad enough to cover all of the features scoreboards provide within the bounds of Skript itself isn't exactly the easiest task (that is; syntax, semantics and pragmatics). I'd gladly start working on it if someone else could think all of the above (without blowing up) for me.

**Closed** 2019-04-17 02:01 UTC
