### ISSUE TITLE
Parser bug doesn't allow custom events

### ISSUE THREAD

**Issue by StealWonders** [SkriptLang/Skript#995] opened 2017-12-02 23:00 UTC
I'm using the latest dev32b version of Skript with the latest MundoSk version.
`call custom event "TELEPORT_LOBBY_EVENT" to details loop-player and loop-player's location`
Whenever I use this code here: `evt "TELEPORT_LOBBY_EVENT":
	giveFirework(event-player)` event-player can't be found. If I use an older version of MundoSk it doesn't work either. --> Skript fault

**Comment by Pikachu920** [comment] 2017-12-03 01:37
How is this a parser bug? Obviously custom events work fine, other addons events work fine, this is actually a "custom custom" event.

**Comment by bensku** [comment] 2017-12-04 10:36
1. You report the issue to addon author
2. Addon author will be able to provide me *useful* details about the issue if it is caused by Skript
3. Issue is fixed by addon author, my or someone doing a pull request

**Comment by bensku** [comment] 2017-12-04 20:41
Apparently OP had contacted addon author. Still need more information, though.

**Comment by Louis-D** [comment] 2017-12-04 20:42
https://gyazo.com/dd963ddedf40ccfc356a415d5ceb2c06?token=eec13fbfd04c2b848d618fa7f97f6398

**Comment by Louis-D** [comment] 2017-12-04 20:43
https://gyazo.com/6b049020403ec3f2fa18df6a0613c565

**Comment by TheBentoBox** [comment] 2017-12-04 21:02
Since it seems there's a possibility that this is related to the parsing of the player's location (since Tlat said that putting `player` after `player's location` worked in his testing) this may be related to the bug I found over in #946 which is causing a lot of the script reload errors on the recent versions.

**Comment by bensku** [comment] 2017-12-04 21:04
That seems likely. Have not had time to look at that bug yet.

**Closed** 2021-05-23 18:15 UTC
Labels: bug, completed
