### ISSUE TITLE
Improve "can see" condition

### ISSUE THREAD

**Issue by erenkarakal** [SkriptLang/Skript#7003] opened 2024-08-29 04:41 UTC
### Suggestion

The "can see" syntax only allows you to check if a player can see another player but paper has a method that lets you check if a player can see an entity (they are even the same name)

https://skripthub.net/docs/?id=2827

https://jd.papermc.io/paper/1.21.1/org/bukkit/entity/Player.html#canSee(org.bukkit.entity.Entity)

### Why?

Very minor change, won't break old code and makes this syntax more useful

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Efnilite** [comment] 2024-09-01 16:32
Duplicate of https://github.com/SkriptLang/Skript/issues/6795

**Closed** 2024-09-01 16:40 UTC
Labels: enhancement, priority: low, good first issue
