### ISSUE TITLE
Skript doesn't load up

### ISSUE THREAD

**Issue by iDanEzz** [SkriptLang/Skript#6802] opened 2024-06-20 09:08 UTC
### Skript/Server Version

```markdown
2.8.7
```

### Bug Description

It doesn't load up first time (Purpur 1.21).

### Expected Behavior

It stops working because of that error.

### Steps to Reproduce

Just put Skript in a new instance of 1.21 mc

### Errors or Screenshots

[12:03:02] [ForkJoinPool.commonPool-worker-1/INFO]: [Skript] You're currently running the latest stable version of Skript.
[12:03:03] [Server thread/ERROR]: Error occurred while enabling Skript v2.8.7 (Is it up to date?)
java.lang.IllegalArgumentException: LAVA_CAULDRON isn't an item
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
at org.bukkit.inventory.ItemStack.of(ItemStack.java:69) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:148) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:128) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:115) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:307) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:705) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:614) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:506) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:492) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:475) ~[Skript-2.8.7.jar:?]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:468) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:433) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:389) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.Skript.onEnable(Skript.java:508) ~[Skript-2.8.7.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2235-778995d]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2235-778995d]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2235-778995d]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2235-778995d]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:03:03] [Server thread/INFO]: [Skript] Disabling Skript v2.8.7
[12:03:03] [Server thread/ERROR]: Error occurred while disabling Skript v2.8.7
java.lang.ExceptionInInitializerError: null
at Skript-2.8.7.jar/ch.njol.skript.Skript.beforeDisable(Skript.java:1192) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.Skript.onDisable(Skript.java:1204) ~[Skript-2.8.7.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.jar:1.21-2235-778995d]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.jar:1.21-2235-778995d]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.jar:1.21-2235-778995d]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2235-778995d]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2235-778995d]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2235-778995d]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2235-778995d]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
at Skript-2.8.7.jar/ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1299) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.Skript.registerEvent(Skript.java:1501) ~[Skript-2.8.7.jar:?]
at Skript-2.8.7.jar/ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:39) ~[Skript-2.8.7.jar:?]
... 17 more

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2024-06-20 10:11
Duplicate of #6796

**Closed by sovdeeth** 2024-06-20 10:11 UTC
