### ISSUE TITLE
Entity of Vehicle Create Event

### ISSUE THREAD

**Issue by yunanmadenci** [SkriptLang/Skript#4887] opened 2022-07-09 23:41 UTC
### Skript/Server Version

```markdown
[23:34:00 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:34:00 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[23:34:00 INFO]: [Skript] Server Version: git-Purpur-1693 (MC: 1.19)
[23:34:00 INFO]: [Skript] Skript Version: 2.6.2
[23:34:00 INFO]: [Skript] Installed Skript Addons: 
[23:34:00 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[23:34:00 INFO]: [Skript]  - SkBee v1.17.0 (https://github.com/ShaneBeee/SkBee)
[23:34:00 INFO]: [Skript] Installed dependencies: 
[23:34:00 INFO]: [Skript]  - Vault v1.7.3-b131
[23:34:00 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

You can't get the exact entity when you use the `vehicle create` event.

### Expected Behavior

It should output it as the entity, boat, minecart etc. but instead it outputs it as `<none>`

### Steps to Reproduce

Insert this code to your Skript:
```
vehicle create:
    send "%entity%" to players
```
Place a boat or minecart.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/103884633/178125936-1e8fadfe-776f-4e63-ae49-53f2a43d45ac.png)
![image](https://user-images.githubusercontent.com/103884633/178125988-f621ce20-13c1-4fcf-8ff0-4cb0a8f8b32b.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-07-09 23:44
Duplicate of #1337

**Closed by AyhamAl-Ali** 2022-07-09 23:44 UTC
