### ISSUE TITLE
database doesnt work

### ISSUE THREAD

**Issue by Nesanco** [SkriptLang/Skript#5242] opened 2022-12-11 01:26 UTC
### Skript/Server Version

```markdown
[01:28:12 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[01:28:12 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[01:28:12 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[01:28:12 INFO]: [Skript] Server Version: git-Pufferfish-46 (MC: 1.19.2)
[01:28:12 INFO]: [Skript] Skript Version: 2.6.4
[01:28:12 INFO]: [Skript] Installed Skript Addons: 
[01:28:12 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[01:28:12 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[01:28:12 INFO]: [Skript]  - SkQuery v4.1.7
[01:28:12 INFO]: [Skript]  - SkBee v2.5.4 (https://github.com/ShaneBeee/SkBee)
[01:28:12 INFO]: [Skript] Installed dependencies: 
[01:28:12 INFO]: [Skript]  - SQLibrary v7.1
[01:28:12 INFO]: [Skript]  - Vault v1.7.3-b131
[01:28:12 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

i installed sqlibrary, i put in the correct database info and its saying it can't access it. 

databse config:
`	database 1:
		# An example database to describe all possible options.
		
		type: MySQL
		# The type of this database. Allowed values are 'CSV', 'SQLite', 'MySQL' and 'disabled'.
		# CSV uses a text file to store the variables, while SQLite and MySQL use databases, and 'disabled' makes Skript ignore the database as if it wasn't defined at all.
		
		pattern: .*
		# Defines which variables to save in this database.
		# This pattern uses Regex syntax, e.g. use 'db_.*' (without the quotes) to store all variables prefixed with 'db_' in this database,
		# or use '.*' (the default value) to store all variables here (recommended for the last database in this list, as otherwise some variables might not be saved).
		# Please note that variables are only stored in one database, and databases are checked from top to bottom,
		# e.g. if a variable matches the topmost database's pattern it will be saved there and nowhere else.
		# BTW: Patterns are checked in a separate thread, i.e. your server likely won't run slower when using complicated patterns.
		
		monitor changes: false
		monitor interval: 20 seconds
		# If 'monitor changes' is set to true, variables will repeatedly be checked for updates in the database (in intervals set in 'monitor interval').
		# ! Please note that you should set 'pattern', 'monitor changes' and 'monitor interval' to the same values on all servers that access the same database!
		
		# == MySQL configuration ==
		host: 91.208.9....# Where the database server is located at, e.g. 'example.com', 'localhost', or '192.168.1.100'
		port: 3306# 3306 is MySQL's default port, i.e. you likely won't need to change this value
		user: u5_Fn....
		password: +VrBv....
		database: s5_variables# The database to use, the table will be created in this database.
		table: variables21# The name of the table to create. 'variables21' is the default name, if this was to be omitted.
		# (If the table exists but is defined differently that how Skript expects it to be you'll get errors and no variables will be saved and/or loaded)
		# == SQLite/CSV configuration ==
		file: ./plugins/Skript/variables.db
		# Where to save the variables to. For a CSV file, the file extension '.csv' is recommended, but not required, but SQLite database files must end in '.db' (SQLibrary forces this).
		# The file path can either be absolute (e.g. 'C:\whatever\...' [Windows] or '/usr/whatever/...' [Unix]), or relative to the server directory (e.g. './plugins/Skript/...').
		
		#table: variables21
		# The name of the table to create. 'variables21' is the default name, if this was to be omitted.
		# (If the table exists but is defined differently that how Skript expects it to be you'll get errors and no variables will be saved and/or loaded)
		# This is generally not required as the the .db file will only be used by Skript, unless you want to split different variables into different tables
		
		backup interval: 2 hours
		# Creates a backup of the file every so often. This can be useful if you ever want to revert variables to an older state.
		# Variables are saved constantly no matter what is set here, thus a server crash will never make you loose any variables.
		# Set this to 0 to disable this feature.`

`[01:22:03 ERROR]: #!#! 
[01:22:03 ERROR]: #!#! ===!!!=== Skript variable load error ===!!!===
[01:22:03 ERROR]: #!#! Unable to load (all) variables:
[01:22:03 ERROR]: #!#! Cannot connect to the database 'database 1'! Please make sure that all settings are correct and that the database software is running.
[01:22:03 ERROR]: #!#! 
[01:22:03 ERROR]: #!#! Skript will work properly, but old variables might not be available at all and new ones may or may not be saved until Skript is able to create a backup of the old file and/or is able to connect to the database (which requires a restart of Skript)!
[01:22:03 ERROR]: #!#! `

the database info is 100% correct ive checked like 5 times and it works perfectly fine with luckperms (just did this to test and made sure it worked)

### Expected Behavior

it should connect to the database

### Steps to Reproduce

make a database and put the info in the skript config

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-12-11 22:01
Unfortunately database support in Skript is not working currently (probably?).
There are many database issues currently open, see #1168 as well.

Duplicate of #3948

**Closed by AyhamAl-Ali** 2022-12-11 22:01 UTC
