### ISSUE TITLE
`on damage: message "something"` does not error

### ISSUE THREAD

**Issue by Nicofisi** [SkriptLang/Skript#1415] opened 2018-07-26 23:37 UTC
#### Code
```
on damage:
    message "damage"
```
this code loads with no errors, yet does nothing at runtime (neither sends the message to the victim nor to the attacker)

#### Expected behavior
It should error, saying that in the damage event either `attacker` or `victim` should be explicitly specified

**Comment by Pikachu920** [comment] 2018-07-28 03:10
to add some info to this: it seems like the error is going off but gets stuck in a log handler somewhere

**Comment by nfell2009** [comment] 2018-07-28 10:14
I always thought Skript errored saying that you need to specify the player receiving the message? Such as the attacker or the victim.

**Comment by Nicofisi** [comment] 2018-07-28 10:40
@nfell2009 iirc people on skUnity said that it only errors when you explicitly use `event-player` or `event-entity`, aka not here

**Comment by Nicofisi** [comment] 2018-07-28 12:52
@OfusMC nope, it does completely nothing

**Comment by TheBentoBox** [comment] 2018-07-29 19:49
Not really sure what prio to put this at, I'm considering medium since I know many have encountered this behavior before including myself and it's unclear what's happening.

**Comment by TheLimeGlass** [comment] 2018-07-31 01:33
Andrew made a fix for this iirc

**Comment by xXAndrew28Xx** [comment] 2018-07-31 01:48
I tried to but I couldn't figure out how to print the error message in the part of the SkriptParser where I wrote the patch (Github name is set wrong :|): https://github.com/SkriptLang/Skript/compare/master...xXAndrew28Xx:fix-1415

**Comment by TheLimeGlass** [comment] 2018-07-31 01:50
Isn't it the same system like the parse expression? Call it to listen then parse and an error gets printed

**Comment by xXAndrew28Xx** [comment] 2018-07-31 01:55
Hmm I'll look into that. Thanks.

**Comment by TheLimeGlass** [comment] 2020-02-23 07:08
Found and fixed bug;

The issue is this mess <https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/registrations/EventValues.java#L165-L181>

Readable version:
```java
for (EventValueInfo<?, ?> ev : eventValues) {
    if (!c.isAssignableFrom(ev.c)) // Projectile would pass
        continue;
    if (!EventValues.checkExcludes(ev, e)) // EntityDamageByDamage (ev.event) is not assignable from EntityDamageEvent
        return null;
    if (ev.event.isAssignableFrom(e)) // EntityDamageByDamage (ev.event) is not assignable from EntityDamageEvent
        return (Getter<? extends T, ? super E>) ev.getter;
    if (!e.isAssignableFrom(ev.event)) // EntityDamageByDamage (ev.event) is not assignable from EntityDamageEvent
        continue;
    return new Getter<T, E>() {
        @Override
        @Nullable
        public T get(E event) {
            // This looks like a fix that was added afterwards, because lots of related events can get here.
            if (!ev.event.isInstance(event)) // EntityDamageByDamage (ev.event) is not an instance of EntityDamageEvent
                return null; // Why EffMessage with no command sender doesn't work for default expressions.
            return ((Getter<? extends T, E>) ev.getter).get(event);
        }
    };
}
```
The issue is that the event value <https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/BukkitEventValues.java#L402> is taking priority, the projectile is an entity, so it passes those isAssignableFrom, it passes all the event isAssignableFrom because EntityDamageByEntity is not assignable from EntityDamageEvent it's vice versa, and the getter will return null because EntityDamageByEntity is not an instance of EntityDamageEvent, so the EffMessage default expression sends the message to no consolesender.

**Closed** 2020-07-21 00:31 UTC
Labels: bug, completed, priority: low
