### ISSUE TITLE
Glass pane not recognized in loops and drops

### ISSUE THREAD

**Issue by DavidVioMC** [SkriptLang/Skript#2328] opened 2019-08-02 21:03 UTC
### Description
Glass panes not recognized in loops or drops.

### Steps to Reproduce
```
on inventory close:
	if inventory name of current inventory of player contains "Test":
		drop all items in player's current inventory where [input != glass pane]

on inventory close:
	if inventory name of current inventory of player contains "Test":
		loop all items in player's current inventory:
			loop-item != glass pane
			remove glass pane from loop-item
			drop loop-item at player```

on inventory close:
	if inventory name of current inventory of player contains "Test":
		drop all items in player's current inventory where [input != Black Stained Glass Pane]
```

### Expected Behavior
Everything is dropped from player's current inventory except glass panes but they carry on dropping, if you change panes to something else, they will not be dropped.

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:1.12.2 hosted on VPS**       
* **Skript version:2.4 beta 4**

**Comment by Matocolotoe** [comment] 2019-08-04 07:24
> drop all items in player's current inventory where [input != glass pane]

You can't expect glass panes to be dropped since the input cannot be one

> loop-item != glass pane

Condition to check if the item is not a glass pane...

> drop all items in player's current inventory where [input != Black Stained Glass Pane]

Slightly different but same thing...

**Comment by Wealthyturtle** [comment] 2019-09-22 10:20
Wouldn't this work?
```
on inventory close:
	if inventory name of current inventory of player contains "Test":
		loop all items in player's current inventory:
			if loop-item is glass pane:
				drop loop-item at player
```

**Comment by Matocolotoe** [comment] 2019-09-22 10:57
Actually he says that glass panes are not recognized but he explicitly adds a condition to check if the item is not a glass pane xDD

**Comment by Wealthyturtle** [comment] 2019-09-22 11:03
?!!?!?!?!?!? *confusion noises*

**Comment by Wealthyturtle** [comment] 2019-09-22 13:10
Someone please close this issue it's hurting

**Comment by Matocolotoe** [comment] 2019-09-22 15:04
Yeah lmao here's a quick summary of the issue
![image](https://user-images.githubusercontent.com/42092549/65389932-08bedf80-dd5b-11e9-93ed-e4389a4e3b63.png)

**Comment by Matocolotoe** [comment] 2019-10-04 15:34
someone please close this

**Comment by TheBentoBox** [comment] 2019-10-04 20:32
I'd advise you all to read stuff more carefully next time. OP clearly states that they ARE trying to prevent glass panes from dropping but that they were still dropping, so this from @Matocolotoe:

> Actually he says that glass panes are not recognized but he explicitly adds a condition to check if the item is not a glass pane xDD

Is incorrect. The user clearly stated the following as the expected behavior:

> Everything is dropped from player's current inventory except glass panes **but they carry on dropping**...

Emphasis added by me, but the point stands. They were still dropping when OP explicitly was trying to make them not drop, hence it appeared to be a bug.

Luckily for you all I can't reproduce this behavior anyway. The conditions seem to be working fine and I believe, if anything, you were just using the wrong aliases; `glass pane` refers to plain, unstained glass panes. Do capture any stained glass pane use `stained glass pane`. To capture both you can use `input != glass pane or stained glass pane`.

**Closed by TheBentoBox** 2019-10-04 20:32 UTC
