### ISSUE TITLE
Can't check entity spawn type

### ISSUE THREAD

**Issue by krfcm** [SkriptLang/Skript#4019] opened 2021-05-23 16:06 UTC
Hey, after update my skript stop working, and i get error message in cosnole.

Skript code:
on spawn:
	if entity is zombie:
		broadcast "a"

Error:
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[18:02:48] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[18:02:48] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[18:02:48] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Stack trace:
[18:02:48] [Server thread/ERROR]: #!#! java.lang.ClassCastException: class org.bukkit.event.entity.EntitySpawnEvent cannot be cast to class org.bukkit.event.entity.ProjectileLaunchEvent (org.bukkit.event.entity.EntitySpawnEvent and org.bukkit.event.entity.ProjectileLaunchEvent are in unnamed module of loader 'app')
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitEventValues$42.get(BukkitEventValues.java:1)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:267)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:100)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:86)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:112)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:154)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.lambda$0(CondCompare.java:309)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:171)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:50)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[18:02:48] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[18:02:48] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:02:48] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:02:48] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[18:02:48] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntitySpawnEvent(CraftEventFactory.java:715)
[18:02:48] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:690)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1933)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1829)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.BlockFalling.tickAlways(SourceFile:45)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:676)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:1477)
[18:02:48] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:309)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:59)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1064)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1563)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:433)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138)
[18:02:48] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[18:02:48] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Version Information:
[18:02:48] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[18:02:48] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[18:02:48] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[18:02:48] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[18:02:48] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[18:02:48] [Server thread/ERROR]: #!#!   Java: 11.0.11 (Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194)
[18:02:48] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Server platform: Paper
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Current node: null
[18:02:48] [Server thread/ERROR]: #!#! Current item: the entity is equal to the zombie (comparator: ch.njol.skript.classes.data.DefaultComparators$14@293fa65c)
[18:02:48] [Server thread/ERROR]: #!#! Current trigger: spawn (spawn) (xxx.sk, line 1)
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Thread: Server thread
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! Language: english
[18:02:48] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[18:02:48] [Server thread/ERROR]: #!#! 
[18:02:48] [Server thread/ERROR]: #!#! End of Error.

**Comment by TPGamesNL** [comment] 2021-05-23 16:09
Duplicate of https://github.com/SkriptLang/Skript/issues/3499

**Closed by TPGamesNL** 2021-05-23 16:09 UTC
