### ISSUE TITLE
Variables: high ram usage & memory leak

### ISSUE THREAD

**Issue by Feerko** [SkriptLang/Skript#1609] opened 2018-10-16 15:25 UTC
Hello

The server has 8 gb RAM. Gc frees memory up to 300mb, 400mb ... 1gb ... 4gb ... after a few hours the server is overloaded. 
I use Aikar's flag. http://mcflags.emc.gs

Paper version git-Paper-1581 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Skript version 2.2-dev37c

<img width="861" alt="zrzut ekranu 2018-10-16 o 17 11 06" src="https://user-images.githubusercontent.com/16988054/47027381-a2ebd000-d167-11e8-9198-9136bddae625.png">
<img width="682" alt="zrzut ekranu 2018-10-16 o 17 18 05" src="https://user-images.githubusercontent.com/16988054/47027382-a2ebd000-d167-11e8-947e-67dbaacc31c4.png">
<img width="775" alt="zrzut ekranu 2018-10-16 o 17 18 18" src="https://user-images.githubusercontent.com/16988054/47027383-a2ebd000-d167-11e8-887b-90c5473b112d.png">
<img width="856" alt="zrzut ekranu 2018-10-16 o 17 19 10" src="https://user-images.githubusercontent.com/16988054/47027384-a2ebd000-d167-11e8-89b5-d6708ca5bc31.png">

**Comment by bensku** [comment] 2018-10-16 21:18
Duplicate of #1570. Also likely fixed in latest Skript release, but I've not yet heard confirmation from anyone experiencing this bug.

**Closed by bensku** 2018-10-16 21:18 UTC
