### ISSUE TITLE
Error on block break

### ISSUE THREAD

**Issue by kenace87** [SkriptLang/Skript#1920] opened 2019-02-27 10:57 UTC
### Description
Error on block break

On using this skript, Every block break produces an error in console.

### Steps to Reproduce
load the script ingame
--------
aliases:
    acacia [wood[en]] bark [block¦s] = minecraft:log2 {Damage:12}
    dark oak [wood[en]] bark [block¦s] = minecraft:log2 {Damage:13}
on mine of dark oak bark:
    "%region at player%" contains "minetree"
    cancel event
    give player dark oak log
    set event-block to air
    stop
--------

Every single block break will produce an error to console.

### Expected Behavior
Block breaks and placed into inventory - this happens, but the error is created every break of block.

### Errors / Screenshots
https://gist.github.com/kenace87/60c0fc99ce19a405ed6a3c8d73f6a837

### Server Information
* **Server version/platform:**       spigot 1.12.2
* **Skript version:**                2.3.5 <https://github.com/SkriptLang/Skript/releases>

**Comment by Plutoren** [comment] 2019-03-01 19:05
I can also vouch for this bug.
To simplify the issue the following code causes a console error.
The code works fine but spams console.
```
on break:
	set event-block to dirt
```
However doing something like this in a command causes no console errors so it must be related to the event.
I am also using 2.3.5 on 1.12.2

**Comment by bensku** [comment] 2019-03-02 12:49
Duplicate of #1902.

**Closed by bensku** 2019-03-02 12:49 UTC
