### ISSUE TITLE
Water is not a block in 1.19.4

### ISSUE THREAD

**Issue by Envqu** [SkriptLang/Skript#5946] opened 2023-08-27 21:29 UTC
### Skript/Server Version

```markdown
[23:21:26 INFO]: [Skript] Server Version: git-Purpur-1967 (MC: 1.19.4)
[23:21:26 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[23:21:26 INFO]: [Skript] Installed Skript Addons: 
[23:21:26 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[23:21:26 INFO]: [Skript]  - skript-db v1.3.9
[23:21:26 INFO]: [Skript]  - SkQuery v4.1.9
[23:21:26 INFO]: [Skript]  - SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
[23:21:26 INFO]: [Skript] Installed dependencies: 
[23:21:26 INFO]: [Skript]  - Vault v1.7.3-b131
[23:21:26 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Water is not a thing in 1.19.4.
Instead of "water" you have to type "minecraft:water"

### Expected Behavior

"water" should work as always.

### Steps to Reproduce

Not works:
```
loop all blocks in radius 2 of event-location:
	if loop-block is water:
		broadcast "X"
```
`There's no loop that matches 'loop-block is water'`

Works:
```
loop all blocks in radius 2 of event-location:
	if loop-block is minecraft:water:
		broadcast "X"
```

Not works:
```
block under {_loc} is lava or water:
	broadcast "X"
```
`Can't compare a block with an object`

Works:
```
block under {_loc} is lava or minecraft:water:
	broadcast "X"
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2023-08-27 21:47
Already fixed in #5503, cannot replicate in 2.7.0-beta3

**Comment by sovdeeth** [comment] 2023-08-27 21:47
Oops didn't mean to close

**Comment by Fusezion** [comment] 2023-08-27 21:58
This can be closed as the issue was caused by type.arts is what the error should say.

Additionally any old issues for this would of been closed. This was fixed in at least 2.7beta2 maybe beta1

**Comment by sovdeeth** [comment] 2023-08-27 21:59
> This can be closed as the issue was caused by type.arts is what the error should say.
> 
> Additionally any old issues for this would of been closed. This was fixed in at least 2.7beta2 maybe beta1

The submitter apparently is on skript 2.7.0-beta3, indicating it didn't get fixed.

**Comment by Envqu** [comment] 2023-08-27 22:00
First example is fixed. Before I was using beta2.
But second still occurs on beta3

**Comment by sovdeeth** [comment] 2023-08-27 22:01
> First example is fixed. Before I was using beta2. But second still occurs on beta3

Have you tested without addons?

**Comment by Envqu** [comment] 2023-08-27 22:06
Yes.

```
options:
	world: world
	x-max: 800
	x-min: -800
	z-max: 800
	z-min: -800

command /test:
	trigger:
		set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
		while block under {_loc} is air or lava:
			remove 1 from y-coords of {_loc}
			block under {_loc} is lava or water:
				set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
				while "%region at {_loc}%" is not "<none>":
					set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
		if block under {_loc} is snow or short grass:
			remove 1 from y-coords of {_loc}
		set block at {_loc} to stone
```

**Comment by sovdeeth** [comment] 2023-08-27 22:09
> Yes. This is my example and its not works
> 
> ```
> options:
> 	world: world
> 	x-max: 800
> 	x-min: -800
> 	z-max: 800
> 	z-min: -800
> 
> command /test:
> 	trigger:
> 		set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
> 		while "%region at {_loc}%" is not "<none>":
> 			set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
> 		while block under {_loc} is air or lava:
> 			remove 1 from y-coords of {_loc}
> 			block under {_loc} is lava or water:
> 				set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
> 				while "%region at {_loc}%" is not "<none>":
> 					set {_loc} to location at random integer between {@x-min} and {@x-max}, 260, random integer between {@z-min} and {@z-max} in "{@world}"
> 		if block under {_loc} is snow or short grass:
> 			remove 1 from y-coords of {_loc}
> 		set block at {_loc} to stone
> ```

I have no issues with it on 1.19.4 and 2.7.0-beta3. Can you send a screenshot of the error and your /sk info together?

**Comment by Envqu** [comment] 2023-08-27 22:10
![image](https://github.com/SkriptLang/Skript/assets/70281617/0cdcf001-f57c-46c4-8040-faa74fa1ed43)

**Comment by Envqu** [comment] 2023-08-27 22:24
Okay, no errors without addons. Error is caused by SkQuery.
Sorry for bothering

**Comment by sovdeeth** [comment] 2023-08-27 22:25
Good to hear, thanks.

**Closed by sovdeeth** 2023-08-27 22:25 UTC
Labels: investigating, can not reproduce
