### ISSUE TITLE
conditions in effect commands

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#2946] opened 2020-04-24 12:48 UTC
### Description
it would be nice if we could use conditions in effect commands, right now you can do
`send "true" if true is true`, but it would be nice if we could just do `send "%if true is true%"`
this could also be useful outside of effect commands

**Comment by Romitou** [comment] 2020-04-24 21:06
Hi, I'm not sure I understand the use and the utility. You can't mix effects and conditions in text?
Forget this, that will exit the script if we run `send "%if true is true%"` ?

**Comment by MrScopes** [comment] 2020-04-24 21:24
> Hi, I'm not sure I understand the use and the utility. You can't mix effects and conditions in text?
> Forget this, what will happen if we run `send "%if true is true%"` ?

it would say `true`

**Comment by Romitou** [comment] 2020-04-24 21:29
Oh, I see.
So yes, this would be great.

**Comment by TheLimeGlass** [comment] 2020-05-01 06:14
LargeSk had this https://github.com/Nicofisi/LargeSk/blob/master/src/main/java/pl/pickaxe/largesk/conditions/CondEvaluateCondition.java I personally don't see the point of allowing it to be an expression, when you can use the ternary `send "example" if player is named "LimeGlass"`

**Comment by ShaneBeee** [comment] 2020-05-12 10:16
I'm going to mark this as a duplicate of #2207 
I know it's not 100% related, but its pretty close, and I think the conversation for very similar topics should be kept together.

**Closed by ShaneBeee** 2020-05-12 10:16 UTC
