### ISSUE TITLE
Catserver incompatibility?

### ISSUE THREAD

**Issue by NymburkSRO** [SkriptLang/Skript#3509] opened 2020-10-31 23:31 UTC
### Description
I updated Skript from 2.2 to 2.5.1 Started server with Catserver core (lastest version on 1.12.2) and few mods. This was error i got on startup - problem with forge items i guess.

### Errors / Screenshots
[00:22:21] [Server thread/ERROR]: Error occurred while enabling Skript v2.5.1 (Is it up to date?)
java.lang.AssertionError: java.lang.NoSuchFieldException: EXTRATREES_DOORSHEMLOCK
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808) ~[TypeAdapters$EnumTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834) ~[TypeAdapters$30.class:?]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:126) ~[MapTypeAdapterFactory.class:?]
        at com.google.gson.Gson.getAdapter(Gson.java:423) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:886) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[Gson.class:?]
        at ch.njol.skript.bukkitutil.BukkitUnsafe.loadMaterialMap(BukkitUnsafe.java:174) ~[?:?]
        at ch.njol.skript.bukkitutil.BukkitUnsafe.initialize(BukkitUnsafe.java:115) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:405) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-65a5f07]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-65a5f07]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-65a5f07]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-65a5f07]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-65a5f07]
        at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NoSuchFieldException: EXTRATREES_DOORSHEMLOCK
        at java.lang.Class.getField(Class.java:1703) ~[?:1.8.0_262]
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:797) ~[TypeAdapters$EnumTypeAdapter.class:?]
        ... 19 more

**Comment by WeeskyBDW** [comment] 2020-10-31 23:37
Hey
See https://github.com/SkriptLang/Skript/issues/2339, it's a similar problem

**Comment by ShaneBeee** [comment] 2020-11-01 09:53
Duplicate of #2339 (or close enough)

Skript only supports the Bukkit platform (Spigot and Paper), and we do not have any plans to support other platforms.

**Closed by ShaneBeee** 2020-11-01 09:53 UTC
