### ISSUE TITLE
Issues parsing strings as items

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2110] opened 2019-05-28 11:03 UTC
### Description
Inconsistent behaviour

### Steps to Reproduce
!give player chorus fruit <<< works absolutely fine
!give player "chorus fruit" parsed as item <<< doesnt work

it appears to be fully random which items work in the latter method, and which dont. as to why this is useful: when loading items that are edited and stored in a yaml file

this works though:
!give player "diamond hoe" parsed as item <<<

some items just do, some dont - i havent found a pattern unfortunately

### Server Information
* **Server version/platform:**      paper 1.13.2
* **Skript version:**               skript 2.3.6

**Comment by ShaneBeee** [comment] 2019-05-28 11:09
I think this issue stems from the fact that "chorus fruit" is an ItemType not an item.
Item = ItemStack
itemtype = ItemType

Ex:
chorus fruit would = item type
player's tool would = item

ex:
`!give player "%player's tool%" parsed as item` works
`!give player "chorus fruit" parsed as itemtype` works

**Comment by TheBentoBox** [comment] 2019-05-28 13:17
Not to be defensive since I wrote most of the new aliases but we can do without the sarcasm next time. Especially since the issue isn't in the aliases themselves but something within the plugin's parsing of items. The two systems are only related in parallel.

Also not going to label this until someone verifies it on the latest alpha since you're not on the latest version. Normally we just close issues from people on outdated versions but I'll give the benefit of the doubt that this is probably still happening.

**Comment by TheBentoBox** [comment] 2019-05-28 13:18
And I've fixed your issue title for you, next time make sure it actually describes your problem so it's at all useful to us at a glance.

**Comment by jaylawl** [comment] 2019-05-28 13:56
@TheBentoBox im sorry about the sarcasm. it's a product of being cranky due to still being tired and some frustration with skript item related stuff. no harm intended!

**Comment by TheBentoBox** [comment] 2019-06-09 19:04
@jaylawl Do you still experience this in the 2.4 alpha releases?

**Comment by jaylawl** [comment] 2019-06-10 11:04
@TheBentoBox Hey, sorry, but i can't test that - i only upgrade to major releases due to the volatile and complicated nature of what i've coded  and can't test that D: 
i did what shanebee recommended (parse as itemtype) and that worked around the issue

**Comment by TheBentoBox** [comment] 2019-06-10 13:13
You don't have to upgrade your entire infrastructure to test something, it takes just a few minutes to start a new local test server. But it's fine, I can test it myself later.

**Comment by PanGargamel** [comment] 2019-08-07 23:30
@TheBentoBox I can confirm that the issue is still present on the newest Skript release (2.4-beta5).
It seems to me that the problem occurs for multi-state items only, like redstone lamp or a furnace - it can be lit or unlit. Every item that I found impossible to convert from string to an item gives multi-state output using this script:
```
command /test:
	trigger:
		set {_item} to chorus fruit # change chorus fruit to any other item
		send "%{_item}%"
```

For example, the output for "furnace" is "furnace, lit furnace or furnace". The output for "chorus fruit" is "chorus fruit or chorus fruit".

**Comment by Wealthyturtle** [comment] 2019-10-15 13:54
Can confirm this with Skript 2.4-beta8 still.

**Comment by APickledWalrus** [comment] 2020-10-03 21:25
There are two main issues that I see here:
1. chorus fruit is registered twice, so that's why you're seeing "chorus fruit or chorus fruit"
2. "furnace" represents the alias "[any] furnace", so that's why you're seeing "furnace, lit furnace, or furnace"

I'm not sure whether this really can or should be fixed, since it isn't *really* broken. The duplicate aliases should be resolved though.

**Comment by TPGamesNL** [comment] 2021-08-14 15:31
The chorus fruit double alias issue will be fixed in https://github.com/SkriptLang/skript-aliases/pull/73
The difference between 'item' and 'itemtype' is explained in the docs: https://skriptlang.github.io/Skript/classes.html#itemstack, so it should be expected that an alias that represents multiple items will not work for parsing as an item.

**Closed** 2021-08-30 20:42 UTC
Labels: bug, priority: low, completed, aliases
