### ISSUE TITLE
formatted title not working

### ISSUE THREAD

**Issue by HakanUnsalP** [SkriptLang/Skript#4744] opened 2022-04-28 07:30 UTC
### Skript/Server Version

```markdown
[10:25:51] [Server thread/INFO]: [Skript] Server Version: git-Pufferfish-64 (MC: 1.18.2)
[10:25:51] [Server thread/INFO]: [Skript] Skript Version: 2.6.1
[10:25:51] [Server thread/INFO]: [Skript] Installed Skript Addons: 
[10:25:51] [Server thread/INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[10:25:51] [Server thread/INFO]: [Skript]  - Skacket v1.0.9
[10:25:51] [Server thread/INFO]: [Skript]  - skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui)
[10:25:51] [Server thread/INFO]: [Skript]  - DiSky v4.0-beta2
[10:25:51] [Server thread/INFO]: [Skript]  - skript-yaml v1.4
[10:25:51] [Server thread/INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[10:25:51] [Server thread/INFO]: [Skript]  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[10:25:51] [Server thread/INFO]: [Skript]  - Skript-Packet v2.0.1 (www.github.com/Anarchick/skript-packet)
[10:25:51] [Server thread/INFO]: [Skript]  - ItemsAdder v3.1.2 (devs.beer)
[10:25:51] [Server thread/INFO]: [Skript] Installed dependencies: 
[10:25:51] [Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[10:25:51] [Server thread/INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

custom font works in chat and actionbar but not in title

### Expected Behavior

```/title @a title {"text":"hello world","font":"uniform"}```
![image](https://user-images.githubusercontent.com/58227275/165700189-df60b003-6de4-465f-9faa-e52c339f46fa.png)

```/title @a title {"text":"hello world","font":"alt"}```
![image](https://user-images.githubusercontent.com/58227275/165700259-995a5a42-ef75-45f0-b44c-35b215051d10.png)

### Steps to Reproduce

1. ```send title "<font:uniform> hello world" to player```
2. ```send title formatted "<font:uniform> hello world" to player```

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/58227275/165700440-57aae8c5-7757-48a4-a3ae-4785dacbb9c3.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-04-30 14:06
Duplicate of https://github.com/SkriptLang/Skript/issues/3112

The only things in Skript currently supporting advanced formatting, such as <font>, is the message and broadcast effect.

**Closed by TPGamesNL** 2022-04-30 14:06 UTC
