### ISSUE TITLE
Using formatted text

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#2867] opened 2020-03-19 17:43 UTC
### Question (or a bug ?)

Hello !
I preferred to post this message as a question, because I am not sure that it is a bug.
This is why I ask you. 😃 

```applescript
command /formatmsg:
    trigger:
        set {test::msg} to "<tooltip:This is just a test. Waow!>This is my example text. Interesting?"
        broadcast formatted {test::msg} # This doesn't send a formatted text.
        send formatted {test::msg} # This send a formatted text!
```
Is it normal that broadcast does not support formatted texts?
![image](https://user-images.githubusercontent.com/35146758/77097595-51f1a280-6a11-11ea-8677-8942cf7827a9.png)

MC: 1.15.2 - SK: 2.5-alpha1 (should i update to alpha2?)

Sorry if this was normal, please close this issue in this case.
Have a good day or night and sorry for my English !

**Comment by noftaly** [comment] 2020-03-19 18:36
Duplicate of #1093
There is also another issue mentioning this but I can't find it.
To summarize it is normal behavior because `broadcast` includes the console and you can't send a formatted message to the console, so use `send "" to all players` instead ^^

**Closed** 2020-03-19 18:56 UTC
