### ISSUE TITLE
Removing one item from player's inventory causes server crash.

### ISSUE THREAD

**Issue by NathanAdhitya** [SkriptLang/Skript#4083] opened 2021-06-18 08:41 UTC
### Description

Deducting one item from inventory causes the entire server to crash.

### Steps to Reproduce

1. Spigot + Skript version as mentioned below
2. Script:
```skript
command /flightcoupon:
    permission: skript.flightcoupon
    trigger:
        give player 1 paper named "&a1h Flight Coupon" with lore "Right click to redeem your 1h of flight!"

on rightclick with paper:
	if player has event-item in inventory:
		if event-item is paper named "&a1h Flight Coupon" with lore "Right click to redeem your 1h of flight!":
			execute console command "lp user %player's name% permission settemp skript.fly true 1h accumulate"
			message "&aYou used a voucher! Use /fly to activate."
			remove 1 of event-item from player's inventory
```

### Expected Behavior

Item is deducted from the player's inventory./

### Errors / Screenshots
```
Encountered an unexpected exception
java.lang.AssertionError: TRAP
        at net.minecraft.world.item.ItemStack.checkEmpty(ItemStack.java:189) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1232) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:445) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1609) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3149-Spigot-101ebb6-9122f5a]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Server Information
* **Server version/platform:** CraftBukkit version 3149-Spigot-101ebb6-9122f5a (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
* **Skript version:** Tested with 2.6-alpha1, 2.5.3

### Additional Context
 -

**Comment by AyhamAl-Ali** [comment] 2021-06-18 09:02
This happened to me multiple times before and has been reported here as well. Not sure if it's a Skript bug or a bukkit/spigot kind of bug but try follow this [comment](https://github.com/SkriptLang/Skript/issues/2143#issuecomment-499615192)

**Comment by NathanAdhitya** [comment] 2021-06-18 09:43
> This happened to me multiple times before and has been reported here as well. Not sure if it's a Skript bug or a bukkit/spigot kind of bug but try follow this [comment](https://github.com/SkriptLang/Skript/issues/2143#issuecomment-499615192)

Thanks for the response, waiting for one tick works, but is not elegant.
The elegant solution provided instead does not work for some reason. The item amount does not get subtracted.

**Comment by AyhamAl-Ali** [comment] 2021-06-18 10:35
You're welcome. You can also try using `player's tool` instead of `event-item`, I never had issues when I use `player's tool`

**Comment by TPGamesNL** [comment] 2021-06-18 11:32
Duplicate of https://github.com/SkriptLang/Skript/issues/2143

**Closed by TPGamesNL** 2021-06-18 11:32 UTC

**Comment by NathanAdhitya** [comment] 2021-06-18 12:03
> Duplicate of #2143

Hello, I believe otherwise. Using the fix mentioned by subtracting the item amount does not work. Though, that might fit into another issue instead. 

> You're welcome. You can also try using `player's tool` instead of `event-item`, I never had issues when I use `player's tool`

player's tool is not reliable for some reason. the event on a right-click could be either from the offhand and from the mainhand. Both cases also crash the server when used without the wait.

**Comment by TPGamesNL** [comment] 2021-06-18 13:06
> > Duplicate of #2143
> 
> Hello, I believe otherwise. Using the fix mentioned by subtracting the item amount does not work. Though, that might fit into another issue instead.
> 
> > You're welcome. You can also try using `player's tool` instead of `event-item`, I never had issues when I use `player's tool`
> 
> player's tool is not reliable for some reason. the event on a right-click could be either from the offhand and from the mainhand. Both cases also crash the server when used without the wait.

Although the fix may not work, the issue is the same. If the fix does not work, try commenting under that issue
