### ISSUE TITLE
Support Gamerule in Minecraft 1.12.2

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#4187] opened 2021-07-14 08:00 UTC
### Suggestion

Allow using GameRule in Minecraft 1.12.2

### Why?

It's useful and Bukkit support it:
_World.setGameRuleValue(String, String)_
return a boolean, if it is true, it succeed

### Other

No

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment] 2021-07-22 15:30
Duplicate of #3350

**Closed by TPGamesNL** 2021-07-22 15:30 UTC
Labels: enhancement, pre-1.13, priority: lowest
