### ISSUE TITLE
Skript does not stop properly

### ISSUE THREAD

**Issue by CrazyWords1** [SkriptLang/Skript#4150] opened 2021-07-02 10:08 UTC
### Description
Sometimes (very often to be honest) i have problem with server stop, in console i see message like this: "[Skript] Disabling Skript", but this message hangs forever, and server not stopped
### Steps to Reproduce
I don't know

### Errors / Screenshots
This Issue, a full copy of this https://github.com/SkriptLang/Skript/issues/3896#issue-855392114

### Server Information
![изображение](https://user-images.githubusercontent.com/32343185/124258860-5202ac80-db47-11eb-8ea4-79a44f97430c.png)
![изображение](https://user-images.githubusercontent.com/32343185/124258933-6646a980-db47-11eb-9e0e-0d415a54bc29.png)

### Additional Context

I'm enable debug mode, and wait for issue.
As for evil, as soon as I turned on debug, it started shutting down the server normally, I also want to note that most likely the error is related to variables, a week ago I tried to fix everything by resetting the data, but the error persisted.
I must say right away, I do not have the financial opportunity to continue testing everything on the production server, the variables are rolled back, for about 2-5 hours, the players are crying, I hope for your help

**Comment by CrazyWords1** [comment] 2021-07-02 10:11
Forget config 	newsqlite:
		type: sqlite
		pattern: .*
		file: ./plugins/Skript/newsqlite.db
		backup interval: 30 minute
		monitor changes: false
		monitor interval: 20 seconds

**Comment by CrazyWords1** [comment] 2021-07-02 10:15
I read somewhere in issues that the problem may be caused by addons

**Comment by CrazyWords1** [comment] 2021-07-02 10:18
After enable debug mode, sometimes, i seen this message, its okey? :)
![изображение](https://user-images.githubusercontent.com/32343185/124260072-b4a87800-db48-11eb-8de8-5cd02658745a.png)

**Comment by TPGamesNL** [comment] 2021-07-02 10:21
Can you show your console log from those infinite script repeating errors?

**Comment by CrazyWords1** [comment] 2021-07-02 10:29
> 
> 
> Can you show your console log from those infinite script repeating errors?
log file is very large, download now as fast as i can

**Comment by CrazyWords1** [comment] 2021-07-02 11:00
> 
> 
> Can you show your console log from those infinite script repeating errors?
[13:31:07] [Server thread/INFO]: [Skript] == org.bukkit.event.inventory.InventoryOpenEvent ==
[13:31:07] [Server thread/INFO]: [Skript] # inventory open
[13:31:07] [Server thread/INFO]: [Skript] inventory open (simple event)
[13:31:07] [Server thread/INFO]: [Skript]   -<none> is equal to [[boolean:true]] (comparator: null)
[13:31:07] [Server thread/INFO]: [Skript] # inventory open took 0.070824 milliseconds
[13:31:07] [Server thread/INFO]: [Skript] # inventory open
[13:31:07] [Server thread/INFO]: [Skript] inventory open (simple event)
[13:31:07] [Server thread/INFO]: [Skript] The script 'music.sk' infinitely (or excessively) repeated itself!
[13:31:07] [Server thread/WARN]: java.lang.StackOverflowError
[13:31:07] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1044)
[13:31:07] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1043)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:596)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:568)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1000)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:600)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:568)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1000)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1)
log above, repeat 200x times
```
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:600)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:568)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1000)
[13:31:07] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1)
```

**Comment by CrazyWords1** [comment] 2021-07-02 11:02
> 
> 
> Can you show your console log from those infinite script repeating errors?

[13:31:16] [Server thread/INFO]: [Skript] == org.bukkit.event.inventory.InventoryClickEvent ==
[13:31:16] [Server thread/INFO]: [Skript] # inventory click
[13:31:16] [Server thread/INFO]: [Skript] inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge)
[13:31:16] [Server thread/INFO]: [Skript] The script '101.sk' infinitely (or excessively) repeated itself!
[13:31:16] [Server thread/WARN]: java.lang.StackOverflowError
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:568)
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1000)
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1)
200x times
```
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:600)
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.registrations.Classes.toString(Classes.java:568)
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1000)
[13:31:16] [Server thread/WARN]: 	at ch.njol.skript.classes.data.BukkitClasses$20.toString(BukkitClasses.java:1)
```

**Comment by TPGamesNL** [comment] 2021-07-02 11:04
Those errors are a duplicate of https://github.com/SkriptLang/Skript/issues/3733

Please edit your previous comments instead of commenting twice in a row.

**Comment by CrazyWords1** [comment] 2021-07-02 11:18
In config.sk i'm enable backup in 30 minutes, 2 last backup, their size is the same, I think this is already an indicator that something is wrong
![изображение](https://user-images.githubusercontent.com/32343185/124266806-df96ca00-db50-11eb-84e3-b652f4dde0b5.png)
![изображение](https://user-images.githubusercontent.com/32343185/124266843-eae9f580-db50-11eb-9bcf-c71ac2ad6733.png)

**Comment by TPGamesNL** [comment] 2021-07-02 11:20
Skript's non-CSV variable storage system has always had problems, I guess this is also one of them.

**Comment by CrazyWords1** [comment] 2021-07-02 11:21
> 
> 
> Skript's non-CSV variable storage system has always had problems, I guess this is also one of them.

Okey, how i can export variables to normal CSV?
And thk u for helping me, here, and in your Discord server, you awesome developer

**Comment by TPGamesNL** [comment] 2021-07-02 11:27
Thanks \:D
You could try enabling both SQLite and CSV storages, and set the variable pattern for the CSV to match everything (the default value), and make sure that CSV is *before* the SQLite section in config.sk. I think this'll make Skript load variables from both databases, but save them in the CSV file, but I also think you will still have to keep the SQLite db connected (since Skript only saves changed variables AFAIK)

**Comment by CrazyWords1** [comment] 2021-07-02 12:12
I transferred everything to CSV, everything is fine, if there is no bug, I think it will be possible to close the topic, I just suggest adding information to the config that sql is not stable together with Skript

**Comment by CrazyWords1** [comment] 2021-07-03 16:00
Now i'm restarting server 5 times, and all work perfectly on CSV save method.

I draw the following conclusions, working with sql is not stable at the moment and requires improvement, I suggest informing users about this in config.sk
this issue can be closed

**Comment by CrazyWords1** [comment] 2021-07-04 20:48
I'm migrate to CSV file storage system, and have a rollback

```
[23:32:04] [Server thread/INFO]: [Skript] Disabling Skript v2.5.3
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[23:32:05] [Server thread/ERROR]: #!#! An error occurred while shutting down.
[23:32:05] [Server thread/ERROR]: #!#! This might or might not cause any issues.
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[23:32:05] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:32:05] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:32:05] [Server thread/ERROR]: #!#! Here is full list of them:
[23:32:05] [Server thread/ERROR]: #!#! skRayFall v1.9.15 (https://sk.rayfall.net/) SkriptJSON v1.0.0 skript-reflect v2.1.0 (https://github.com/TPGamesNL/skript-reflect) TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe) MCJukebox v2.6.7 Reqn v1.2.4 skript-db v1.2.0 
[23:32:05] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:32:05] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:32:05] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:32:05] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:32:05] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:32:05] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Stack trace:
[23:32:05] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:706)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:339)
[23:32:05] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onDisable(Skript.java:1040)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[23:32:05] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363)
[23:32:05] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
[23:32:05] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:702)
[23:32:05] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Version Information:
[23:32:05] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[23:32:05] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[23:32:05] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[23:32:05] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[23:32:05] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[23:32:05] [Server thread/ERROR]: #!#!   Java: 11.0.8 (OpenJDK 64-Bit Server VM 11.0.8+10-post-Debian-1deb10u1)
[23:32:05] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.19.0-9-amd64
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Server platform: Paper
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Current node: null
[23:32:05] [Server thread/ERROR]: #!#! Current item: null
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Thread: Server thread
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! Language: english
[23:32:05] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[23:32:05] [Server thread/ERROR]: #!#! 
[23:32:05] [Server thread/ERROR]: #!#! End of Error.
[23:32:05] [Server thread/ERROR]: #!#! 
```

**Comment by CrazyWords1** [comment] 2021-07-04 20:49
@TPGamesNL

**Comment by APickledWalrus** [comment] 2021-07-04 21:00
That error is from trying to store a region in a global variable. Skript allows you to, but it shouldn't currently because it does not work properly.

**Comment by CrazyWords1** [comment] 2021-07-04 21:02
> 
> 
> That error is from trying to store a region in a global variable. Skript allows you to, but it shouldn't currently because it does not work properly.

The problem is:
all the other variables rollback, not only "region" variables

**Comment by TPGamesNL** [comment] 2021-07-05 09:14
That is a duplicate of #3203

**Closed by TPGamesNL** 2021-07-05 09:14 UTC
Labels: bug, variables
