### ISSUE TITLE
Wither damage cause

### ISSUE THREAD

**Issue by Guarmanda** [SkriptLang/Skript#551] opened 2017-05-08 17:32 UTC
As I was configuring some damage causes on my server I found that "If damage cause is wither" returned "can't copare damage cause with potion". Since the wither damage cause is here: http://njol.ch/projects/skript/doc/classes/#damagecause I think that there's a problem with it...

**Comment by TheBentoBox** [comment] 2017-05-09 17:55
That's the syntax you should be using for checking a damage cause, you want to use [this condition](http://bensku.github.io/Skript/conditions.html#CondDamageCause), so the correct syntax would be `if damage was caused by wither`. 

That being said, this still sounds like a bug, because realistically even though it's not the ideal syntax, it should still work (just like how `if damage cause is fall` works even though you should do `if damage was caused by fall`). Up to Bensku if he wants to fix because I'm not sure how would be best to do so or how easy it is.

**Comment by Snow-Pyon** [comment] 2017-05-09 23:37
A while ago, someone created this post on the forums:
https://forums.skunity.com/threads/cancel-damage-from-dragons-breath.3060/
This might be related to this also.

**Comment by bensku** [comment] 2017-05-10 13:34
I think it just tries to parse entity it as entity wither and fails. Will need to do some changes to work around this issue, as I can't just break all scripts that check for wither entities.

**Comment by Syst3ms** [comment] 2017-05-10 14:26
@bensku Actually it tries to compare it with the wither potion effect type. I'd recommend doing some sort of low parse priority for the compare condition. We've all seen conflicts with it, and I think that would solve it.

**Comment by TheBentoBox** [comment] 2019-06-22 17:53
Closed in favor of the more up-to-date #2184.

**Closed by TheBentoBox** 2019-06-22 17:53 UTC
Labels: bug, priority: medium
