### ISSUE TITLE
Cant name real chest

### ISSUE THREAD

**Issue by CGDoctor8** [SkriptLang/Skript#2698] opened 2019-12-15 12:47 UTC
### Description
When trying to name a placed chest in the world it will fail silently i would also expect this to work with droppers, dispensers, ender-chest, trap chest, double wide chest

### Steps to Reproduce
```
command /name [<text>]:
    trigger:
        if target block is a chest:
            set {_t} to inventory of target block
            add 1 dirt to {_t}
            set the name of {_t} to "test"
        else:
            send "&cYou must be looking at a chest"
```

**Comment by Wealthyturtle** [comment] 2019-12-15 14:11
Are you sure you're doing it right? Have you tried directly modifying the inventory data instead of the variable?

```
command /name [<text>]:
    trigger:
        if target block is a chest:
            add 1 dirt to inventory of target block
            set the name of inventory of target block to "test"
        else:
            send "&cYou must be looking at a chest"
```
Try that

**Comment by CGDoctor8** [comment] 2019-12-15 23:52
Also unsable to name chest with that code

**Comment by Wealthyturtle** [comment] 2019-12-16 01:21
What server version and skript version are you using?

**Comment by CGDoctor8** [comment] 2019-12-16 01:41
Just put together the latest spigot and skript stable release for 1.14.4 still nothing with either code blocks and to be clear I'm am expecting this name to change 
![image](https://user-images.githubusercontent.com/39572468/70873294-08726100-1fa5-11ea-87be-1beb29684118.png)

**Comment by Wealthyturtle** [comment] 2019-12-16 02:15
Duplicate of #2069 I believe.

**Closed by Wealthyturtle** 2019-12-16 02:15 UTC
Labels: waiting for reply
