### ISSUE TITLE
Ripe wheat plant on latest version do not work!!

### ISSUE THREAD

**Issue by INTmAker** [SkriptLang/Skript#2294] opened 2019-07-24 08:19 UTC
**My skript:**
on break of stage 8 wheat plant:
	cancel event
	set event-block to air
	wait 2 seconds
	set event-block to ripe wheat plant

No errors. When i break wheat, it does not cancel event!

**Comment by infmemory** [comment] 2019-07-26 08:43
I recommend using `freshly planted {plantName} plant` and `fully grown {plantName} plant`.

The following code works for me on Skript  2.4-beta3 (no addons):
```
on break of fully grown wheat plant:
#{
    cancel event
    set block to freshly planted wheat plant
#}
```

I was however able to cancel the event in 2.4-beta3 using `stage 8 wheat plant`, I used the code below. Are you sure the script is loaded/enabled?
```
on break of stage 8 wheat plant:
#{
    cancel event
#}
```

**Comment by INTmAker** [comment] 2019-07-29 09:35
Still do not work I use spigot 1.12.2

**Comment by bensku** [comment] 2019-07-29 17:25
Issue template was not followed, and because of that, we don't know your Skript version. This would be a known problem in 2.3, which was fixed by rewriting the relevant system in 2.4. That change is too large to be backported.

**Comment by INTmAker** [comment] 2019-07-30 21:47
I use Skript (2.4-beta2) and spigot 1.12.2

**Comment by ilsubyeega** [comment] 2019-07-31 14:43
rewriting this with silmar problems


### Description
Aliases
Wheat is showing to "CROPS"

### Steps to Reproduce

```
on break:
	broadcast "Block: %event-block%"
```

When you break the crops, it just broadcasts to "CROPS"
### Expected Behavior

it should be ~~ wheat

### Errors / Screenshots

Video: https://youtu.be/uCpi7Ea5hTA


### Server Information
* **Server version/platform:**  git-Spigot-e8ded36-acbc348 (1.12.2)     
* **Skript version:**  2.4-beta4              

### Additional Context

I think it might be skript-aliases error(they are wheat items and blocks)

**Comment by bensku** [comment] 2019-08-04 11:56
Still likely 1.12 specific issue.

**Comment by TheBentoBox** [comment] 2019-09-02 21:48
Closing in favor of #2394 as it is the same bug and that one better describes the problem.

**Closed by TheBentoBox** 2019-09-02 21:48 UTC
Labels: investigating
