### ISSUE TITLE
The Right of Direction does not return the correct position.

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#3334] opened 2020-08-24 16:43 UTC
### Description

"infont" goes to the front of the facing.
"right" also goes to the right of the facing.
But reach of right is shortened when the pitch of facing changes.

### Steps to Reproduce

```skript
command /test:
	trigger:
		set {_loc} to location 1 right head of player
		execute command "/particle dust 0 0 1 2 %x-coord of {_loc}% %y-coord of {_loc}% %z-coord of {_loc}% 0 0 0 0 50 normal @a" by console
```

### Expected Behavior

Regardless of the pitch, you need to be able to get the right position in the direction you look.

### Errors / Screenshots

![2020-08-25_01 18 56](https://user-images.githubusercontent.com/59043053/91071970-c8a36380-e673-11ea-9b3d-978cc2e1cf92.png)
![2020-08-25_01 19 07](https://user-images.githubusercontent.com/59043053/91071990-cfca7180-e673-11ea-98fa-d0b141b7f7b9.png)
![2020-08-25_01 19 10](https://user-images.githubusercontent.com/59043053/91071994-d1943500-e673-11ea-8cfc-140f40b9f906.png)

### Server Information
* **Server version/platform:** Paper 1.16.1 build 116
* **Skript version:** 2.5-beta2

### Additional Context
I know how to solve this problem with a vector. However, I wonder if the value returned by right of direction is intended.

**Comment by ShaneBeee** [comment] 2020-10-06 21:53
Duplicate of #1544

**Closed by ShaneBeee** 2020-10-06 21:53 UTC
