### ISSUE TITLE
`items in player's inventory` seems to no longer work

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#6331] opened 2024-01-14 22:30 UTC
### Skript/Server Version

```markdown
[14:23:50 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:23:50 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:23:50 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:23:50 INFO]: [Skript] Server Version: git-Paper-381 (MC: 1.20.4)
[14:23:50 INFO]: [Skript] Skript Version: 2.8.0-pre2 (skriptlang-github)
[14:23:50 INFO]: [Skript] Installed Skript Addons: 
[14:23:50 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[14:23:50 INFO]: [Skript]  - skript-reflect v2.4-dev1 (https://github.com/SkriptLang/skript-reflect)
[14:23:50 INFO]: [Skript]  - SkBee v3.1.0 (https://github.com/ShaneBeee/SkBee)
[14:23:50 INFO]: [Skript] Installed dependencies: 
[14:23:50 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

using the code:
`!send (items in player's inventory)`
outputs nothing, even tho this used to work on 2.7.x

using the code:
`!send (items in (player's inventory))`
outputs a list of the player's tool

### Expected Behavior

To output a list of items

### Steps to Reproduce

see bug description

### Errors or Screenshots

<img width="516" alt="Screenshot 2024-01-14 at 2 25 39 PM" src="https://github.com/SkriptLang/Skript/assets/20008482/f9411ccf-b03e-4519-a07b-6cdc6600baa9">

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment] 2024-01-14 22:37
I think this is a duplicate of https://github.com/SkriptLang/Skript/issues/6290

**Closed** 2024-01-15 04:59 UTC
Labels: duplicate
