### ISSUE TITLE
conditions || &&

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3917] opened 2021-04-24 00:40 UTC
I think we should have the ability to do something like `if x or y` similar to `||`, so `if player is op or player's money > 100`. same with `&&` so `if player is op and player's money > 100`, or `if player is op, player's money > 100 and player is cute`

**Comment by FranKusmiruk** [comment] 2021-04-24 01:36
duplicate of #2207

**Comment by AyhamAl-Ali** [comment] 2021-04-24 01:36
I think this is related to #3838

**Closed by FranKusmiruk** 2021-04-24 01:36 UTC
