### ISSUE TITLE
Removing items does not work correctly

### ISSUE THREAD

**Issue by SoMuchWessel** [SkriptLang/Skript#2727] opened 2019-12-26 22:18 UTC
Hello,

I ran into a bug since skript 2.4-beta10.

If i have the code:
`Remove 1 dirt named "Dirt101" from player's inventory`

It will not only remove the named dirt, but it will also remove normal ones without names ect.

**Comment by Wealthyturtle** [comment] 2019-12-27 00:54
Please test on Skript 2.4.1.

**Comment by SoMuchWessel** [comment] 2019-12-27 00:55
> Please test on Skript 2.4.1.

It is in every version since skript 2.4-beta10. I first discovered it in 2.4.1 and downgraded till it worked again, which was in 2.4-beta9

**Comment by bensku** [comment] 2019-12-27 18:12
Duplicate of #2714. Good to know when it started happening, though.

**Closed by bensku** 2019-12-27 18:12 UTC
Labels: duplicate
