### ISSUE TITLE
Shield cannot appear in 'format slot...'

### ISSUE THREAD

**Issue by Eng1ner** [SkriptLang/Skript#4368] opened 2021-10-16 11:13 UTC
### Skript/Server Version

```
Server Version: git-Paper-788 (MC: 1.16.5)
Skript Version: 2.5.3
Installed Skript Addons:
- Skellett v1.9.11
- skript-yaml v1.3.2
- Reqn v1.2.1
- SkQuery v4.1.4
```

### Bug Description

While trying to format slot to shield in virtual chest it doesn't appear. I can click it so command after "to close then run" is working, but there is just empty slot. I tested both with _shield_ and _shield item_.

### Expected Behavior

Shield should normally appear in indicated slot.

### Steps to Reproduce

I tested those commands, none of them work properly. Changing slot number didn't solve the problem.
```
open chest with 1 row to player
wait 1 tick
format slot 0 of player with 1 of shield to be unstealable
format slot 1 of player with shield to be unstealable
format slot 2 of player with 1 of shield item to be unstealable
format slot 3 of player with shield item to be unstealable
```

### Errors or Screenshots

There is no errors, Skript successfully reloaded file.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by noySq** [comment] 2021-10-16 11:16
it's skquery syntax not from skript

**Comment by TPGamesNL** [comment] 2021-10-17 10:11
Duplicate of https://github.com/SkriptLang/Skript/issues/2534

**Closed by TPGamesNL** 2021-10-17 10:11 UTC
