### ISSUE TITLE
Skript can't tell difference between freshly planted wheat and fully grown wheat

### ISSUE THREAD

**Issue by Downed-new** [SkriptLang/Skript#6416] opened 2024-02-08 20:10 UTC
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://gibhut.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-409 (MC: 1.20.4)
[Skript] Skript Version: 2.8.2 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

`on mine:
	if event-block is stage 8 wheat plant:
		send "%event-block%" to player`

Basically, if i break freshly planted wheat seed it sends the message even though i only want it to send if the wheat is fully grown.
It doesn't madder whether you use "fully grown wheat plant", "stage 8 wheat plant" or "ripe wheat plant"

### Expected Behavior

It was only supposed to send the message if the wheat was fully grown.

### Steps to Reproduce

I did it on a MINEHUT server. Freshly created all default settings, first i had the issue on another server, but i thought it might be addons or something messing with skript. But after making a new server ALSO ON MINEHUT, i still had the issue.

### Errors or Screenshots

![2024-02-08_20 57 49](https://github.com/SkriptLang/Skript/assets/119142747/a9fe33d7-dc98-4e87-9be5-6774e67e17f8)
![2024-02-08_20 57 49_2](https://github.com/SkriptLang/Skript/assets/119142747/5d906435-8eb3-42bd-82d5-f7b877fd31db)
![2024-02-08_21 09 51](https://github.com/SkriptLang/Skript/assets/119142747/23552686-b7db-426c-91fd-40d529f5ea15)
![Skærmbillede 2024-02-08 211141](https://github.com/SkriptLang/Skript/assets/119142747/2f996539-b154-46f3-b1da-97d4933cca32)

I tried to find a way to copy the /Skript info command but i didn't know how, so i just typed it out by hand.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2024-02-09 23:32
Duplicate of #4582

**Closed by AyhamAl-Ali** 2024-02-09 23:32 UTC
