### ISSUE TITLE
Player Head / Skull Item -> Item Type Issue

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#1877] opened 2019-02-06 09:47 UTC
Spigot: Paper 1.13.2
Skript: Skript v2.3.2 (also tested with 2.3.3)

My script:
```
on rightclick:
	broadcast "&4%event-item%"
	if event-item is player head item:
		broadcast "test1"
		cancel event
	else if event-item is player head:
		broadcast "test2"
		cancel event
	else if event-item is skull item:
		broadcast "test3"
		cancel event
	else if event-item is player skull:
		broadcast "test4"
		cancel event

```

I am using a player skull (from a plugin called Head Database, but you can use any other custom player skull that you want) for this example.
Take it in my hand and rightclick with it on a block:

(just as a note:)
- clicking on top of a block will trigger "on block place" event and the "on rightclick" event.
- clicking on side of a block will not trigger "on block place" event but the "on rightclick" event.

The result is (screenshot):
[https://i.imgur.com/GZn0EzT.png](https://i.imgur.com/GZn0EzT.png)

But it should also broadcast any of the strings (test1, 2, 3 or 4).

**Comment by ShaneBeee** [comment] 2019-02-06 11:00
Try updating Skript to 2.3.3
Bug reports are only accepted when you are using the latest version as things may have been fixed in the recent update.

**Comment by bloggy** [comment] 2019-02-06 12:44
Sry, updated now. But bug is still there.

**Comment by bensku** [comment] 2019-02-08 19:54
Cannot reproduce. Skull item of my character (created by Skript) matches the first test case. Does this happen for someone else?

**Comment by bloggy** [comment] 2019-02-09 12:38
This is the line of code where I set the skull:

`		set {_sackitem} to a player head with nbt "{display:{Name:""%{_p}%'s Rucksack""},SkullOwner:{Id:""7a433072-a39e-ad6b-6fed-b829e1bcecb7"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTg0NTlmM2I2NWIyM2NmYThjOWIxNDQzMjViOWJhODE0MDdiZTkzODJjZDg1OTkyZWY5NzljZjBlNzgzZjYifX19""}]}}}" with name "%{_p}%'s Rucksack" with lore "&5Ein Rucksack mit tollen", "&5Sachen darin." AND "&c&oNicht platzierbar!"`

**Comment by Nicofisi** [comment] 2019-02-09 13:12
Does it work without the `with nbt`?

**Comment by bloggy** [comment] 2019-02-09 22:10
yes it does work without `with nbt`

**Comment by bensku** [comment] 2019-02-23 11:50
Bukkit API is not exactly good for dealing with NBT. I'm not sure how this could be fixed.

**Comment by TheBentoBox** [comment] 2019-02-26 14:11
@bloggy Does this still occur in 2.3.5? Another item comparison issue was fixed since 2.3.3.

**Comment by bloggy** [comment] 2019-03-02 12:33
@TheBentoBox it seems to work now in 2.3.5

**Comment by bensku** [comment] 2019-03-02 13:00
Nice!

**Closed by bensku** 2019-03-02 13:00 UTC
