### ISSUE TITLE
please 1.8.8 Minecraft :D

### ISSUE THREAD

**Issue by crazymusic21** [SkriptLang/Skript#3851] opened 2021-03-25 13:26 UTC
Plase 1.8.8 servers _D

**Comment by TPGamesNL** [comment] 2021-03-25 13:40
Duplicate of https://github.com/SkriptLang/Skript/issues/847

**Closed by TPGamesNL** 2021-03-25 13:40 UTC

**Comment by WeeskyBDW** [comment] 2021-03-25 14:00
See [Matacolote Skript fork for 1.8](https://github.com/Matocolotoe/Skript-1.8)
