### ISSUE TITLE
[1.14] inventory of event-block

### ISSUE THREAD

**Issue by OverBrave** [SkriptLang/Skript#2138] opened 2019-06-04 19:11 UTC
### Description

```
on break of barrel: 
    name of inventory of event-block is "&3&lS&c&lC&b&lSAT"
```

this skript not working on 1.14.2

### Server Information
* **Server version/platform:**      Paper #65 1.14.2
* **Skript version:**                2.4-alpha3

**Comment by TheBentoBox** [comment] 2019-06-04 19:33
Not working how? That script alone would do nothing but I assume you have code after that and the conditional isn't running. Are there any errors?

**Comment by Moderocky** [comment] 2019-06-04 19:42
I believe this expression was missed when everything was moved to use inventory titles instead of names in 1.14.
Getting it always returns null, though there is no error.
Setting it does nothing.

The fact that this section:
![image](https://user-images.githubusercontent.com/14147477/58908686-1ba89800-8709-11e9-8c2a-dbbae0e6884d.png)
is commented out, might suggest that it was just missed from the release.
It's from this [ExprName](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprName.java) class I think.

**Comment by OverBrave** [comment] 2019-06-04 21:00
> Not working how? That script alone would do nothing but I assume you have code after that and the conditional isn't running. Are there any errors?


This is an example. The skript we wrote after this do not work.

**Comment by ShaneBeee** [comment] 2019-06-04 21:01
This is a duplicate of #2069

**Closed** 2019-06-04 21:15 UTC
