### ISSUE TITLE
"Contains" Doesn't Work When List is Empty

### ISSUE THREAD

**Issue by Bartuzen** [SkriptLang/Skript#1493] opened 2018-08-29 17:11 UTC
```
command /s:
    trigger:
        {_s::*} contains "a":
            send "contains"
        {_s::*} doesn't contain "a":
            send "doesnt contain"
```
{_s::*} is empty. This command send nothing to me. Both "contains" and "doesn't contain" return false it the list is empty.

**Comment by TheBentoBox** [comment] 2018-08-29 17:15
What version of Skript are you running?

**Comment by Nicofisi** [comment] 2018-08-30 14:11
Can somebody please check whether this happens too for example with `%entities% are in world %world%` vs `%entities% aren't in world %world%` or `"%livingentities% are wearing %itemtypes%` vs  `"%livingentities% aren't wearing %itemtypes%`? If so then the `.check` method of the SimpleExpression class might require some modification

**Comment by Blueyescat** [comment] 2018-08-30 14:34
Isn't this related to how the contains check works? 
```java
for (Object o : all) {
	if (Relation.EQUAL.is(Comparators.compare(o, item)))
		return true; // Found equal, success!
}
return false; // Not found
```
It will return false directly and it will be true because negated.

**Comment by bensku** [comment] 2018-10-09 18:38
This has been reported previously - see #404. It is also intended behavior; variables that do not exist are not lists. It is a bit confusing, though, especially since adding to nothingness creates a list.

Feedback on this welcome. If we decide to change this, it shouldn't be too hard.

**Comment by TheBentoBox** [comment] 2018-10-09 18:48
Smart programming with Skript often includes handling false or disabled states by having the variable not exist at all. This isn't possible in many languages but in Skript we have the freedom to say `if {_random garbage variable name} is set` which saves on both memory and load time. That being the case, my opinion is that unset variables should be respected somewhat like a falsy value because we know that people will be checking values against unset variables as if they were set. So IMO an unset variable should effectively act like a set-but-empty list for all intents and purposes - adding stuff to it works, removing stuff does nothing but doesn't fail/error, and checking `contains` against it never passes while `doesn't contain` should always pass.

**Comment by Nicofisi** [comment] 2018-10-14 11:34
With my recent commit doing for example `players in world "world" doesn't contain {_some.online.player}` when no players are in the world `world` should return true, but with list variables the issue (described by @bensku) still exists, and I agree with @TheBentoBox here:
> IMO an unset variable should effectively act like a set-but-empty list for all intents and purposes

**Comment by Blueyescat** [comment] 2019-09-06 21:50
This is already fixed with the last changes on CondContains.

**Closed** 2019-09-06 23:09 UTC
Labels: enhancement, priority: medium
