### ISSUE TITLE
Edit: Variables between "%" do not work correctly (Only console does work.)

### ISSUE THREAD

**Issue by Agnax** [SkriptLang/Skript#2298] opened 2019-07-25 05:04 UTC
### EDIT: 
Ok, what really happens is that the variables between "%" do not work correctly, it only works when they are sent to the console.

### Description
In the last update, the "loop all players" does not work properly, and leaves residues of the last loop.
It only happens in the loop, if you send the message directly to the console, it does not happen.

### Steps to Reproduce

 **The loop does not need to be in a function for the error to occur.**

Example 1:
```
command /sc [<text>]:
	executable by: players
	trigger:
		if arg is set:
			MandarMsj(player,argument)

function MandarMsj(j:player,m:text):
	loop all players:
		if loop-player has permission "insanitychat.staff":
			send "&6&l%{_j}% &f&l> &e%{_m}%" to loop-player
			play sound "entity.arrow.hit_player" with volume 0.2 with pitch 1.2 at loop-player
	send "&6&l%{_j}% &f&l> &e%{_m}%" to console
```
Example 2:
```
command /sc [<text>]:
	executable by: players
	trigger:
		if arg is set:
			loop all players:
				if loop-player has permission "insanitychat.staff":
					send "&6&l%player% &f&l> &e%arg%" to loop-player
					play sound "entity.arrow.hit_player" with volume 0.2 with pitch 1.2 at loop-player
			send "&6&l%{_j}% &f&l> &e%{_m}%" to console
```

### Expected Behavior
- It does not give errors in the console.
- From what I've tested, it only happens with loop all players.
- It only happens in the last update, if I go back to the previous one, it stops happening.

### Errors / Screenshots
GIF:
https://gyazo.com/6a6c1402c663968160c144dcd758c3e3
In Game:
https://gyazo.com/ec285009753b49d7bc4c6f6a9124fc2e
Console:
https://gyazo.com/0e95c74cebb92d3383c91d04e0e652dd

### Server Information
* **Server version/platform:**       1.14.4/Paper
* **Skript version:**                2.4-beta3 released

### Additional Context

- As seen in the image, the player and the message accumulate infinitely.
- In the two examples I inserted, the same thing happens
- The server is running locally.
- I already tried it on a hosted server, the same thing happens.
- It only happens in the update.

**Comment by bensku** [comment] 2019-07-28 08:42
Duplicate of #2279.

**Closed by bensku** 2019-07-28 08:42 UTC
