### ISSUE TITLE
lore list value

### ISSUE THREAD

**Issue by noy98** [SkriptLang/Skript#1840] opened 2019-01-21 08:42 UTC
### Description

 I put lore of an item to list value, when I clicked item on inventory click, but it doesn't work
### Steps to Reproduce

set {_lore::*} to lore of clicked item
		{_lore::*} is not set:
			stop
		{_lore::*} doesn't contain "구매가격":
			{_lore::*} doesn't contain "판매가격":
				stop
### Server Information
* **Server version/platform:**      1.12.2 
* **Skript version:**               2.3.2

**Comment by ShaneBeee** [comment] 2019-01-21 09:11
Someone may have a better answer than me, but from my understanding this is why.
When checking a list if it contains something, it is checking if your object matches each value individually as a whole. Therefor its comparing the object to each line of the lore.

Two ways around it
1) Loop the list and check the value against the loop value
```
loop {_lore::*}:
    if loop-value contains "whatever you are checking for":
        do something
```
2) or you can do a silly way (but it works)
```
if "%lore of player's tool%" contains "whatever you are checking for"
```
Option two is much shorter, and works like a charm. It may look silly, but it's a lot less effort.

**Comment by Snow-Pyon** [comment] 2019-01-21 11:21
Duplicate of #1838.

**Closed by Snow-Pyon** 2019-01-21 11:21 UTC
