### ISSUE TITLE
Articles and plurality markers automatically removed when surrounding expressions

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#367] opened 2017-01-29 15:08 UTC
If (for example) {_faction} is "black"

> send message "You are not a member of the %{_faction}% faction" to the player

returns

> You are not a member of black faction

Missing "the"

**Comment by Pyon-Pyon** [comment] 2017-01-29 15:11
That's surely the Advanced Syntax feature of Skript, try doubling the `the` or putting it on the variable.

**Comment by JeepSmash** [comment] 2017-01-29 20:47
I was able to duplicate this issue. This is definitely a bug. However it only does this if the text has no formating.  If you apply a color or format code to the "the" it will be displayed properly and if you don't want it colored you can place a &r and it will remain.   
Work Around Examples that work properly:
`		set {_faction} to "black"
		message "&bYou are not a member of &bthe %{_faction}% faction"
		message "You are not a member of &rthe %{_faction}% faction"`

**Comment by TheBentoBox** [comment] 2017-01-31 20:44
As Pyon said, this is a result of the Advanced Syntax feature of Skript, which means it's not really a "bug" necessarily. However, it does cause issues like this sometimes, and I don't really see why Skript should interfere with hard-coded parts of texts, so we'll see if Bensku wants to do anything about this or just leave it as is.

**Comment by bensku** [comment] 2017-02-07 19:52
Tagging this as enhancement. At some point you should be able to at least use config to turn advanced syntax off.

**Comment by TheBentoBox** [comment] 2019-04-19 14:37
Since this has been brought up multiple times by other issues in the past year... has this EVER been desired by anyone? I've never found this feature useful and it's only ever caused me (and many others as the issues make clear) strange bugs that can only be fixed by extra hard-coded "a"s and "the"s in my strings.

It's been put off for a long time but I really think this functionality could basically be hard deleted with no config option and nobody would miss it, unless it's doing something subtle and useful which I'm missing.

**Comment by Misio12320** [comment] 2020-01-24 06:52
When this will be added??? 3 *& years waiting..

**Comment by bluelhf** [comment] 2020-03-25 07:43
@Nicofisi Yes, #2840 is indeed a duplicate of some weirdly named issue! 

My proposed solution would be to have advanced syntax disabled by default, and have a config option to enable it in the rare case that anyone wants it.

**Comment by TheBentoBox** [comment] 2020-03-25 13:32
I've updated this to finally have a more explanatory and hopefully understandable title.

**Closed** 2021-05-23 18:15 UTC
Labels: completed, enhancement, priority: low
