### ISSUE TITLE
all (something) doesn't return a list with some objects

### ISSUE THREAD

**Issue by J-ak-e** [SkriptLang/Skript#5109] opened 2022-09-22 00:42 UTC
### Skript/Server Version

```markdown
[02:34:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/Skriptlang/skript-aliases 
[02:34:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/ 
[02:34:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials 
[02:34:51 INFO]: [Skript] Server Version:git-Paper-161 (MC: 1.19.2)
[02:34:51 INFO]: [Skript] Skript Version: 2.6.3 (02:34:51 INFO): Skript Installed Skript Addons: 
[02:34:51 INFO]: [Skript] - Disky v4.3.0 
[02:34:51 INFO]: [Skript] - skript-yaml v1.4 
[02:34:51 INFO]: [Skript] - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect) 
[02:34:51 INFO]: [Skript] - SkBee v2.3.1 (https://github.com/ShaneBeee/SkBee) 
[02:34:51 INFO]: [Skript] - Skript-Packet v2.1.0 (www.github.com/Anarchick/skript-packet) 
[02:34:51 INFO]: [Skript] Installed dependencies: 
[02:34:51 INFO]: [Skript] - Vault v1.7.3-b131
```

### Bug Description

`all ores`
`all armor`
`all helmets` (same for chestplates, leggings and boots)
`all swords` (same for hoes, axes, pickaxes and shovels)
don't return a list, 

### Expected Behavior

they should return a list of all the item types

### Steps to Reproduce

`send random element of (all swords)`
`send random element of (all ores)` and so on

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-09-22 17:18
What does it return instead?

**Comment by Fusezion** [comment] 2022-09-23 13:20
To add onto this. it's not that is doesn't return a list it's that it returns a formatted list as if we did `send "%all chestplates%"`
a quick test for this is doing

`give player all chestplates` works as intended
`give player random element out of chestplates` gives me all chestplates instead of a single one
`give player random item out of all chestplates` will only give 1 item

by formatted I mean like this 
![image](https://user-images.githubusercontent.com/81952476/191969173-a3167eab-57d7-4e0d-b691-ca7950f6d874.png)

and not like how you normally see returned list of objects
![image](https://user-images.githubusercontent.com/81952476/191969382-f00bd62f-93bc-4904-95d0-f61d1417d83f.png)

**Comment by DelayedGaming** [comment] 2022-09-23 13:49
These are intended behavior as they are not actual expressions, but **aliases**.
You can take a look at your aliases file and locate these.

**Comment by TheLimeGlass** [comment] 2022-09-24 08:37
It was changed when the aliases got reworked. It used to work how you think.

I think all chest plates should return all chest plates and a random itemtype out of all chest plates should return one chest plate.

**Comment by TheLimeGlass** [comment] 2023-01-24 01:20
Will probably be in 2.7 when we build latest branch off aliases repo.

**Comment by TheLimeGlass** [comment] 2023-01-24 01:30
All of these work except for the ores which is fixed in a pull request on aliases repo.

**Comment by J-ak-e** [comment] 2023-02-04 05:39
Amazing, a lot of people will be happy because of this.

**Closed** 2023-03-10 20:09 UTC
Labels: bug, priority: low, completed, aliases
