### ISSUE TITLE
SkriptLoader Error

### ISSUE THREAD

**Issue by PrtyBlk** [SkriptLang/Skript#2971] opened 2020-05-06 17:20 UTC
### Description
```
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: PID: 25 | Suspended: false | Native: false | State: RUNNABLE
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: Stack:
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.nextBracket(SkriptParser.java:1298)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1533)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1565)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1526)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:224)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.lang.Statement.parse(Statement.java:59)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1041)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:694)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:410)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader$$Lambda$3649/0x000000080122d040.run(Unknown Source)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:429)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:348)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader$$Lambda$3647/0x000000080122d840.run(Unknown Source)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:381)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: ch.njol.skript.Skript$2.run(Skript.java:592)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: app//net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
06.05 13:18:35 [Server] Startup [17:18:35 ERROR]: java.base@11.0.6/java.lang.Thread.run(Unknown Source)
```

### Server Information
* **Server version/platform:**       Paper v253
* **Skript version:**                2.5-a3

**Comment by BurntValentine** [comment] 2020-05-06 18:27
Possibly the same issue as #2945 - try backdating to Paper 1.15.2 build 209 without changing anything else on your server, see if it helps.

**Comment by ShaneBeee** [comment] 2020-05-12 09:26
Duplicate of #2945 
As closing this due to an extreme lack of information.

**Closed by ShaneBeee** 2020-05-12 09:26 UTC
