### ISSUE TITLE
Issues with viewing (pasting) blocks for client past build height

### ISSUE THREAD

**Issue by Bramsies** [SkriptLang/Skript#4434] opened 2021-11-22 20:11 UTC
### Skript/Server Version

```
[15:02:08 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:02:08 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[15:02:08 INFO]: [Skript] Server Version: git-Paper-280 (MC: 1.17.1)
[15:02:08 INFO]: [Skript] Skript Version: 2.6
[15:02:08 INFO]: [Skript] Installed Skript Addons:
[15:02:08 INFO]: [Skript]  - Skent v3.1.0
[15:02:08 INFO]: [Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[15:02:08 INFO]: [Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[15:02:08 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[15:02:08 INFO]: [Skript]  - Reqn v1.2.3
[15:02:08 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[15:02:08 INFO]: [Skript]  - SkQuery v4.1.5
[15:02:08 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

I've managed to adjust the server's max build height through a data pack (specifically to y0 - y1024)

I'm copying blocks from one location to another -- I'm having no issues placing the blocks; it's actually displaying the blocks to players that seems to be the problem. Parts of the pasted blocks aren't shown to the player, but are in fact there (if you apply a block update to them they appear).

### Expected Behavior

The blocks are pasted and shown fine below 256, but above 256 they are not shown correctly.

### Steps to Reproduce

```
set block at {_loc} to {_block}
```
+ Max build height change

### Errors or Screenshots

N/A

### Other

I'd like to reiterate that the blocks are in fact **there** -- they can be made visible again via something along the lines of
```make all players see loop-block as loop-block```
This is however very taxing, inefficient and resets said blocks on relog.
-- Relogging does not fix the issue, it merely hides the blocks again --

Thanks :)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-11-23 18:38
I don't think this is a problem from Skript, rather Minecraft/CraftBukkit/Spigot/Paper if anything. I searched in the project, Skript doesn't have any hardcoded references to the maximum world height, it only uses calls to `WorldInfo#getMaxHeight`. This would also explain why the blocks are actually there, just not visible initially. 

I see you're using skript-reflect, try `(block at {_loc}).setType(Material.STONE)` (with import `org.bukkit.Material`) to see if that gives the same result

**Comment by ShaneBeee** [comment] 2021-11-26 17:31
> I don't think this is a problem from Skript, rather Minecraft/CraftBukkit/Spigot/Paper if anything. I searched in the project, Skript doesn't have any hardcoded references to the maximum world height, it only uses calls to `WorldInfo#getMaxHeight`. This would also explain why the blocks are actually there, just not visible initially.
> 
> I see you're using skript-reflect, try `(block at {_loc}).setType(Material.STONE)` (with import `org.bukkit.Material`) to see if that gives the same result

Skript 2.6 does not include this fix, I did that PR after Skript 2.6 came out I believe

Anyways, closing as this is a duplicate of #4324 
Theres also a new PR I did recently which fixes a mistake I did that doesnt allow for going to the new world height, #4440

**Comment by TPGamesNL** [comment] 2021-11-26 17:53
@ShaneBeee That issue (and PR fixing it) is about the minimum height, this one is about the maximum height, the PR will not have fixed it

**Comment by ShaneBeee** [comment] 2021-11-26 17:56
> @ShaneBeee That issue (and PR fixing it) is about the minimum height, this one is about the maximum height, the PR will not have fixed it

1) the min height issue was fixed a while ago by a PR I did AFTER 2.6 was released. Ive tested it in my own build works perfect
2) the new PR I have is to fix max build height (as I made a mistake in that other PR and didnt change the height setup)

**Comment by TPGamesNL** [comment] 2021-11-26 17:57
This issue isn't about minimum height, nor is the AABB class involved.

**Comment by ShaneBeee** [comment] 2021-11-26 18:01
oh crap, I was thinking about this wrong then.

Anyways, I am able to set blocks past 256 with Skript no problem. 
<img width="966" alt="Screen Shot 2021-11-26 at 10 00 26 AM" src="https://user-images.githubusercontent.com/20008482/143617787-92c558ec-2b43-411a-bc1a-e985ce44cbc5.png">

**Comment by TPGamesNL** [comment] 2021-11-26 18:02
In that case we can close it anyway, as it is more likely to be a server issue anyway :P

**Closed by TPGamesNL** 2021-11-26 18:02 UTC
Labels: waiting for reply
