### ISSUE TITLE
Iron doors with left or right hinges parse as strings differently 

### ISSUE THREAD

**Issue by bessel28** [SkriptLang/Skript#3244] opened 2020-07-29 19:51 UTC
### Description
iron doors with hinges on the right when parsed as strings always get set to "iron door" no matter which way they are facing or if they are powered while iron doors with hinges on the left when parsed as strings contain the direction they are facing, what half they are and if they are powered (im sure theres more i dont know about too).

### Steps to Reproduce
i used:
```
on click on door:
	set {_block} to "%event-block%"
	broadcast {_block}
```
and set up two blocks, then walk anticlockwise around one and clockwise around the other to place the doors with hinges on the right and left around either of the blocks. then clicking them shows "iron door" for all with hinges on the right and something along the lines of "top-half eastward iron door" for the doors with hinges on the left
### Expected Behavior
all the doors should say the full amount of detail so we can use the strings to check if doors are powered

### Screenshots
![image](https://user-images.githubusercontent.com/68969379/88845822-a0435900-d1dc-11ea-9c6b-ddbf6f1f457c.png)

### Server Information
* **Server version/platform:** git-Paper-108 (MC: 1.16.1)
* **Skript version:** 2.5-alpha6-MH

**Comment by ShaneBeee** [comment] 2020-07-31 01:43
Duplicate of #2006

This is just due to Skript retrieving the default state of a block.

**Closed by ShaneBeee** 2020-07-31 01:43 UTC
