### ISSUE TITLE
Make wearing condition ignore non-specified meta

### ISSUE THREAD

**Issue by kleinesgumi** [SkriptLang/Skript#420] opened 2017-03-06 13:20 UTC
#### Description
Currently, the wearing condition works exactly the same as the comparison condition, which makes it pretty useless. The suggestion is to make the wearing condition ignore meta that isn't specified on the statement.

**Comment by kleinesgumi** [comment] 2017-03-06 13:21
on every 1 seconds:
	loop all players:
		if loop-player is wearing a chestplate with name "&aTest":
			apply health boost to the loop-player for 15 seconds

**Comment by kleinesgumi** [comment] 2017-03-07 10:34
i have a leather helmet with only "&aTest" works fine but i enchant or dye it not work anymore.

**Comment by TheBentoBox** [comment] 2017-03-07 15:44
That's because the "is" conditional checks for stuff to exactly equate. If you test if they're wearing a `leather helmet named "&aExample"`, it will want it to be a plain leather helmet with that name and nothing else. I'm not sure if it's something that can be fixed in the near future. 

Certainly not a bug, but it'd be nice if Skript instead split apart the parameters of the item stack and compared if each one holds true for the comparing item instead of checking if the whole item stack perfectly equals the other. I'll tag @bensku to see what he thinks on it, but if he's happy with how the condition works now, this may just get closed.

For now, you can separate the conditions yourself, e.g.

```
player is wearing a leather helmet
player's helmet's name is "&aTest"
```

These will both pass even if it's dyed any color.

**Comment by bensku** [comment] 2017-03-10 11:07
I will see if this can be fixed. Doesn't seem to make a lot sense right now.

**Comment by skripttpbug2** [comment] 2017-03-11 02:03
or with skquery - `if check [player is wearing a leather helmet]->[name of player's helmet is "test"]:` if  you want a one liner

**Comment by ShaneBeee** [comment] 2020-08-06 22:06
I did some testing.

Test Code:
```vb
command /test:
    trigger:
        set {_a} to a diamond helmet of unbreaking 3 named "BOB" with lore "some lore" and "more lore"
        dye {_a} green
        set player's helmet to {_a}
        wait 1 tick
        if player is wearing a diamond helmet named "BOB" with lore "some lore" and "more lore":
            send "&aYAY HELMET MATCHES type, name and lore" to console
        else:
            send "&cBOO NO MATCH type, name and lore" to console

        if player is wearing  a diamond helmet named "BOB":
            send "&aYAY HELMET MATCHES type and name" to console
        else:
            send "&cBOO NO MATCH type and name" to console

        if player is wearing a diamond helmet with lore "some lore" and "more lore":
            send "&aYAY HELMET MATCHES type and lore" to console
        else:
            send "&cBOO NO MATCH type and lore" to console

        if player is wearing a diamond helmet:
            send "&aYAY HELMET MATCHES type" to console
        else:
            send "&cBOO NO MATCH type" to console
```

Result:
<img width="842" alt="Screen Shot 2020-08-06 at 3 05 35 PM" src="https://user-images.githubusercontent.com/20008482/89587334-4ce19400-d7f6-11ea-8234-159b79856f3e.png">

bensku did some comparison fixes a little while back. Im guessing those fixes also fixed this issue.

Closing this as this does not seem to be an issue anymore.

**Closed by ShaneBeee** 2020-08-06 22:06 UTC
Labels: completed, enhancement, priority: lowest
