### ISSUE TITLE
" player has item " code is not working in skript functions

### ISSUE THREAD

**Issue by Pledix** [SkriptLang/Skript#754] opened 2017-07-29 19:01 UTC
" player has item " code is not working in skript functions

My server version spigot 1.12
My skript version latest now dev build

i get not error
i wait your answer

example usage:
 `if {_p} has 5 leather:`

**Comment by melinstagibson** [comment] 2017-07-29 19:19
Same here. 
Tried Using 'if player has x of {@itemoption}' and it didnt work either. I had to work around with it by using 'if Player's inventory contains x of item'

**Comment by TheBentoBox** [comment] 2017-08-01 19:08
Can confirm, also on 1.12

**Comment by bensku** [comment] 2017-08-01 20:24
Oh, wonderful... This will be so _fun_ to debug :(

**Comment by melinstagibson** [comment] 2017-08-21 20:55
or just make it so it throws an error or disable the syntax? i use it mostly for stuff thats actually important on the server like checking conditions for trades and such.

**Comment by xbxymax** [comment] 2017-09-22 11:18
You need to use it this way 
if {_p}'s inventory has 5 leather:

**Comment by Pikachu920** [comment] 2017-09-22 22:18
@xbxymax Well, then it would be an issue related to an addon.

**Comment by infmemory** [comment] 2017-12-21 00:58
I recently ran into this issue.
I set a variable {_price} to a line from a sign _parsed as item_.
`set {_price} to uncolored line 4 of event-block parsed as item`

I used `if player has {_price}:` but it always returned false.
When I used **is holding** it resulted in true when holding the item stack. As expected.

My problem was setting the {_price} variable to **item** and not **item type**

Example:
`set {_item} to uncolored line 2 of event-block parsed as item type`

```
if player has {_price}:
    message "yay"
else:
    message "nay"
```

Maybe this could be mentioned in the doc ([#CondContains](http://bensku.github.io/Skript/conditions.html#CondContains))?

Hope this helps someone.

**Comment by TheLimeGlass** [comment] 2018-04-21 05:46
Can someone check if this issue was fixed in dev-35 there were a few fixes to the contains.

**Comment by xbxymax** [comment] 2018-04-21 05:49
This is your plug-in problem. You put SkQuery's mysql code inside Skellett. I have already found someone to delete the related code. Now there is no problem.

**Comment by xbxymax** [comment] 2018-04-21 05:51
**if {_p}'s inventory has 5 leather:**

**Comment by TheLimeGlass** [comment] 2018-08-25 09:29
The CondContains doesn't handle Variables correctly. I have got Bensku to check it out since he last modified it prior to this issue.

A workaround for now is
```
function test(p: player) :: text:
	if "%{_p}%" parsed as player has 5 stone:
		return "&aFound %{_p}%"
	else:
		return "&cNegative %{_p}%"
```
Using parse.

**Comment by SiebeDW** [comment] 2019-08-06 10:20
```
function test(p: player) :: text:
	if {_p} has 5 of stone:
		return "&aFound %{_p}%"
	else:
		return "&cNegative %{_p}%"
command /test:
	trigger:
		message test(player)```
Cannot reproduce with this code. When i have 5 stone i get "Found SiebeDW" and when i dont have 5 stone i get "Negative SiebeDW". I think this is fixed.

**Comment by TheBentoBox** [comment] 2019-08-06 13:40
I'd like slightly more verification on this one since it has existed for so long but that's great to hear!

**Comment by Blueyescat** [comment] 2019-09-05 11:37
I can't confirm @SiebeDW, still works with parsing etc.

**Comment by SiebeDW** [comment] 2019-09-06 06:15
Weird. I will try it again later this day.

**Comment by SiebeDW** [comment] 2019-09-06 16:35
Using this skript:
![image](https://user-images.githubusercontent.com/29002908/64444345-3c9bd300-d0d4-11e9-9c42-b0d3ad881c16.png)
I get this:
https://streamable.com/wfcc8
Tested on:
1.12.2 (Video)
1.14.4
Skript Version:
![image](https://user-images.githubusercontent.com/29002908/64444549-aae09580-d0d4-11e9-8dd3-3d4d97c5d266.png)

So i think this is not an issue or am I misunderstanding this?

**Comment by Blueyescat** [comment] 2019-09-06 19:07
Hmm yea, i tried again and it works as expected. But somehow when i last tried it didn't work.
Also i'm working on the `contains` condition to rework it and fix some other things, and i have found a thing that causes this issue. Not sure what is going on, but the issue can be closed i guess.

**Comment by ShaneBeee** [comment] 2020-03-02 10:36
I did some testing (on both 1.15.2 and 1.12.2 using **Skript 2.5-alpha2**) with the following code:

```vb
command /test:
    trigger:
        test(player)

function test(p: player):
    if {_p} has 5 leather:
        send "&aHAS 5 LEATHER" to {_p}
    else:
        send "&cDOES NOT HAVE 5 LEATHER" to {_p}
```

## Outcome:
### No leather in my inventory
![](https://i.imgur.com/RCOQWOZ.png)

### With leather in my inventory
![](https://i.imgur.com/SNSyzDY.png)

Needless to say, I believe this issue has been resolved.

**Closed** 2020-03-02 10:36 UTC
Labels: bug, completed, priority: medium
