### ISSUE TITLE
Severe Error

### ISSUE THREAD

**Issue by AlexBartles** [SkriptLang/Skript#6330] opened 2024-01-14 19:55 UTC
### Skript/Server Version

```markdown
[19:52:32 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:52:32 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:52:32 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:52:32 INFO]: [Skript] Server Version: git-Paper-386 (MC: 1.20.4)
[19:52:32 INFO]: [Skript] Skript Version: 2.8.0-pre2 (skriptlang-github)
[19:52:32 INFO]: [Skript] Installed Skript Addons: None
[19:52:32 INFO]: [Skript] Installed dependencies:
[19:52:32 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

I ran my command and got this severe error. I tried without arguments and with. Same result.

### Expected Behavior

It was meant to ban everyone online.

### Steps to Reproduce

Run my command with or without any arguments!

### Errors or Screenshots

https://paste.gg/p/anonymous/015b2a33288b4dd298be10c026076e21

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2024-01-14 19:59
So go ahead and do /stop on the server once that fully closes start your server

**Comment by AlexBartles** [comment] 2024-01-14 20:47
> So go ahead and do /stop on the server once that fully closes start your server

I restarted my server and that did nothing.

**Comment by AyhamAl-Ali** [comment] 2024-01-15 12:57
Probably duplicate of #6165 which have been seen multiple times now but I doubt it's from our side, probably as Kenzie said it might be related to pluginman or corrupted file. Please try to download the file again from Github and make sure your server JAR is not corrupted as well.

**Closed by AyhamAl-Ali** 2024-01-15 12:57 UTC
