### ISSUE TITLE
Server hangs long times when using syntax with the long processing time

### ISSUE THREAD

**Issue by myheart3123** [SkriptLang/Skript#3652] opened 2020-12-23 02:43 UTC
### Steps to Reproduce

When uses like a `{variable} parsed as the offline player` or waiting for responses.

### Expected Behavior

Skript should make process threads for that when syntax takes a long time.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/44206495/102953146-fb6f4280-4513-11eb-9a58-592c69a05948.png)
After around 5 seconds:
![image](https://user-images.githubusercontent.com/44206495/102953183-0e821280-4514-11eb-9133-387d6cd82129.png)

### Server Information
* **Server version/platform:** Tuinity-cc34294 (fork of Paper) 
* **Skript version:** 2.5.4

**Comment by Pikachu920** [comment] 2020-12-23 13:48
unfortunately it is not possible to make expressions async

**Comment by TPGamesNL** [comment] 2021-02-21 14:26
This would partially be fixed by https://github.com/SkriptLang/Skript/pull/3764, as the example image shows an invalid name. The other part, offline player resolving taking a long time: there's not much to do about that, besides doing it async, which could be done with a separate syntax in the effect suggested by #3561.

**Comment by myheart3123** [comment] 2021-02-23 14:37
I found a solution a few days ago. 
Just use the `$ thread` effect included with skQuery and write your code under it.

**Comment by AzonFR** [comment] 2021-03-14 14:19
Using skript-reflect we can use sections running async.
Example: 
![08206bcd06d82709631f4518bdfbc2ca](https://user-images.githubusercontent.com/63419139/111071862-62c7dd80-84d8-11eb-8ee5-e9b8636cf179.png)
(The regex condition isn't very useful since #3764)
Sections explained: https://tpgamesnl.gitbook.io/skript-reflect/advanced/reflection/sections

**Comment by TPGamesNL** [comment] 2021-08-15 15:28
Duplicate of https://github.com/SkriptLang/Skript/issues/3742 / https://github.com/SkriptLang/Skript/issues/3561

**Closed by TPGamesNL** 2021-08-15 15:28 UTC
