### ISSUE TITLE
Functions error

### ISSUE THREAD

**Issue by Fenish** [SkriptLang/Skript#2548] opened 2019-10-10 15:38 UTC
When i reload **"Folder\Test.sk"** it gives this error

```java
[18:32:45 ERROR]: A function named 'test' already exists in script 'folder\test.sk' ( folder\test.sk, line 21: function test():')
```

**folder\test.sk**
```vb
Function test():
         broadcast "1"
```

**Edit**
I figured something.
When i first reload script file **No Errors**
but i reloaded again it gives this error

**Edit number 2**
I think this is not about folder this is about functions

**Edit number 3**
NOT! this is totally about folders

Script file before reload
https://cdn.discordapp.com/attachments/335009741505822721/631879576674369537/unknown.png

Script file when first reload
https://cdn.discordapp.com/attachments/335009741505822721/631879635894009867/unknown.png

Script file when second reload
https://cdn.discordapp.com/attachments/335009741505822721/631879690864427050/unknown.png

**Comment by noftaly** [comment] 2019-10-10 17:19
> this is totally about folders
then it is a duplicate of #2461

**Comment by TheBentoBox** [comment] 2019-10-10 17:31
Duplicate of #2461.

**Closed by TheBentoBox** 2019-10-10 17:31 UTC
