### ISSUE TITLE
Can't set a tab list name using variables for player

### ISSUE THREAD

**Issue by Guarmanda** [SkriptLang/Skript#539] opened 2017-05-01 09:38 UTC
The following line doesn't works:
set tab list name of {_player} to coloured arg 2 
but the following lines works:
set tab list name of player to coloured arg 2
set tab list name of arg 1 to coloured arg 2

I tried to parse {_player} as player, but the error "tab list name of {_player} can't be set to anything" still appears.

**Comment by TheBentoBox** [comment] 2017-05-01 19:20
How is `{_player}` being set in the context of the first line?

**Comment by Guarmanda** [comment] 2017-05-01 19:28
I set {_player} using:
set {_player} to player 
and
set {_player} to arg 1 (arg 1 being a player)
I wante to use {_player} and define it at the top of the command to write less lines, but at first, I used player or arg 1. (the lines I posted in my first post)

**Comment by Snow-Pyon** [comment] 2017-05-01 20:13
Can confirm this behavior, had this issue while working on my Tab script.

**Comment by Blueyescat** [comment] 2017-05-23 15:22
Same for me.

**Comment by bensku** [comment] 2017-09-20 15:47
Does this still happen? Might have been related to a parser bug that has been already fixed.

**Comment by TheLimeGlass** [comment] 2018-05-03 00:40
Still a thing, the issue is the expression class ExprName not taking into account variables or Skript not converting the variable to the proper object before sending to a PropertyExpression, thus making the NameType get methods return null because the object may still be in variable format.

**Comment by Guarmanda** [comment] 2018-05-03 08:05
Seems like there is moments when I don't say stupid things x)
This code, however, is working:
```command /tablist <player> <text>:
	trigger:
		set {_player} to arg 1
		set tablist name of "%{_player}%" parsed as player to arg 2```

**Comment by FranKusmiruk** [comment] 2020-07-09 23:24
A recent commit may have fixed this, marking as complete unless someone can confirm the bug still exists.

**Closed** 2020-07-21 05:31 UTC
Labels: bug, completed, priority: medium
