### ISSUE TITLE
location error

### ISSUE THREAD

**Issue by Lakingsun** [SkriptLang/Skript#2367] opened 2019-08-13 08:49 UTC
### Description

if I use location function, I get a bukkit error
### Steps to Reproduce

```
on load:
	set {loc} to location(0,0,0)
```
### Expected Behavior

set {_loc1} to location 0, 0, 0
### Errors / Screenshots

```
[17:40:35] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[17:40:35] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:40:35] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[17:40:35] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Stack trace:
[17:40:35] [Server thread/ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:314)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:1)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:217)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:754)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:773)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:406)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:425)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[17:40:35] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:183)
[17:40:35] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:40:35] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[17:40:35] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887)
[17:40:35] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[17:40:35] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Version Information:
[17:40:35] [Server thread/ERROR]: #!#!   Skript: 2.4-beta5 (latest)
[17:40:35] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[17:40:35] [Server thread/ERROR]: #!#!     Date: 2019-08-04
[17:40:35] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[17:40:35] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[17:40:35] [Server thread/ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[17:40:35] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Server platform: Spigot
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Current node: null
[17:40:35] [Server thread/ERROR]: #!#! Current item: set {_loc}(as java.lang.Object) to location([[long:0]], [[long:0]], [[long:0]])
[17:40:35] [Server thread/ERROR]: #!#! Current trigger: script load (script load) (test.sk, line 1)
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Thread: Server thread
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! Language: english
[17:40:35] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[17:40:35] [Server thread/ERROR]: #!#!
[17:40:35] [Server thread/ERROR]: #!#! End of Error.
[17:40:35] [Server thread/ERROR]: #!#!
```

### Server Information
* **Server version/platform:**         1.14.4/spigot
* **Skript version:**                  skript 2.4 beta5

**Comment by Matocolotoe** [comment] 2019-08-14 11:35
Duplicate of #1767 
Also you need to indicate the world in which the location is to solve the problem, for example `location(0, 0, 0, world("world"))`

**Closed** 2019-08-15 02:48 UTC
