### ISSUE TITLE
NotSerializableException when using "end rod" aliases/visual effect

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#6555] opened 2024-04-12 06:24 UTC
### Skript/Server Version

```markdown
[02:18:49 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[02:18:49 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[02:18:49 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[02:18:49 INFO]: [Skript] Server Version: git-Paper-430 (MC: 1.20.4)
[02:18:49 INFO]: [Skript] Skript Version: 2.8.4 (skriptlang-github)
[02:18:49 INFO]: [Skript] Installed Skript Addons:
[02:18:49 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[02:18:49 INFO]: [Skript]  - skript-yaml v1.5
[02:18:49 INFO]: [Skript]  - skript-particle v1.2.0 (https://github.com/sovdeeth/skript-particle)
[02:18:49 INFO]: [Skript]  - skript-reflect v2.4-dev2 (https://github.com/SkriptLang/skript-reflect)
[02:18:49 INFO]: [Skript]  - SkBee v3.4.2 (https://github.com/ShaneBeee/SkBee)
[02:18:49 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

When attempting to set a variable to `end rod` on `on load`, skript throws a NotSerializableException for visual effect classinfo.
This does not appear to happen when using an effect command.

### Expected Behavior

Don't throw me a stack trace when all I want is an end rod

### Steps to Reproduce

```
on load:
    set {_test} to end rod
    # set {_test::*} to end rod
```

### Errors or Screenshots

stack trace https://gist.github.com/Fusezion/7a28bb28fa43cef5572870032957173d

### Other

This error was brought to my attention by a discord user, and testing shows this was created in the 2.8.4 release 2.8.3 and below have no issues

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Romitou** [comment] 2024-04-12 20:30
Can't replicate with 2.8.4.
```
[22:29:27 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:29:27 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:29:27 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:29:27 INFO]: [Skript] Server Version: git-Paper-483 (MC: 1.20.4)
[22:29:27 INFO]: [Skript] Skript Version: 2.8.4 (skriptlang-github)
[22:29:27 INFO]: [Skript] Installed Skript Addons: None
[22:29:27 INFO]: [Skript] Installed dependencies: None
```

**Comment by Fusezion** [comment] 2024-04-13 02:17
> Can't replicate with same addons.

Hmm you shouldn't need any addons, as the person who reported this to me stated he had no addons when attempting this and his stacktrace shows it as well.
Message history started here. https://discord.com/channels/135877399391764480/138027100593455104/1228222235848736820

**Comment by Fusezion** [comment] 2024-04-13 02:21
Alright so after testing my step to reproduce was incorrect, using local vars doesn't cause an issue as skript shouldn't check for serializable state using a global var such as `{blah}` or `{blah::*}` was able to cause this, sorry for confusion I thought when I tried it prior it errored

**Comment by sovdeeth** [comment] 2024-04-14 12:42
Duplicate of #4196

**Closed by sovdeeth** 2024-04-14 12:42 UTC
