### ISSUE TITLE
ExprScripts: PatternSyntaxException

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#3193] opened 2020-07-22 18:20 UTC
### Description
An error is displayed in the console when I use the expression `scripts`.

### Steps to Reproduce
Just run `send "%scripts%"`.

### Expected Behavior
There should be no error.

### Errors / Screenshots
https://gist.github.com/Romitou/f7685d189b8735eec9e500b56d530fad

### Server Information
* **Server version/platform:** git-Spigot-800b93f-8160e29 (MC: 1.15.2)
* **Skript version:** tested with 2.5-alpha5 and 2.5-alpha6 (I forgot to test with 2.5-alpha6(rev1), but the error is finally the same).

**Comment by TPGamesNL** [comment] 2020-07-22 18:27
This is caused by ExprScripts using `String#replaceFirst` with the intention of the first argument being a normal string, but it is actually parsed as regex

**Comment by APickledWalrus** [comment] 2020-07-22 23:57
Should be fixed in #3194, and you are welcome to test out the nighty-build to find out (LINK HERE). **However**, the nightly build will contain the serious #3185 bug, just so that you are aware.

**Comment by Romitou** [comment] 2020-07-23 09:07
Thank you for the fix! 😄
I will test it asap.

**Closed** 2020-08-03 10:23 UTC
Labels: bug, completed, priority: medium
