### ISSUE TITLE
Skript: Severe error

### ISSUE THREAD

**Issue by vilhu-github** [SkriptLang/Skript#2564] opened 2019-10-14 14:23 UTC
### Description
Hey there, Skript gods, an error in my console adviced to post here. I'm not very familiar with github, so if I did anything wrong, feel free to ask. 

### Steps to Reproduce
Steps to reproduce: Happens immediately after Skript loads aliases. I don't know what causes this.
EDIT: adding to this, I've been able to start the server without issues ~5-10 times with the current version of skript and paper before this.

### Expected Behavior
I expected the server (and skript) to start normally.

### Errors / Screenshots
Console error - [gist](https://gist.github.com/vilhu-github/63b5921564a141803087e5c368545df7)

### Server Information
* **Server version/platform:**        1.14.4/PaperMC 209
* **Skript version:**                 Skript v2.4-beta8

### Additional Context
This is a private server that I host on my PC for me and my friends. I also use a Discord bot to allow my friends turn on the server if I happen to not be around my computer.

**Comment by Matocolotoe** [comment] 2019-10-14 16:27
Duplicate of #2487

**Comment by ShaneBeee** [comment] 2019-10-14 18:33
Duplicate of #2487

**Closed by ShaneBeee** 2019-10-14 18:33 UTC
