### ISSUE TITLE
Spigot start bug?

### ISSUE THREAD

**Issue by Perdume** [SkriptLang/Skript#3124] opened 2020-07-10 03:17 UTC
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! [Skript] Severe Error:
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Something went horribly wrong with Skript.
[12:13:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:13:48 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:13:48 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Stack trace:
[12:13:48 ERROR]: #!#! java.nio.file.FileSystemException: C:\Users\pessi\Desktop\Minecraft(backupfolder)\Backupfolder\plugins\zipfstmp5398076283880593949.tmp: The process cannot be accessed because another process is using the file.

[12:13:48 ERROR]: #!#!     at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[12:13:48 ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[12:13:48 ERROR]: #!#!     at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[12:13:48 ERROR]: #!#!     at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
[12:13:48 ERROR]: #!#!     at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.nio.file.Files.deleteIfExists(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.nio.file.Files.copy(Unknown Source)
[12:13:48 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.getTempPathForEntry(ZipFileSystem.java:844)
[12:13:48 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystem.newFileChannel(ZipFileSystem.java:723)
[12:13:48 ERROR]: #!#!     at com.sun.nio.zipfs.ZipPath.newFileChannel(ZipPath.java:747)
[12:13:48 ERROR]: #!#!     at com.sun.nio.zipfs.ZipFileSystemProvider.newFileChannel(ZipFileSystemProvider.java:271)
[12:13:48 ERROR]: #!#!     at java.nio.channels.FileChannel.open(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.nio.channels.FileChannel.open(Unknown Source)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:118)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:489)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:473)
[12:13:48 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.ArrayList.forEach(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[12:13:48 ERROR]: #!#!     at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:466)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:432)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:404)
[12:13:48 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:405)
[12:13:48 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:13:48 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:13:48 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:13:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[12:13:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[12:13:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[12:13:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[12:13:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940)
[12:13:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:13:48 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Version Information:
[12:13:48 ERROR]: #!#!   Skript: 2.5-alpha5 (latest)
[12:13:48 ERROR]: #!#!     Flavor: skriptlang-github
[12:13:48 ERROR]: #!#!     Date: 2020-07-02
[12:13:48 ERROR]: #!#!   Bukkit: 1.16.1-R0.1-SNAPSHOT
[12:13:48 ERROR]: #!#!   Minecraft: 1.16.1
[12:13:48 ERROR]: #!#!   Java: 1.8.0_241 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
[12:13:48 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Server platform: Paper
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Current node: null
[12:13:48 ERROR]: #!#! Current item: null
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Thread: Server thread
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! Language: english
[12:13:48 ERROR]: #!#! Link parse mode: DISABLED
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: #!#! End of Error.
[12:13:48 ERROR]: #!#!
[12:13:48 ERROR]: Error occurred while enabling Skript v2.5-alpha5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ch.njol.skript.Skript.onEnable(Skript.java:420) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-73]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-73]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-73]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-73]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-73]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-73]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-73]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-73]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: type stationary water not found
        at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:566) ~[?:?]
        at ch.njol.skript.classes.data.BukkitEventValues.<clinit>(BukkitEventValues.java:305) ~[?:?]
        ... 11 more

**Comment by Wealthyturtle** [comment] 2020-07-11 04:01
I am confused... you say you're using Spigot but your jar is patched_1.16.1.jar:git-Paper-73?

Regardless, did you recently change Skript versions?

**Comment by TheLimeGlass** [comment] 2020-07-16 04:17
Related https://github.com/SkriptLang/Skript/issues/3121

**Comment by Wealthyturtle** [comment] 2020-08-11 10:35
Closing as duplicate of #3054 and very likely a user error.

**Closed by Wealthyturtle** 2020-08-11 10:35 UTC
