### ISSUE TITLE
Double slabs not saving in variables properly

### ISSUE THREAD

**Issue by sjoerdtim** [SkriptLang/Skript#2291] opened 2019-07-23 22:30 UTC
### Description
When you save a block type variable to be a double slab, it reverts to a single slab after a server restart.

### Steps to Reproduce
To reproduce this, you follow these steps:
1. Use /savevariable
2. Restart the server
3. Use /showvariable
This last step will show you "oak wood slab" instead of the "double oak wood slab" you saved it as. This problem also occurs for other slabs as far as I have tested.
```
command /savevariable:
	trigger:
		set {saved.variable} to double oak wood slab

command /showvariable:
	trigger:
		send "%{saved.variable}%" to player
```

### Expected Behavior
The expected behavior would be that /showvariable shows "double oak wood slab" even after a restart.

### Server Information
* **Server version/platform:** Paper version git-Paper-639 (MC 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.4-beta3

**Comment by TPGamesNL** [comment] 2021-06-12 14:27
Can confirm

**Comment by TPGamesNL** [comment] 2021-08-16 09:49
Duplicate of #2111

**Closed by TPGamesNL** 2021-08-16 09:49 UTC
Labels: bug, priority: low, variables
