### ISSUE TITLE
Entities in radius only tracks feet

### ISSUE THREAD

**Issue by Jjman739** [SkriptLang/Skript#2619] opened 2019-11-04 23:02 UTC
### Description

When you loop entities in a given radius, instead of seeing which entities have hitboxes within that radius, it returns which entities have their foot position in that radius.

### Steps to Reproduce

```
loop entities in radius 1 around head of player:
    damage loop-entity by 1
```
The player will not be damaged in this case.

### Expected Behavior

I expected it to return the player, as a great portion of the player's hitbox is within a 1-meter radius of the player's head.

### Server Information
* **Server version/platform:**       1.14.4-R0.1-SNAPSHOT
* **Skript version:**                2.4-beta9

### Additional Context

On Minecraft 1.13.2, with the same version of Skript, this was not an issue.

**Comment by Wealthyturtle** [comment] 2019-11-10 10:13
From what you're saying, looks like commit 22dbc09 caused a change in behavior.

**Comment by Blueyescat** [comment] 2019-11-11 21:32
@Wealthyturtle my PR didn't change any logic on the code

Also no, it never worked with hitboxes, but locations. And location of a player is at their foot.

**Comment by Jjman739** [comment] 2019-11-14 00:52
Okay, looks like I got something wrong. I just tested again with the effect command `!message "%entities in radius 1 around head location of player%"` and it works in 2.4 on Minecraft 1.13.2, but not in 2.4 on Minecraft 1.14.4, so... I don't know what to make of that.

**Comment by Wealthyturtle** [comment] 2019-11-14 01:08
Could you see if any behavior changed between 1.13.2 and 1.14.0? Might have been caused by Minecraft itself modifying something.

**Comment by Jjman739** [comment] 2019-11-14 14:40
Looking at the wiki, I see that 1.14.0 "Updated hitboxes and eye positions of many entities." It was probably the positioning, but I'm going to see if I can spin up a server in that version to test it out.

Also, interesting note, in both versions, looping `players in radius 1 around head location of player` returns <none>, while looping entities still returns the player.

**Comment by Jjman739** [comment] 2019-11-14 18:32
Yup, it's also broken in 1.14.0, so I guess that update did the change.

**Comment by Wealthyturtle** [comment] 2019-11-17 05:06
Closing this issue as this seems to be a Minecraft issue.

**Closed by Wealthyturtle** 2019-11-17 05:06 UTC
Labels: needs-testing
