### ISSUE TITLE
Drag event or inventory action in Skript

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#3744] opened 2021-02-09 21:00 UTC
Currently, an add-on like TuSKe or skript-reflect is required to implement effective control of inventory interactions within Skript. When, for example, the cursor item is dragged across the inventory to split the items evenly among the selected slots, no event is called. This event exists as [the InventoryDragEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryDragEvent.html) in Spigot and I believe an implementation in Skript would be largely beneficial.

Mainly, I'm thinking of two possible ways of implementing this:
1. Merge it to the inventory click event, adding the corresponding inventory actions and making the event effectively responsible for the entire abstract InventoryInteractEvent superclass.
2. Create a separate item drag event

The former seems like the most sensible implementation. It would also be sensible to create an alternate syntax like `on inventory interact` to avoid confusion, while keeping backwards compatibility.

**Comment by Romitou** [comment] 2021-02-09 21:05
See https://github.com/SkriptLang/Skript/issues/3339

**Comment by TPGamesNL** [comment] 2021-02-20 18:33
Duplicate of #3339

**Comment by FranKusmiruk** [comment] 2021-02-20 20:10
I'd like to leave this one open instead since it also opens the discussion on the impl details, which I believe is the reason we haven't yet implemented it, I can remember one of the people in the team talking about implementing it.

The former idea seems to be the better option here though, we would probably have to release it on a major version since it would generate undesired behaviour in scripts that weren't handling this new event call. If anything, we could make it so only the `inventory interact` pattern triggers for the inventory drag event till the release of a major version.

**Closed** 2023-09-09 08:52 UTC
Labels: enhancement, priority: low, completed
