### ISSUE TITLE
Right clicking on player triggers event twice

### ISSUE THREAD

**Issue by colton-boi** [SkriptLang/Skript#4867] opened 2022-07-05 15:00 UTC
### Skript/Server Version

```markdown
[14:58:36 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:58:36 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[14:58:36 INFO]: [Skript] Server Version: git-Paper-411 (MC: 1.17.1)
[14:58:36 INFO]: [Skript] Skript Version: 2.6.2
[14:58:36 INFO]: [Skript] Installed Skript Addons: 
[14:58:36 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[14:58:36 INFO]: [Skript]  - SkBee v1.16.3 (https://github.com/ShaneBeee/SkBee)
[14:58:36 INFO]: [Skript] Installed dependencies: 
[14:58:36 INFO]: [Skript]  - Vault v1.7.3-b131
[14:58:36 INFO]: [Skript]  - WorldGuard v7.0.5+3827266
```

### Bug Description

Can replicate this issue (1.17.1, 2.6.2)

Right clicking on a PLAYER (not tested with npcs) with this code:

```
on right click:

    broadcast event-itemtype
```

broadcasts:

With no held items:
1.   Single broadcast of "0 air"

With item in tool slot:
1.   Double broadcast of item

With item in offhand and NOT in tool slot:
1.   Single broadcast of "0 air"
2.   Single broadcast of item

With item in offhand AND tool slot:
1.   Double broadcast of tool slot item

broadcasting event-entity instead of event-itemtype shows that one event has the target as the event-entity and the other has the executor as the event-entity

### Expected Behavior

The event should only be triggered once

### Steps to Reproduce

Add a skript with the code 
```
on right click:

    broadcast event-itemtype
```
and right click on a player

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by colton-boi** [comment] 2022-07-05 15:07
Note: Once again, this only happens with PLAYERS, (and possibly NPCs, haven't tested them) not mobs/entities

**Comment by TheLimeGlass** [comment] 2022-07-06 19:40
Do you have ViaVersion or ProtocolSupport installed?

**Comment by honkling** [comment] 2022-07-13 15:37
Was able to reproduce using Holographic Displays v3.0.0-SNAPSHOT, Skript v2.6.2 (v2.6.3 applies), & ViaVersion v4.3.2

**Comment by honkling** [comment] 2022-07-13 15:49
Looks like it's ViaVersion's fault :sweat_smile: Cannot reproduce w/o ViaVersion

**Comment by TheLimeGlass** [comment] 2022-07-13 16:42
Been an issue since 1.9 and BaeFell has attempted to fix it multiple times in the code with no luck. ViaVersion is sending double packets for this event for some reason and Spigot is just doing it's job. We won't be able to fix at Spigot level, we'll have to do some NMS work to fix.

**Comment by AyhamAl-Ali** [comment] 2022-07-15 11:10
Closing due to not a Skript issue, if it turns out to be at some point feel free to reopen.

**Closed by AyhamAl-Ali** 2022-07-15 11:10 UTC
Labels: dev needed
