### ISSUE TITLE
Console Error when setting blocks between two blocks

### ISSUE THREAD

**Issue by APickledWalrus** [SkriptLang/Skript#2615] opened 2019-11-03 18:22 UTC
### Description
Whenever I try and set the blocks between two locations, it causes an error to appear in my console. The code parses with no errors however.

### Steps to Reproduce
```
options:
    world: world
    corner1.x: 30.5
    corner1.y: 67.0
    corner1.z: -1.5
    corner2.x: 30.5
    corner2.y: 64.0
    corner2.z: -0.5
    colors: blue concrete, red concrete, lime concrete, and yellow concrete

# This is part of a larger function, but this is the part that errors.

set {_random} to a random integer between 10 and 15
        loop {_random} times:
            set {_color::*} to a random element out of {@colors}
        set {_color} to a random element out of {_color::*}
        loop 3 times:
            loop {@colors}:
                if loop-value-1 is 3:
                    if loop-value-2 is {_color}:
                        exit 4 sections
                    else:
                        set all blocks between block at {_corner1} and block at {_corner2} to loop-value-2
                        set all blocks between block south 1 of block at {_corner1} and block north 1 of block at {_corner2} to loop-value-2
                else:
                    set all blocks between block at {_corner1} and block at {_corner2} to loop-value-2
                    set all blocks between block south 1 of block at {_corner1} and block north 1 of block at {_corner2} to loop-value-2
                wait 5 ticks
```

### Expected Behavior
For the blocks between the two points to be set.

### Errors / Screenshots
https://gist.github.com/APickledWalrus/c1cf4a9bbd4e2b7904a43839c7a65b82

### Server Information
* **Server version/platform:**       git-paper-225 (MC: 1.14.4) (Latest Version of Paper)
* **Skript version:**                2.4-beta9

**Comment by Wealthyturtle** [comment] 2019-11-04 14:10
Could you shrink your code even further? Stuff like ``loop {@colors}:`` and ``wait 5 ticks``. Are they truly necessary to replicate this issue?. Make it such that it's easier to find the root cause - sometimes the exception itself can be deceiving in what actually causes the issue (could be a combination of expressions, etc.)

**Comment by APickledWalrus** [comment] 2019-11-04 18:36
Yeah, I can do that :). I just posted in the code that I was using that caused the error.

**Comment by ShaneBeee** [comment] 2019-11-05 05:24
Based on the code you have given, there is no way we can test that.
The code you provided (as you stated) is part of a much larger function. 
For future notice, in the "Steps to Reproduce" section, please put code that we can actually use to reproduce said error.

Without having reproducible code, I had to write some of my own, here is what I tested with:
```vb
command /test <item type>:
	trigger:
		set {_1} to location 3 west of player
		set {_2} to location 5 north of player
		set blocks between block at {_1} and block at {_2} to arg-1
```
With this code, it successfully sets the blocks to whatever type I type into the command.

I also tested with:
```vb
options:
	colors: blue concrete, red concrete, lime concrete, and yellow concrete

command /test:
	trigger:
		set {_1} to location 3 west of player
		set {_2} to location 5 north of player
		loop {@colors}:
			set blocks between block at {_1} and block at {_2} to loop-value
			wait 1 second
```
Each of the colors in the `{@colors}` option, are set as expected.

Needless to say, I can not reproduce this error.

**Comment by APickledWalrus** [comment] 2019-11-10 05:43
I am still encountering this error. I tested it two ways to see if it would make any difference, but it did not. I am using the following code:

```
command /blockstest:
    trigger:
        set {_corner1} to block 3 north of player
        set {_corner2} to block 4 west of player
        set all blocks between block south 1 of {_corner1} and block north 2 of {_corner2} to dirt
        #set all blocks between block south 1 of block at {_corner1} and block north 2 of block at {_corner2} to dirt
```
Console Error: https://gist.github.com/APickledWalrus/6bdde9775df4dcf249cf9efc9686e3a7

This seems to be related to the ```south 1 of block``` part.

**Comment by ShaneBeee** [comment] 2019-11-26 07:01
I did some poking around, and I believe the issue is coming from you using the expression wrong.
http://skriptlang.github.io/Skript/expressions.html#ExprDirection

as you can see, it should be used like 
`block 1 south of`
but you are using
`block south 1 of` (which is not how the expression works. 

Can you please try using the expression correctly and report back.

**Comment by APickledWalrus** [comment] 2019-12-01 01:32
Using the proper syntax, I encountered no issues. Perhaps some sort of check could be added to ExprXOf or ExprDirection so that a syntax error is given instead?

**Comment by TPGamesNL** [comment] 2021-06-12 14:19
Closing since the syntax was used incorrectly, and the console error is a duplicate of https://github.com/SkriptLang/Skript/issues/3814

**Closed by TPGamesNL** 2021-06-12 14:19 UTC
Labels: needs testing
