### ISSUE TITLE
Skript 1.8

### ISSUE THREAD

**Issue by Helios19932** [SkriptLang/Skript#2611] opened 2019-10-31 18:33 UTC
Can you please make new versions of skript compatible with 1.8? My pc is too weak for newer minecraft versions and old versions of skript are glitched. Or if you can, just fix 2.2-dev27's if player has item condition.

**Comment by TPGamesNL** [comment] 2019-10-31 18:41
See #847 
The latest version that works on 1.8 is said to be dev36, use that instead.
You could also check out https://github.com/Matocolotoe/Skript-1.8.

**Comment by ShaneBeee** [comment] 2019-10-31 18:42
1) Its been discussed many many times. The devs have agreed that if someone wants to attempt to make the newer versions work on 1.8, they can submit a PR for it. The dev team themselves really have no desire to do this. 
1.8.x was succeeded by 1.9 three and a half years ago. 1.15 will be coming out in the next few months, with 1.16 around the corner. 
Its hard enough keeping this plugin compatible with 1.9-1.12.2 and 1.13+, trying to add compatibility with 1.8.x will make things even harder. There were a decent amount of changes in the API in 1.9 that would make this compatibility far from easy. 

1) "Or if you can, just fix 2.2-dev27's " <-- I can assure you that will never happen. Try upgrading to 2.2-dev36, that is what most 1.8.x users are using. 


All that said, don't keep your hopes up. 2.3+ came out a year ago, and since then no one on the dev team has had a desire to "update" this plugin to work on a 4 year old server version. Its time to move on. 
"My pc is too weak for newer minecraft versions " <-- if your computer can run 1.8.x, Im pretty sure it can run 1.9.4

Im closing this as its a duplicate of #847

**Closed by ShaneBeee** 2019-10-31 18:42 UTC

**Comment by Helios19932** [comment] 2019-11-01 13:22
I tried 2.2-dev36, but it's not working. Latest version that work on my server is dev27.

**Comment by APickledWalrus** [comment] 2019-11-01 13:24
What version of 1.8 are you using

**Comment by Helios19932** [comment] 2019-11-01 14:43
I'm using paperspigot 1.8.8, plugin crashes when starting server

**Comment by APickledWalrus** [comment] 2019-11-01 15:40
I would say go to one of the skript support discords and post your error log there

**Comment by Matocolotoe** [comment] 2019-11-01 23:55
https://github.com/Matocolotoe/Skript-1.8

**Comment by Matocolotoe** [comment] 2019-11-01 23:58
Official Skript doesn't support 1.8 so as @TPGamesNL said you could probably use the beta7 version of my fork (beta8 is buggy).
