### ISSUE TITLE
Console Errors Bug

### ISSUE THREAD

**Issue by annemettean** [SkriptLang/Skript#2562] opened 2019-10-14 10:27 UTC
### Description

There are coming some errors in my console and the console say I need to go to this website and post the console errors in a pastebin to you. 

I do not have any skript addons on my server!

### Expected Behavior

Many console errors

### Errors / Pastebin
[12:16:26 INFO]: [Skript] Enabling Skript v2.4-beta8
[12:16:27 INFO]: [Skript] You're currently running the latest stable version of Skript.
[12:16:32 INFO]: [Skript] Loaded 93106 aliases in 5651ms
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! [Skript] Severe Error:
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Something went horribly wrong with Skript.
[12:16:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:16:32 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:16:32 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Stack trace:
[12:16:32 ERROR]: #!#! java.lang.NullPointerException
[12:16:32 ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
[12:16:32 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[12:16:32 ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[12:16:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[12:16:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[12:16:32 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Version Information:
[12:16:32 ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[12:16:32 ERROR]: #!#!     Flavor: skriptlang-github
[12:16:32 ERROR]: #!#!     Date: 2019-09-29
[12:16:32 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[12:16:32 ERROR]: #!#!   Minecraft: 1.13.2
[12:16:32 ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[12:16:32 ERROR]: #!#!   OS: Linux amd64 4.9.0
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Server platform: Spigot
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Current node: null
[12:16:32 ERROR]: #!#! Current item: null
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Thread: Server thread
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Language: english
[12:16:32 ERROR]: #!#! Link parse mode: DISABLED
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! End of Error.
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! [Skript] Severe Error:
[12:16:32 ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Something went horribly wrong with Skript.
[12:16:32 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[12:16:32 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[12:16:32 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Stack trace:
[12:16:32 ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[12:16:32 ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
[12:16:32 ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1546)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1414)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
[12:16:32 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[12:16:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[12:16:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[12:16:32 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[12:16:32 ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[12:16:32 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:16:32 ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Version Information:
[12:16:32 ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[12:16:32 ERROR]: #!#!     Flavor: skriptlang-github
[12:16:32 ERROR]: #!#!     Date: 2019-09-29
[12:16:32 ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[12:16:32 ERROR]: #!#!   Minecraft: 1.13.2
[12:16:32 ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[12:16:32 ERROR]: #!#!   OS: Linux amd64 4.9.0
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Server platform: Spigot
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Current node: null
[12:16:32 ERROR]: #!#! Current item: null
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Thread: Server thread
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! Language: english
[12:16:32 ERROR]: #!#! Link parse mode: DISABLED
[12:16:32 ERROR]: #!#!
[12:16:32 ERROR]: #!#! End of Error.
[12:16:32 ERROR]: #!#!
[12:16:32 INFO]: [Skript]  ~ created by & ? Peter G?ttinger aka Njol ~

### Server Information
* **Server version/platform:** Spigot 1.13.2      
* **Skript version:**  2.4-beta8

**Comment by ShaneBeee** [comment] 2019-10-14 10:28
Duplicate of #2487

**Closed by ShaneBeee** 2019-10-14 10:28 UTC
