### ISSUE TITLE
Problem with multiplication between args and other

### ISSUE THREAD

**Issue by Diduck** [SkriptLang/Skript#5903] opened 2023-08-10 13:20 UTC
### Skript/Server Version

```markdown
Serveur : Mohist 1.12.2
Skript: 2.5.3
```

### Bug Description

Multiplication between an <int> arg and a variable not working:

arg-1 = 1
{_variable} = 15

Output= arg-1*{_variable} = -14

Solution: 

set {_variable_temp} to arg-1
{_variable} = 15

Output=  {_variable_temp}*{_variable} = 15

### Expected Behavior

X

### Steps to Reproduce

options:
    zinc: stone
    pricezinc: 15

command /sellzinc <int>:
    trigger:
            set {_unit-price} to {@zincprice}
            set {_prix} to arg-1*{_unit-price}

            send "&7[&ePrison&dCraft&7] &aVous avez reçu %{_prix}% €"

### Errors or Screenshots

X

### Other

X

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment] 2023-08-10 16:19
This is working fine, you're saying `(arg) - 1*{_variable}`, not `(arg-1) * {_variable})`. You can use parentheses to clarify:
`arg-1*{_variable}` ⇒ `(arg-1)*{_variable}`

**Comment by AyhamAl-Ali** [comment] 2023-08-10 19:42
Duplicate of #5901

**Closed by AyhamAl-Ali** 2023-08-10 19:42 UTC
