### ISSUE TITLE
Change "armor" aliases

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#4860] opened 2022-07-01 23:54 UTC
### Suggestion

Change "armor" from "generic armor" to match "all armor"

EX:
``send armor -> leather chestplate, chainmail chestplate, iron chestplate, ect``

CURRENT:
``send armor -> generic armor``

### Why?

While I was messing around with effect commands and figuring out what's what for aliases. I noticed that using `!send swords` will send all swords the same as `!send shield` sending shield so I thought using `!send armor` would send all armor like swords however I was met with `generic armor` which is an attribute type I feel like this should be changed to armor to fit in with others.

### Other

While I'm at this I also believe attribute types should have all aliases outside of their main name removed

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment] 2022-07-02 13:57
Duplicate of https://github.com/SkriptLang/Skript/issues/4773, as a part of the fix for that will be to create a priority list for types with literal parsers (if a proper type cannot be chosen from context) and items will be prioritized over attribute types

**Closed by TPGamesNL** 2022-07-02 13:57 UTC
Labels: enhancement, priority: lowest, aliases
