### ISSUE TITLE
at <time>: events not working

### ISSUE THREAD

**Issue by whoshenry** [SkriptLang/Skript#463] opened 2017-04-04 21:39 UTC
I have a simple script that uses the 'at time:' event.

Sometimes it works fine, other times it doesn't work at all, no rhyme or reason.

This is my script:
```
at 01:00 or 02:00 or 03:00 or 04:00 or 05:00 or 07:00 or 08:00 or 09:00 or 10:00 or 11:00 or 12:00 or 13:00 or 14:00 or 15:00 or 16:00 or 17:00 or 19:00 or 20:00 or 21:00 or 22:00 or 23:00 or 00:00 in "Survival5":
	broadcast "&0 "
	broadcast "&3Time &9> &fThe current server time is &b%time%"
```

Seems like a simple script but some hours it works and then the next hour it doesn't register.

Using bensku dev25 build. and Spigot 1.11.2.

**Comment by bensku** [comment] 2017-04-07 14:15
Hmm, I have heard of this before. For some reason, time events have never been very reliable.

**Comment by whoshenry** [comment] 2017-04-08 10:37
Is this something that will be looked into soon? I have some scripts in mind that require the time events working well, if not I'll have to think of a workaround for it.

**Comment by Nicofisi** [comment] 2018-02-22 13:22
Can be related to #464 but probably no

**Comment by Nicofisi** [comment] 2018-07-11 00:45
Does anyone have *any* info that would help to reproduce it?

**Comment by Nicofisi** [comment] 2018-07-15 01:52
Now as I'm thinking about it, I think I've already seen some very closely related issue/comment here on the issue tracker already.. You're saying that
> some hours it works and then the next hour it doesn't register

Perhaps you use some world management plugin that loads worlds *after* Skript parses the scripts? But that would show a parse time error in the console during server startup. The question is, did you check that, and is/was what I said possible at all in your case?

Because that would pretty well explain why it worked later, after a reload ("register")... hmm

**Comment by FranKusmiruk** [comment] 2020-07-09 23:15
Closing this issue isn't very clear by itself, open another issue with more information.

**Closed by FranKusmiruk** 2020-07-09 23:15 UTC
Labels: bug, investigating, priority: low
