### ISSUE TITLE
Comment Area

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3528] opened 2020-11-07 23:01 UTC
It would be nice if we could comment areas, like:
```
#<
this area
is 
completely
commented
>#
```
this would also be valid:
```
#< hello test 
hello >#
```
this would save time if you're commenting large areas, there could also be further implementation with this, such as:
```
command /hi:
    trigger:
        send "TPS: %tps from the last minute% #<this is the lag measurement of the server>#, PING: %player's ping% #<the player's connection to the server># ms"

out:
TPS: 20, Ping: 0ms
```
^ isn't the most practice example, but you get the point

**Comment by ShaneBeee** [comment] 2020-11-07 23:02
Duplicate of #2180

**Closed by ShaneBeee** 2020-11-07 23:02 UTC
