### ISSUE TITLE
After setting Entity's name, the entity's name only visible when pointing cursor at them

### ISSUE THREAD

**Issue by BoQsc** [SkriptLang/Skript#2236] opened 2019-07-07 14:46 UTC
## 🤔 Going to ping some of you: 
@bensku @ShaneBeee @FranKusmiruk 

## ℹ️ Prerequisite information
**Minecraft Client:** 1.14.2
**Spigot:** 1.14.2 `(online-mode=false)`
**Skript version:**  [**2.4-alpha4**]( https://github.com/SkriptLang/Skript/releases/tag/2.4-alpha4) (Latest as of creation of this issue)
No other plugins or extensions.

## ⁉️ Question

I wanted to make all spawned entities with my custom names.

For testing I managed to create these few lines of example code.

```
on spawn:
	set name of last spawned entity to "&5Logger"


command /testmob:
	trigger:
		spawn 1 villager at player's location
```

**What works:** 
the villager is spawned and it does have a name "Logger" with the appropriate color.

**What's unexpected:** 
the Name of this newly spawned entity cannot be seen until I point my cursor at them while being very close to them.

**What I want**:
I want to see the name of the mobs all the time, **not only when I'm near them and pointing the cursor at them.**

![Screenshot (36)](https://user-images.githubusercontent.com/21064622/60770051-7e61ca80-a0df-11e9-8a3f-01f949e814b1.png)
![Screenshot (37)](https://user-images.githubusercontent.com/21064622/60770052-7e61ca80-a0df-11e9-92bc-aaf6e497ae67.png)

**Comment by MrScopes** [comment] 2019-07-07 17:57
that's how minecraft works

**Comment by Blueyescat** [comment] 2019-07-07 18:00
Duplicate of #1279

using `display name` will work like i said in that issue

**Closed** 2019-07-07 18:02 UTC

**Comment by BoQsc** [comment] 2019-07-07 18:41
```
on spawn:
	set display name of last spawned entity to "&5Logger"


command /testmob:
	trigger:
		spawn 1 villager at player's location
```

**Comment by Blueyescat** [comment] 2019-07-07 19:34
@BoQsc you are doing it wrong, `last spawned entity` returns the lastly spawned entity the spawn effect. You need to use `[event-]entity` in the spawn event.
