### ISSUE TITLE
Copies List with its Indices

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4948] opened 2022-07-24 15:54 UTC
### Suggestion

Allow support for carrying over indices of a list to another list in the SET changer.

The following image shows otherwise:
![Screenshot_20220724-233023_Edge](https://user-images.githubusercontent.com/72163224/180655568-63fbc229-efa7-4408-a398-deee9166d900.png)

### Why?

I find this makes sense if you wish to clone a list to a new list, instead of cloning the values.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment] 2022-07-24 15:59
Related issue #4947

**Comment by TPGamesNL** [comment] 2022-07-24 15:59
Duplicate of https://github.com/SkriptLang/Skript/issues/3127

**Closed by TPGamesNL** 2022-07-24 15:59 UTC
Labels: enhancement, priority: lowest
