### ISSUE TITLE
Integer variables get converted to numbers when adding 1

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#1925] opened 2019-03-02 15:07 UTC
### Description
When you set a variable to an integer, then set the variable to itself + 1, it will be a number instead of an integer.

### Steps to Reproduce
```
command /test:
	trigger:
		set {_i} to 1
		set {_i} to {_i} + 1
		if {_i} is a integer:
			message "integer"
		else if {_i} is a number:
			message "number"
		else:
			message "neither"
```

### Expected Behavior
The variable should remain an integer

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/29547183/53683719-68449780-3d04-11e9-945d-23e75e83dfaf.png)

### Server Information
* **Server version/platform:** Spigot 1.13.2
* **Skript version:** 2.3.5

### Additional Context
It will remain an integer when using `add 1 to {_i}`
`1 + 1` does return a integer
This isn't very important, but it can be annoying for functions, because when the return type is an integer, it won't work (won't even parse when it's being used within the return effect): 
```
function testFunction() :: integer:
	set {_i} to 1
	return {_i} + 1
```
![image](https://user-images.githubusercontent.com/29547183/53683775-089abc00-3d05-11e9-9635-3d804d61531f.png)

**Comment by FranKusmiruk** [comment] 2019-03-08 21:40
Duplicate of #1602

**Closed by FranKusmiruk** 2019-03-08 21:40 UTC

**Comment by TPGamesNL** [comment] 2019-03-10 09:43
Well I thought it was different since 1 + 1 does return an integer, but {_i} + 1 doesn't, and those are two different things
