### ISSUE TITLE
skript error

### ISSUE THREAD

**Issue by rjsndksla** [SkriptLang/Skript#6941] opened 2024-07-28 12:59 UTC
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: 4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4)
[Skript] Skript Version: 2.9.0 (skriptlang-github)
[Skript] Installed Skript Addons: None
[Skript] Installed dependencies: None
```

### Bug Description

I used the phrase on player move, but this message appears in the console window and I cannot use it.

### Expected Behavior

Originally, a message should have been sent to the player saying 1 if he moved, but the message was not sent. So I checked the console, and while reloading skript, a message like the picture below appeared.

### Steps to Reproduce

I don't know what caused this problem. I tried uninstalling the old add-on and restarting, but I still get this message. Here is the code where this error occurs:
on player move:
	send "1" to player

### Errors or Screenshots

[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:46:52] [Server thread/ERROR]: #!#! Could not load chunk.sk
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[21:46:52] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:46:52] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[21:46:52] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Stack trace:
[21:46:52] [Server thread/ERROR]: #!#! java.lang.NullPointerException: Cannot read the array length because "<local8>" is null
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptEvent.init(SkriptEvent.java:90)
[21:46:52] [Server thread/ERROR]: #!#!     at org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[21:46:52] [Server thread/ERROR]: #!#!     at org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptEvent.parse(SkriptEvent.java:284)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.structures.StructEvent.init(StructEvent.java:69)
[21:46:52] [Server thread/ERROR]: #!#!     at org.skriptlang.skript.lang.structure.Structure.init(Structure.java:131)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseStatic(SkriptParser.java:207)
[21:46:52] [Server thread/ERROR]: #!#!     at org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:217)
[21:46:52] [Server thread/ERROR]: #!#!     at org.skriptlang.skript.lang.structure.Structure.parse(Structure.java:200)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:675)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$3(ScriptLoader.java:503)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:424)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:440)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:502)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:459)
[21:46:52] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:853)
[21:46:52] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:82)
[21:46:52] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[21:46:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[21:46:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:391)
[21:46:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242)
[21:46:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054)
[21:46:52] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[21:46:52] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:842)
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Version Information:
[21:46:52] [Server thread/ERROR]: #!#!   Skript: 2.9.0 (latest)
[21:46:52] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:46:52] [Server thread/ERROR]: #!#!     Date: 16:01:35.354421100
[21:46:52] [Server thread/ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[21:46:52] [Server thread/ERROR]: #!#!   Minecraft: 1.20.4
[21:46:52] [Server thread/ERROR]: #!#!   Java: 17.0.11 (Java HotSpot(TM) 64-Bit Server VM 17.0.11+7-LTS-207)
[21:46:52] [Server thread/ERROR]: #!#!   OS: Windows 11 amd64 10.0
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Server platform: Spigot
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Current node: on player move: (chunk.sk, line 34)
[21:46:52] [Server thread/ERROR]: #!#! Current item: null
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Thread: Server thread
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! Language: english
[21:46:52] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:46:52] [Server thread/ERROR]: #!#!
[21:46:52] [Server thread/ERROR]: #!#! End of Error.
[21:46:52] [Server thread/ERROR]: #!#!
![bug](https://github.com/user-attachments/assets/dc2260fa-61ab-4f63-b03d-3f3cf4ec9ff4)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by EquipableMC** [comment] 2024-07-28 13:02
Duplicate of [#6938](https://github.com/SkriptLang/Skript/issues/6938)

**Comment by rjsndksla** [comment] 2024-07-28 13:05
> Duplicate of [#6938](https://github.com/SkriptLang/Skript/issues/6938)

Hello can you please help me?

**Comment by EquipableMC** [comment] 2024-07-28 13:10
> > Duplicate of [#6938](https://github.com/SkriptLang/Skript/issues/6938)
> 
> Hello can you please help me?

Read that Issue I sent, it's a known issue and will be fixed soon.

**Comment by rjsndksla** [comment] 2024-07-28 13:21
> > > Duplicate of [#6938](https://github.com/SkriptLang/Skript/issues/6938)
> > 
> > 
> > Hello can you please help me?
> 
> Read that Issue I sent, it's a known issue and will be fixed soon.

Oh sorry, I was too lazy to read it. thank you for your reply

**Comment by EquipableMC** [comment] 2024-07-28 13:22
> > > > Duplicate of [#6938](https://github.com/SkriptLang/Skript/issues/6938)
> > > 
> > > 
> > > Hello can you please help me?
> > 
> > 
> > Read that Issue I sent, it's a known issue and will be fixed soon.
> 
> Oh sorry, I was too lazy to read it. thank you for your reply

no worries and you're welcome!

**Closed** 2024-07-28 13:24 UTC
