### ISSUE TITLE
Unable to change item amount.

### ISSUE THREAD

**Issue by TheMisterWolf** [SkriptLang/Skript#2850] opened 2020-03-06 07:31 UTC
**This issue is with the latest UNSTABLE release of skript.**

The Issue that I have found is that in the latest unstable release I am unable to change the item amount of a variable. (I have only tested using event-slot.)

Steps to reproduce:
use Skript's on inventory click: event and set a variable to event-item. Then try and change the item amount of said variable.

Expected behavior:
No console or Skript error the item amount just doesn't change.

Server information:
* **Server version/platform: Paper 1.15.2**
* **Skript version: Second 2.5 Unstable Release**

Sorry if this isn't formatted well I don't have much experience with GitHub.

**Comment by ShaneBeee** [comment] 2020-03-06 11:20
Duplicate of #2707 
I know its not a direct duplicate but it appears the issue is with the `item amount` expression, doesn't seem to work across the board.

**Closed by ShaneBeee** 2020-03-06 11:20 UTC
