### ISSUE TITLE
Player is holding named item bug

### ISSUE THREAD

**Issue by GiraffeBoy451** [SkriptLang/Skript#4166] opened 2021-07-05 16:14 UTC
### Skript/Server Version

```
2.6 - 1.17
```

### Bug Description

When you have a `player is holding [item] named "[name]":` condition, it will completely ignore the name of the item and work anyway, even if you're holding the item without the correct name.

### Expected Behavior

The condition is only supposed to work if the item is named a certain thing, but it completely ignores this.

### Steps to Reproduce

As far as I know this only happens on Skript 2.6 & Version 1.17
I switched back to 2.5.3 to see if the bug happened, but it worked as intended
You can try something as simple as
```
on right click:
    player is holding stick named "&7Knockback Stick":
        broadcast "hi"
```
This will work with any stick, doesn't matter what the name is

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-07-05 20:12
duplicate of #4163

**Closed** 2021-07-06 03:21 UTC
Labels: duplicate
