### ISSUE TITLE
Unfounded error of an expression inside a variable

### ISSUE THREAD

**Issue by carlodrift** [SkriptLang/Skript#3110] opened 2020-07-06 23:13 UTC
### Description
Skript doesn't understand the effect, it should.

### To Reproduce
```as
set {_a::%size of {_b::*}%} to true
```

### Server Information
* **Server version/platform:** Paper 1.15.2
* **Skript version:** Tried 2.4.1 and 2.5-alpha5

**Comment by FranKusmiruk** [comment] 2020-07-06 23:21
I believe this is the same issue as #3082, can someone confirm?

**Comment by APickledWalrus** [comment] 2020-07-06 23:30
> I believe this is the same issue as #3082, can someone confirm?

Looks like it. Main issue seems to be that putting a an expression that has a variable in it within a variable does not work.

**Comment by TPGamesNL** [comment] 2021-05-08 13:35
Duplicate of #837

**Closed by TPGamesNL** 2021-05-08 13:35 UTC
Labels: investigating
