### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4190] opened 2021-07-15 21:06 UTC
### Suggestion

In [here](https://github.com/SkriptLang/Skript/blob/master/src/main/resources/lang/english.lang)
there are some options that need to be put on the config, for example, the `commands:` should be on the config to edit its messages

### Why?

very useful for people who wants the `no permission message:` to be 1 message and they don't have to worry about doing `permission message: My custom permission message`

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by APickledWalrus** [comment] 2021-07-16 02:07
I'm thinking #3999 will solve this as you *should* be able to edit the english.lang file

**Comment by TPGamesNL** [comment] 2021-07-20 08:29
Duplicate of #136

**Closed by TPGamesNL** 2021-07-20 08:29 UTC
Labels: enhancement
