### ISSUE TITLE
Skript Wont Run Right, '/skript help'

### ISSUE THREAD

**Issue by AnswerPlease** [SkriptLang/Skript#2921] opened 2020-04-11 00:53 UTC
### Description
Skript wont run. Says '/skript help' when using /sk or /skript

### Steps to Reproduce
No Skripts enabled. Just trying to run skript right.
Plugins: WorldEdit, NametagEdit, Skript, Multiverse-Core, SK-NBeeT, Skellett, skDragon, skRayFall, SkQuery, ExtrasSK

### Expected Behavior
Expected Skript to work properly and not just say '/skript help'

### Errors / Screenshots

https://gist.github.com/AnswerPlease/ecfd7121c8d0f92aaff8ac955fbb2ab9

### Server Information
* **Server version/platform:**       1.15.2-R0.1-SNAPSHOT
* **Skript version:**               v2.5-alpha3

**Comment by ShaneBeee** [comment] 2020-04-11 01:42
Duplicate of #2752

**Comment by ShaneBeee** [comment] 2020-04-11 01:43
Something that has worked for most people with this issue, is upgrading to OpenJDK
https://adoptopenjdk.net

**Closed by ShaneBeee** 2020-04-11 01:42 UTC

**Comment by AnswerPlease** [comment] 2020-04-11 03:08
Thanks this worked! Appreciate you taking the time to help.
