### ISSUE TITLE
Why skript is "nulling" some types, when I register this things?

### ISSUE THREAD

**Issue by MorkaZ** [SkriptLang/Skript#800] opened 2017-08-19 22:15 UTC
Why skript is "nulling" some types/expressions, when I register, for example, this event?:
Skript.registerEvent("mor.offhand item change", SimpleEvent.class, PlayerSwapHandItemsEvent.class, "[mor.]offhand [item] change [event]");
(this event is from bukkit API)

Nulled example: 
on inventory click:
  broadcast "%cursor item of player%" 

Without this event register - output is right, but when I register this ^ event, output is always null.
ExprCursorItemWithPlayer.class: 
https://pastebin.com/3uqsaxpD

This register is bugging "location of <something>" (for example: location of event-block returns null, but location of player works):
Skript.registerExpression(ExprLocationOfInventory.class, Location.class, ExpressionType.SIMPLE, "[mor.]location of [inventory] %inventory%");

ExprLocationOfInventory.class pastebin:
https://pastebin.com/v2Z7PDSM

It is really weird. All is only happening, when I register one of this two things.
I have noticed that those things contains newest bukkit classes/methods. Maybe this is the case?
I am using spigot 1.10.2 and newest Skript.jar release from this site.
Thanks for any help.

**Comment by bensku** [comment] 2017-08-22 14:02
Interesting, have never encountered this. Sadly issues like these are extremely difficult to trace for me too. I'm not even sure if this is a bug or intended behaviour... Will take a look at some point when I have too much time.

**Comment by piter909** [comment] 2017-08-25 13:14
I am suprised too. Never saw something like this :P
The similar thing of this two classes is that, they are pretty new in bukkit. Maybe problem is inside this classes? Maybe somewhere is @override with same method and it is bugging it?

**Comment by TheLimeGlass** [comment] 2018-01-12 20:24
I ran into this issue a few days ago. My conclusion and fix is that; When using expressions within the event syntax. You MUST extend a SkriptEvent it can't be a SimpleEvent because the whole point of having an expression in the event is to handle it via a SkriptEvent class. That is the main issue of this report.

I encountered this and fix it right away but there is also another issue that crashes Skript. If you're making a custom event and it doesn't have a `static` HandlerList it will cause this issue and sometimes crash Skript aswell. So in conclusion you should be extending SkriptEvent and making that extended class replace the `SimpleEvent.class` parameter.

You can close this issue if you want @bensku it's due to improper API handling and is quite old.

**Closed** 2019-06-09 19:14 UTC
Labels: investigating
