### ISSUE TITLE
Suggestion: Parse quotes (") better in expressions in strings

### ISSUE THREAD

**Issue by noftaly** [SkriptLang/Skript#2806] opened 2020-02-04 17:52 UTC
Hi!
I have a suggestion:
I think we should be able to do things like that in strings:
```vb
message "%myFunction("Hello")% world"
message "%"Hi" if {_x} is 0, else "Hello"% world"
```
instead of
```vb
message "%myFunction(""Hello"")% world"
message "%(""Hi"") if {_x} is 0, else (""Hello"")% world"
```

In other words, strings in "embedded" expressions should be surrounded with simple quotes, like normal strings, not with double quotes...

It will help with visibility, it will be easier for newcomers and more intuitive, and it will fit better with the core idea of Skript: being natural English phrases (you will never write ""..."" in a correct English 😄 )

**Comment by ShaneBeee** [comment] 2020-02-04 19:17
I honestly don't think this will ever happen.
How would Skript know when a quote is an inner quote and not just the end of a quote?

You have to do things like this in any programming language, java for example:
```java
String string = "this is some string \"this is an inner string\" more string";
```

The language needs to be able to define which quote actually ends the string.

**Comment by noftaly** [comment] 2020-02-04 19:25
> I honestly don't think this will ever happen.
> How would Skript know when a quote is an inner quote and not just the end of a quote?
> 
> You have to do things like this in any programming language, java for example:
> 
> ```java
> String string = "this is some string \"this is an inner string\" more string";
> ```
> 
> The language needs to be able to define which quote actually ends the string.

I meant in expressions inside a string, between the %%.
I know with JavaScript you can do ```js
let msg = `${true ? `Hello` : "Hi"} world`;
```, where ${} is the equivalent of “%%” in Skript

**Comment by TheLimeGlass** [comment] 2020-02-24 23:51
Related https://github.com/SkriptLang/Skript/issues/1295

**Comment by real2two** [comment] 2020-05-01 18:27
I think this would also be possible by only checking if the first quote exists and where the last quote is and then continue from the last quote, but implementing this kinda looks like you would need to somehow define if you are using double quotes or just this

**Comment by TPGamesNL** [comment] 2021-02-20 10:54
Closing as a duplicate of https://github.com/SkriptLang/Skript/issues/590

**Closed by TPGamesNL** 2021-02-20 10:54 UTC
Labels: enhancement, priority: lowest
