### ISSUE TITLE
Syntax conflict with potion effect

### ISSUE THREAD

**Issue by Romitou** [SkriptLang/Skript#5117] opened 2022-09-24 17:02 UTC
### Skript/Server Version

```markdown
[18:52:36 INFO]: [Skript] Server Version: git-Paper-42 (MC: 1.18)
[18:52:36 INFO]: [Skript] Skript Version: 2.6.3 (selfbuilt-unknown)
[18:52:36 INFO]: [Skript] Installed Skript Addons:
[18:52:36 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Using the `apply %potioneffects% to %livingentities%` effect is impossible: another pattern is matched instead of the one it should have been.

According to the [EffPotion](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffPotion.java#L53-L56) class, four patterns are registered:
- `apply [potion of] %potioneffecttypes% [potion] [[[of] tier] %-number%] to %livingentities% [for %-timespan%] [(1¦replacing [the] existing effect)]`
- `apply ambient [potion of] %potioneffecttypes% [potion] [[[of] tier] %-number%] to %livingentities% [for %-timespan%] [(1¦replacing [the] existing effect)]`
- `apply [potion of] %potioneffecttypes% [potion] [[[of] tier] %-number%] without [any] particles to %livingentities% [for %-timespan%] [(1¦replacing [the] existing effect)]`
- `apply %potioneffects% to %livingentities%`

### Expected Behavior

The expected behaviour is that the fourth pattern is matched, except that the first is matched.

### Steps to Reproduce

```applescript
command /potion:
    trigger:
        set {_potion} to potion effect of slowness of tier 5 for 10 seconds
        apply {_potion} to player
```
The `apply {_potion} to player` effect is not effective because it matches the syntax `apply [potion of] %potioneffecttypes% [potion] [[[of] tier] %-number%] to %livingentities% [for %-timespan%] [(1¦replacing [the] existing effect)]`.
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffPotion.java#L53

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2022-09-24 17:30
alright so I've already found a fix for this I'll see about making a pull request for it shortly
all we have to do is move `apply %potioneffects% to %livingentities%` to the first pattern and everything works as intended
found no other issues while testing

**Comment by TheLimeGlass** [comment] 2022-09-24 17:57
Probably related to it not knowing the type of the variable.

**Closed** 2022-11-22 00:28 UTC
Labels: bug, priority: low, completed
