### ISSUE TITLE
MySQL variables don't want to delete themselves

### ISSUE THREAD

**Issue by Emrolehero** [SkriptLang/Skript#3541] opened 2020-11-14 08:06 UTC
### Description
MySQL variables don't clear when we use the effect:
clear {variable}
It clear the variable in the server loaded when starting but not in the mysql skript table.

### Steps to Reproduce
I tried to delete a variable with a command but when the server restarted, the variable was still here because at server start the variables are loaded from mysql database.

### Expected Behavior
Variables don't delete themselves in MySQL database. The clear effect just clear the variable until the server restart.

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/56135028/99142779-9abd3200-2658-11eb-833d-f6640972f6d7.png)
![image](https://user-images.githubusercontent.com/56135028/99142786-a6105d80-2658-11eb-964f-fc72b955ed9c.png)

### Server Information
* **Server version/platform:** Paper 1.15.2
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment] 2020-11-14 09:42
I know this isn't really a duplicate of #568 but I'm going to mark it as one. Mainly due to the entire MySQL system in Skript does not currently work, and bensku has stated there are no current plans to fix it!

If you would like to continue discussion regarding MySQL issues please refer to #568

**Closed by ShaneBeee** 2020-11-14 09:42 UTC

**Comment by Emrolehero** [comment] 2020-11-14 09:45
Is this also the case with SQLite?
