### ISSUE TITLE
on rightclick doesn't work if second hand is in use

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#2176] opened 2019-06-18 18:36 UTC
### Description

like in topic, on rightclick doesn't work if second hand is used

### Steps to Reproduce

> on rightclick on very berried sweet berry bush:
>     send "test"

it works when second hand is empty, if u have a torch for example - it doesn't works

### Expected Behavior

I think it should work when you have smth in second hand

### Server Information
* **Server version/platform:**Paper 94 1.14.2       
* **Skript version:** 2.4-alpha3

**Comment by TheRemiDev** [comment] 2019-07-11 18:26
The problem is still not solved, it's getting boring, it poses a lot of problems...

**Comment by iOshawott** [comment] 2019-07-11 18:42
even no assigned priority

**Comment by TheBentoBox** [comment] 2019-07-11 18:44
This one fell through the cracks but if it's true it's definitely a huge issue

**Comment by TheRemiDev** [comment] 2019-07-11 21:22
Yes, I confirm that to be a big problem it is! For all actions / possible mini-games with the double hand, which uses for example an NPC, as soon as you put something in the second hand, without having anything in the first hand, it no longer works.

**Comment by SiebeDW** [comment] 2019-08-06 10:29
I can not reproduce this.

**Comment by TheBentoBox** [comment] 2019-08-06 13:38
Likely resolved in the latest release.

**Closed by TheBentoBox** 2019-08-06 13:38 UTC
Labels: bug, priority: high
