### ISSUE TITLE
java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by Zzheyd** [SkriptLang/Skript#2903] opened 2020-04-03 12:55 UTC
Hi here, i dont know why ... 2 time /5 i need re restart my server because skript dont load correctly 

And have this :

https://pastebin.com/Y9GKk2Qc

Paper 1.15.2 / Skript v2.4.1

If you have any idea :s please

**Comment by Romitou** [comment] 2020-04-03 13:23
Seems to be duplicate of #2752.

**Closed** 2020-04-03 13:35 UTC
Labels: duplicate
