### ISSUE TITLE
Checking player's tool and NBT issue

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1758] opened 2018-12-18 20:57 UTC
Okay, There's a little problem with skript for example:

```
command /isitpickaxeoffort3:
	trigger:
		if player's tool is diamond pickaxe of fortune 3:
			send "&aYes is is!"
		else:
			send "&cNo, it isn't!"
```

And a problem:

https://youtu.be/nI2sU6g09NQ

**Comment by TheBentoBox** [comment] 2018-12-18 21:03
This is actually a duplicate of #420. You're checking if the item is, exactly, a diamond pickaxe of fortune 3. If there are ANY other properties on it, the exact item comparison won't match, so it will fail. For now, you should just be able to individually check the tool's type and the level of fortune of the tool.

**Closed by TheBentoBox** 2018-12-18 21:03 UTC

**Comment by iOshawott** [comment] 2018-12-18 22:14
Hmmm... I remember I could use "any diamond pickaxe" but now it's not possible. Is an expression "any (smth)" not in skript? It's from addons?
