### ISSUE TITLE
Skript cannot handle offline player permissions.

### ISSUE THREAD

**Issue by Adrihun** [SkriptLang/Skript#604] opened 2017-05-29 17:38 UTC
So I got a stat script where if i type /stat (name) it will broadcast in chat, when the player joined, and how much money they have. Unfortunately, when the player is offline, and I try to type the command in, nothing happens. 

Skript can't handle offline player permissions. It would be nice if it could.

**Comment by TheBentoBox** [comment] 2017-05-29 18:12
Not sure how possible it is, but would be nice

**Comment by Snow-Pyon** [comment] 2017-05-29 20:21
This wouldn't be possible such as the most part of permissions plugin load player permissions on join and the method from the SpigotAPI doesn't support offline players. The only way to do this would be using the method that some permission plugin offers to do so, but I don't see any other way.

**Comment by Adrihun** [comment] 2017-05-31 16:57
@Snow-Pyon Pex?

**Comment by Snow-Pyon** [comment] 2017-05-31 21:39
@Adrihun the problem is that Skript would have to do a plugin-specific permission hook (not every permission plugin uses the same method or some of them don't have such feature). I think the Vault has something to achieve this anyways.

**Comment by Adrihun** [comment] 2017-05-31 22:31
@Snow-Pyon SkUnity:

I wanted to ban myself so my posts would get deleted so people would stop being butthurt

**Comment by TheLimeGlass** [comment] 2017-06-01 06:26
You need to create a fake player instance of a player then load the permissions apon them. Thus using reflection with NMS coding and Skript doesn't do that.

Permission managers such as Pex like you said, use database storage systems such as MySQL, Yaml, etc. So that you (The user) can access offline permissions.

**Comment by Snow-Pyon** [comment] 2017-06-01 13:56
> You need to create a fake player instance of a player then load the permissions apon them. Thus using reflection with NMS and Skript doesn't do that.
@TheLimeGlass that doesn't work sadly, if that were the case, the following expression of TuSKe:
```
player data of %offline player%
%offline player%'s player data
```
would work for that and as far I know it doesn't.

**Comment by Tuke-Nuke** [comment] 2017-06-01 15:47
Cause it doesn't trigger the events `on join/connect` so the plugins can set up the permission.

**Comment by FranKusmiruk** [comment] 2020-07-09 23:55
Closing, as it is something hook-related.

**Closed by FranKusmiruk** 2020-07-09 23:55 UTC
Labels: enhancement, priority: low
