### ISSUE TITLE
Teleportation in same world Issue

### ISSUE THREAD

**Issue by Jeremylo1** [SkriptLang/Skript#5945] opened 2023-08-27 20:37 UTC
### Skript/Server Version

```markdown
Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://docs.skriptlang.org/
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Paper-60 (MC: 1.20.1)
Skript Version: 2.7.0-beta3 (skriptlang-github)
Installed Skript Addons: 
 - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
 - SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
 - ItemsAdder v3.5.0c-r4 (devs.beer)
Installed dependencies: 
 - Vault v1.7.3-b131
 - WorldGuard v7.0.9+5934e49
```

### Bug Description

I'm encountering an issue where teleporting a player within the "instances" world does not work as expected. When attempting this teleportation, the player remains stationary. However, when teleporting the player from a different world to the "instances" world, it functions as expected. For debugging purposes, I added test messages, which are displayed correctly, indicating that the events and functions are being triggered.

In my example I use the "instances" world but this is present can import the world name!

### Expected Behavior

A player within the "instances" world should be able to be teleported to another location within the same world without any issues.

### Steps to Reproduce

1. Ensure a player is in the "instances" world.
2. The script is supposed to teleport the player to another location in the "instances" world. This is where the teleportation fails.
3. Here is the specific code used:
```SkriptLang
on death of player:
    if victim's world is "instances":
        cancel event
        leaveDungeon2(victim, "death")
        message "Test 1" to victim

function leaveDungeon2(p: player, reason: text):
    teleport {_p} to location(-51.5, -40.0, 755.5, world("instances"), -180.0, 0.5)
    set {_p}'s gamemode to survival

    set {Donjon2::%{_p}'s uuid%::room} to 0

    remove mining fatigue from {_p}

    message "Test 2" to {_p}

    if {_reason} is "death":
        wait a tick
        extinguish {_p}
        heal {_p}
```

### Errors or Screenshots

No console errors are reported, and in-game, the player receives the "Test 1" and "Test 2" messages, but the teleportation doesn't occur.

### Other

I obviously tried to test the script without any other scripts and addons ;)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2023-08-27 20:45
Cannot replicate on paper 1.20.1 (164) and Skript 2.7.0-beta3. 
Tested with "world" and "world_nether".

Have you tried waiting a tick after cancelling the event before calling the function?

**Comment by Jeremylo1** [comment] 2023-08-27 20:59
I just tested with the "world", "world_nether" and "world_the_end" worlds, the problem remains the same! On the other hand, I can confirm that putting a "wait a tick" before calling the function solved my problem! Thank you and sorry to bother you about this.

Here is the corrected version:
```SkriptLang
on death of player:
    if victim's world is "instances":
        cancel event
        wait a tick
        leaveDungeon2(victim, "death")
        message "Test 1" to victim

function leaveDungeon2(p: player, reason: text):
    teleport {_p} to location(-51.5, -40.0, 755.5, world("instances"), -180.0, 0.5)
    set {_p}'s gamemode to survival

    set {Donjon2::%{_p}'s uuid%::room} to 0

    remove mining fatigue from {_p}

    message "Test 2" to {_p}

    if {_reason} is "death":
        wait a tick
        extinguish {_p}
        heal {_p}
```

**Comment by sovdeeth** [comment] 2023-08-27 21:01
I'm unsure as to the cause, but seems unlikely to be a Skript issue, as teleporting while in the "dying" state has always been iffy. Leaving open for a bit in case others have input.

**Comment by AyhamAl-Ali** [comment] 2024-02-19 07:24
I guess waiting a tick before teleporting is compulsory is death events OR using on respawn event instead. Closing issue due to inacitivity.

**Closed by AyhamAl-Ali** 2024-02-19 07:24 UTC
Labels: investigating, cannot reproduce
