### ISSUE TITLE
on explode doesn't run when "create explosion" effect

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#4014] opened 2021-05-22 03:00 UTC
### Description
"on explode" event doesn't trigger when "create an explosion" effect runs

### Steps to Reproduce
`
command /test:
trigger:
create an explosion of force 2 at player

on explode:
broadcast "Boom!"
`
### Expected Behavior
on explode says "Boom!" when effect runs

### Errors / Screenshots
doesn't have

### Server Information
* **Server version/platform:** PaperSpigot snapshot #667
* **Skript version:** 2.5.3

### Additional Context

**Comment by AyhamAl-Ali** [comment] 2021-05-22 07:02
Added an event for that in #3990

**Comment by TPGamesNL** [comment] 2021-05-22 15:31
Closing as duplicate of #3759

**Closed by TPGamesNL** 2021-05-22 15:31 UTC
