### ISSUE TITLE
(dust|item) is required in the redstone dust alias

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#1684] opened 2018-11-11 17:09 UTC
```
command /monety:
    trigger:
        if player has permission "monety.sk": #TO JEST PERMISJA#
            give 1 sunflower of infinity 1 named "<red><bold>Kryptowaluta" to player
            give 1 redstone dust of infinity 1 named "<red><bold>BitBetterCoin" to player
            give 1 slimeball of infinity 1 named "<red><bold>SlimeCoin" to player # hmmmm #
        else:
            message "<light gre﻿y>Nie masz wystarczajacych uprawnien!<light red> (monety.sk)"
command /wymien:
    trigger:
        if player has 1 redstone named "<red><bold>BitBetterCoin":
            remove 1 redstone named "<red><bold>BitBetterCoin" from player's inventory
            give player diamond sword of sharpness 10 named "&4BitBetterCoin"
        else:
            send "&cNie posiadasz 128 Piekielnych Krysztalow aby to zakupic." 
```

And the error: 
```
[17:09:12 ERROR]: can't understand this condition: 'player has 1 redstone named "<red><bold>BitBetterCoin"' (Krypto.sk, line 11: if player has 1 redstone named "<red><bold>BitBetterCoin":')
[17:09:12 ERROR]: 'else' has to be placed just after an 'if' or 'else if' section (Krypto.sk, line 14: else:')
[17:09:12 INFO]: [Skript] Encountered 2 errors while reloading Krypto.sk!
```

**Comment by ShaneBeee** [comment] 2018-11-11 18:11
This is not a bug.
"redstone" is not an item. 
You gave the player redstone dust, then checked if they had redstone, which isn't a current alias
```
unchanged redstone:
	# Redstone block in building
	redstone (wire|dust block)¦s = minecraft:redstone_wire
	redstone (dust|item)¦s = minecraft:redstone
	any redstone item = redstone block, redstone item
```

**Comment by TheBentoBox** [comment] 2018-11-11 18:15
Updated title to truly reflect the "issue". As Shane said, this is not a bug, but it probably makes sense to make an adjustment to the redstone alias to allow just "redstone" to refer to redstone dust.

**Comment by Misio12320** [comment] 2018-11-11 20:19
Lol. Just wanted create coins and source copied pasted that all some changes by own self cuz I do not understand this language 😂. Started use it yesterday cuz want create a small elevator Skript so... So whats wrong here hm? Can I get repaired script?

**Comment by Misio12320** [comment] 2018-11-11 21:38
Any suggestion: if selected crafting/enchant/open succesfull (do something), ''on specific cords'' - drop, summon, something? I want to do a enchanting table and when enchant is succesfull summon lightningbolt on specific cords. Lol...

**Comment by ShaneBeee** [comment] 2018-11-11 21:41
I suggest joining either the [SkUnity discord](https://discord.gg/0l3WlzBPKX7WNjkf) or [Skript-Chat Discord](https://discord.gg/V4qFVnh) if you are looking for help with writing scripts, as this GitHub is strictly for reporting issues with the Skript plugin itself.

**Comment by Misio12320** [comment] 2018-11-11 22:03
Okay, thanks and where request a suggestions? Thanks for getting answer from you, you are good I saw that on spigot when was talking with you 1 time about worldborder 😂

**Comment by ShaneBeee** [comment] 2018-11-11 22:05
Join one of the two discords I gave the links to.
People there can help you out :)

**Comment by Misio12320** [comment] 2018-11-11 22:12
Did I done something wrong? I suggested here hm 😳how im shamed😂. Yeah anyway thanks for help i would fix that milion Times this 1 Skript lol cuz Im New with that and all :D.

**Comment by TheBentoBox** [comment] 2018-11-12 03:09
This is fixed in the aliases for the next release

**Comment by TheBentoBox** [comment] 2018-11-28 15:03
2.3-beta3's alias update should fix this

**Closed by TheBentoBox** 2018-11-28 15:03 UTC
Labels: aliases, completed, enhancement, priority: low

**Comment by Snow-Pyon** [comment] 2018-11-28 15:17
@bensku for further reference,  you can pass issues between repositories of the same organization. Meaning you could move this to the skript-aliases repo
