### ISSUE TITLE
Parsing Illegal Offline Player Names Causes Significant TPS Drop

### ISSUE THREAD

**Issue by not-3than** [SkriptLang/Skript#3938] opened 2021-05-01 07:56 UTC
### Description

When I run a command like /stats &#$!!, where it is set up as `/stats <offline player>`, Skript can't parse &#$!! as an offline player, because player's cant have symbols in their usernames, but something is going wrong that is making the server freeze for a couple seconds instead of just continuing the code or providing a message saying "Players can't contain symbols in their names."
### Steps to Reproduce

Set up a command that takes offline players into account, either parsing a <text> as an offline player or having <offline player> as one of the arguments. Then run /<cmd> (some random symbols like &#!!) and see the significant TPS drop.
### Expected Behavior

Skript should know that this isn't a possible username for a player, but it takes it a little while to try to parse it as a player.
### Errors / Screenshots

http://prntscr.com/12cln87 (The TPS is constantly 20, except when running a command like this)

### Server Information
* **Server version/platform:** Paper version git-Paper-"b89788a" MC 1.16.5, API 1.16.5-R0.1-SNAPSHOT
* **Skript version:** 2.5.3

### Additional Context

My server runs on a custom fork of Skript, 2.5.3-MH, but upon testing with regular 2.5.3, the issue is still present.

**Comment by TPGamesNL** [comment] 2021-05-01 08:20
This is a duplicate of [your own issue](https://github.com/SkriptLang/Skript/issues/3742)...

If an issue is open but doesn't have the completed tag, it means it has been resolved, but is not yet available in a public release.

**Closed by TPGamesNL** 2021-05-01 08:20 UTC
