### ISSUE TITLE
The plural suffix "s" is ignored after expressions in some scenarios: "%something%s"

### ISSUE THREAD

**Issue by Ofus-Will** [SkriptLang/Skript#2840] opened 2020-03-01 19:56 UTC
### Description
Skript parser does not recognise the "s" at the end of a string 

### Steps to Reproduce
```
                set {_pt} to {session::%loop-player's uuid%}
                if {_pt} > 86400:
                    set {_session::days} to "%floor({_pt} / 86400)%d "
                    remove ( 86400 * floor({_pt} / 86400) ) from {_pt}
                if {_pt} > 3600:
                    set {_session::hours} to "%floor({_pt} / 3600)%h "
                    remove ( 3600 * floor({_pt} / 3600) ) from {_pt}
                if {_pt} > 60:
                    set {_session::minutes} to "%floor({_pt} / 60)%m "
                    remove ( 60 * floor({_pt} / 60) ) from {_pt}
                set {_session::seconds} to "%{_pt}%"
                
                set {_sess} to "%{_session::*}%s"
```

### Expected Behavior
**"s"** should be present at the end of the joined string

### Errors / Screenshots
The parser completely ignores it, and instead says that I shouldn't write **"%{var}%s"** because it's already string (as it just sees it as **"%{var}%"** where **{var}** is of type string)

### Server Information
* **Server version/platform:**       1.15.2
* **Skript version:**                2.5-Alpha1

### Additional Context
This can be fixed utilising `join {session::*} and "s"`, but thought it was worth reporting anyway

**Comment by Govindass** [comment] 2020-03-02 07:04
I've noticed a similar bug with especially the "s" letter in much older skript versions (even 2.2 dev36)

**Comment by Nicofisi** [comment] 2020-03-02 12:58
I would be surprised if this wasn't a duplicate of some other weirdly-named issue due to how old it is and how many times I saw this brought up on other platforms. But hey, this title isn't any better...

**Comment by TPGamesNL** [comment] 2020-03-24 17:36
Duplicate of https://github.com/SkriptLang/Skript/issues/367 probably

**Comment by TheBentoBox** [comment] 2020-03-25 13:31
Thank you, was trying to find 367 when this was logged but I couldn't.

**Closed by TheBentoBox** 2020-03-25 13:31 UTC
