### ISSUE TITLE
Bug: Inventory slot function returns <none> for slots 36-39(armour slots) when they are empty

### ISSUE THREAD

**Issue by RoboBlawck** [SkriptLang/Skript#1488] opened 2018-08-28 06:42 UTC
Slots 36-39 in the inventory slot function represents the armor slots of a player's inventory. When attempting to retrieve the item of an empty armor slot using this function, the function returns `<none>` instead of air.
However, inventory slot works as normal with non-empty items.

Code used:

```
function testSlot(p: player):
	set helm of {_p} to air
	set {_inv} to slot 39 of {_p}'s inventory #slot 39 is helm of player
	set {_armour} to helm of {_p}
	
	broadcast "------- Without diamond_helmet -------"
	broadcast "Inventory Slot: %{_inv}%"
	broadcast "Armour slot: %{_armour}%"
	
	set helm of {_p} to diamond helmet
	set {_inv} to slot 39 of {_p}'s inventory 
	set {_armour} to helm of {_p}
	
	broadcast "------- With diamond_helmet -------"
	broadcast "Inventory Slot: %{_inv}%"
	broadcast "Armour slot: %{_armour}%"
	
	
command /testSlot:
	trigger:
		testSlot(player)
```
Theoretical Result:
```
[23:37:16 INFO]: ------- Without diamond_helmet -------
[23:37:16 INFO]: Inventory Slot: air
[23:37:16 INFO]: Armour slot: air
[23:37:16 INFO]: ------- With diamond_helmet -------
[23:37:16 INFO]: Inventory Slot: diamond_helmet
[23:37:16 INFO]: Armour slot: diamond_helmet
```
Actual Result:
```
[23:37:16 INFO]: ------- Without diamond_helmet -------
[23:37:16 INFO]: Inventory Slot: <none>
[23:37:16 INFO]: Armour slot: air
[23:37:16 INFO]: ------- With diamond_helmet -------
[23:37:16 INFO]: Inventory Slot: diamond_helmet
[23:37:16 INFO]: Armour slot: diamond_helmet
```

While it is a bug, it's not a high-priority bug as you can instead use the Armour slot function as a substitute.

**Comment by TheBentoBox** [comment] 2018-08-28 13:15
I'll label as a super low prio bug for now until a dev can take a look and see why this would be the case. Armor slots are handled differently than the other slots so this may technically be working as intended.

**Comment by SiebeDW** [comment] 2019-09-06 17:17
![image](https://user-images.githubusercontent.com/29002908/64447071-c5b60880-d0da-11e9-8032-c9f7d1587605.png)
I think this is fixed.

Skript Version: 2.4-beta7
Tested MC Version: 1.12.2

**Comment by TPGamesNL** [comment] 2021-04-02 15:02
Fixed in https://github.com/SkriptLang/Skript/commit/83727d873d49a658b548cea386cffbfbebaf581f

**Closed by TPGamesNL** 2021-04-02 15:02 UTC
Labels: bug, needs testing, priority: lowest
