### ISSUE TITLE
Bug: difference involving metadata and timestamps

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1417] opened 2018-07-27 20:53 UTC
dev37c
Reproduce using: (make sure you dont click a block if using this trigger)
```
on left click:
    event-player has metadata value "test":
        difference between now and event-player's metadata value "test"
    set metadata value "test" of event-player to now
```
Reloading this throws this error: https://hastebin.com/fecuwivopu.cs
I have seen a similar error while triggering the script, but cannot reproduce it unfortunately
This error is not thrown, if you set a local variable to the metadata and compare that instead

**Comment by Nicofisi** [comment] 2018-07-27 21:55
Seems to be a duplicate of #994 and maybe something else too

**Comment by Pikachu920** [comment] 2018-07-28 00:00
provides useful, info, though. both of the times this bug was reported it's been with difference between *and* using an expression that has an unknown return type (variables and metadata) so thanks @jaylawl

**Closed by Pikachu920** 2018-07-28 00:00 UTC

**Comment by TheLimeGlass** [comment] 2018-07-28 00:02
parse the metadata as a timespan or whatever you're trying to do, a date and object can't be compared.

**Comment by TheLimeGlass** [comment] 2018-07-28 00:05
Copy of hastebin: https://pastebin.com/ysu27a00

**Comment by Pikachu920** [comment] 2018-07-28 00:48
it does not need to be parsed. metdata acts the same way as variables.
