### ISSUE TITLE
1 log handler was not stopped properly!

### ISSUE THREAD

**Issue by Dancull47** [SkriptLang/Skript#3831] opened 2021-03-17 12:32 UTC
### Description

Occasionally when I reload a specific Skript, I get spammed with the "log handler" error. It works perfectly fine with a Server Restart, and I never face any issues, I only get errors thrown and the script stops working when I reload it.
### Errors / Screenshots

https://pastebin.com/2umq8UWB

### Server Information
* **Server version/platform:** 
* **Skript version:** 
![l0Op6s7](https://user-images.githubusercontent.com/36930553/111467796-3d66e980-86fb-11eb-90f9-409c829e3e85.png)

### Additional Context

Script https://pastebin.com/vQppj3qb

![](https://i.imgur.com/l0Op6s7.png)

**Comment by TPGamesNL** [comment] 2021-03-17 17:49
Duplicate of https://github.com/SkriptLang/Skript/issues/3453
Looking at the error, you have a `ExprParse` (`%text% parsed as (%*type%|"<.*>")`) that ran on another thread (not the main server thread). There's a fix for this on the way: https://github.com/SkriptLang/Skript/pull/3800, but not yet merged

**Closed by TPGamesNL** 2021-03-17 17:49 UTC
