### ISSUE TITLE
Timespan doesn't work with weeks

### ISSUE THREAD

**Issue by JIBSIL** [SkriptLang/Skript#4314] opened 2021-09-02 14:36 UTC
### Skript/Server Version

```
[14:33:42 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:33:42 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[14:33:42 INFO]: [Skript] Server Version: git-Paper-221 (MC: 1.17.1)
[14:33:42 INFO]: [Skript] Skript Version: 2.6-beta2
[14:33:42 INFO]: [Skript] Installed Skript Addons:
[14:33:42 INFO]: [Skript]  - SkQuery v4.1.4
[14:33:42 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
[14:33:42 INFO]: [Skript]  - TuSKe v1.8.2 (github.com/Tuke-Nuke/TuSKe)
```

### Bug Description

Weeks don't work in a timespan. `1 week` outputs `< none >`

### Expected Behavior

Output: `1 week`

### Steps to Reproduce

Run this snippet.

```
command /broadcast <text>:
	aliases: /bc
	permission: bc
	trigger:
		set {_time} to "1 week" parsed as timespan
		broadcast "[BROADCAST] %{_time}%"
```

Outputs `< none >`

### Errors or Screenshots

```
< none >
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by wallace4BR** [comment] 2021-09-02 14:51
Timespan only supports ticks/seconds/minutes/hours/days

**Comment by JIBSIL** [comment] 2021-09-02 14:53
> Timespan only supports ticks/seconds/minutes/hours/days

Is there another type that does real world time that can support more?

**Comment by TPGamesNL** [comment] 2021-11-06 08:51
Duplicate of #2220

**Closed by TPGamesNL** 2021-11-06 08:51 UTC
Labels: enhancement, priority: lowest
