### ISSUE TITLE
Wrong error message regarding hastags.

### ISSUE THREAD

**Issue by xSlate6588** [SkriptLang/Skript#6581] opened 2024-04-18 02:55 UTC
### Skript/Server Version

```markdown
[21:52:30 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:52:30 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[21:52:30 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[21:52:30 INFO]: [Skript] Server Version: git-Paper-401 (MC: 1.20.4)
[21:52:30 INFO]: [Skript] Skript Version: 2.8.3 (skriptlang-github)
[21:52:30 INFO]: [Skript] Installed Skript Addons: 
[21:52:30 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[21:52:30 INFO]: [Skript]  - SkBee v3.2.0 (https://github.com/ShaneBeee/SkBee)
[21:52:30 INFO]: [Skript]  - ItemsAdder v3.6.3-beta-12 (devs.beer)
[21:52:30 INFO]: [Skript] Installed dependencies: 
[21:52:30 INFO]: [Skript]  - Vault v1.7.3-b131
[21:52:30 INFO]: [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

The issue is that whenever you have a hashtag included in text, for a hex code or otherwise, and only put one instead of two to tell the code that you meant to put a hashtag it gives the error of using quotes wrong. 
![image_2024-04-17_205334423](https://github.com/SkriptLang/Skript/assets/82844573/e6514d47-e7f2-46ae-8043-bd3e311d69ab)

You can clearly see that my quotes are fine (there is one thing that looks wrong but it's a percentage symbol), but I only have one hashtag. Upon doubling the hashtag the error went away. This has been an issue for multiple versions so far, I even tried to update to the newest version to see if it would fix and it would not. 

### Expected Behavior

The error should specify that the hashtag was not doubled up properly.

### Steps to Reproduce

Include a single hashtag in any text, try to run on server, experience error.

### Errors or Screenshots

![image_2024-04-17_205447902](https://github.com/SkriptLang/Skript/assets/82844573/6cb981f1-f51e-4032-9ac5-1b1b83bb5a47)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Phill310** [comment] 2024-04-18 03:39
The reason it says there is an error with quotes is because the single # denotes a comment. From the parser's point of view all you put was `set message format to "%{_clan}% %player's display name% <`
I am not sure how this issue would be adressed because if you give a warning every time you see 1 #, that just ruins comments

**Comment by xSlate6588** [comment] 2024-04-18 04:27
> The reason it says there is an error with quotes is because the single # denotes a comment. From the parser's point of view all you put was `set message format to "%{_clan}% %player's display name% <` I am not sure how this issue would be adressed because if you give a warning every time you see 1 #, that just ruins comments

I guess that makes sense, thank you for the quick response!

**Comment by sovdeeth** [comment] 2024-04-18 18:55
duplicate of #5181 which was mistakenly closed

**Closed by sovdeeth** 2024-04-18 18:55 UTC
