### ISSUE TITLE
Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2491] opened 2019-09-30 06:43 UTC
I get this error on startup on a fresh server with latest skript:

https://pastebin.com/1T2uTjnv

Another issue (this wg version is needed because of fawe)

Enabling WorldGuard v7.0.0-beta-03;e51a220

[09:04:15] [Server thread/ERROR]: [Skript] An error occurred while trying to enable support for FAWE WorldGuard 7. WorldGuard region support has been disabled!
[09:04:15] [Server thread/ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard

**Comment by Wealthyturtle** [comment] 2019-09-30 07:41
Should be fixed by https://github.com/SkriptLang/Skript/pull/2488, duplicate of https://github.com/SkriptLang/Skript/issues/2487

**Closed** 2019-09-30 15:27 UTC
