### ISSUE TITLE
Add an optional [dyed %color%] when setting player's armor.

### ISSUE THREAD

**Issue by Asleeepp** [SkriptLang/Skript#6606] opened 2024-04-23 17:38 UTC
### Suggestion

Instead of the current `set player's chestplate to leather chestplate` and then having to do `dye player's chestplate red`, you could simply do `set player's chestplate to leather chestplate dyed blue`, or `set player's chestplate to leather chestplate colo(u)red blue` 

Now of course this would only work for leather armor, but yeah.

### Why?

Because I feel like this should be built into the expression, and having to use a seperate effect for it doesn't feel "right" to me. I don't really know how to explain it.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment] 2024-04-23 17:56
Duplicate of #5326

**Closed** 2024-04-23 18:22 UTC
