### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by in0ob4k** [SkriptLang/Skript#3807] opened 2021-03-12 08:18 UTC
```
``[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
[09:14:03] [Server thread/ERROR]: #!#! Run /sk update check to get a download link to latest Skript!
[09:14:03] [Server thread/ERROR]: #!#! You will be given instructions how to report this error if it persists after update.
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Stack trace:
[09:14:03] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Removing entity while ticking!
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.removeEntity(WorldServer.java:1125)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.removePlayer(WorldServer.java:1144)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:448)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1489)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:279)
[09:14:03] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:335)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffKick.execute(EffKick.java:81)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[09:14:03] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[09:14:03] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[09:14:03] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[09:14:03] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:250)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:741)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:1250)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:734)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.EntityTNTPrimed.explode(EntityTNTPrimed.java:88)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.EntityTNTPrimed.tick(EntityTNTPrimed.java:67)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:663)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.World.a(World.java:718)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:398)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1105)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[09:14:03] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[09:14:03] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Version Information:
[09:14:03] [Server thread/ERROR]: #!#!   Skript: 2.5.1 (OUTDATED)
[09:14:03] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[09:14:03] [Server thread/ERROR]: #!#!     Date: 2020-10-22
[09:14:03] [Server thread/ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[09:14:03] [Server thread/ERROR]: #!#!   Minecraft: 1.16.4
[09:14:03] [Server thread/ERROR]: #!#!   Java: 1.8.0_281 (Java HotSpot(TM) 64-Bit Server VM 25.281-b09)
[09:14:03] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Server platform: Spigot
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Current node: null
[09:14:03] [Server thread/ERROR]: #!#! Current item: kick {_exe}(as org.bukkit.entity.Player) on account of "No al grief"
[09:14:03] [Server thread/ERROR]: #!#! Current trigger: explosion (simple event) (grief.sk, line 47)
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Thread: Server thread
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! Language: english
[09:14:03] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[09:14:03] [Server thread/ERROR]: #!#!
[09:14:03] [Server thread/ERROR]: #!#! End of Error.
[09:14:03] [Server thread/ERROR]: #!#!
```

I have this error, what can i do?

**Comment by TPGamesNL** [comment] 2021-03-12 08:23
Duplicate of #2880

**Closed by TPGamesNL** 2021-03-12 08:23 UTC
