### ISSUE TITLE
Bungeecord Support

### ISSUE THREAD

**Issue by Tringlle** [SkriptLang/Skript#4734] opened 2022-04-18 12:31 UTC
### Suggestion

This one is a big change, but could have some extra benefits. Add bungeecord/velocity support, basically, when on bungee, the commands get registered on bungee side, therefore able to be run on all servers at once. 

### Why?

Because it could be useful for things like global server variables

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment] 2022-04-18 15:09
Duplicate of #1509

I wouldn't rely on anyone making this anytime soon btw, this is a big task with little priority

**Closed by TPGamesNL** 2022-04-18 15:09 UTC
