### ISSUE TITLE
[Internal Error Report]Problems regards writing a isAir function to check is certain location of block is air

### ISSUE THREAD

**Issue by Ghostfish123** [SkriptLang/Skript#2967] opened 2020-05-06 01:11 UTC
### Description

Thanks for the time to read through!

Try times to write a location within the function:
1. an internal error occurred sometimes
2. it gave the wrong answer
3. it tell me can't have location/player/world in function event

Then I try to write the location/player/world part outside of the function, such as isAir(block.getID) (java way to say) and compare the ID inside of the function
it tells me an internal error occurred.

Then I try to delete the function, rerun it like this:
```
command ///isAir:
    executable by: players
    trigger:
        set {a} to id of block at location({x2}, {y2}, {z2})
        message "%{a}%"
```
it still give me an internal error

### Steps to Reproduce
```
on break:
    if player's held item is a stone axe:
        cancel event
        set {x2} to rounded down x-position of event-block
        set {y2} to rounded down y-position of event-block
        set {z2} to rounded down z-position of event-block
        message "[TBCBath] Pos1 (X, Y, Z): [%{x2}%, %{y2}%, %{z2}%]"

function isAir(id: number) :: text:
    if {id} is 0:
        return "yes"
    if {id} is not 0:
        return "no"

command ///isAir:
    executable by: players
    trigger:
        set {a} to id of block at location({x2}, {y2}, {z2})
        message "%{a}%"
```
or 
```
command ///isAir:
    executable by: players
    trigger:
        if isAir(id of block at location({x2}, {y2}, {z2})) is "yes":
            make player execute command "/tppos %{x2}% %{y2}% %{z2}%"
            message "yes"
        if isAir({x2}, {y2}, {z2}) is "no":
            make player execute command "/tppos %{x2}% %{y2}% %{z2}%"
            message "no"

command //isAir:
    executable by: players
    trigger:
        if id of block at location at {x2}, {y2}, {z2} is 0:
            message "yes"
        if id of block at location {x2}, {y2}, {z2} of player's world is not 0:
            message "no"
```

### Expected Behavior

it sends me yes is the block is air and sends me no if the block is not air. I want to use this to let code recognize the direction of a building

### Errors / Screenshots
```
> [00:54:27 INFO]: Ghostfish_ issued server command: ///isAir
> [00:54:27 INFO]: Ghostfish_ [72a0f688-a85f-3b10-bb0f-11344b75e11a]: ///isAir
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! [Skript] Severe Error:
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Something went horribly wrong with Skript.
> [00:54:27 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [00:54:27 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
> [00:54:27 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Stack trace:
> [00:54:27 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
> [00:54:27 ERROR]: #!#! at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:317)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:1)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.function.Function.execute(Function.java:136)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:267)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.util.Direction$1.get(Direction.java:387)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.util.Direction$1.get(Direction.java:1)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
> [00:54:27 ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
> [00:54:27 ERROR]: #!#! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [00:54:27 ERROR]: #!#! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [00:54:27 ERROR]: #!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [00:54:27 ERROR]: #!#! at java.lang.reflect.Method.invoke(Method.java:498)
> [00:54:27 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [00:54:27 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [00:54:27 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [00:54:27 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1346)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [00:54:27 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [00:54:27 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
> [00:54:27 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
> [00:54:27 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Version Information:
> [00:54:27 ERROR]: #!#! Skript: 2.5-alpha3 (latest)
> [00:54:27 ERROR]: #!#! Flavor: skriptlang-github
> [00:54:27 ERROR]: #!#! Date: 2020-03-28
> [00:54:27 ERROR]: #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
> [00:54:27 ERROR]: #!#! Minecraft: 1.11.2
> [00:54:27 ERROR]: #!#! Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
> [00:54:27 ERROR]: #!#! OS: Linux amd64 3.10.0-957.el7.x86_64
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Server platform: Spigot
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Current node: null
> [00:54:27 ERROR]: #!#! Current item: set {a}(as java.lang.Object) to the id of (the block (at location({x2}(as java.lang.Number), {y2}(as java.lang.Number), {z2}(as java.lang.Number)) >> ch.njol.skript.expressions.ExprBlock$1@3250d3c4: location -> block))->ch.njol.skript.aliases.ItemType
> [00:54:27 ERROR]: #!#! Current trigger: command ///isair (simple event) (TBCRecogRoofFunctions.sk, line -1)
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Thread: Server thread
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! Language: english
> [00:54:27 ERROR]: #!#! Link parse mode: DISABLED
> [00:54:27 ERROR]: #!#!
> [00:54:27 ERROR]: #!#! End of Error.
> [00:54:27 ERROR]: #!#!
```

### Additional Context
Thank you so much to read this and track the problem!!
I appreciate for creating this plugin for us!

**Comment by Ghostfish123** [comment] 2020-05-06 01:13
another Internal error I got while I attempted several time using a different way:
> [00:51:34 INFO]: Ghostfish_ issued server command: ///isAir
> [00:51:34 INFO]: Ghostfish_ [72a0f688-a85f-3b10-bb0f-11344b75e11a]: ///isAir
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! [Skript] Severe Error:
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Something went horribly wrong with Skript.
> [00:51:34 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [00:51:34 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [00:51:34 ERROR]: #!#! Here is full list of them:
> [00:51:34 ERROR]: #!#! SkQuery v3.6.5
> [00:51:34 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
> [00:51:34 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [00:51:34 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [00:51:34 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [00:51:34 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [00:51:34 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Stack trace:
> [00:51:34 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 0
> [00:51:34 ERROR]: #!#! at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:317)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.classes.data.DefaultFunctions$23.execute(DefaultFunctions.java:1)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.function.Function.execute(Function.java:136)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:267)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:44)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.util.Direction$1.get(Direction.java:387)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.util.Direction$1.get(Direction.java:1)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:168)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:292)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:251)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:251)
> [00:51:34 ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:168)
> [00:51:34 ERROR]: #!#! at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source)
> [00:51:34 ERROR]: #!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [00:51:34 ERROR]: #!#! at java.lang.reflect.Method.invoke(Method.java:498)
> [00:51:34 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [00:51:34 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [00:51:34 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [00:51:34 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1346)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [00:51:34 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [00:51:34 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
> [00:51:34 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
> [00:51:34 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Version Information:
> [00:51:34 ERROR]: #!#! Skript: 2.5-alpha3
> [00:51:34 ERROR]: #!#! Flavor: skriptlang-github
> [00:51:34 ERROR]: #!#! Date: 2020-03-28
> [00:51:34 ERROR]: #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
> [00:51:34 ERROR]: #!#! Minecraft: 1.11.2
> [00:51:34 ERROR]: #!#! Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
> [00:51:34 ERROR]: #!#! OS: Linux amd64 3.10.0-957.el7.x86_64
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Server platform: Spigot
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Current node: null
> [00:51:34 ERROR]: #!#! Current item: set {a}(as java.lang.Object) to the id of (the block (at location({x2}(as java.lang.Number), {y2}(as java.lang.Number), {z2}(as java.lang.Number)) >> ch.njol.skript.expressions.ExprBlock$1@2162a4f6: location -> block))->ch.njol.skript.aliases.ItemType
> [00:51:34 ERROR]: #!#! Current trigger: command ///isair (simple event) (TBCRecogRoofFunctions.sk, line -1)
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Thread: Server thread
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! Language: english
> [00:51:34 ERROR]: #!#! Link parse mode: DISABLED
> [00:51:34 ERROR]: #!#!
> [00:51:34 ERROR]: #!#! End of Error.
> [00:51:34 ERROR]: #!#!

**Comment by Ghostfish123** [comment] 2020-05-06 01:15
I deleted skQuery after the internal error of the comment showed up. Then the first internal error on the top of the page occurred

**Comment by ShaneBeee** [comment] 2020-05-16 22:04
Why are you using numerical IDs and why are you creating a function for this anyways?
You can literally do
```vb
if (block here) is air:
```

I understand the error is most likely frustrating but 2 things to remember here:
1) There is absolutely no reason to be running 1.11.2, and I dont really see anyone on the dev team really wanting to investigate this much further. You should at least be running 1.12.2. There was nothing added/removed/changed in 1.12.x that would deter someone from wanting to use it over 1.11.2.
2) Numeric IDs have been deprecated for years, and haven't been supported by Skript since Skript 2.3. The ID expression basically shouldn't even be used.

**Comment by Ghostfish123** [comment] 2020-05-17 22:18
Thank you to reply, the reason we use 1.11.2 is that in 1.12.2 we can't make a cross glass flowing (we are using the barrier block to make the cross glass right now) in the air anymore. And the one for using numerical IDs is that worldedit is using it :)
our craft style partly relies on cross glass
By the way, where could I find all alias IDs of Skript, I might want to code a function to convert numerical input to that alias.
However, I find out another way to code it, thanks and have a good day!

**Comment by ShaneBeee** [comment] 2020-05-17 22:19
all of the aliases are on the alias repo:
https://github.com/SkriptLang/skript-aliases

**Comment by Ghostfish123** [comment] 2020-05-17 22:27
> all of the aliases are on the alias repo:
> https://github.com/SkriptLang/skript-aliases

Thanks

**Comment by TPGamesNL** [comment] 2021-04-02 15:20
Duplicate of https://github.com/SkriptLang/Skript/issues/3597

**Closed by TPGamesNL** 2021-04-02 15:20 UTC
