### ISSUE TITLE
Console Error on Startup

### ISSUE THREAD

**Issue by ChrisTechke** [SkriptLang/Skript#2462] opened 2019-09-18 22:42 UTC
**Skript Version:** v2.4-beta7

**Server Type:** Paper

**Server Version:** git-Paper-192 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Description:** When the server is started Skript produces this error in the console.

**Log:** https://gist.github.com/ChrisTechke/3a6a05e5d660e1304f34454da6ab29ec

**Comment by Wealthyturtle** [comment] 2019-09-19 07:46
Duplicate of #1117

**Closed** 2019-09-19 13:05 UTC
