### ISSUE TITLE
Parsing of "Indexes of List" expression changed in 2.6.1 and is inconsistent with documentation

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4603] opened 2022-02-16 04:51 UTC
### Skript/Server Version

```
[04:58:26 Server thread/INFO] [Skript] Server Version: git-Paper-399 (MC: 1.17.1)
[04:58:26 Server thread/INFO] [Skript] Skript Version: 2.6.1
```

### Bug Description

This script:

```
command /test:
  trigger:
    set {_test::a} to 1
    set {_test::b} to 2
    set {_test::c} to 3
    message indexes of {_test::*}
    message all indexes of {_test::*}
    message all the indexes of {_test::*}
```

... gives no errors in Skript 2.6, but gives errors in Skript 2.6.1:

```
> sk reload test
[05:12:00 Server thread/INFO] [Skript] Reloading test.sk...
[05:12:00 Server thread/ERROR] Line 10: (test.sk)
    Can't understand this condition/effect: message all indexes of {_test::*}
    Line: message all indexes of {_test::*}

[05:12:00 Server thread/ERROR] Line 11: (test.sk)
    Can't understand this condition/effect: message all the indexes of {_test::*}
    Line: message all the indexes of {_test::*}

[05:12:00 Server thread/INFO] [Skript] Encountered 2 errors while reloading test.sk! (21ms)
```

All these syntaxes are correct according to [current documentation](https://docs.skriptlang.org/expressions.html#ExprIndices):

```
[the] (indexes|indices) of %objects%
(all of the|all the|all) (indices|indexes) of %objects%
```

### Expected Behavior

No errors.

### Steps to Reproduce

Described above.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-02-16 10:38
Duplicate of https://github.com/SkriptLang/Skript/issues/4547

**Closed by TPGamesNL** 2022-02-16 10:38 UTC
