### ISSUE TITLE
[16:15:35 ERROR]: #!#! Something went horribly wrong with Skript.

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#3833] opened 2021-03-18 15:17 UTC
Error:
```
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! [Skript] Severe Error:
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Something went horribly wrong with Skript.
[16:15:35 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:15:35 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[16:15:35 ERROR]: #!#! Here is full list of them:
[16:15:35 ERROR]: #!#! SkQuery v4.1.4 
[16:15:35 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[16:15:35 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[16:15:35 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[16:15:35 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[16:15:35 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[16:15:35 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Stack trace:
[16:15:35 ERROR]: #!#! java.lang.ClassCastException: class org.bukkit.event.entity.CreatureSpawnEvent cannot be cast to class org.bukkit.event.entity.ProjectileLaunchEvent (org.bukkit.event.entity.CreatureSpawnEvent and org.bukkit.event.entity.ProjectileLaunchEvent are in unnamed module of loader 'app')
[16:15:35 ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitEventValues$42.get(BukkitEventValues.java:1)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:267)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:100)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:86)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:112)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:154)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.lambda$0(CondCompare.java:309)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:171)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:308)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:55)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[16:15:35 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[16:15:35 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:15:35 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:15:35 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[16:15:35 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:699)
[16:15:35 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:620)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1188)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1089)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:13)
[16:15:35 ERROR]: #!#!     at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[16:15:35 ERROR]: #!#!     at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[16:15:35 ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldAccess.addAllEntities(WorldAccess.java:13)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:252)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.SpawnerCreature.spawnMobs(SpawnerCreature.java:178)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.SpawnerCreature.a(SpawnerCreature.java:154)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:842)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:629)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:824)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:742)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:461)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1364)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1216)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004)
[16:15:35 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[16:15:35 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Version Information:
[16:15:35 ERROR]: #!#!   Skript: 2.5.3 (latest)
[16:15:35 ERROR]: #!#!     Flavor: skriptlang-github
[16:15:35 ERROR]: #!#!     Date: 2020-12-11
[16:15:35 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[16:15:35 ERROR]: #!#!   Minecraft: 1.16.5
[16:15:35 ERROR]: #!#!   Java: 11.0.9 (OpenJDK 64-Bit Server VM 11.0.9+11)
[16:15:35 ERROR]: #!#!   OS: Linux amd64 4.15.0-112-generic
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Server platform: Paper
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Current node: null
[16:15:35 ERROR]: #!#! Current item: event-entity is equal to the squid (comparator: ch.njol.skript.classes.data.DefaultComparators$14@6a24514b)
[16:15:35 ERROR]: #!#! Current trigger: spawn (spawn) (nolag.sk, line 1)
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Thread: Server thread
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! Language: english
[16:15:35 ERROR]: #!#! Link parse mode: DISABLED
[16:15:35 ERROR]: #!#! 
[16:15:35 ERROR]: #!#! End of Error.
[16:15:35 ERROR]: #!#! 
```
Skript code:
```
on spawn:
	event-entity is squid
	chance of 80%
	cancel event
```

**Comment by Romitou** [comment] 2021-03-18 15:21
I think it's related to https://github.com/SkriptLang/Skript/issues/3499. Can you try with this script to confirm that?
```
on spawn:
	event-entity is a squid
	chance of 80%
	cancel event
```

**Comment by TPGamesNL** [comment] 2021-03-18 15:35
Duplicate of #3499

**Closed by TPGamesNL** 2021-03-18 15:35 UTC

**Comment by XfedeX** [comment] 2021-03-18 15:47
@Romitou You are right, thanks!
