### ISSUE TITLE
Issue in console on my server

### ISSUE THREAD

**Issue by mayalabeybz** [SkriptLang/Skript#3524] opened 2020-11-06 22:26 UTC
I have this issue:
> [23:21:12 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1606)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by ShaneBeee** [comment] 2020-11-06 22:28
Closing due to lack of information.

When reporting issues, please fill in the template provided, rather than deleting it.

On that note, that error is almost always caused by using an outdated version of Skript-mirror.
For future reference, please try reproduce all errors without using any adding before reporting issues. This way you can determine if the issue is coming from an add-on or Skript prior to reporting to Skript.

**Closed by ShaneBeee** 2020-11-06 22:28 UTC
