### ISSUE TITLE
Click events firing twice

### ISSUE THREAD

**Issue by Spaantjes** [SkriptLang/Skript#2259] opened 2019-07-18 15:59 UTC
### Question
Okay I have a problem that when I do a command it automatically does it twice and it is quite annoying.
LINK: https://gyazo.com/cadb808819a67e1544b22f4f49a77f8d

**Comment by TPGamesNL** [comment] 2019-07-18 16:00
Code?
Skript version?
Server version?

**Comment by Spaantjes** [comment] 2019-07-18 16:02
Code: https://pastebin.com/gFgRSa2A
Skript version: 2.3.7
Server version: 1.11.2

**Comment by TPGamesNL** [comment] 2019-07-18 16:08
Do you get the double message when you click the item or when you run the command yourself?
If it's the first, it's probably an issue with SkQuery, not Skript, so it wouldn't belong here. Use TuSKe for you GUI's, not SkQuery.

**Comment by Spaantjes** [comment] 2019-07-18 16:10
When i run the command by my self then i get the double message + with the gui and that gui with tuske i dont know how to do that

**Comment by ShaneBeee** [comment] 2019-07-18 19:13
This can be caused by a double instance of the same script being loaded

Ex: 
Lets say your script is called "Test.sk"
if your server loads, it loads "Test.sk", and if you run `/sk reload test` it will then create a new instance of the same script (This is an error in Skript that's already been reported)

Restart your server and make sure when you reload the script, you are typing it case sensitive.

**Comment by Matocolotoe** [comment] 2019-07-18 19:34
/sk reload (script) should be case sensitive then

**Comment by Blueyescat** [comment] 2019-07-20 10:28
Should be because Citizens's NPC right click event is called for main and off hand. Just use Skript's `right click` event and this shouldn't happen, also use `clicked entity`.

**Comment by TheLimeGlass** [comment] 2019-07-23 19:47
Are you using a plugin that allows multiple clients to join the server? Like ViaVersion or ProtocolSupport.

There is a bug in clicking entity events. When a client like a 1.9 client clicks an entity in 1.8 it sends double for some reason and only in Skript. Baefell fixed this in Baefell's 1.9 edit.

This was also fixed later around 1.11 by Bensku with Npc villagers doing the same.

Try the latest Skript and Spigot and next time please only test with vanilla Skript, SkQuery is no considered vanilla Skript.

**Comment by Wealthyturtle** [comment] 2019-10-15 13:48
Renaming this issue as it seems like the bug is not caused by duplicate script loading but by the event itself firing twice, there's loads of Spigot issues on this, e.g. https://hub.spigotmc.org/jira/browse/SPIGOT-2278, https://hub.spigotmc.org/jira/browse/SPIGOT-1643, etc.

**Comment by bensku** [comment] 2019-10-15 15:20
Skript tries to deduplicate interaction events. Nowadays it usually works.

**Comment by TheLimeGlass** [comment] 2019-10-15 20:23
The event is called twice because one is for the offhand, and one is for the main hand. It's honestly a really poor API design on Spigot to have the same event called twice just to handle the offhand and main hand.

**Comment by Blueyescat** [comment] 2019-10-15 20:47
They are using an addon/plugin event, [my comment](https://github.com/SkriptLang/Skript/issues/2259#issuecomment-513456052) was an explanation to close the issue.

**Comment by Wealthyturtle** [comment] 2019-10-15 23:25
My bad, did not see that this issue is using non-vanilla Skript code

**Closed by Wealthyturtle** 2019-10-15 23:25 UTC
Labels: bug, priority: low
