### ISSUE TITLE
If "on teleport" is used, "on portal" stops working

### ISSUE THREAD

**Issue by oskarkk** [SkriptLang/Skript#4705] opened 2022-03-27 14:06 UTC
### Skript/Server Version

```markdown
[15:51:47 Server thread/INFO] [Skript] Server Version: git-Paper-"aab1f8a" (MC: 1.18.2)
[15:51:47 Server thread/INFO] [Skript] Skript Version: 2.6.1
[15:51:47 Server thread/INFO] [Skript] Installed Skript Addons: None
[15:51:47 Server thread/INFO] [Skript] Installed dependencies: None
```

### Bug Description

If you use `on teleport` event in any script, `on portal` event won't work. 

### Expected Behavior

Both events should be usable in any configuration.

### Steps to Reproduce

```
on teleport:
   stop trigger

on portal:
    log "on portal"
    message "on portal"
```

The above script will give no message when entering the portal. Remove the `on teleport` trigger, **restart the server** and you'll get the message. Without restarting the server, problem persists.

### Other

I've tested it on a clean 1.18.2 Paper server with only the newest Skript installed. No other scripts were present excluding the snippet above.

It was hard to reproduce, finding what prevented `on portal` from working when I had like 40 scripts was tedious, especially because it needed server restarts. It may be related to these issues which were closed because they couldn't be reproduced: #4331, #3006.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:10
On teleport event is called when the portal is about to teleport you, so cancelling on teleport is probably like checking teleport cause = nether protal -> cancel event
![image](https://user-images.githubusercontent.com/20037329/160285528-9f2828ed-6357-4e39-af68-84f6aa7a0c4f.png)

**Comment by oskarkk** [comment] 2022-03-27 14:12
There's no cancelling of the event. `stop trigger` in my example code just does nothing. Actually on my server I had only some message shown to the player after teleporting, so nothing was done with the teleport itself.

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:16
Gotcha, have you tested this on earlier minecraft/skript versions?

**Comment by oskarkk** [comment] 2022-03-27 14:20
No, but the somewhat related issue from SkQuery was present for me for like two years, so if they have the same cause, it's an old bug.

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:23
Tested on 1.16.5, Skript 2.6.1
Tested using `on teleport` before and after `on portal` event

![image](https://user-images.githubusercontent.com/20037329/160286017-c4df6eeb-1590-49b5-9eca-26ee69e35e80.png)

**Comment by oskarkk** [comment] 2022-03-27 14:28
As I've said, I've tested it on a clean server with only Skript. Are you testing on Paper?

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:28
Yes, that's paper, will test on spigot

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:32
Seems like a spigot issue 
![image](https://user-images.githubusercontent.com/20037329/160286448-b0ed4fee-58d1-4d3e-ba09-ec6cf08c4d96.png)

**Comment by oskarkk** [comment] 2022-03-27 14:35
But I've tested it on Paper...

**Comment by AyhamAl-Ali** [comment] 2022-03-27 14:42
Tested using skript-reflect and it works on both paper and spigot
```v

import:
	org.bukkit.event.player.PlayerTeleportEvent
	org.bukkit.event.player.PlayerPortalEvent

on PlayerTeleportEvent:
	# stop trigger
	broadcast "2"

on PlayerPortalEvent:
	broadcast "1"	
	
```

no idea yet what caused it

**Comment by oskarkk** [comment] 2022-03-27 15:10
Don't forget restarting the server every time when you're testing.

**Comment by AyhamAl-Ali** [comment] 2022-03-27 15:12
With the code above, no restart was needed, I was able to switch between skript-reflect methods and skript's methods and former kept working while the latter failed from the first time

**Comment by oskarkk** [comment] 2022-03-27 15:18
Tested, code with skript-reflect works for me on 1.18.2 Paper.

**Comment by oskarkk** [comment] 2022-03-27 15:23
Also this works:

```
import:
    org.bukkit.event.player.PlayerTeleportEvent
    org.bukkit.event.player.PlayerPortalEvent

on teleport:
    broadcast "2"

on PlayerPortalEvent:
    broadcast "1"
```

And this doesn't:

```
import:
    org.bukkit.event.player.PlayerTeleportEvent
    org.bukkit.event.player.PlayerPortalEvent

on PlayerTeleportEvent:
    broadcast "2"

on portal:
    broadcast "1"
```

**Comment by Pikachu920** [comment] 2022-03-28 01:31
Seems like it is an issue with the structure of the Event classes. `PlayerPortalEvent` (on portal) extends `PlayerTeleportEvent` (on teleport) extends `PlayerMoveEvent` (on any move). So basically, it seems like only the highest super of the events in the chain get called. This would explain why `on any move` from skquery breaks `on teleport`. It likely also breaks `on portal`. The reason skript-reflect doesn't have this issue is because it registers it's own listeners and the event that Skript sees is actually a wrapper class which shares no superclass with any Bukkit event.

**Comment by Pikachu920** [comment] 2022-03-28 02:12
I haven't tested but this check seem suspicious especially with the comment by it
https://github.com/SkriptLang/Skript/blob/bc8458fccfc986f71ea4c36aaa02c64439d7f7e5/src/main/java/ch/njol/skript/SkriptEventHandler.java#L68-L69

**Comment by oskarkk** [comment] 2022-03-28 09:44
It's implied in the [Skript docs](https://docs.skriptlang.org/events.html#move) that Skript's `on move` event is never unregistered:

> Called when a player or entity moves. NOTE: Move event will only be called when the entity/player moves position, not orientation (ie: looking around). NOTE: These events can be performance heavy as they are called quite often. If you use these events, and later remove them, a server restart is recommended to clear registered events from Skript.

**Comment by TPGamesNL** [comment] 2022-04-01 12:41
The issue is that Skript only registered an event if there is not already a superclass of that event registered:
https://github.com/SkriptLang/Skript/blob/31bc6c4d5b73fd055535b937e2698c10a086f37d/src/main/java/ch/njol/skript/SkriptEventHandler.java#L259-L274

However, this is not how Bukkit determines which listeners are called for which events. Bukkit determines this by the class that implements the static getHandlerList method (Bukkit stores listeners in an HanderList instance).

Because Skript first registers PlayerTeleportEvent, this adds the listener to the HandlerList of PlayerTeleportEvent. 
Now we get to the next trigger, which tries to register PlayerPortalEvent. However, Skript sees that it has already registered a superclass of this event (PlayerTeleportEvent), and it therefore doesn't register this.
This is a problem, because when CB calls PlayerPortalEvent, its HandlerList does not contain Skript's listener.

This could be fixed by changing the register check to one that first gets the registration class (see `SimplePluginManager#getRegistrationClass`), checks if Skript has a listener registered for that class, and if not registers it (so the registeredEvents set should only contain events from getRegistrationClass).
We could also rework SkriptEventHandler, for example if we want it to unregister listeners, see for example [reflect's](https://github.com/TPGamesNL/skript-reflect/blob/2.x/src/main/java/com/btk5h/skriptmirror/skript/reflect/EvtByReflection.java), downside is that it'll unregister and re-register a listener when reloading.

**Closed** 2023-03-11 04:15 UTC
Labels: bug, priority: medium, completed
