### ISSUE TITLE
on vehicle create: not working with event-entity

### ISSUE THREAD

**Issue by haahl** [SkriptLang/Skript#4820] opened 2022-06-18 15:39 UTC
### Skript/Server Version

```markdown
Skript 2.6.2
Paper 1.18.2
```

### Bug Description

When using on vehicle create: and checking for event-entity, the returned value is `<none>`

### Expected Behavior

The vehicle creation event is supposed to return the entity which has been created.

### Steps to Reproduce

```
on vehicle create:
  send "test %event-entity%"
```
  

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/97468049/174445704-b14ebc3c-db3e-4f9e-867e-8b21b031c232.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-06-18 18:06
Duplicate of #1337

**Closed by AyhamAl-Ali** 2022-06-18 18:06 UTC
