### ISSUE TITLE
Can't set player list name of a variable containing a player

### ISSUE THREAD

**Issue by bluelhf** [SkriptLang/Skript#2485] opened 2019-09-29 14:19 UTC
### Description
Skript doesn't allow you to set the player list name of a variable that contains a player.
(the player list name of {variable} can't be set to anything)

### Steps to Reproduce
1. Set a variable to any player object
2. Try to set the tablist name of that variable

### Expected Behavior
The tablist name should change and no error should be given.

### Errors / Screenshots
![img](https://i.imgur.com/J4lG5ad.png)
![img](https://i.imgur.com/Bon3uMu.png)
![img](https://i.imgur.com/AmDBTAu.png)

### Server Information
* **Server version/platform:** git-Paper-199 (1.14.4)
* **Skript version:** 2.4-beta7

### Additional Context
The issue can be worked around by parsing the string representation of the variable as a player.

**Comment by ShaneBeee** [comment] 2019-10-10 07:29
I can confirm this behaviour.

**Comment by Wealthyturtle** [comment] 2019-10-10 11:50
Really odd indeed... going to investigate this one

**Comment by SiebeDW** [comment] 2019-10-10 19:21
#539

**Comment by ShaneBeee** [comment] 2019-10-10 19:22
duplicate of #539

**Closed by ShaneBeee** 2019-10-10 19:22 UTC
Labels: bug, priority: medium
