### ISSUE TITLE
more hand/off-hand issues

### ISSUE THREAD

**Issue by Pilvinen** [SkriptLang/Skript#51] opened 2016-04-10 07:42 UTC
```
on right click with iron hoe:
  event-block is grass or dirt
  cancel event
```

1) Switch hoe to off-hand.
2) Switch placable block, dirt for example, in main hand
3) Stand on dirt/grass.
4) Look down at your feet.
5) Right click to place the dirt block in your hand.
6) You can't place the dirt block because you are standing on the block where you're trying to place it.
7) Minecraft tries to use the hoe instead.
8) Cancel event above fails to work.

**Comment by TheBentoBox** [comment] 2016-12-24 17:36
I verify this old issue, it is still occurring in 2.2-dev22g.

The problem of course lies in [EvtClick.java](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/events/EvtClick.java), but this is a very complicated issue. In this particular situation, there's actually NO right click event being fired by Skript. I tried with this code:

```
on right click:
	send "%event-item%"
```

Then put a piece of dirt in my main hand, an iron hoe in my offhand, stood on top of some dirt and looked down, then tried to hoe it -- no message.

For @bensku, something that could help you out is checking out the [method summary of the PlayerInteractEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerInteractEvent.html) in detail, most particularly the `hasBlock` and `hasItem` functions, especially combining the former with the `isBlockInHand` function. Really, the issue is Spigot's poor implementation of the dual wielding feature. Realistically, it should just fire one click event -- the one that actually went through. It's such a pain to actually determine which hand's event actually happened as there are so many particular edge cases. For example, if you're standing BARELY inside of a block, and are holding a piece of dirt in your main hand and a small block (e.g. flower pot) in your offhand, the flower pot placement will go through, but any reasonable method of checking would probably tell you that nothing happened as the player tried to place something where they couldn't (since both hands held a block and they were trying to place it inside of themselves).

Not sure of the best way to progress, I'll poke around for any good API-side solutions.

**Comment by bensku** [comment] 2018-05-21 15:53
Someone please verify if this still happens.

**Comment by Blueyescat** [comment] 2018-06-04 19:36
@bensku I did what he says in the issue and i can confirm. PaperSpigot 1.12.2 and Skript 2.2-dev36.

**Comment by TheLimeGlass** [comment] 2018-06-12 09:10
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/bukkitutil/Workarounds.java

**Comment by antoinech2** [comment] 2018-09-23 15:55
Skript 2.2-dev37c with Paper-1438 in Mc 1.12.2

**Comment by xion87** [comment] 2018-10-03 07:10
Same still happen with firework on 1.12.2

**Comment by FranKusmiruk** [comment] 2019-03-14 00:29
Closing this since most of the things mentioned above were fixed and even then, there are new issues covering it.

**Closed by FranKusmiruk** 2019-03-14 00:29 UTC
Labels: bug, help wanted, priority: medium
