### ISSUE TITLE
Time between condition 

### ISSUE THREAD

**Issue by DampfWaffel** [SkriptLang/Skript#5041] opened 2022-08-22 15:26 UTC
### Skript/Server Version

```markdown
[17:21:22 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[17:21:22 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[17:21:22 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[17:21:22 INFO]: [Skript] Server Version: git-Purpur-1632 (MC: 1.18.2)
[17:21:22 INFO]: [Skript] Skript Version: 2.6.3
[17:21:22 INFO]: [Skript] Installed Skript Addons:
[17:21:22 INFO]: [Skript]  - SkImage v1.8
[17:21:22 INFO]: [Skript]  - DiSky v4.1.1
[17:21:22 INFO]: [Skript]  - skript-yaml v1.4
[17:21:22 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[17:21:22 INFO]: [Skript]  - skript-db v1.3.4
[17:21:22 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

the condition is fulfilled although it is not given.
If the time is queried, it will let through everything on the day if `is` given.

### Expected Behavior

`if time in world "world" is between 18:00 and 06:00:` should passes only when its night.

### Steps to Reproduce

```
every second:
	if time in world "world" is dusk or night:
		broadcast "&bye kinda night"
	if time in world "world" is not between 18:00 and 06:00:
		broadcast "&1night time"
	if time in world "world" is between 18:00 and 06:00:
		broadcast "&dshould be night time"
	if time in world "world" is between 06:00 and 18:00:
		broadcast "&6day time"
	if time in world "world" is not between 06:00 and 18:00:
		broadcast "&cshould not be day time"
	broadcast "%time in world "world"%"
```

### Errors or Screenshots

only got a video.
https://cdn.discordapp.com/attachments/1011295008642572370/1011295050489155654/2022-08-22_17-19-14.mp4

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-08-22 15:28
Duplicate of #1354

**Closed by AyhamAl-Ali** 2022-08-22 15:28 UTC
