### ISSUE TITLE
mob spawner type

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4779] opened 2022-06-03 16:19 UTC
### Skript/Server Version

```markdown
[19:16:39 INFO]: [Skript] Server Version: git-Purpur-1628 (MC: 1.18.2)
[19:16:39 INFO]: [Skript] Skript Version: 2.6.2
[19:16:39 INFO]: [Skript] Installed Skript Addons:
[19:16:39 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[19:16:39 INFO]: [Skript]  - skript-gui v1.3-beta2-nightly-e646705 (https://github.com/APickledWalrus/skript-gui)
[19:16:39 INFO]: [Skript]  - BungeeSK v2.0.0 (https://github.com/ZorgBtw/BungeeSK)
[19:16:39 INFO]: [Skript]  - DiSky v4.0-beta4
[19:16:39 INFO]: [Skript]  - skript-yaml v1.4
[19:16:39 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[19:16:39 INFO]: [Skript]  - SkBee v1.16.0-Beta1 (https://github.com/ShaneBeee/SkBee)
[19:16:39 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[19:16:39 INFO]: [Skript] Installed dependencies:
[19:16:39 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

can't give mob spawner to player
skript recognizes mob spawner, spawner as a spawn reason.

### Expected Behavior

recognise spawner and mob spawner as an itemtype in give effect.

### Steps to Reproduce

`!give spawner to player`
`!give mob spawner to player`

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/59025999/171905177-3f94b580-c3ff-4db0-bfbe-4872186b30ad.png)

### Other

This might've been a duplicate issue but I searched spawner and didn't come across with any issues like this.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment] 2022-06-04 03:13
Duplicate of https://github.com/SkriptLang/Skript/issues/4769 I believe

**Closed by APickledWalrus** 2022-06-04 03:13 UTC
