### ISSUE TITLE
IllegalMonitorStateException on shutdown

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#1572] opened 2018-09-30 14:11 UTC
```
[07:09:33] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[07:09:33] [Server thread/ERROR]: #!#! An error occurred while shutting down.
[07:09:33] [Server thread/ERROR]: #!#! This might or might not cause any issues.
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[07:09:33] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[07:09:33] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[07:09:33] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Stack trace:
[07:09:33] [Server thread/ERROR]: #!#! java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
[07:09:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:444)
[07:09:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:428)
[07:09:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1341)
[07:09:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:881)
[07:09:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:416)
[07:09:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:346)
[07:09:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onDisable(Skript.java:920)
[07:09:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[07:09:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363)
[07:09:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[07:09:33] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[07:09:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:365)
[07:09:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:625)
[07:09:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:770)
[07:09:33] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Version Information:
[07:09:33] [Server thread/ERROR]: #!#!   Skript: 2.3-alpha4
[07:09:33] [Server thread/ERROR]: #!#!   Bukkit: 1.13.1-R0.1-SNAPSHOT
[07:09:33] [Server thread/ERROR]: #!#!   Minecraft: 1.13.1
[07:09:33] [Server thread/ERROR]: #!#!   Java: 1.8.0_181 (OpenJDK 64-Bit Server VM 25.181-b13)
[07:09:33] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-862.11.6.el7.x86_64
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Server platform: Spigot
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Current node: null
[07:09:33] [Server thread/ERROR]: #!#! Current item: null
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Thread: Server thread
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! Language: english
[07:09:33] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[07:09:33] [Server thread/ERROR]: #!#! 
[07:09:33] [Server thread/ERROR]: #!#! End of Error.
```

**Comment by Nicofisi** [comment] 2018-09-30 14:13
Duplicate of #1558

**Closed by Nicofisi** 2018-09-30 14:13 UTC
