### ISSUE TITLE
Make aliases also override other plugins command

### ISSUE THREAD

**Issue by WarnDa** [SkriptLang/Skript#6257] opened 2023-12-26 11:36 UTC
### Suggestion

When you use "command /is:" it overrides the **/is** command if used by another plugin.
But if you put this command in aliases, like :
```
command /islands [<text>] [<text>]:
    aliases: is, island
```
Then the "is" and "island" command do not override existing command.

So it would be cool to make aliases override other commands (OR add an expression like "aliases-override: true/false" (and false if not set)

### Why?

I override the command to translate the subcommands or add more informations with tab complete and permissions.
And I wanted to compress my skript instead of having to copy/paste them 4-5 times to changes the aliases.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment] 2023-12-29 01:58
Duplicate of #966

**Closed by sovdeeth** 2023-12-29 01:58 UTC
