### ISSUE TITLE
async

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#3568] opened 2020-11-24 15:40 UTC
async stuff would be pretty epic
```
async loop xxx:
```
```
async:
    loop xxx:
        do xxx
    xxx
```
```
async send "hi"
```
async is available in basically every language lol, it should be in skript as well

**Comment by ShaneBeee** [comment] 2020-11-25 02:10
*incoming long reply*

While it is true that other languages have async operations, Skript is hardly like most languages. 
That said, the majority of the Bukkit API is not thread safe. To add to that, in my opinion, adding something like this is just going to cause more issues than positives. 
ex:
Some users decides to async spawn some entities. 
Then all of a sudden we get a new issue on GitHub because the entities aren't spawning.
"why no work?"

Same thing for manipulating an entity or player. We would need to internally handle all the times Bukkit says "no, you can't do that on another thread"
Something like this couldn't really be done at parse time, unless we were to go thru every single expression/effect/condition and add a method like `isThreadSafe()`, meaning this would have to be checked at runtime, the user is not going to get any "reload" errors.... they're just going to have a bunch of code that doesn't run.

Personally I do not feel this should be in Skript.
Im not saying no to this 100%, as the final decision is not mine to choose, but just restating that in my opinion, I don't think this should be added.

**Comment by TPGamesNL** [comment] 2021-08-15 15:33
Duplicate of #4005, because it has more info

**Closed by TPGamesNL** 2021-08-15 15:33 UTC
Labels: enhancement
