### ISSUE TITLE
Velocity expression not working and docs issues

### ISSUE THREAD

**Issue by Snow-Pyon** [SkriptLang/Skript#792] opened 2017-08-13 18:12 UTC
So, I was gonna try some stuff with this expression and realized that it doesn't have any type value, that means you can't get the velocity from anywhere therefore it throws a NullPointerException. 

Now, here are some issues with the current documentation:

- [x] This expression doesn't have the correct "since" value, it's "INSERT VERSION" right now:
http://bensku.github.io/Skript/expressions.html#ExprVelocity

- [ ] The `world`, `tree type`, `time`, `timeperiod`, `timespan`, `experience`, `item type`, `item/material`,  `number` and `enchantment type` classinfos has some html tags around it.

- [ ] The `potion effect type` classinfo has `null` between its values.

- [ ] The `enchantment` classinfo has `enchantments.names.sweeping_edge` between its values.

- [ ] The `direction`, `command sender`, `entity type with amount` and `living entity` classinfos has a href tag in the pattern.

**Comment by bensku** [comment] 2017-08-13 18:56
Oooops, I probably merged this pull request a bit too fast, as it had some other useful features. @Snow-Pyon please post the NPE here fully. I hope @Sashie takes a look at it before next release, as I'm kinda busy.

Docs issues are something that I'll need to check. Thanks for reporting them.

**Comment by Snow-Pyon** [comment] 2017-08-13 19:15
Well, I think my memory didn't serve me right, it wasn't a NPE, it was an IndexOutOfBoundsException. Here is it anyways:
https://gist.github.com/Snow-Pyon/c44641627b2a33c37942c5f58f92ff26

**Comment by JeepSmash** [comment] 2017-08-14 02:45
More doc issues:
Every expression/condition/event/etc with a link in its description is Broken.  404 error for every link i could find in the docs

**Comment by bensku** [comment] 2017-08-14 04:12
@Snow-Pyon Try without addons...

**Comment by Snow-Pyon** [comment] 2017-08-14 10:11
@bensku the addons doesn't matter, it's clearly an issue of Skript as how the velocity expression is being registered.

**Comment by bensku** [comment] 2017-08-15 14:45
The thing is, addons can override expressions with their own, so if an addon had velocity expressions, it might break stuff. But anyway, doesn't seem to be the cause in this case.

**Comment by TheBentoBox** [comment] 2019-06-09 19:21
I believe this has been fixed long ago by now. At least, I personally have used the velocity expression without issue.

**Closed by TheBentoBox** 2019-06-09 19:21 UTC
Labels: bug, documentation, priority: medium
