### ISSUE TITLE
custom helmet example script fix

### ISSUE THREAD

**Issue by OGContent** [SkriptLang/Skript#4053] opened 2021-06-03 06:31 UTC
(So the first thing the preset script fix because this preset script allows a dupe, if ur helmet slot was air and you tried to put in the custom helmet the helmet slot will become ur custom helmet + ur cursor would still have the custom helmet
```
# Allows specified items to be used as helmets for survival players (Minecraft 1.9 recommended).
#

aliases:
    custom helmets = iron block, gold block, diamond block # Change this to anything you'd like

on inventory click:
    inventory action is place all or nothing
    cursor slot of player is custom helmets # Check if item is allowed as helmet
    event-slot is helmet slot of event-player # Check that player clicked the helmet
    cancel the event
    set {_old helmet} to helmet of player # Store old helmet
    set helmet of player to cursor slot of player # Set new helmet to item in player's cursor
    set cursor slot of player to {_old helmet} # Set player's cursor to old helmet, possibly air

on right click:
    tool of player is custom helmets
    helmet of player is air
    cancel the event
    set helmet of player to tool of player
    set tool of player to air
```
    
 so the last 3 lines of the `on inventory click:` is the issue and it should be updated to 
```
    set {_old helmet} to helmet of player # Store old helmet
    if event-slot is air: # Checks if the helmet slot is air
        set helmet of player to cursor slot of player # Set new helmet to item in player's cursor
        set cursor slot of player to air # Will set player's cursor to air
        stop #Stops the code
    set helmet of player to cursor slot of player
    set cursor slot of player to {_old helmet} # Set player's cursor to old helmet
```
edit: the fix didn't work after 1 restart ;/

**Comment by TPGamesNL** [comment] 2021-06-03 06:47
2nd is duplicate of https://github.com/SkriptLang/Skript/issues/3899

**Closed** 2022-01-26 05:30 UTC
Labels: enhancement, priority: low, completed
