### ISSUE TITLE
Passing block type to object function won't stay as a block type

### ISSUE THREAD

**Issue by EndergamerHUN** [SkriptLang/Skript#4381] opened 2021-10-28 09:58 UTC
### Skript/Server Version

```
[CHAT] [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[CHAT] [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[CHAT] [Skript] Server Version: git-Paper-338 (MC: 1.17.1)
[CHAT] [Skript] Skript Version: 2.6-beta3
[CHAT] [Skript] Installed Skript Addons:
[CHAT] [Skript]  - skript-reflect v2.2.2-dev (https://github.com/TPGamesNL/skript-reflect)
```

### Bug Description

When you pass a block to a function that requires an object, the type of the variable will not be a block (using if {_object} is a block:). When I try it with item, it works as expected, but not with block. This works in 2.6-beta1, but breaks in 2.6-beta 2 or 3.

### Expected Behavior

When passing it a block type, it will be a block type in the function.

### Steps to Reproduce

This is the code I used: (It needs skript-reflect for broadcasting the class information)
```
function getType(object:object):
    broadcast "&6Testing&f %{_object}%"
    broadcast "&6Type:&f %{_object}'s class%"
    broadcast "It is a block" if {_object} is a block
    broadcast "It is an item" if {_object} is an item
    broadcast ""

command /testBlock:
    trigger:
        broadcast "&4Testing block"
        getType(block below player)
command /testItem:
    trigger:
        broadcast "&4Testing item"
        getType(player's tool)
```

### Errors or Screenshots

[Screenshot](https://imgur.com/a/yptrrlg)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TheLimeGlass** [comment] 2023-08-02 09:54
Actually a duplicate of https://github.com/SkriptLang/Skript/issues/5536

**Closed as completed by TheLimeGlass** 2023-08-02 09:54 UTC
