### ISSUE TITLE
Parsing as item do not work

### ISSUE THREAD

**Issue by weberlepecheur** [SkriptLang/Skript#1862] opened 2019-01-30 16:49 UTC
### Description
~~I have the same loop in different skript but the loop doesn't works on the same way (yeah hard to explain my issue). One works fine, he recognize my item, but the other one don't.~~

~~On the loop inside the command, all the conditions pass without any problems, but the loop inside the function didn't pass the condition _loop-item is_~~

### Expected Behavior
~~The loop works the same way, but it doesn't~~

### Errors / Screenshots
~~No error..~~

### Server Information
* **Server version/platform:**
Paper 1.13.2-501
* **Skript version:**
Skript 2.3.2

**Read the comments below**

**Comment by BlightedBlue** [comment] 2019-01-30 20:17
Don't use the github for Skript help. Use either the Skript Chat or SkUnity discord servers ([here](https://discord.gg/CUFbm7B) and [here](https://discord.gg/tdEP9md)).

By the way, the problem is that your variable seems to be a string (you parsed it as an item). You can't compare an item with a string.

**Comment by weberlepecheur** [comment] 2019-01-30 21:08
Im not asking for help.. A make this code because of this issue #1836 i opened days ago. 
I saved the variables like this :

> add trident to {Tellus_peuple::%{_peuple}%::1::*}

Still even if i make a local variables parsed as item is didnt work either..

**Comment by GermanMinerDE** [comment] 2019-01-31 16:55
Same problem here.

**Comment by GermanMinerDE** [comment] 2019-01-31 17:01
Same problem here

We save item types to a string like:
`set {item-type-name} to "%type of tool of player%"`

Then we want to get it back:
`set {_item-parsed} to ({item-type-name} parsed as item)`

Doesn't work.
We need to do that like this, because we want to be efficient with variable usage (> 400 players daily) and save more information into the one string-variable with splitters.
Example: `set {item} to "%type of tool of player%;;;%damage of tool of player%;;;%{_otherVar}%;;;%nbt of tool of player%"`

Paper 1.12.2 Build 1596
Skript 2.3.2

**Comment by bensku** [comment] 2019-02-01 12:00
Duplicate of #1850. As a side note, I'm not exactly convinced that your variable usage is in any way efficient.

**Closed by bensku** 2019-02-01 12:00 UTC
