### ISSUE TITLE
Allow Priority with Events

### ISSUE THREAD

**Issue by Dancull47** [SkriptLang/Skript#3850] opened 2021-03-23 21:08 UTC
Currently it seems the only way to change the priority of listening for an Event is by setting Skript's plugin priority in the config.yml or using an Add-On which allows for Java usage like Skript-Mirror.

It'd be extremely useful if we could change the priority based on each Event of our choice, rather than relying on an add-on, or one overall set within the config.yml which affects all scripts.

Why would this be useful? Sometimes you may make a script which has to work with another Plugin. Lets say for example, one Plugin cancels block breaks, but you want Skript to still track it. You would then have to set the priority of the Event lower than what the Plugin which cancels it is set to, or just set it to the lowest. Once set, you can then track the block break like you wanted.

**Comment by Ankoki-Dev** [comment] 2021-03-24 01:05
I can't really think of a way this could be nicely implemented, maybe an ```on %event% [with [the] event-priority [of] %priority%```? or maybe as shane touched on before in the squinty discord, annotations like in bukkit

**Comment by Dancull47** [comment] 2021-03-24 02:16
> I can't really think of a way this could be nicely implemented, maybe an `on %event% [with [the] event-priority [of] %priority%]`? or maybe as shane touched on before in the squinty discord, annotations like in bukkit

Yes, I was thinking exactly like the example you gave! This is an example of the usage with Mirror `on BlockBreakEvent with priority LOWEST:`

**Comment by FranKusmiruk** [comment] 2021-03-24 03:44
duplicate of https://github.com/SkriptLang/Skript/issues/197

**Closed by FranKusmiruk** 2021-03-24 03:44 UTC
