### ISSUE TITLE
anvil inventory deleting items

### ISSUE THREAD

**Issue by SubGplayz** [SkriptLang/Skript#6812] opened 2024-06-23 21:43 UTC
### Skript/Server Version

```markdown
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Server Version: git-Purpur-2062 (MC: 1.20.1)
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Skript Version: 2.8.4 (skriptlang-github)
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Installed Skript Addons: 
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - skript-placeholders v1.6.0 (https://github.com/APickledWalrus/skript-placeholders)
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - SkBee v3.4.3 (https://github.com/ShaneBeee/SkBee)
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - skript-oraxen v1.0
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - SkVault v2.0
[22:36:10] [Render thread/INFO]: [CHAT] [Skript] Installed dependencies: 
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - Vault v1.7.3-b131
[22:36:10] [Render thread/INFO]: [CHAT] [Skript]  - WorldGuard v7.0.9+5934e49
```

### Bug Description

When I open an anvil inventory to the player and shift click an item into the gui, it deletes the item.

### Expected Behavior

When shift clicking the item into the gui, it should not delete the item, and should act the same as a vanilla anvil.

### Steps to Reproduce

1. use the following skript:
```
command /anvil:
    trigger:
        show anvil inventory for player
```

2. run the command /anvil
3. shift click an item into the anvil gui

### Errors or Screenshots

https://youtu.be/G-7mAv2HEYQ

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2024-06-30 09:55
duplicate of #6470

**Closed by sovdeeth** 2024-06-30 09:55 UTC
