### ISSUE TITLE
Skript Startup Severe Error

### ISSUE THREAD

**Issue by masonzettle** [SkriptLang/Skript#2557] opened 2019-10-13 02:32 UTC
### Description

On server startup, I receive a severe error from Skript and a few of my skript features break because of the error.

### Steps to Reproduce

Considering how I still get the error even if I remove all skripts and addons, I don't know how to give an accurate way of reproducing this issue.

### Expected Behavior

I shouldn't be getting errors from Skript and all of my skript files should work.

### Errors / Screenshots

Here is a link to the severe error: https://gist.github.com/masonzettle/2b4212ad6329da5b63cbdf6e497c7a0b

### Server Information
* **Server version/platform:**       git-Paper-193 (MC: 1.14.4)
* **Skript version:**                2.4-beta8

### Additional Context

I began having these issues after trying to add some code to set a variable to a trident that would take more damage than usual if it hit an entity. Since then, there has been no way of fixing this error.

**Comment by Wealthyturtle** [comment] 2019-10-13 04:53
Thanks for the report, but this is a duplicate of #2487

**Closed by Wealthyturtle** 2019-10-13 04:53 UTC
