### ISSUE TITLE
Severe Error with loop-value in difference expression

### ISSUE THREAD

**Issue by JeepSmash** [SkriptLang/Skript#718] opened 2017-07-11 01:39 UTC
I'm getting severe errors trying to get the difference between a loop-value (a date/time) and 'now'

Did not have this issue until updating to most recent (1.12) version of skript

the issue seems to be with using 

```
loop {_finishtimes::*}:
 set {_dif} to difference between loop-value and now
```

but changing it a little and there is no more severe error

```
loop {_finishtimes::*}:
  set {_ftime} to loop-value
  set {_dif} to difference between {_ftime} and now
```

So my guess is that there isn't support or compatibility for using loop-value in a difference expression

Here is the Console error Message
```
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! End of Error.
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! Thread: Server thread
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! Current item: null
10.07 18:03:35 [Server] ERROR #!#! Current node: set {_t} to difference between loop-value and now (itemmod.sk, line 240)
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! Running CraftBukkit: false
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.6.2.el6.x86_64
10.07 18:03:35 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
10.07 18:03:35 [Server] ERROR #!#!   Minecraft: 1.12
10.07 18:03:35 [Server] ERROR #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
10.07 18:03:35 [Server] ERROR #!#!   Skript: 2.2-dev29
10.07 18:03:35 [Server] ERROR #!#! Version Information:
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source)
10.07 18:03:35 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
10.07 18:03:35 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
10.07 18:03:35 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
10.07 18:03:35 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
10.07 18:03:35 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
10.07 18:03:35 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:695)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:66)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
10.07 18:03:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:324)
10.07 18:03:35 [Server] ERROR #!#!     at java.lang.Class.isAssignableFrom(Native Method)
10.07 18:03:35 [Server] ERROR #!#! java.lang.NullPointerException
10.07 18:03:35 [Server] ERROR #!#! Stack trace:
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
10.07 18:03:35 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
10.07 18:03:35 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
10.07 18:03:35 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
10.07 18:03:35 [Server] ERROR #!#! and check whether this error has already been reported.
10.07 18:03:35 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
10.07 18:03:35 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
10.07 18:03:35 [Server] ERROR #!#! 
10.07 18:03:35 [Server] ERROR #!#! Could not load itemmod.sk
10.07 18:03:35 [Server] ERROR #!#! [Skript] Severe Error:
10.07 18:03:35 [Server] ERROR #!#!
```

**Comment by bensku** [comment] 2017-07-19 09:04
Interesting... Bugs like this were supposed to be already fixed.

**Comment by JeepSmash** [comment] 2017-10-01 17:50
Additional info:
When this issue occurs Skript does not report any errors or problems in game with the /sk reload <script> command.  It actually reports that it is all good with no errors and successful reload
```
[Skript] Reloading jobv2.sk...
[Skript] Successfully reloaded jobv2.sk.
```
but upon trying to use any command or event from that file resulted in "unknown command" or nothing happening telling me that the entire file was not loaded not just the part with an error.  Checking console output is the only way to see what the error is or that there was an error at all

**Comment by TheLimeGlass** [comment] 2018-05-03 04:04
Potentially related https://github.com/bensku/Skript/issues/575

**Comment by ShaneBeee** [comment] 2020-08-06 23:04
Closing as duplicate of #575

**Closed by ShaneBeee** 2020-08-06 23:04 UTC
Labels: bug, needs-testing, priority: medium
