### ISSUE TITLE
why loop serveral many times?  (  on inventory click )

### ISSUE THREAD

**Issue by zidlsl** [SkriptLang/Skript#2702] opened 2019-12-17 11:26 UTC
### Description

On inventory click Event
i using Loop

but several times like 2 or 3

### Errors / Screenshots

![제목 없음](https://user-images.githubusercontent.com/35989737/70991680-51442a00-210b-11ea-9084-a1f68148b1c4.png)

### Server Information
* **Server version/platform:**        1.12.2
* **Skript version:**                 2.4

**Comment by zidlsl** [comment] 2019-12-17 12:06
i think problem is cancel event

**Comment by Wealthyturtle** [comment] 2019-12-17 14:04
Is there a parse error with this script? If so, please attach it here.

**Comment by zidlsl** [comment] 2019-12-18 08:10
> Is there a parse error with this script? If so, please attach it here.

No Error

**Comment by Wealthyturtle** [comment] 2019-12-18 11:53
Uhh what's the problem then with the script? What are you reporting exactly?

**Comment by nopeless** [comment] 2019-12-22 02:58
@zidlsl you don’t need to clear {_stack::*}, there are redundant code everywhere.
this place is where you submit issues about skript not issues about your script.
how do you even reproduce the error

i suggest closing

**Comment by Wealthyturtle** [comment] 2019-12-23 08:37
Closing this issue since it is unclear what OP is reporting.

**Closed by Wealthyturtle** 2019-12-23 08:37 UTC
Labels: waiting for reply
