### ISSUE TITLE
There is a ClassCastException when a spawn event is triggered

### ISSUE THREAD

**Issue by 0XPYEX0** [SkriptLang/Skript#4505] opened 2022-01-16 08:06 UTC
### Skript/Server Version

```
Server: Purpur version git-Purpur-1503 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9723e94 on HEAD)
Skript: 2.6 : https://github.com/SkriptLang/Skript/releases/tag/2.6
```

### Bug Description

There is a ClassCastException when a spawn event is triggered

### Expected Behavior

Trigger the event normally

### Steps to Reproduce

on spawn:
    do something

Just like this

### Errors or Screenshots

```
https://paste.ubuntu.com/p/2WwDtqT4Wx/
```

### Other

Nothing

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by bluelhf** [comment] 2022-01-16 13:38
Not reproducible with Skript 2.6 on git-Paper-71 (MC 1.18.1)
```hs
on spawn:
  send "An entity, %event-entity%, just spawned!" to console
  ```

Results in:
![image](https://user-images.githubusercontent.com/52505120/149662393-375a7e75-1052-4220-a908-98820e65c6b3.png)

  
  Please provide a minimum working example that causes the bug to occur.

**Comment by TPGamesNL** [comment] 2022-01-16 13:40
Likely duplicate of https://github.com/SkriptLang/Skript/issues/3499.

Also, as blue said, please either provide the code you used to reproduce the bug, or make sure the code you do send here shows the bug.

**Closed by TPGamesNL** 2022-01-16 13:40 UTC

**Comment by 0XPYEX0** [comment] 2022-01-17 03:58
https://paste.ubuntu.com/p/Qry87djXW3/    This is the error
on spawn:
-if event-entity is skeleton:
--if chance of 3%:
---set helmet of event-entity to wither skeleton skull
---set tool of event-entity to trident
---set offhand tool of event-entity to shield
---set name of event-entity to "&c&l不死战士"
---set max health of event-entity to 25
---set health of event-entity to 25
This is my codes

**Comment by 0XPYEX0** [comment] 2022-01-17 04:00
If I changed the second line just like this
```if event-entity is skeleton:```
to
```if "%type of event-entity%" is "skeleton":```
the event triggered normally
