### ISSUE TITLE
Character "s" doesn't appear after variable in text

### ISSUE THREAD

**Issue by Kormic1** [SkriptLang/Skript#3730] opened 2021-02-01 22:05 UTC
### Description

Title says it all. When you try to send letter "s" right after variable, it won't show up regardless of type of value stored in that variable.

This bug was mentioned in [#2437](https://github.com/SkriptLang/Skript/issues/2437), but it has been closed.

### Steps to Reproduce

Use this code:

```
command /test:
	trigger:
		set {_t} to "s" # or you may set it to anything else
		send "%{_t}%s" to sender
```
### Expected Behavior

Command should send "ss", but it sends only "s", so letter "s" after the variable is ignored.

### Errors / Screenshots

No errors.

### Server Information
* **Server version/platform:** Spigot 1.12.2
* **Skript version:** Skript 2.5.3

### Additional Context

I tried with and without all my Skript addons, no difference.

**Comment by ShaneBeee** [comment] 2021-02-02 02:42
Closing as duplicate of #367

**Closed by ShaneBeee** 2021-02-02 02:42 UTC
