### ISSUE TITLE
event-item bug

### ISSUE THREAD

**Issue by short509** [SkriptLang/Skript#2771] opened 2020-01-15 22:09 UTC
### Description
"event-item" which worked well in version 2.4, does not work.

### Steps to Reproduce
```
on rightclick:
       if player is sneaking:
               message "%type of event-item%" to player
```

### Errors / Screenshots

![2020-01-16_07 05 59](https://user-images.githubusercontent.com/27778635/72475853-2266c400-382f-11ea-8c5e-8213d867fc00.png)

### Server Information
* **Server version/platform:** 1.15.1
* **Skript version:** 2.5-alpha

**Comment by APickledWalrus** [comment] 2020-01-20 04:02
I did some testing, and this only seems to be an issue with click events. The issue is that `the event-item` is returning no value, not the type expression.

**Comment by iOshawott** [comment] 2020-02-02 14:14
well in my skripts
"set {_y} to number of event-item in player's inventory"
doesn't work too :(

**Comment by short509** [comment] 2020-02-02 18:00
> well in my skripts
> "set {_y} to number of event-item in player's inventory"
> doesn't work too :(

"event-item" seems to be the problem.

**Comment by Misio12320** [comment] 2020-02-09 09:17
Give there a priority and event-entity, does not work too

**Comment by iOshawott** [comment] 2020-02-09 09:21
Hope this, 2714 and 2802 will be fixed in next release

**Comment by TheLimeGlass** [comment] 2020-02-24 23:52
Duplicate https://github.com/SkriptLang/Skript/issues/2736

**Comment by bensku** [comment] 2020-02-25 18:37
@TheLimeGlass No, this is separate issue that may be caused by same underlying issue.

**Comment by ShaneBeee** [comment] 2020-03-02 23:58
I think the "issue" here is whether or not you consider this an issue.

Prior versions, `event-item` returned the player's tool.
Whereas now it returns the item type you clicked on.
In this case, you didn't click on anything, hence it being none.
If you right-clicked on grass it would return grass.

Now, in my option, I think this way makes more sense. 
`event-item` = clicked block
`player's tool` = thing in hand.

Personally I wouldn't classify this as a bug, but maybe a change for the better? 
I guess the "issue" here is that it changed, which could potentially break scripts.

**Comment by bensku** [comment] 2020-03-03 15:25
Event item used to give the item that was activated by clicking, which could be offhand item too.

**Comment by iOshawott** [comment] 2020-03-05 19:56
`command /czek [<number>] [<number>]:
	trigger:
		if arg-1 is not set:
			send "&aUżycie: /czek KWOTA ILOŚĆ"
			send "&bKwota: minimum 5"
			send "&cIlość: ilość czeków do wydania (np. 10)"
			send "&e/czek 10 5 da do eq 5 czeków po 10$ każdy"
			stop
		if arg-2 is set:
			if arg-2 is greater than 128:
				stop
		arg-1 is greater than 4.99
		if arg-2 is not set:
			set {_ile} to 1
		else:
			set {_ile} to arg-2
		loop {_ile} times:
			if player doesn't have enough space for 1 bedrock:
				send "&cNo zrób najpierw miejsce w eq"
				stop
			set {_x} to number-argument-1
			set {_x} to {_x}-0.01
			if player's balance is greater than {_x}:
				set {_x} to {_x}+0.01
				remove {_x} from player's balance
				add 1 paper of unbreaking 1 named "&b&lCzek" with lore "&a%number-argument-1%$" to player's inventory
on rightclick with paper:
	if name of player's tool contains "&b&lCzek":
		if player's gamemode is creative:
			send "&cXD"
			stop
		if name of player's tool contains "&b&lCzek":
			if player's gamemode is creative:
				send "&cXD"
				stop
			set {_q} to level of unbreaking of player's tool
			if {_q} is not set:
				delete player's tool
				send "&cTen item nie ma poprawnego enchantu"
				stop
			set {_x} to uncolored line 1 of lore of player's tool
			replace all "$" with "" in {_x}
			set {_x} to {_x} parsed as number
			set {_y} to number of event-item in player's inventory
			set {_z} to the first 2 characters of "%event-item%" parsed as number
			if {_y} is {_z}:
				set {_x} to {_x}*{_y}
			else:
				if {_y} is not 1:
					send "&cZestackuj czeki by je użyć!"
					stop
			execute console command "eco give %player% %{_x}%"
			send " Czek - %{_y}% czeków " to console
			send "%line 1 of lore of player's tool% - %player%" to console
			send " Czek " to console
			delete player's tool`

With event-item doesn't work porperly you can't get "set {_y} to number of event-item in player's inventory", changing it to number of player's tool causes issue, that it can't be more than one and breaks this checks system which works good on 2.4

**Comment by Misio12320** [comment] 2020-04-26 15:05
?!??? How its still need-testing??? Its a bug, go and fix it.

**Comment by iOshawott** [comment] 2020-04-26 16:59
I hope it'll get fixed and then I'll update from 2.4.1 ;|

**Comment by ShaneBeee** [comment] 2020-04-26 19:38
> ?!??? How its still need-testing??? It's a bug, go and fix it.

I don't even know hot to reply to you. Your utter rudeness and sheer ignorance is really bothering me, and some others. 
This is an open source project, please feel free to fix it and submit a PR.

**Comment by Misio12320** [comment] 2020-04-26 21:55
> > ?!??? How its still need-testing??? It's a bug, go and fix it.
> 
> I don't even know hot to reply to you. Your utter rudeness and sheer ignorance is really bothering me, and some others.

I got little rage because Dev of SkQuery has answer me after 2 months of my report bug and said "this is Skript bug". And there is still no update in mean need-testing. Its again my fault because your arguments are not possible to break. Apologies. 

> This is an open source project, please feel free to fix it and submit a PR.

Good to know. If I wouldnt have depressed brain I would try to fix it. Some chill ShaneBee to my rage, thanks.

**Comment by APickledWalrus** [comment] 2020-07-10 15:09
This is still a present issue. `event-item` is returning the wrong value, and this may have broke *many* scripts.

**Closed** 2020-07-21 00:31 UTC
Labels: bug, completed, priority: high
