### ISSUE TITLE
Dismounting detection not working with silverfish

### ISSUE THREAD

**Issue by SiebeDW** [SkriptLang/Skript#2031] opened 2019-04-29 16:16 UTC
### Description
Silverfish entity is not detected on dismount

### Steps to Reproduce
Use this code
```
command /test:
	trigger:
		spawn silverfish at player's location
		make player ride the last spawned entity

on dismount:
	broadcast "Vehicle: %event-entity's vehicle%"
	event-entity's vehicle is silverfish
	broadcast "Found it!"
```

### Expected Behavior
It would say "Found It!" because you are riding a silverfish.

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:**       Paper (Build 624)
* **Skript version:**                       2.3.6 (Last release when the issue got created)

### Additional Context
A dupe of #1361 because it was made in an invalid format.

**Comment by Wealthyturtle** [comment] 2019-10-04 13:15
This isn't specific to silverfish actually, occurs with zombies too - it's a problem related to comparing entity types, since using ``"%event-entity's vehicle%" is silverfish`` fixes the comparison

**Comment by Wealthyturtle** [comment] 2019-10-16 00:56
Closing this issue as it's a comparison issue with entities, and a duplicate of #2213

**Closed by Wealthyturtle** 2019-10-16 00:56 UTC
Labels: bug, priority: low
