### ISSUE TITLE
Click event doesn't work with off-hand for villagers

### ISSUE THREAD

**Issue by ruddeTR** [SkriptLang/Skript#1927] opened 2019-03-02 22:25 UTC
Skript doesn't detect my right click when I have an item in my off hand (but it works with baby villagers).

https://imgur.com/a/2CQpHyX

Skript version: 2.3.5
Server version: paper-551 (1.13.2)

Code:
```
on click on villager:
	{x} isn't "test"
	send "trigger" to player
	cancel event
```

**Comment by Bartuzen** [comment] 2019-03-04 14:10
It's fixed in 2.3.6.

**Comment by ruddeTR** [comment] 2019-03-04 21:02
No, it still exists.

**Comment by FranKusmiruk** [comment] 2019-03-07 19:51
The issue is weird, it won't trigger when you have an usable item in your off-hand and a non-usable one in your main hand, it does trigger when both are usable items though.

**Closed** 2019-05-18 19:52 UTC
Labels: bug, priority: medium
