### ISSUE TITLE
Potions are broken on 1.9

### ISSUE THREAD

**Issue by bensku** [SkriptLang/Skript#2587] opened 2019-10-21 14:31 UTC
### Description
Comparing potions with water yields true on MC 1.9, which is incorrect. MC 1.9 client is broken on Linux (Mint 19.2), so I can't verify if adding potions to inventories is also broken.

### Steps to Reproduce
1. Modify regtest for #2581 to run on 1.9 (on master branch)
2. Asserts fail
3. Log into test development server with 1.9 client and test things

### Expected Behavior
Potion aliases work on all Minecraft versions supported by Skript.

### Errors / Screenshots
Test results:
```
Failed:
  potion aliases (on 1 environments)
    wrong potion alias (on paper-1.9.4)
```

### Server Information
* **Server version/platform:** Paper 1.9.4
* **Skript version:** 2.4 (branch; prerelease status unknown), master

### Additional Context
Target fix to 2.4, and merge to master. Regtest only exists on master.

**Comment by bluelhf** [comment] 2019-10-21 14:36
Related to #2581?

**Comment by bensku** [comment] 2019-10-21 15:40
Yes, noticed this while running regtest on 1.9

**Comment by ShaneBeee** [comment] 2019-10-21 19:37
In my opinion, the priority of this should be higher than "low".
This is caused by https://github.com/SkriptLang/Skript/commit/12662ca8b6c6db73b7fd7e89b247815f4d13ba72

This change also breaks the ability to use any potion alias. My assumption is because the new compareItemMeta method only checks for name, lore and enchantments of an item.
I've been doing some fiddling around with adding a test for potion data (which fixes this issue), but there are a lot more metas now in Spigot, including CrossbowMeta, SuspiciousStewMeta, and I believe some meta for tipped arrows, plus some other ones I cant think of off the top of my head. 

When testing creating my own custom aliases, such as:
```vb
aliases:
    test item invis = minecraft:potion {"Potion": "minecraft:invisibility"}
    test item leap = minecraft:potion {"Potion": "minecraft:leaping"}

command /test:
    trigger:
        give player 1 of test item invis
        give player 1 of test item leap
```
This results in giving the player 2 of the invisible potion.


This change will most likely break any item comparisons with anything that has meta outside of name, lore and enchantments, including NBT data on items.

**Comment by sovdeeth** [comment] 2024-02-25 13:40
Closing because Skript no longer supports 1.9

**Closed by sovdeeth** 2024-02-25 13:40 UTC
Labels: bug, priority: low, PR available, legacy versions
