### ISSUE TITLE
Uncolored var -> delete caractere

### ISSUE THREAD

**Issue by Gleush** [SkriptLang/Skript#4320] opened 2021-09-04 19:48 UTC
### Skript/Server Version

```
>.... [21:41:46 INFO]: [Skript] Server Version: git-Airplane-73 (MC: 1.17.1)
>.... [21:41:46 INFO]: [Skript] Skript Version: 2.6-beta3
>.... [21:41:46 INFO]: [Skript] Installed Skript Addons:
>.... [21:41:46 INFO]: [Skript] - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
>.... [21:41:46 INFO]: [Skript] - skript-yaml v1.4
>.... [21:41:46 INFO]: [Skript] - skRayFall v1.9.26 (https://sk.rayfall.net/)
>.... [21:41:46 INFO]: [Skript] - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
>.... [21:41:46 INFO]: [Skript] - SharpSK v1.6.3
>.... [21:41:46 INFO]: [Skript] - Skript-Packet v1.2 (www.github.com/Anarchick/skript-packet)
>.... [21:41:46 INFO]: [Skript] - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
>.... [21:41:46 INFO]: [Skript] - SkUniversal v2.12.5
>.... [21:41:46 INFO]: [Skript] - DiSky v2.2 (https://disky.itsthesky.info/)
>.... [21:41:46 INFO]: [Skript] - skUtilities v0.9.2 (https://tim740.github.io/)
>.... [21:41:46 INFO]: [Skript] - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
>.... [21:41:46 INFO]: [Skript] - skript-db v1.3.3
>.... [21:41:46 INFO]: [Skript] - SkQuery v4.1.5
>.... [21:41:46 INFO]: [Skript] - SkriptJSON v1.0.0
>.... [21:41:46 INFO]: [Skript] - OstraAnvilSK v1.0
>.... [21:41:46 INFO]: [Skript] - WolvSK v1.7.2
```

### Bug Description

I have a little problem with ```uncolored message``` when player try to do ```<3``` it removed a caractere and send ```3```
It's worked in the past

### Expected Behavior

Remove the color but not a caractere from the message

### Steps to Reproduce

You can try with this code :
```
on chat:
    set message to uncoloured message
    set {_msg} to message
    loop all players:
        message formatted "%{_msg}%" to loop-player
```
And send ```<3``` in the chat in game

### Errors or Screenshots

![Capture d’écran 2021-09-04 214336](https://user-images.githubusercontent.com/46963775/132106244-fe635ec4-1911-45c3-b44c-3186d28f4f28.png)
_(Screen from a bigger code, you can probably don't have the same)_

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-09-04 21:37
Duplicate of #3787

**Closed** 2021-09-05 09:31 UTC
