### ISSUE TITLE
Commands have trouble registering and deregistering

### ISSUE THREAD

**Issue by AhplBusinessman** [SkriptLang/Skript#6486] opened 2024-03-08 02:03 UTC
### Skript/Server Version

```markdown
[18:52:41 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[18:52:41 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[18:52:41 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[18:52:41 INFO]: [Skript] Server Version: git-Paper-405 (MC: 1.20.4)
[18:52:41 INFO]: [Skript] Skript Version: 2.8.3 (skriptlang-github)
[18:52:41 INFO]: [Skript] Installed Skript Addons:
[18:52:41 INFO]: [Skript]  - skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect)
[18:52:41 INFO]: [Skript]  - SkBee v3.3.0 (https://github.com/ShaneBeee/SkBee)
[18:52:41 INFO]: [Skript] Installed dependencies:
[18:52:41 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

Only specific commands are registering in a pattern i can't discern, commands are not being deregistered upon reload when its no longer located in the file, I am very sure the files are saving

the removed commands persist through restarts of the server

### Expected Behavior

Commands are registered and deregistered properly

### Steps to Reproduce

```
command /abcdef:
	trigger:
		broadcast {var}

command /removea <number>:
	trigger:
		remove arg-1 from {var}

command /takea <number>:
	trigger:
		add arg-1 to {var}
```

### Other

The contents of the commands or if there are arguments specified seem to not matter at all

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2024-03-12 11:26
Are you still having this issue? can you try Skript 2.8.2 see if that fixes the issue

**Comment by Moderocky** [comment] 2024-04-16 13:17
Closing, no more information was provided and we can't reproduce the bug.

**Closed by Moderocky** 2024-04-16 13:17 UTC
Labels: waiting for reply
