### ISSUE TITLE
Skript is not working on paper 1.21

### ISSUE THREAD

**Issue by vitek182009** [SkriptLang/Skript#6800] opened 2024-06-19 14:38 UTC
### Skript/Server Version

```markdown
skript info

[16:32:40 WARN]: Unexpected exception while parsing console command "skript info"

org.bukkit.command.CommandException: Cannot execute command 'skript' in plugin Skript v2.8.7 - plugin is disabled.

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:974) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:498) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:472) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-9-4ea696f]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Bug Description

I know paper 1.21 is still in development, but I think this could help updating Skript to latest version
I tried running it on latest 1.21 spigot and it worked well.

This is the full error of skript runned on paper 1.21 build #9:

```
[15:39:06 INFO]: [Skript] Enabling Skript v2.8.7

[15:39:08 INFO]: [Skript] You're currently running the latest stable version of Skript.

[15:39:09 ERROR]: Error occurred while enabling Skript v2.8.7 (Is it up to date?)

java.lang.IllegalArgumentException: LAVA_CAULDRON isn't an item

at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]

at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:307) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:705) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:614) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:506) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:492) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:475) ~[Skript-2.8.7.jar:?]

at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]

at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]

at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]

at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]

at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]

at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]

at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]

at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]

at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:468) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:433) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:389) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.Skript.onEnable(Skript.java:508) ~[Skript-2.8.7.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-9-4ea696f]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-9-4ea696f]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

[15:39:09 INFO]: [Skript] Disabling Skript v2.8.7

[15:39:09 ERROR]: Error occurred while disabling Skript v2.8.7

java.lang.ExceptionInInitializerError: null

at Skript-2.8.7.jar/ch.njol.skript.Skript.beforeDisable(Skript.java:1192) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.Skript.onDisable(Skript.java:1204) ~[Skript-2.8.7.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-9-4ea696f]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-9-4ea696f]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-9-4ea696f]

at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-9-4ea696f]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-9-4ea696f]

at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization

at Skript-2.8.7.jar/ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1299) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.Skript.registerEvent(Skript.java:1501) ~[Skript-2.8.7.jar:?]

at Skript-2.8.7.jar/ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:39) ~[Skript-2.8.7.jar:?]

... 17 more
```

### Expected Behavior

It should boot up normally.

### Steps to Reproduce

This error is only on paper, not on spigot. I don't know what is this caused by

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment] 2024-06-19 14:43
Duplicate of https://github.com/SkriptLang/Skript/issues/6796

thanks for the report. we're actively working towards a fix for this.

**Closed by APickledWalrus** 2024-06-19 14:43 UTC
