### ISSUE TITLE
Server can't start

### ISSUE THREAD

**Issue by Helios19932** [SkriptLang/Skript#2406] opened 2019-08-29 20:16 UTC
When I try to start a server, I have errors like this in console: [22:08:52] [Server thread/ERROR]: [Skript] 27603 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
how to fix this?

**Comment by ShaneBeee** [comment] 2019-08-29 20:24
1) You should fill out the template that is given when you create a new issue rather than deleting it
2) I feel like theres more to this error than you are showing
3) 

> [Skript] 27603 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

this is usually caused by using an older version of skript-mirror, you will need to use skript-mirror 2.0.0

**Comment by Matocolotoe** [comment] 2019-08-29 22:20
https://circleci.com/gh/btk5h/skript-mirror/3#artifacts/containers/0

**Comment by Wealthyturtle** [comment] 2019-09-06 03:01
Duplicate of #2369?

**Comment by FranKusmiruk** [comment] 2019-09-06 15:01
Addon issue, closing.

**Closed by FranKusmiruk** 2019-09-06 15:01 UTC
