### ISSUE TITLE
Indistinguishable redstone lamp

### ISSUE THREAD

**Issue by RenfaMimit** [SkriptLang/Skript#2591] opened 2019-10-22 11:33 UTC
### Description
Lit redstone lamp and unlit redstone lamp are confused.

Tested Versions:
2.4-beta9: Problematic
2.4-beta8: Problematic
2.4-beta7: Problematic
2.4-beta6: Problematic
2.4-beta5: Working as expected

### Steps to Reproduce
```
command /check:
    trigger:
        if target block is lit redstone lamp:
            message "lit redstone lamp"
        if target block is unlit redstone lamp:
            message "unlit redstone lamp"
```

### Expected Behavior
Lit redstone lamp and unlit redstone lamp do not occur at the same time.

### Errors / Screenshots
https://imgur.com/a/UjK6W9F

### Server Information
* **Server version/platform:** paper-221 (MC: 1.14.4)
* **Skript version:**  Skript2.4-beta9

**Comment by bluelhf** [comment] 2019-10-26 10:41
`[unlit] redstone lamp`... Redstone Lamp and Unlit Redstone Lamp should be different aliases, but they aren't.

**Comment by bluelhf** [comment] 2019-10-26 10:46
@RenfaMimit Does this occur on versions after 1.13?

**Comment by Wealthyturtle** [comment] 2019-10-27 02:01
Did some digging, I think https://github.com/SkriptLang/skript-aliases/blob/a514420407477b45e6ddaab63cbd112d7f49407c/redstone.sk#L118 is the cause, because ``lit_redstone_lamp`` doesn't actually exist in the Java Edition

**Comment by APickledWalrus** [comment] 2019-10-27 02:56
What changed in beta6 that could have caused this issue to start happening?

**Comment by Wealthyturtle** [comment] 2019-10-27 03:03
I honestly have no clue, tried searching but could not find any commits that seemed to cause this issue... although I can replicate that it occurs in 2.4-beta9

**Comment by APickledWalrus** [comment] 2020-10-01 16:12
![image](https://user-images.githubusercontent.com/29044720/94835077-2f3c3f80-03df-11eb-8e9c-ead651991d54.png)
Looks like this works properly now (2.5) so I'm going to close this issue. If you (or anyone else) is still having this issue, comment back here and I can take another look.

**Closed by APickledWalrus** 2020-10-01 16:12 UTC
Labels: aliases, bug, priority: low
