### ISSUE TITLE
Item remove doesn't work.

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#2745] opened 2020-01-05 10:41 UTC
### Description
We just updated our script from 2.2 to 2.4.1.
After updating, item removal does not work properly.
It seems that an item with a name or lore is usually not removed.
'remove 1 banner from player's tool' I need to remove an item with a name and a lore one, but it doesn't work.

Not all items are like that.

### Steps to Reproduce
command /test:
	trigger:
		set slot 40 of player to air
		remove all rose red from player's inventory
		remove all golden hoe from player's inventory
		remove all tripwire hook from player's inventory
		remove all shield from player's inventory
		remove all leather boots from player's inventory
		remove all paper from player's inventory
		remove all carrots on a stick from player's inventory

### Server Information
1.12.2
Paper
Skript 2.4.1

**Comment by ShaneBeee** [comment] 2020-01-05 10:45
Duplicate of #2714

**Closed by ShaneBeee** 2020-01-05 10:45 UTC

**Comment by madebygood** [comment] 2020-01-05 10:50
Too many bugs after the update
I should roll back to version 2.2dev37.

**Comment by ShaneBeee** [comment] 2020-01-05 10:52
For 1.9->1.12.2 that might be a good idea. Or even 2.3.7
2.4+ is mainly geared towards 1.14+ but we are still trying to fix these issues. Bensku has already done a lot of work that fixes a bunch of these issues in the future 2.5 version. He said he is hoping to get an alpha out soon(ish)

**Comment by madebygood** [comment] 2020-01-05 10:56
Thank you for your hard work. Looking forward to the next update.

**Comment by TPGamesNL** [comment] 2020-01-05 10:58
> Thank you for your hard work. Looking forward to the next update.
> 
> 2.3.7
> Is a non-existent version.
> 
> You said 2.3.6?

https://github.com/SkriptLang/Skript/releases/tag/2.3.7
