### ISSUE TITLE
Variables not accepted as an integer when they can be an integer

### ISSUE THREAD

**Issue by BuggyAl** [SkriptLang/Skript#5029] opened 2022-08-14 17:56 UTC
### Skript/Server Version

```markdown
[Skript] Server Version: git-Paper-81 (MC: 1.19)
[Skript] Skript Version: 2.6.3
[Skript] Installed Skript Addons: 
[Skript]  - SkQuery v4.1.7
[Skript]  - SkBee v2.0.0 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Function inputs (mostly number-related types) don't work properly.
```
command /test:
	trigger:
		set {_add} to 3
		set {_testNum} to 1 + {_add}
		test({_testNum})

function test(num: integer):
	broadcast {_num}
```
Below are a few variations of Line 4.
`set {_testNum} to 1 + {_add}` --> Broadcasts "<‎ none‎ >"
`set {_testNum} to (1 + {_add} parsed as integer)` --> Broadcasts "1"
`set {_testNum} to (1 + {_add} parsed as number)` --> Broadcasts nothing?

### Expected Behavior

The code provided above broadcasts "4"

### Steps to Reproduce

Type the following code and run /test
```
command /test:
	trigger:
		set {_add} to 3
		set {_testNum} to 1 + {_add}
		test({_testNum})

function test(num: integer):
	broadcast {_num}
```

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2022-08-14 22:43
The adding on line 4 seems to result in testNum being a double, which causes problems when passed into the function where an integer is supposed to be.
![image](https://user-images.githubusercontent.com/10354869/184557458-cbc45501-e7f2-43f4-be1e-88a030934dc6.png)

Adding a `round()` around the addition keeps testNum as a long, which makes the function work.
![image](https://user-images.githubusercontent.com/10354869/184557427-36d53baf-66ff-4521-8219-df651249cea2.png)
 
Used the `class of` expression from skript reflect. Tested on 2.6.3, 1.19.2 with skript-reflect 2.3

**Comment by TheLimeGlass** [comment] 2022-08-15 06:01
Skript uses Long for everything as the default. This only happens when using `integer` as the type. `number` makes it work fine.

**Comment by TheLimeGlass** [comment] 2022-08-15 07:42
Skript moment

![image](https://user-images.githubusercontent.com/16087552/184595694-a65bc1e7-a387-46a1-8b0d-f2e892947d48.png)

**Comment by TheLimeGlass** [comment] 2022-08-15 08:12
Gonna close this, as it was after the fix was already applied.

**Comment by TheLimeGlass** [comment] 2022-08-15 08:31
Also related https://github.com/SkriptLang/Skript/issues/4445

**Comment by TPGamesNL** [comment] 2022-08-15 08:33
Duplicate of #4445. Same solution as mentioned there, number converters (number -> integer etc) will fix this

**Closed by TPGamesNL** 2022-08-15 08:33 UTC
Labels: investigating
