### ISSUE TITLE
[BUG] Sever Skript issue. (saving variables I think)

### ISSUE THREAD

**Issue by aRandomMenno** [SkriptLang/Skript#6972] opened 2024-08-12 13:14 UTC
### Skript/Server Version

```markdown
[15:09:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:09:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[15:09:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[15:09:51 INFO]: [Skript] Server Version: 1.21-130-b1b5d4c (MC: 1.21)
[15:09:51 INFO]: [Skript] Skript Version: 2.9.1 (skriptlang-github)
[15:09:51 INFO]: [Skript] Installed Skript Addons: None
[15:09:51 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

```markdown
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! [Skript] Severe Error:
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Something went horribly wrong with Skript.
[15:06:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:06:16 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[15:06:16 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Stack trace:
[15:06:16 ERROR]: #!#! java.io.NotSerializableException: ch.njol.skript.util.visual.VisualEffectType
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:154)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:227)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:179)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:227)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.registrations.Classes.serialize(Classes.java:761)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:812)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.variables.Variables.serialize(Variables.java:793)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:822)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:543)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.variables.Variables.setVariable(Variables.java:526)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Variable.setIndex(Variable.java:501)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Variable.change(Variable.java:545)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:292)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[15:06:16 ERROR]: #!#!     at Skript-2.9.1.jar//ch.njol.skript.events.EvtScript.lambda$runTrigger$0(EvtScript.java:91)
[15:06:16 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[15:06:16 ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[15:06:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[15:06:16 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[15:06:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[15:06:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[15:06:16 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[15:06:16 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Version Information:
[15:06:16 ERROR]: #!#!   Skript: 2.9.1 (latest)
[15:06:16 ERROR]: #!#!     Flavor: skriptlang-github
[15:06:16 ERROR]: #!#!     Date: 14:17:55.682181900
[15:06:16 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[15:06:16 ERROR]: #!#!   Minecraft: 1.21
[15:06:16 ERROR]: #!#!   Java: 21.0.4 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS)
[15:06:16 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Server platform: Paper
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Current node: null
[15:06:16 ERROR]: #!#! Current item: null
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Thread: Server thread
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! Language: english
[15:06:16 ERROR]: #!#! Link parse mode: STRICT
[15:06:16 ERROR]: #!#! 
[15:06:16 ERROR]: #!#! End of Error.
[15:06:16 ERROR]: #!#!
```

### Expected Behavior

It shouldn't give any errors.

### Steps to Reproduce

Start the server, or reload amy skript with changing variables.

### Other

The error doesn't make the server crash, it also gives this error everytime you reload a script.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by kiip1** [comment] 2024-08-14 09:06
Duplicate of #5557, seems like it hasn't been fixed after all.

**Comment by sovdeeth** [comment] 2024-08-14 22:23
duplicate #4196

**Closed by sovdeeth** 2024-08-14 22:23 UTC
