### ISSUE TITLE
Skript Not Working

### ISSUE THREAD

**Issue by JustSkeppYT** [SkriptLang/Skript#4297] opened 2021-08-21 15:20 UTC
### Skript/Server Version

```
21.08 15:17:03 [Server] Server thread/INFO Enabling Skript v2.6-beta2
21.08 15:17:04 [Server] INFO 2021-08-21 15:17:04,207 Server thread ERROR Recursive call to appender File
21.08 15:17:04 [Server] Server thread/WARN Loaded class ch.njol.skript.Skript from Skript v2.6-beta2 which is not a depend, softdepend or loadbefore of this plugin.
21.08 15:17:04 [Server] Server thread/ERROR Error occurred while enabling Skript v2.6-beta2 (Is it up to date?)
21.08 15:17:04 [Server] INFO java.lang.ExceptionInInitializerError: null
21.08 15:17:04 [Server] INFO at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[Skript%20(6).jar:?]
21.08 15:17:04 [Server] INFO at ch.njol.skript.Skript.onEnable(Skript.java:434) ~[Skript%20(6).jar:?]
21.08 15:17:04 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[Spigot_Latest_1.16.5.jar:3094-Spigot-9fb885e-fae895a]
21.08 15:17:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
21.08 15:17:04 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1076
21.08 15:17:04 [Server] INFO at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:101) ~[Skript%20(6).jar:?]
21.08 15:17:04 [Server] INFO at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:78) ~[Skript%20(6).jar:?]
21.08 15:17:04 [Server] INFO at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:101) ~[Skript%20(6).jar:?]
21.08 15:17:04 [Server] INFO ... 12 more
```

### Bug Description

Skript doesn't work and keeps saying **/skript help** on running command /skript or anything

### Expected Behavior

It is suppost to say Skript's Command Info and stuff.

### Steps to Reproduce

It randomly happened

### Errors or Screenshots

```
none includable
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-08-21 15:24
Duplicate of https://github.com/SkriptLang/Skript/issues/2578

**Closed by TPGamesNL** 2021-08-21 15:24 UTC
