### ISSUE TITLE
Paper Spigot Error

### ISSUE THREAD

**Issue by Aseltic** [SkriptLang/Skript#2205] opened 2019-06-27 19:54 UTC
Im using Paper Spigot 1.12.2 (Latest (Today's Release) )

### Description

I have 2 errors...
When skript loads, it shoots out a huuge error.
Also, "on server list ping:" dosent seem to work anymore...

### Steps to Reproduce

Get paper spigot 1.12.2, install Skript in the server, restart the server.

### Expected Behavior

When skript is loading on start, it just prints out lots of error (red text) messages... But Skript still seems to be fine.

"on server list ping:" just wont work when I set the motd or do anything, mostly motd.

### Errors / Screenshots

[15:44:04 INFO]: [Skript] You're currently running the latest stable version of Skript.
[15:44:14 INFO]: [Skript] Loaded 18144 aliases in 10846ms
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! [Skript] Severe Error:
[15:44:16 ERROR]: #!#! Version supports setTamed but MethodHandle lookup failed
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Something went horribly wrong with Skript.
[15:44:16 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:44:16 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:44:16 ERROR]: #!#! Here is full list of them:
[15:44:16 ERROR]: #!#! skRayFall (https://sk.rayfall.net/) skript-mirror (https://github.com/btk5h/skript-mirror) TuSKe (github.com/Tuke-Nuke/TuSKe) MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/)
[15:44:16 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:44:16 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:44:16 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:44:16 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:44:16 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:44:16 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Stack trace:
[15:44:16 ERROR]: #!#! java.lang.IllegalAccessException: no private access for invokespecial: interface org.bukkit.entity.Ocelot, from java.lang.Object/public
[15:44:16 ERROR]: #!#!     at java.lang.invoke.MemberName.makeAccessException(MemberName.java:850)
[15:44:16 ERROR]: #!#!     at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1572)
[15:44:16 ERROR]: #!#!     at java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1002)
[15:44:16 ERROR]: #!#!     at ch.njol.skript.entity.OcelotData.<clinit>(OcelotData.java:46)
[15:44:16 ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[15:44:16 ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[15:44:16 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[15:44:16 ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[15:44:16 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:44:16 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[15:44:16 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:44:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[15:44:16 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[15:44:16 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[15:44:16 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[15:44:16 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[15:44:16 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[15:44:16 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[15:44:16 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Version Information:
[15:44:16 ERROR]: #!#!   Skript: 2.4-alpha4 (latest)
[15:44:16 ERROR]: #!#!     Flavor: skriptlang-github
[15:44:16 ERROR]: #!#!     Date: 2019-06-27
[15:44:16 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[15:44:16 ERROR]: #!#!   Minecraft: 1.12.2
[15:44:16 ERROR]: #!#!   Java: 1.8.0_211 (Java HotSpot(TM) 64-Bit Server VM 25.211-b12)
[15:44:16 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Server platform: Paper
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Current node: null
[15:44:16 ERROR]: #!#! Current item: null
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Thread: Server thread
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! Language: english
[15:44:16 ERROR]: #!#! Link parse mode: DISABLED
[15:44:16 ERROR]: #!#!
[15:44:16 ERROR]: #!#! End of Error.
[15:44:16 ERROR]: #!#!

### Server Information
* **Server version/platform:**    Paper Spigot 1.12.2   
* **Skript version:**        Latest as of Todays Date (June/27/2019) 3:54pm Eastern standered time

**Comment by iOshawott** [comment] 2019-06-27 19:58
duplicate of #2203

**Comment by Aseltic** [comment] 2019-06-27 22:52
its not a duplicate because it dosent crash my server

**Comment by ShaneBeee** [comment] 2019-06-27 23:41
Its the exact same error, and its been fixed, try the newest update (redownload Alpha 4)

**Comment by Aseltic** [comment] 2019-06-28 00:50
ok

**Comment by Aseltic** [comment] 2019-06-28 00:51
ill close this when i dont get the error, gimme a sec

**Closed** 2019-06-28 01:10 UTC
