### ISSUE TITLE
my server install skript have some error 

### ISSUE THREAD

**Issue by Yuanyuan0580** [SkriptLang/Skript#7017] opened 2024-08-31 03:06 UTC
### Skript/Server Version

```markdown
[11:04:51 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:04:51 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:04:51 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:04:51 INFO]: [Skript] Server Version: 1.21.1-2299-5c0d2f7 (MC: 1.21.1)
[11:04:51 INFO]: [Skript] Skript Version: 2.9.1 (skriptlang-github)
[11:04:51 INFO]: [Skript] Installed Skript Addons: None
[11:04:51 INFO]: [Skript] Installed dependencies: 
[11:04:51 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

[message.txt](https://github.com/user-attachments/files/16823259/message.txt)

### Expected Behavior

[message.txt](https://github.com/user-attachments/files/16823260/message.txt)

### Steps to Reproduce

Actually I didn't do anything. I just installed SK.

### Errors or Screenshots

[message.txt](https://github.com/user-attachments/files/16823263/message.txt)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2024-08-31 03:43
do you have an idea in your code what is causing this? the error is saying that it can't find EntityMountEvent for ExprVehicle can we get the snippet of code where you have this event?

**Comment by APickledWalrus** [comment] 2024-08-31 05:26
Duplicate of https://github.com/SkriptLang/Skript/issues/6882, but not sure what causes it

**Closed** 2024-09-01 16:41 UTC
Labels: duplicate
