### ISSUE TITLE
Ability to sort variables without losing indices

### ISSUE THREAD

**Issue by TrademarkTM** [SkriptLang/Skript#202] opened 2016-10-06 16:41 UTC
Hey!
I'm trying to make a "top time online" for my script, but it doesn't keep the loop-index, for example:
- {timeonline::%player%} is 10 hours >> after sorting, it keeps only the 10 hours, not the %player%.

The %player% gets replaced by a number (1, 2, 3 in the order of sort).

I really need this, sorting numbers without the loop-index doesn't make sense...

**Comment by bensku** [comment] 2016-10-07 17:22
Pleaw post exact code. I don't quite understand why this should work. Sort is meant for lists using numeric keys, of course.

**Comment by TheBentoBox** [comment] 2016-10-07 17:55
Well the idea is that the stuff that's actually being sorted is the loop-values, not the loop-indices. In theory, the loop-index is just a key for referencing the value, so sorting the values shouldn't affect the keys. As it stands you can't sort a list where the indices matter without losing all of that data. e.g.

```
every 1 second:
	loop players:
		add 1 to {playtime::%loop-player's uuid%}
```

This is common practice for storing lists (putting info in the index). If I wanted to sort this list so I could get a top list of playtimes, the indices are what stores the actual important info (WHO has that playtime), so the `sorted %objects%` expression in vanilla Skript wouldn't work. 

In fact, this exact example is one I've come across on my server. I had to use RandomSK's sorting since it's the only one that works for retaining the index.

**Comment by bensku** [comment] 2016-10-07 20:56
Uhh, right. The problem is that current sort is just expression which takes some values and returns others. I'll need to dig into variable system to get any better results.

**Comment by TheBentoBox** [comment] 2017-02-27 17:56
A scripted solution for this was posted in #399 (a duplicate of this), in case anyone wants a temporary workaround:

```
    set {_sortedList::*} to sorted {_yourList::*}
    loop {_yourList::*}:
      add 1 to {_count}
      set {_indexes::%loop-value%} to loop-index
      if mod({_count}, 20) = 0:
        wait 1 tick
    loop {_sortedList::*}:
      set {_current} to {_indexes::%loop-value%}
      broadcast "%{_current}% - %loop-value%"
```

**Comment by bloggy** [comment] 2017-03-12 13:10
Hope this issue can be fixed soon. Really need it as well

**Comment by Wealthyturtle** [comment] 2020-07-10 07:08
Closing in favor of #371

**Closed by Wealthyturtle** 2020-07-10 07:08 UTC
Labels: enhancement, priority: low
