### ISSUE TITLE
Double pound ## as a comment causes Skript error

### ISSUE THREAD

**Issue by leonardo-dgs** [SkriptLang/Skript#1211] opened 2018-04-24 23:31 UTC
If in a skript a comment starts with a "#", Skript an error saying "invalid line - all code has to be put into triggers" ecc.

**Comment by Snow-Pyon** [comment] 2018-04-25 00:07
Could you show us an example of what you're talking about?

**Comment by TheBentoBox** [comment] 2018-04-25 01:07
I'm pretty sure this is related to the fact that a double pound sign is how you insert an actual pound sign in Skript. For example, if you want to `send "You're #1" to player`, you actually have to do `send "You're ##1" to player` to prevent the pound from being interpreted as the start of the comment. When you do the same at the start of a comment, it's not interpreting it as a comment anymore, but as a symbol which is part of a syntax or something of that nature.

Whether or not that's exactly a bug is up to the devs. I could see changing it to not parse double pounds like that at the start of a line as an enhancement.

**Comment by Blueyescat** [comment] 2018-04-25 14:52
Yeah he is talking about comment lines starting with double number signs. Which is should be fixed

**Comment by ShaneBeee** [comment] 2018-04-25 16:10
This is off topic but I love that Bento is clearly older like me, and how we call it the pound sign... #OldSchool ;)

**Comment by TheBentoBox** [comment] 2018-04-25 16:27
:^*

Also, I've marked this as an enhancement since in theory the # parsing is "working as intended" here, I guess. I'm not sure if bensku would consider it a bug or not but regardless it's very low prio since I imagine you could fix it by literally just adding a space after the first pound sign.

**Comment by Nicofisi** [comment] 2020-03-02 12:55
Are we interested in adding this? Should be very easy, basically the task is to find the place where separate lines are parsed, and at the beginning check whether `line.trim().startsWith("#")`. If so - skip it.

**Closed** 2024-01-01 23:20 UTC
Labels: enhancement, priority: lowest, completed, feature-ready
