### ISSUE TITLE
Push player in direction of player's targeted block (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by yuompioka** [SkriptLang/Skript#3949] opened 2021-05-07 08:12 UTC
---
name: Direction problem
about: `Cannot get data class of Modern Material`

---
### Description
Trying to make a function that pushes player to the targeted block.

### Steps to Reproduce
Use the expression mentioned in issues name or any similiar expression that includes `in direction of player's targeted block`
```
#example.sk
command /push:
  trigger:
    set {_z} to player's targeted block
    push player in direction of {_z} at speed 0.5
```

### Expected Behavior
Player is being pushed to the block with stated speed.

### Errors / Screenshots
```
Stack trace:
[10:55:32 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot get data class of Modern Material
[10:55:32 ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[10:55:32 ERROR]: #!#!     at org.bukkit.Material.getData(Material.java:3696)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.util.Direction.getFacing(Direction.java:221)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.expressions.ExprDirection.get(ExprDirection.java:156)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.expressions.ExprDirection.get(ExprDirection.java:1)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:58)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.effects.EffPush.execute(EffPush.java:68)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:291)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:248)
[10:55:32 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[10:55:32 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[10:55:32 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[10:55:32 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:55:32 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2293)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2116)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2069)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1346)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1339)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1315)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1155)
[10:55:32 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[10:55:32 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
```

### Server Information
* **Server version/platform:** Paper
* **Skript version:** Skript: 2.5.3 (latest)

### Additional Context

**Comment by TPGamesNL** [comment] 2021-05-07 09:29
Duplicate of https://github.com/SkriptLang/Skript/issues/3876

**Closed by TPGamesNL** 2021-05-07 09:29 UTC

**Comment by Comthefox2486** [comment] 2022-06-23 04:52
This issue is closed, but it still seems to happen on the latest version of Skript for me. If I do the exact same setup as the original poster (marked resolved), I get the exact error. If I am doing something wrong, please tell me.

**Comment by AyhamAl-Ali** [comment] 2022-06-23 08:20
> This issue is closed, but it still seems to happen on the latest version of Skript for me. If I do the exact same setup as the original poster (marked resolved), I get the exact error. If I am doing something wrong, please tell me.

Send you `/sk info` here

**Comment by Comthefox2486** [comment] 2022-06-24 18:25
> > This issue is closed, but it still seems to happen on the latest version of Skript for me. If I do the exact same setup as the original poster (marked resolved), I get the exact error. If I am doing something wrong, please tell me.
> 
> Send your `/sk info` here. Also send the error you're getting


deleted my old comment bc I got around it by using plugins and some math. I got a muuuuuch better result and probably shouldn't have complained on some random gh page.
soz
