### ISSUE TITLE
[Spigot v1_17_R1] Parsing block state "cauldron level" failed, Block minecraft:cauldron does not have property 'level'; Minecraft id minecraft:grass_path is not valid

### ISSUE THREAD

**Issue by hohoaisan** [SkriptLang/Skript#4088] opened 2021-06-19 07:40 UTC
### Description
Skript failed to parse cauldron's level state in Minecraft 1.17 (Spigot) and thrown 1 more error that Minecraft id minecraft:grass_path is not valid
### Steps to Reproduce
1. Using the lastest stable build in Github release
2. Placed in the plugins folder and start the server

### Expected Behavior
No error or failed message was shown

### Errors / Screenshots
```
[14:32:15] [Server thread/ERROR]: [Skript] Parsing block state [level=3] failed! (brewing.sk, line 80: {cauldron level} cauldronªs = minecraft:cauldron')
[14:32:15] [Server thread/WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=3]
[14:32:15] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:519)
[14:32:15] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:1991)
[14:32:15] [Server thread/WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1498)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.ArrayList.forEach(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[14:32:15] [Server thread/WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[14:32:15] [Server thread/WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[14:32:15] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:32:15] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[14:32:15] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:32:15] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[14:32:15] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[14:32:15] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608)
[14:32:15] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[14:32:15] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
[14:32:15] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[14:32:15] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[14:32:15] [Server thread/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[14:32:19] [Server thread/ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]ªs = minecraft:grass_path')
[14:32:19] [Server thread/ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]ªs = minecraft:grass_path')
```

### Server Information
* **Server version/platform:** Spigot v1_17_R1
* **Skript version:**  Skript 2.5.3

### Additional Context
The plugin has no issue on Paper 1.16.5

**Comment by TPGamesNL** [comment] 2021-06-19 07:55
Duplicate of https://github.com/SkriptLang/Skript/issues/4082

**Closed by TPGamesNL** 2021-06-19 07:55 UTC
