### ISSUE TITLE
Both "on portal" and "on teleport" does not work making it inpossible to cancel player teleport to Nether

### ISSUE THREAD

**Issue by Eng1ner** [SkriptLang/Skript#5186] opened 2022-10-30 12:44 UTC
### Skript/Server Version

```markdown
Server version: git-Paper-125 (MC: 1.19.2)
Skript version: 2.6.3
Installed Skript Addons:
- Skellett v2.0.7
- skript-db v1.3.6
- SkQuery v4.1.6
- SkBee v1.17.3
Installed dependencies:
- Vault v1.7.3-b131
- WorldGuard v7.0.7+216b061
```

### Bug Description

"On portal" and "On teleport" event does not work. Example of code:
```
on teleport:
	broadcast "1"
on player portal:
	broadcast "2"
```
Both broadcasts is not executing, when going through the Nether portal.
Broadcast is just an example, none of the experssions works, as if the event not even starts.

### Expected Behavior

On chat should be sent two messages "1" and "2" after teleporting to the Nether dimension.

### Steps to Reproduce

1. Create an example code shown above.
2. Reload the skript or restart the server.
3. Go through the portal.

### Errors or Screenshots

No errors are shown.

### Other

Server is using Multiverse-NetherPortals plugin, although issue occurs even on default server worlds, that are not linked via MV.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-10-30 13:31
Duplicate of #4705
You can use the nighly build of this PR for the fix (may not be stable on production servers - it's better to wait for an official release)

**Closed by AyhamAl-Ali** 2022-10-30 13:31 UTC
