### ISSUE TITLE
Server crashes when reloading some scripts

### ISSUE THREAD

**Issue by MinecollYT** [SkriptLang/Skript#4004] opened 2021-05-14 22:45 UTC
### Description
Server stopped responding until crashed

### Steps to Reproduce
Reload some spefific scripts

### Expected Behavior
Reload fast or at least without a crash

### Errors / Screenshots
Error message: https://pastebin.com/dLTyCqEt
My code: https://pastebin.com/LnuLFutM

### Server Information
* **Server version/platform:** Paper 1.16.5
* **Skript version:** 2.5.3

### Additional Context
I'm not sure if this error is caused by me because I did some mistake writing it.

**Comment by TheDGOfficial** [comment] 2021-05-15 01:12
That is not a crash and it clearly says "Do not report" (to Paper), it does not say do not report to Skript but, you know, it is just telling you that server is doing some hard work and not responding. IT is NOT a crash or a bug, although it is because of Skript's slow parser kicking in.

I'll recommend not reloading big scripts and writing your scripts in a test server where you can freely reload everything even if it'll crash; and when finished you can upload it to your production server and load it when your server is restarted.

Reload fast part will probably be improved by parallel loading and "at least without a crash" part is already fixed by async loading, it can also be fixed by fake ticking Spigot/Paper Watchdog, but that will just hide underlying issue and it  will become a worse issue if we do not keep the player/console up that their script is still reloading.

**Comment by TPGamesNL** [comment] 2021-05-15 09:26
Duplicate of https://github.com/SkriptLang/Skript/issues/3780

**Closed by TPGamesNL** 2021-05-15 09:26 UTC
