### ISSUE TITLE
Object Oriented Programing

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4537] opened 2022-01-27 15:51 UTC
### Suggestion

Create a class feature

### Why?

this very usefull

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TPGamesNL** [comment] 2022-01-27 15:56
Duplicate of https://github.com/SkriptLang/Skript/issues/4071

I also recommend putting more effort into a feature request like this, like providing how you think it should look and what it should do

**Closed by TPGamesNL** 2022-01-27 15:56 UTC
