### ISSUE TITLE
/skript help = /skript help (PLEASE IMPORTANT I CANT USE SKRIPT)

### ISSUE THREAD

**Issue by Erkan53** [SkriptLang/Skript#3045] opened 2020-06-11 08:32 UTC
https://prnt.sc/sxqq0x
just check this
latest version doesnt work for me
Im using 1.15.2 spigot
and skript version is in the link

but 2.4 beta-7 works just fine
though my only problem is commands are not registering to minecraft sure they works but they look red whenever i type the command

**Comment by Olyno** [comment] 2020-06-11 13:53
First, calm down. The title of your issue and the body of this one is very agressive. If you want to get some help, please calm down.
Second, I never got any issue using latest paper spigot version and Skript 2.4.1. Your issue comes probably from an addon you have and which create a conflict. It can be caused by Umbaska, Wildskript or any other addon which is old and not compatible with latest version of Skript.

**Comment by Erkan53** [comment] 2020-06-11 18:09
i only have skrayfall that old 2.4 beta-7 version works only and im not using paper spigot just normal spigot

**Comment by Olyno** [comment] 2020-06-11 19:00
So try [Paper Spigot](https://papermc.io/downloads) and try to [update SkRayFall](https://forums.skunity.com/resources/skrayfall.259/)

**Comment by ShaneBeee** [comment] 2020-06-11 19:10
"No errors" I highly doubt that. 100% of the time this happens, Skript has errors on load which can help detail the issue. 

Closing this due to the template is missing (ie: you deleted it) and theres a huge lack of information here. There is nothing we can do if we dont have any details.

**Closed by ShaneBeee** 2020-06-11 19:10 UTC

**Comment by Erkan53** [comment] 2020-06-11 20:26
@ShaneBeee You keep telling me there cant be "No errors" but there are no errors i have provided you with screenshots that tells you there are no errors.
I also fixed the problem.
turns out java version was 32bit it needs to be 64 bit so you could add it in dependencies

**Comment by ShaneBeee** [comment] 2020-06-11 20:28
> turns out java version was 32bit it needs to be 64 bit so you could add it in dependencies

Yeah I know. That has already been discussed in another issue, where the user posted the error. So yes, there is an error when Skript starts up.
