### ISSUE TITLE
ItemType with enchantments expression

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#6522] opened 2024-04-02 18:21 UTC
### Suggestion

I would like to suggest adding an expression, something like:
`%itemtypes% (of|enchanted with) %enchantmenttypes%`

### Why?

Quite often when people ask for the docs on how to enchant items, we have to send them the confusing ItemType type doc.
Its not the easiest one to read.

On top of that, people try do:
`diamond sword named "bob" of sharpness 10`
or
`{_item} of sharpness 10`
We then have to explain the order/literal issues. 

This expression would help alleviate that pressure.

I considered whipping up a PR but wanted feedback before putting the time/effort in.

### Other

I still like turtles 🐢 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment] 2024-04-02 19:24
Hey! Hey! Hey! more reason to continue working on my stale PRs ⚡️ see #4366

**Comment by Moderocky** [comment] 2024-04-03 17:50
I dont think we should mark this PR-available if the PR is a stale draft because somebody else might want to do it.

**Comment by AyhamAl-Ali** [comment] 2024-04-05 20:26
ops, duplicate of #1836

**Closed by AyhamAl-Ali** 2024-04-05 20:26 UTC
Labels: enhancement, priority: low, good first issue, PR available
