### ISSUE TITLE
"Severe Error"

### ISSUE THREAD

**Issue by JustJakeee** [SkriptLang/Skript#4727] opened 2022-04-13 01:56 UTC
### Skript/Server Version

```markdown
Skript Version 2.6.1
Minecraft 1.18.1
```

### Bug Description

When I reload a script the server times out.

### Expected Behavior

The script was supposed to be able to reload like normal.

### Steps to Reproduce

https://www.mediafire.com/file/ljmf1p23l8550f3/Error.zip/file
I've attached a zipped version of my server's files, run the start.bat and try to reload the scripts, the server should crash.

### Errors or Screenshots

https://paste.gg/p/anonymous/ad0269dc71f44ee783e239ef831b64c0
This is the log I was told to send. (Told by log to send log)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-04-13 12:21
What script caused this? and please upload the logs online (like [https://paste.gg](https://paste.gg)) not in .zip file

**Comment by TPGamesNL** [comment] 2022-04-13 12:56
Likely duplicate of https://github.com/SkriptLang/Skript/issues/1783
Log: https://pastebin.com/x1hnAgQe

This is probably caused by these two lines in skyblock-core.sk:
```
teleport player to middle of location({next-island-pos}'s x-pos + 4, {next-island-pos}'s y-pos + 4, {next-island-pos}'s z-pos + 2, world "main", 90, 0)
set {next-island-pos} to location({next-island-pos}'s x-pos + 256, {next-island-pos}'s y-pos, {next-island-pos}'s z-pos, world "main")
```
Try to split this code over multiple lines, for example:
```
set {_x} to {next-island-pos}'s x-pos + 4
set {_y} to {next-island-pos}'s y-pos + 4
set {_z} to {next-island-pos}'s z-pos + 2
teleport player to middle of location({_x}, {_y}, {_z}, world "main", 90, 0)
```

You could also try using [the Location At expression](https://docs.skriptlang.org/expressions.html#ExprLocationAt).

**Closed by TPGamesNL** 2022-04-13 12:56 UTC
Labels: waiting for reply
