### ISSUE TITLE
Fishing bug

### ISSUE THREAD

**Issue by TomHo41** [SkriptLang/Skript#5907] opened 2023-08-11 09:55 UTC
### Skript/Server Version

```markdown
[11:51:14 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:51:14 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[11:51:14 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:51:14 INFO]: [Skript] Server Version: git-Paper-388 (MC: 1.18.2)
[11:51:14 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[11:51:14 INFO]: [Skript] Installed Skript Addons: 
[11:51:14 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[11:51:14 INFO]: [Skript]  - SkBee v2.14.1 (https://github.com/ShaneBeee/SkBee)
[11:51:14 INFO]: [Skript] Installed dependencies: 
[11:51:14 INFO]: [Skript]  - Vault v1.7.3-b131
[11:51:14 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

I use skript to change drops for fishing

### Expected Behavior

Drop are not changing as they should. They are just vanilla drops

### Steps to Reproduce

Here is my code:
		
```
                   if fish state is CAUGHT_FISH:
			chance of 18%:
				set item of fishing caught entity to {fishing::moneyminicoin}
			else:
				chance of 25%:
					set item of fishing caught entity to {fishing::moneycoin}
				else:
					chance of 24%:
						set item of fishing caught entity to {fishing::moneybigcoin2}
					else:
						chance of 13%:
							set item of fishing caught entity to {fishing::megacoin2}
						else:
							chance of 6%:
                                                                set item of fishing caught entity to air
								execute command "excellentcrates key give %player% medusa_key 1"
							else:
								chance of 4%:
                                                                        set item of fishing caught entity to air
									execute command "excellentcrates key give %player% mythic_klíč 1"
								else:
									chance of 4.2%:
										set item of fishing caught entity to {fishing::krakenulomek}
```

### Errors or Screenshots

Sometimes it prints this error
```
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! [Skript] Severe Error:
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Something went horribly wrong with Skript.
[11:53:43 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:53:43 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:53:43 ERROR]: #!#! Here is full list of them:
[11:53:43 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) SkBee v2.14.1 (https://github.com/ShaneBeee/SkBee) 
[11:53:43 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:53:43 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:53:43 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:53:43 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:53:43 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:53:43 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Stack trace:
[11:53:43 ERROR]: #!#! java.lang.IllegalArgumentException: Cannot drop air
[11:53:43 ERROR]: #!#!     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[11:53:43 ERROR]: #!#!     at net.minecraft.world.entity.item.EntityItem.a(EntityItem.java:506)
[11:53:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_18_R2.entity.CraftItem.setItemStack(CraftItem.java:37)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.util.slot.DroppedItemSlot.setItem(DroppedItemSlot.java:48)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.classes.data.SkriptClasses$12.change(SkriptClasses.java:568)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.classes.data.SkriptClasses$12.change(SkriptClasses.java:496)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:242)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:277)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:146)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:50)
[11:53:43 ERROR]: #!#!     at Skript-2.7.0-beta3 (5).jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:63)
[11:53:43 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[11:53:43 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:53:43 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669)
[11:53:43 ERROR]: #!#!     at net.minecraft.world.entity.projectile.EntityFishingHook.a(EntityFishingHook.java:507)
[11:53:43 ERROR]: #!#!     at net.minecraft.world.item.ItemFishingRod.a(ItemFishingRod.java:30)
[11:53:43 ERROR]: #!#!     at net.minecraft.world.item.ItemStack.a(ItemStack.java:485)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:513)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1931)
[11:53:43 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[11:53:43 ERROR]: #!#!     at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[11:53:43 ERROR]: #!#!     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:53:43 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:53:43 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[11:53:43 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[11:53:43 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1348)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[11:53:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:53:43 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Version Information:
[11:53:43 ERROR]: #!#!   Skript: 2.7.0-beta3 (latest)
[11:53:43 ERROR]: #!#!     Flavor: skriptlang-github
[11:53:43 ERROR]: #!#!     Date: 03:18:03.366646700
[11:53:43 ERROR]: #!#!   Bukkit: 1.18.2-R0.1-SNAPSHOT
[11:53:43 ERROR]: #!#!   Minecraft: 1.18.2
[11:53:43 ERROR]: #!#!   Java: 17.0.8 (OpenJDK 64-Bit Server VM 17.0.8+7)
[11:53:43 ERROR]: #!#!   OS: Linux amd64 6.4.8-arch1-1
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Server platform: Paper
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Current node: null
[11:53:43 ERROR]: #!#! Current item: set the item of entity of fish event caught entity to {fishing::moneyminicoin} (as java.lang.Object)
[11:53:43 ERROR]: #!#! Current trigger: fish (simple event) (Fish.sk, line 16)
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Thread: Server thread
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! Language: english
[11:53:43 ERROR]: #!#! Link parse mode: LENIENT
[11:53:43 ERROR]: #!#! 
[11:53:43 ERROR]: #!#! End of Error.
[11:53:43 ERROR]: #!#! 
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DereWah** [comment] 2023-08-12 10:12
The error seems to be occurring when the chance of 18% condition is met. It is caused by the effect:

`set item of fishing caught entity to {fishing::moneyminicoin}`

Can you please send the content of the variable {fishing::moneyminicoin}? Or share the part of the skript where you initialize it (you assign it a value).

I also did some testing with:

```
set item of fishing caught entity to air
set item of fishing caught entity to {_g} #{_g} is not initialized here
```

But I am not getting the error above, so I think it is because of the content of the variable.

**Closed** 2023-11-20 16:59 UTC
Labels: investigating
