### ISSUE TITLE
Glitch with damage cause types in instant harming potions.

### ISSUE THREAD

**Issue by Iron-Chopper** [SkriptLang/Skript#3323] opened 2020-08-19 15:51 UTC
### Description
So I was making a hazmat suit, and so i put some test messages to indicate what type of damage was going on using
send "%damage cause%"
When I did this, I drank an instant harming potion, and it gave the result of "attack." when I used a splash potion, is gave the result of "potion", and when I used a lingering potion, it gave the "attack" result.

### Steps to Reproduce
I drank an instant harming potion, and it gave the result of "attack." when I used a splash potion, is gave the result of "potion", and when I used a lingering potion, it gave the "attack" result.

### Expected Behavior
I would expect that it should all be just "potion" instead of the inconsistencies of "attack" and "potion" and "attack".

### Errors / Screenshots
I can't provide any screenshots because it would be a more video type of thing.
there are also no console errors.

### Server Information
git-Paper-129 (MC: 1.16.1)
2.5-alpha6

**Comment by ShaneBeee** [comment] 2020-08-19 18:30
This appears to be on Spigot's end, not Skript's. I tested with both Skript and an actual plugin:
(tp = test plugin, sk = Skript)
<img width="966" alt="Screen Shot 2020-08-19 at 11 28 11 AM" src="https://user-images.githubusercontent.com/20008482/90675392-3f250900-e20f-11ea-9f83-2599bf668308.png">


When checking what the attacks mean:
potion (Skript) = MAGIC (Bukkit) = "Damage caused by being hit by a damage potion or spell"

So that one seems accurate. As for drinking a potion giving back "attack", Im not sure why Bukkit/Spigot has it set up that way.

**Comment by Pikachu920** [comment] 2020-08-19 19:50
maybe it's considered entity attack because drinking it is kind of harming themselves? it makes some sense but not much. you could check the damage cause as well as the item the player is holding, maybe?

**Comment by ShaneBeee** [comment] 2020-10-02 05:35
Closing this as its not a Skript issue.

**Closed by ShaneBeee** 2020-10-02 05:35 UTC
