### ISSUE TITLE
Name of inventory doesn't work!

### ISSUE THREAD

**Issue by FinalPlayer024** [SkriptLang/Skript#3103] opened 2020-07-05 12:45 UTC
MC Version: 1.15.2
Skript Version: Skript bensku-2.5-alpha5

Hey guys, I tried in every possible way but seems like the names of inventories do not exist. I've read something somewhere about 1.14 inventory names that do not work anymore and the only way is to find a `getTitle` (?)

So, I tried with Skript-Mirror and it works fine, with 
```
  set {_nameInv} to player.getOpenInventory().getTitle()
  broadcast "%{_nameInv}%"
```

![image](https://user-images.githubusercontent.com/37907926/86533003-55c90800-bece-11ea-8195-2bcd5166a465.png)
Doesn't work ^

![image](https://user-images.githubusercontent.com/37907926/86533015-6d07f580-bece-11ea-8a47-b2b3c55eeb52.png)
Works ^

**Comment by Runakai1** [comment] 2020-07-05 16:44
And so?

**Comment by Sitieno14** [comment] 2020-07-05 16:46
> And so?

It is a major bug that potentially breaks a lot of codes created so far

**Comment by TPGamesNL** [comment] 2020-07-05 16:52
See https://github.com/SkriptLang/Skript/issues/2069

**Comment by Sitieno14** [comment] 2020-07-05 17:03
https://github.com/SkriptLang/Skript/pull/2094 didn't work

**Comment by ShaneBeee** [comment] 2020-07-06 03:58
Closing as this is a duplicate of #2069

**Closed by ShaneBeee** 2020-07-06 03:58 UTC
