### ISSUE TITLE
NPE for EffConnect

### ISSUE THREAD

**Issue by blueheaven566** [SkriptLang/Skript#4349] opened 2021-10-05 20:33 UTC
### Errors or Screenshots

```
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! [Skript] Severe Error:
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Something went horribly wrong with Skript.
[22:30:17 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:30:17 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[22:30:17 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Stack trace:
[22:30:17 ERROR]: #!#! java.lang.NullPointerException
[22:30:17 ERROR]: #!#!     at ch.njol.skript.util.Utils.sendPluginMessage(Utils.java:473)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.util.Utils.sendPluginMessage(Utils.java:419)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.effects.EffConnect.execute(EffConnect.java:66)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:289)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:250)
[22:30:17 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:194)
[22:30:17 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:30:17 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:30:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[22:30:17 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[22:30:17 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[22:30:17 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[22:30:17 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:30:17 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:30:17 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Version Information:
[22:30:17 ERROR]: #!#!   Skript: 2.6-beta3 (latest)
[22:30:17 ERROR]: #!#!     Flavor: skriptlang-github
[22:30:17 ERROR]: #!#!     Date: 14:09:29.995077500
[22:30:17 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[22:30:17 ERROR]: #!#!   Minecraft: 1.12.2
[22:30:17 ERROR]: #!#!   Java: 1.8.0_292 (OpenJDK 64-Bit Server VM 25.292-b10)
[22:30:17 ERROR]: #!#!   OS: Linux aarch64 5.4.0-1044-raspi
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Server platform: Spigot
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Current node: null
[22:30:17 ERROR]: #!#! Current item: connect the player to "Lobby"
[22:30:17 ERROR]: #!#! Current trigger: command /l (simple event) (lobby.sk, line 2)
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Thread: Server thread
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! Language: english
[22:30:17 ERROR]: #!#! Link parse mode: DISABLED
[22:30:17 ERROR]: #!#!
[22:30:17 ERROR]: #!#! End of Error.
```

### Agreement

- [ ] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-10-06 06:39
> You're trying to use Skript 2.6+ on 1.12. Support for 1.12 is dropped in the latest releases, so you need to use 2.5.3 or lower

> **NOTICE**: After a lot of discussion, we have decided to drop support for 1.12 and lower, as it stops us from adding a lot of features and focusing on other parts of Skript. **2.6.x will be the last version working with 1.12 and lower**. Security patches and other kind of fixes might be ported to this version, but keep in mind that features won't be added.

That means 2.6 **should** work with 1.12


The issue is caused by this [line](https://github.com/SkriptLang/Skript/blob/13dd0f120a8fd1d4408280e59377361c818cf297/src/main/java/ch/njol/skript/util/Utils.java#L473) returning null and that's probably caused by `firstPlayer` returning null in this [line](https://github.com/SkriptLang/Skript/blob/13dd0f120a8fd1d4408280e59377361c818cf297/src/main/java/ch/njol/skript/util/Utils.java#L418)

**Comment by TPGamesNL** [comment] 2021-10-06 15:43
Should be fixed by changing EffConnect to get the player array before sending the first plugin message, and not continue if it is empty. 

Besides that, the sendPluginMessage that gets the first of the online players should fail quicker when there are no players online, and there should be a note in its Javadocs (and all methods in Utils using it) saying the method can only be used when there's a player online.

**Closed** 2022-01-26 05:29 UTC
Labels: bug, priority: low, completed
