### ISSUE TITLE
Variables for players whose UUID starts with 0 are not stored properly.

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#5398] opened 2023-01-26 03:43 UTC
### Skript/Server Version

```markdown
[12:28:54 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[12:28:54 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[12:28:54 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[12:28:54 INFO]: [Skript] Server Version: git-Purpur-1858 (MC: 1.19.2)
[12:28:54 INFO]: [Skript] Skript Version: 2.6.4
[12:28:54 INFO]: [Skript] Installed Skript Addons:
[12:28:54 INFO]: [Skript]  - Skacket v1.0.12
[12:28:54 INFO]: [Skript]  - skript-yaml v1.4
[12:28:54 INFO]: [Skript]  - MadeMyPetExtension v1.0.0
[12:28:54 INFO]: [Skript]  - CoroutineSK v1.0.0
[12:28:54 INFO]: [Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[12:28:54 INFO]: [Skript]  - Skore v2.0.5
[12:28:54 INFO]: [Skript]  - skScraft v1.5
[12:28:54 INFO]: [Skript]  - SkBee v2.7.2 (https://github.com/ShaneBeee/SkBee)
[12:28:54 INFO]: [Skript]  - skript-towny v1.0.1
[12:28:54 INFO]: [Skript]  - SkEtcR v4.0 (https://mu-developers.github.io/SkEtcR-Docs/)
[12:28:54 INFO]: [Skript]  - skript-bossbar v1.0
[12:28:54 INFO]: [Skript]  - SkUniversal v2.13
[12:28:54 INFO]: [Skript]  - skDragon v0.17-alex-MC1.18-hack-4
[12:28:54 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[12:28:54 INFO]: [Skript]  - SkQuery v4.1.8
[12:28:54 INFO]: [Skript]  - FileSkRebirth v2.3.2
[12:28:54 INFO]: [Skript]  - Ersatz v1.0
[12:28:54 INFO]: [Skript]  - MadeExtension v3.3.2
[12:28:54 INFO]: [Skript]  - WolvSK v1.7.2
[12:28:54 INFO]: [Skript]  - ItemsAdder v3.3.0b-r5 (devs.beer)
[12:28:54 INFO]: [Skript] Installed dependencies:
[12:28:54 INFO]: [Skript]  - Vault v1.7.3-b131
[12:28:54 INFO]: [Skript]  - WorldGuard v7.0.8-beta-01+cbb2ba7
[12:28:54 INFO]: [Skript]  - GriefPrevention v16.18
```

### Bug Description

Variables for players whose UUID starts with 0 are not being saved properly.

1) `set {test::%player%} to 1`
2) shutdown the server.
3) `{test::%player%}` variables is reset.
4) Not all variables are initialized this way. Some variables are saved fine, but some are missing.

Players on the server reporting that their data keeps resetting:
```
04c2e63b-22f8-4877-a9ea-2faa01cdeb59
08b1165f-3d94-47b0-9a64-7868e99aa244
01ffc72a-1e68-4e5a-b770-859f0071373a
07ecedca-e906-4a6a-8846-9a37e3fc3bc0
02c1ec88-7b1c-494a-9221-807c4be4ed22
08ecaccf-f94f-4a3a-ad5d-f0712fa7883e
05d7fbd8-2f25-483b-93c0-10ca3c5a4d65
```
These users are resetting their money, virtual chest, and quests every day.
please solve it.

All users whose UUIDs do not start with 0 will work fine.

### Expected Behavior

All variables should be well saved as csv in memory.

Currently, neither autosave nor server shutdown can be saved.

### Steps to Reproduce

```
command /cashgive [<offlineplayer>] [<number>]:
	trigger:
		if sender is op or console:
			if arg 2 is set:
				if arg 1 has not played on this server before:
					message "&ccant do that"
					exit
				if arg 2 > 1500:
					message "&cnumber is too big."
					exit
				set {캐쉬::%arg 1's uuid%} to {캐쉬::%arg 1's uuid%}+arg 2
				message formatted "&b%arg 1% : &b+%arg 2% CASH (&e%{캐쉬::%arg 1's uuid%}%&f)" to sender
				exit
```

### Errors or Screenshots

Before server restart:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/43653581/214753935-961b7d70-c605-4f67-82c3-162dc43208b1.png">

After server restart:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/43653581/214754161-44d443aa-a35a-45ab-b6ff-88eb09ca09e5.png">
(It should have been 6 cach, but it was initialized and became 3 caches again)

### Other

This is not an addon issue. Even if I uninstall all addons and run it the same.
Again, not all variables are like this. Only some variables are initialized.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment] 2023-01-26 04:56
Is your server in offline mode by chance? Do you have a Bungeecord network? If so do you have the option `bungeecord` set to true in the spigot.yml? Is this a cracked server?

**Comment by madebygood** [comment] 2023-01-26 05:07
I will tell you my settings.

Only paid genuine users can access.

server.properties : online-mode=false
spigot.yml : bungeecord=true

**Comment by TheLimeGlass** [comment] 2023-01-26 05:19
Is the online mode set to true in the Bungeecord? bungeecord.yml

**Comment by madebygood** [comment] 2023-01-26 05:20
Yes

<img width="403" alt="image" src="https://user-images.githubusercontent.com/43653581/214763896-e6915a26-1991-45bb-8e88-0862019593a7.png">

If there's anything else you need to check, let me know.

**Comment by bluelhf** [comment] 2023-01-26 06:37
UUIDs are serialised properly by Yggdrasil (the least and most significant bits are stored, and those always perfectly reconstruct an UUID)... I wonder if this happens for other variable names that start with zeroes?

**Comment by bluelhf** [comment] 2023-01-26 06:51
Can't reproduce on Skript 2.6.4:
![image](https://user-images.githubusercontent.com/52505120/214773798-85c7ac13-2864-4326-9242-5cddace6da0a.png)

(after restart)
![image](https://user-images.githubusercontent.com/52505120/214773836-8808ab20-4154-4fb9-a902-6209da27dd3b.png)

Code:
```applescript
command /cashgive [<offlineplayer>] [<number>]:
  trigger:
    if arg 2 is set:
      # if arg 1 has not played on this server before:
      #   message "&ccant do that"
      #   exit
      if arg 2 > 1500:
        message "&cnumber is too big."
        exit
      set {캐쉬::%arg 1's uuid%} to {캐쉬::%arg 1's uuid%}+arg 2
      message formatted "&b%arg 1% : &b+%arg 2% CASH (&e%{캐쉬::%arg 1's uuid%}%&f)" to sender
```

@madebygood How are you closing the server? Make sure Skript is being stopped properly, and not being killed before it can save the variables. Have you tried stopping the server with `stop` instead?

**Comment by madebygood** [comment] 2023-01-26 07:03
This is my /stop code.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/43653581/214774824-28c05766-4953-4647-933c-b740e594420a.png">
However, certain variables of certain users are not automatically written to the csv every few minutes apart from /stop. (notepad++ check)


<img width="868" alt="image" src="https://user-images.githubusercontent.com/43653581/214775249-1e57240e-2add-4a53-810f-12a98f2aaa80.png">

Do all users whose UUID starts with 0 lose their variables? = false

Do all users who lose a variable have UUIDs starting with 0? = true

**Comment by TheLimeGlass** [comment] 2023-01-26 08:00
To SkriptLang team;

The provided UUID's all start with a zero and then another number after it, so it may have to deal with that.

**Comment by bluelhf** [comment] 2023-01-26 08:43
Related to [VariablesMap.java](https://github.com/SkriptLang/Skript/blob/145bc59ff69d999883015bc5c3e318cd9607f7ff/src/main/java/ch/njol/skript/variables/VariablesMap.java#L52)?

**Comment by madebygood** [comment] 2023-01-27 02:07
After deleting variables.csv on my server, I tried again and it works fine.

However, I have never corrupted variables. (I am an expert using skript for over 7 years.)

This csv cannot be initialized because it contains all users' money, chests, and quests.

Is there a way to figure out what's wrong with the csv?

I can email you my variables file.

**Comment by DelayedGaming** [comment] 2023-01-27 02:09
If there are any issues whilst loading variables during startup, Skript will notify you in your server console. So be sure keep an eye on it during startup and report back if it’s there!

**Comment by madebygood** [comment] 2023-01-27 02:16
https://pastebin.com/AFJJpwsD

There is no problem when loading.

**Comment by TheLimeGlass** [comment] 2023-01-27 02:39
The errors provided are empty configuration errors, which you need to fix. It's when you have a condition section with no details inside of it. This is after the colon `:` there should be a line break and indentation. Then there are Skript warnings that are not critical.

Skript is not showing any signs of variable saving issues in that provided console log.

Do you have the option `use player UUIDs in variable names` enabled in your config.sk?
Can you also provide us with your config.sk file? You should be able to place the file in a .zip and upload it into GitHub here directly.

**Comment by madebygood** [comment] 2023-01-27 02:55
This is my config file
[config.zip](https://github.com/SkriptLang/Skript/files/10515047/config.zip)



https://pastebin.com/6jYvhwVS
This is the csv file of my {캐쉬::*} variables.

If you put this variable and run it, you can see that the error I tested occurs as it is.

`command /cashgive [<offlineplayer>] [<number>]:
  trigger:
    if arg 2 is set:
      # if arg 1 has not played on this server before:
      #   message "&ccant do that"
      #   exit
      if arg 2 > 1500:
        message "&cnumber is too big."
        exit
      set {캐쉬::%arg 1's uuid%} to {캐쉬::%arg 1's uuid%}+arg 2
      message formatted "&b%arg 1% : &b+%arg 2% CASH (&e%{캐쉬::%arg 1's uuid%}%&f)" to sender`

**Comment by vjh0107** [comment] 2023-01-27 04:22
based on the above, I did a vanilla test.

here is a video of the proof that the variable was not saved.
https://imgur.com/uRy9X89

and here is the script that I used in this test
```
command /cashgive:
    trigger:
        set {_offlineplayer} to "08ecaccf-f94f-4a3a-ad5d-f0712fa7883e" parsed as offlineplayer
        set {캐쉬::%{_offlineplayer}'s uuid%} to 1212.5

command /cashcheck:
    trigger:
        set {_offlineplayer} to "08ecaccf-f94f-4a3a-ad5d-f0712fa7883e" parsed as offlineplayer
        if {캐쉬::%{_offlineplayer}'s uuid%} is set:
            broadcast "true: %{캐쉬::%{_offlineplayer}'s uuid%}%"
        else:
            broadcast "null: %{캐쉬::%{_offlineplayer}'s uuid%}%"
```

and also here is the server files that I used.
https://drive.google.com/file/d/1A9l8EFtSR5YlMy7CMqbfYDBuMgqHc5XT/view?usp=share_link

@bluelhf

**Comment by vjh0107** [comment] 2023-01-28 09:27
https://github.com/SkriptLang/Skript/pull/3929

this error occurred after #3929 
@TPGamesNL

**Comment by Moderocky** [comment] 2023-01-28 11:06
We've triaged the cause and we'll work on a fix shortly.

**Comment by vjh0107** [comment] 2023-01-29 02:53
Sorry, I didn't test well. it happens after #5170

**Comment by mybe** [comment] 2023-06-11 20:08
Still experiencing this on 2.6.4

**Comment by sovdeeth** [comment] 2023-06-11 21:21
> Still experiencing this on 2.6.4

Nothing has been changed on 2.6.4. 
The relevant PR is for 2.7.

**Comment by AyhamAl-Ali** [comment] 2023-06-12 10:26
> Still experiencing this on 2.6.4

Please download [Skript 2.7.0-beta2](https://github.com/SkriptLang/Skript/releases/tag/2.7.0-beta2)

**Closed** 2023-06-12 10:25 UTC
Labels: bug, priority: medium, completed
