### ISSUE TITLE
Spurious event triggers

### ISSUE THREAD

**Issue by emeitner** [SkriptLang/Skript#3548] opened 2020-11-16 02:41 UTC
### Description
Two left click events are triggered under certain circumstances when a right click event is executing. 

### Steps to Reproduce

This is the most basic code I could make to reproduce the problem.

```
on right click with stick:
  cancel event
  send "START right click" to player
  if event-block is emerald block:
    if block below event-block is redstone block:
      set {_l} to location of block below event-block
  if event-block is redstone block:
    if block above event-block is emerald block:
      set {_l} to location of event-block    
  set block at {_l} to air
  set block above {_l} to air
  send "END right click" to player
  
on left click with stick:
  cancel event
  send "START left click" to player
  set block above event-block to redstone block
  set block 2 meters above event-block to emerald block
  send "END left click" to player

```
Do this:
```
1 Left click on the ground
2 Output:
  START left click
  END left click
3 Right click on redstone
4 Output:
  START right click
  END right click

```
So far so good.

```
1 Left click on the ground
2 Output:
  START left click
  END left click
3 Right click on emerald
4 Output:
  START right click
  END right click
  START left click <---------- Spurious event trigger
  END left click
  START left click <---------- Spurious event trigger
  END left click

```
Add "  wait 10 ticks" between the two "set block" statements and the problem ceases.

### Expected Behavior
No left click events after the right click event.

### Errors / Screenshots
No console errors.

### Server Information
[20:34:48 INFO]: This server is running Paper version git-Paper-214 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

[20:35:13 INFO]: [Skript] Server Version: git-Paper-214 (MC: 1.16.3)
[20:35:13 INFO]: [Skript] Skript Version: 2.5.1
[20:35:13 INFO]: [Skript] Installed Skript Addons:
[20:35:13 INFO]: [Skript]  - skRayFall v1.9.23 (https://sk.rayfall.net/)
[20:35:13 INFO]: [Skript]  - SkQuery v3.6.5
[20:35:13 INFO]: [Skript]  - SkBee v1.4.11 (https://github.com/ShaneBeee/SkBee)
[20:35:13 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)

**Comment by emeitner** [comment] 2020-11-16 02:51
Let me confirm that  plugins are not causing the problem before you dig into this.

**Comment by ShaneBeee** [comment] 2020-11-16 03:44
Duplicate of #2148

**Closed by ShaneBeee** 2020-11-16 03:44 UTC

**Comment by emeitner** [comment] 2020-11-16 03:52
Problem persists after disabling all Skript plugins:
SkBee-1.4.11.jar
SkQuery-4.1.2.jar
skRayFall+v1.9.23.jar
skript-holo-1.0.2.jar

All scripts except for the one above have been removed also.

Other plug-ins on server:
PadLock-3.3.jar                              
ChatBot5.3.jar
Vault-1.7.3.jar
scriptrunner-0.1.0.jar  
HolographicDisplays-2.4.4.jar
worldedit-bukkit-7.2.0-beta-05.jar
LuckPerms-Bukkit-5.2.23.jar
worldguard-bukkit-7.0.3.jar
