### ISSUE TITLE
1.13.X Lore issue

### ISSUE THREAD

**Issue by diamondpumpkin** [SkriptLang/Skript#1641] opened 2018-10-29 01:26 UTC
I have been testing out the 1.13 versions of Skript and found a rather inconvenient error when trying to set both the name and lore on an item in a single expression. The examples I listed below for lores are not the only occurrences. Opening an inventory for the player and trying to set lores on items will throw errors as well. This only occurs with names and lores, I can set either or, but not both. I would told there maybe a conflict, which I found to be unlikely since removing the lore expressions from Skript still does not allow SkQuery to work properly.

Spigot: 1.13.1 R0.1 & 1.13.2 R0.1
Skript: v2.3-alpha4 & 2.4-alpha1 on 1.13.2
SkQuery-Lime: v3.6.1 for both 1.13.2 versions

Without SkQuery loaded on the server the script
```
on join:
    add 1 clock named "&aName" with lore "&7&oLore" to the player's inventory
```
will only give the item the lore, removing the 'with lore part' will give the item the name.
In Skript 2.2-dev36, this usually gives an error because it was never implemented.

When SkQuery is loaded on the server using the same script

[Pastebin for join error](https://pastebin.com/fJAdCDqk)
```
30.09 12:15:00 [Server] ERROR Could not pass event PlayerJoinEvent to Skript v2.3-alpha4
30.09 12:15:00 [Server] INFO java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
30.09 12:15:00 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
30.09 12:15:00 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.effects.EffChange.execute(EffChange.java:269) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
30.09 12:15:00 [Server] INFO at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:110) ~[?:?]
30.09 12:15:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:15:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```
removing the lore part again, the name works fine.

The same script works with Skript 2.2-dev36 and SkQuery v3.6.0 on 1.12.2.
Using it as a command instead also works fine in the 1.12.2 version however in 1.13.1

```
command /givemeclock:
    trigger:
        add 1 clock named "&aName" with lore "&7&oLore" to the player's inventory
```
 
[Pastebin for command error](https://pastebin.com/UdeuD5sY)
```
30.09 12:35:43 [Server] INFO diamondpumpkin issued server command: /givemeclock
30.09 12:35:43 [Server] INFO diamondpumpkin [1fb91283-c9fc-4839-8832-44a1533cba64]: /givemeclock
30.09 12:35:43 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to Skript v2.3-alpha4
30.09 12:35:43 [Server] INFO org.bukkit.event.EventException: null
30.09 12:35:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1638) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
30.09 12:35:43 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
30.09 12:35:43 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.effects.EffChange.execute(EffChange.java:269) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.Commands.handleCommand(Commands.java:257) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172) ~[?:?]
30.09 12:35:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
30.09 12:35:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
30.09 12:35:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
30.09 12:35:43 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
30.09 12:35:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO ... 16 more
30.09 12:35:43 [Server] ERROR null
30.09 12:35:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'givemeclock' in plugin Skript v2.3-alpha4
30.09 12:35:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
30.09 12:35:43 [Server] INFO Caused by: java.lang.NoSuchMethodError: ch.njol.skript.aliases.ItemType.getItemMeta()Ljava/lang/Object;
30.09 12:35:43 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:29) ~[?:?]
30.09 12:35:43 [Server] INFO at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.effects.EffChange.execute(EffChange.java:269) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242) ~[?:?]
30.09 12:35:43 [Server] INFO at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:193) ~[?:?]
30.09 12:35:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
30.09 12:35:43 [Server] INFO ... 15 more
```
Without SkQuery, the command does the samething as the join event.

**Please note:** I have contacted LimeGlass about this issue, they said it's a Skript problem. The way they described it didn't make much sense, so if this is most certainly a problem with SkQuery, I can message them again.

**Comment by Snow-Pyon** [comment] 2018-10-29 02:42
The issue is that a method which skQuery uses (ItemType#getItemMeta) changed of return type, which broke the addons using it before. All he has to do is recompile the addon and it should work again.

That said, Skript has a item with lore and lore of item expression which should work fine (except for #1620, should be fixed for next release), if you remove skQuery though.

**Closed by Snow-Pyon** 2018-10-29 02:42 UTC
