### ISSUE TITLE
Bug with /sk reload <script>

### ISSUE THREAD

**Issue by Padlick** [SkriptLang/Skript#1367] opened 2018-07-11 13:13 UTC
Skript version: dev36

When you type for example "/sk reload test", and the script named "test" is disabled, there is this text prompted into my chat:

[15:12:40 ERROR]: Invalid format string at 'skript command.reload.script disabled' in the english language file: <gold>%s<reset> is currently disabled. Use <gray>/<gold>skript <cyan>enable <red>%s<reset> to enable it.
[15:12:40 INFO]: [Skript] Skript command.reload.script disabled

**Comment by Nicofisi** [comment] 2018-07-11 15:05
Can't reproduce with head on e521140 (latest commit currently)
```
sk disable test
[17:03:44 INFO]: [Skript] Successfully disabled test.sk.
sk disable test
[17:03:50 INFO]: [Skript] test.sk is already disabled!
```

**Comment by TheBentoBox** [comment] 2018-07-11 15:12
Not sure what priority this should exactly be, should just be a simple display error but it could be confusing for some users.

**Comment by Padlick** [comment] 2018-07-11 15:19
@Nicofisi That doesn't have anything to do with the "/sk disable <script>", just with "/sk reload <script>" if that script that you want to reload is disabled

**Comment by Nicofisi** [comment] 2018-07-11 15:22
The fix is simple, if some dev could change it, even from GitHub so I don't need to PR, it would be great ❤️ 
```diff
Index: src/main/java/ch/njol/skript/SkriptCommand.java
===================================================================
--- src/main/java/ch/njol/skript/SkriptCommand.java	(revision b10cbd6b250483af1636d211df1b386a7f407509)
+++ src/main/java/ch/njol/skript/SkriptCommand.java	(date 1531322381071)
@@ -171,7 +171,7 @@
 						return true;
 					if (!f.isDirectory()) {
 						if (f.getName().startsWith("-")) {
-							info(sender, "reload.script disabled", f.getName().substring(1));
+							info(sender, "reload.script disabled", f.getName().substring(1), StringUtils.join(args, " ", 1, args.length));
 							return true;
 						}
 						reloading(sender, "script", f.getName());
```
result:
```
sk disable test
[17:21:58 INFO]: [Skript] Successfully disabled test.sk.
sk reload test
[17:22:00 INFO]: [Skript] -test.sk is currently disabled. Use /skript enable test to enable it.
```

**Comment by Pikachu920** [comment] 2018-07-11 20:11
Duplicate of #1269, thanks for the info @Nicofisi i'll probably commit that later

**Closed by Pikachu920** 2018-07-11 20:11 UTC
Labels: bug, priority: low
