### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by pythermal** [SkriptLang/Skript#3060] opened 2020-06-19 01:39 UTC
### Description
I have no idea what this is but I was told to report it

### Steps to Reproduce
Skript code that caused the error:

```
on load:
     set {game} to false

command /startgame:
     trigger:
          command "/tp @a 3.5 70 -6.5 facing ~ ~ 90"
          set {game} to true

every 20 ticks in "world":
     if {game} is true:
          message "Hello" to server
          drop 1 of iron ingot at location(3, 69, -10)
```

### Expected Behavior
The iron ingot was going to drop in a certain location on the world

### Errors / Screenshots

https://gist.githubusercontent.com/pythermal/8557f70a546547128574e27ffa1ebc2f/raw/442cf9e9232a929b399b46d4e7d9bcff9d158df1/error.txt

### Server Information
* **Server version/platform:** Minecraft 1.15.2, Spigot       
* **Skript version:** 2.4.1                

### Additional Context

Sorry if this is a well-known bug or I'm bad at skript, I really have no idea what I'm doing

**Comment by pythermal** [comment] 2020-06-19 01:42
Update: The code works fine when i added a fourth "world" argument to the location function
```
on load:
     set {game} to false

command /startgame:
     trigger:
          command "/tp @a 3.5 70 -6.5 facing ~ ~ 90"
          set {game} to true

every 20 ticks in "world":
     if {game} is true:
          message "Hello" to server
          drop 1 of iron ingot at location(3, 69, -10, world "world")
```

**Comment by Govindass** [comment] 2020-06-19 07:37
this is not a bug, just the way how functions work

**Comment by Pikachu920** [comment] 2020-06-19 23:39
the original code is actually meant to work so this is a bug, see the following snippets:
https://github.com/SkriptLang/Skript/blob/45eaaae5c7049575cef72069b6cbf5d0d210f126/src/main/java/ch/njol/skript/lang/function/Parameter.java#L50-L55
https://github.com/SkriptLang/Skript/blob/45eaaae5c7049575cef72069b6cbf5d0d210f126/src/main/java/ch/njol/skript/classes/data/DefaultFunctions.java#L312
https://github.com/SkriptLang/Skript/blob/f361d3ac9bfeb3368988343802e89518d42afd43/src/main/java/ch/njol/skript/events/EvtPeriodical.java#L50
https://github.com/SkriptLang/Skript/blob/6524d69f1e8583f917ea18c9fe526ec6df66dbfc/src/main/java/ch/njol/skript/events/bukkit/ScheduledEvent.java#L36-L43

**Comment by TheLimeGlass** [comment] 2020-07-03 00:47
Duplicate https://github.com/SkriptLang/Skript/issues/1465

**Comment by ShaneBeee** [comment] 2020-08-06 19:41
Closing this as LimeGlass pointed out, its a duplicate of #1465

**Closed by ShaneBeee** 2020-08-06 19:41 UTC
Labels: bug
