### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#2305] opened 2019-07-27 17:23 UTC
### Description

It would be nice since it have good performance and stuff getting saved in json-like document

**Comment by Matocolotoe** [comment] 2019-07-27 20:53
Duplicate of #1787

**Comment by ham1255** [comment] 2019-07-27 21:07
this as reminder? cause that post was created in Jan 2

**Comment by Wealthyturtle** [comment] 2019-07-28 00:03
Still a duplicate, you could make a comment in the original

**Comment by bensku** [comment] 2019-07-28 08:39
Some issues sit waiting for years, usually because they depend on very large reworks of Skript.

**Closed by bensku** 2019-07-28 08:39 UTC
