### ISSUE TITLE
Ternary returns none

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#3024] opened 2020-05-30 19:29 UTC
### Description
I just upgraded Skript 2.4 to 2.5-alpha-3 and I see ternary is not working properly.

"otherwise" part is returning none. If condition is true, it working properly.
(%objects% if <.+>[,] (otherwise|else) %objects%)

### Steps to Reproduce
```
command /ternarytest:
	trigger:
		set {_x} to ("you awesome") if chance of 50% otherwise ("I have sad news for you")
		send {_x} to player
		send "text: %{_x}%"
```
otherwise ("I have sad news for you") not working.
"you awesome" is working.

### Errors / Screenshots
No any error
https://imgur.com/Wqtp3tm

### Server Information
* **Server version/platform:** Paper 1.15.2 build 322
* **Skript version:** Skript 2.5 alpha-3

**Comment by Wealthyturtle** [comment] 2020-05-31 01:12
Weirdly enough,

```
command /t:
	trigger:
		set {_x} to ("you awesome") if chance of 50% else ("I have sad news for you")
		send {_x} to player
		send "text: %{_x}%"
```
Works.

**Comment by FranKusmiruk** [comment] 2020-06-01 01:17
My wild guess is that it is a syntax conflict with the default value expression

**Comment by bluelhf** [comment] 2020-06-14 10:32
Could we implement the standard `? :` version of ternary, too? That could solve syntax conflicts.

**Comment by Moderocky** [comment] 2020-06-14 13:28
> Could we implement the standard `? :` version of ternary, too? That could solve syntax conflicts.

While I personally would like this, Skript is supposed to be verbose and english-based, and this style of syntax goes against that to some extent.
That having been said, as `?` is being used for the default value expression, I don't see why this shouldn't be added.

Worth noting however that the "java" style (boolean ? X : Y) ternary would in fact be a different format to the current Skript one (X if condition otherwise Y) - so this might be a little confusing for some people as the formats would be in different orders.


> My wild guess is that it is a syntax conflict with the default value expression

This would make sense as Skript seems to generally work backwards, meaning it would probably be trying `chance of 50% else ...` before the rest of the syntax, which is itself a valid syntax `%effect% if %condition%`.

**Comment by FranKusmiruk** [comment] 2020-06-16 05:03
If someone can test whether it doesn't cause parsing issues (considering the ternary's : the end of the line), I am not against the idea.

**Comment by TPGamesNL** [comment] 2021-04-04 10:26
This happens because it's parsed as a 'do if' effect, with the effect being `set {_x} to ("you awesome")`, and the condition `chance of (50% otherwise "I have sad news for you")`, where `50% otherwise ("I have sad news for you")` is a default value expression. `50%` is a valid number, because: https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/classes/data/JavaClasses.java#L71-L84

**Comment by FranKusmiruk** [comment] 2021-04-04 14:18
Closing since now that I look at the issue, TP is right, this is working as intended. It may have been better if we could manage to get it throw an error but that's quite complex given how Skript parsed that statement.

**Closed by FranKusmiruk** 2021-04-04 14:18 UTC
Labels: bug, priority: lowest
