### ISSUE TITLE
Potential Memory Leak w/ function local variables

### ISSUE THREAD

**Issue by PhilCCMG** [SkriptLang/Skript#2877] opened 2020-03-24 17:31 UTC
### Description

When writing functions (not procedures), storing local variables are potentially causing a memory leak as they do not appear to be deleted once the function returns a value.

### Steps to Reproduce

1. Write a function which is often called setting numerous variables, for example
```
function orderLore(i: item) :: item:
    set {_lore::*} to lore of {_i}
    set {_hasce} to false
    set {_enchants} to ""
    loop {_lore::*}:
        set {_b} to loop-value
        replace all "&a" and "&b" with "" in {_b}
        set {_b::*} to {_b} split at " "
        set {_b} to {_b::1}
        {_enchants::*} contains {_b}:
            {_enchants} is "":
                set {_enchants::*} to "%loop-value%"
            else:
                set {_enchants::*} to "%{_enchants}%", "%loop-value%"
        else if loop-value contains "Rarity: ":
            set {_rarity} to loop-value
        else:
            size of {_other::*} is 0:
                set {_other::*} to "%loop-value%"
            else:
                add "%loop-value%" to {_other::*}
    set {_lore::*} to {_enchants::*}, {_other::*}
    set {_i}'s lore to {_lore::*}
    return {_i}
```
2. Run the function on a consistent basis every few seconds.
3. After approximately 1-2 hours, the server will start to dramatically spike in RAM usage.
### Expected Behavior

Local variables should be fully deleted from the RAM and the server should not keep tracking them.

### Errors / Screenshots

Here is a screenshot of the Eclipse Memory Analyser taken during a lagspike.
![image](https://user-images.githubusercontent.com/13520198/77457588-ce5ef980-6df4-11ea-9389-f0a30f33a19c.png)

### Server Information
* **Server version/platform:**  1.12.2 Paper     
* **Skript version:** Skript 2.4 

### Additional Context

Potentially similar to #2337, though it is marked as closed before 2.4 was released.

**Comment by JRoy** [comment] 2020-03-24 17:33
Can you reproduce this in [2.5-alpha2](https://github.com/SkriptLang/Skript/releases/tag/2.5-alpha2)?

**Comment by PhilCCMG** [comment] 2020-03-24 17:34
I'll give it a shot - as stated it takes up to two hours to reproduce as it accumulates and only seems to start after a certain amount of time, but will try.

**Comment by PhilCCMG** [comment] 2020-03-24 18:27
Server isn't even booting; has this error about 50 times on 2.5-alpha2
https://hastebin.com/erehihudin.cs

**Comment by bensku** [comment] 2020-03-24 18:35
Please try without addons, this should have been fixed before 2.4 was released.

**Comment by PhilCCMG** [comment] 2020-03-25 11:54
Hard to tell if it's directly continuing without addons but appears to be.

**Comment by PhilCCMG** [comment] 2020-03-26 21:43
From digging into a heapdump in a bit more detail, it seems to be setting a variable to something split, for instance:
```
set {_lore::*} to player's tool's lore
loop {_lore::*}:
    set {_lines::*} to loop-value split at " " # This seems to be causing the leak
```

**Comment by PhilCCMG** [comment] 2020-03-28 15:53
I'm mistaken.

The {_lore::*} variable from above was set 16 million times after 4 hours of uptime. I'd presume the local variable isn't being deleted when in list form.

**Comment by PhilCCMG** [comment] 2020-03-28 17:43
![image](https://user-images.githubusercontent.com/13520198/77829674-7a695300-711b-11ea-980e-c0b92f7b0858.png)
As an example, however, we see {_lore::*} is being stored 300,000 times in RAM which shouldn't be happening.

**Comment by Govindass** [comment] 2020-06-12 09:20
I am having the same problem, this is critical - I'd love to see it fixed

**Comment by ham1255** [comment] 2020-06-14 10:27
after doing testing with @Govindass  quick solution delete  local variable at the end of a code
like showing below. 
```
delete {_receivers::*}
```

**Comment by Govindass** [comment] 2020-06-14 11:26
> 
> 
> after doing testing with @Govindass quick solution is to delete local variable at the end of a code
> like showing below.
> 
> ```
> delete {_receivers::*}
> ```

got to say I'm not 100% certain it fixes, but we kinda noticed a difference I think

**Comment by Govindass** [comment] 2020-06-17 11:08
seems like it does not fix, doing delete {_receivers::*} still keeps memory leak, having 700mb leak after 38 hours of uptime

**Comment by Wealthyturtle** [comment] 2020-06-18 04:07
I'm not sure if this issue is the same as the issue that I reported in #2337, but it seems like #2337 is still an issue in Skript 2.5-alpha3.

**Comment by Govindass** [comment] 2020-06-19 07:34
I fixed the memory leak by starting to use {_receiver} variable instead of {_receivers::*}
so it only happens with list variables

**Comment by Govindass** [comment] 2020-06-28 08:34
just had a 1.1gb memory leak due to this again, it happens only with functions that loop list variables and only noticeable in those functions that are executed extremely often, like multiplying per player count

**Comment by Govindass** [comment] 2020-06-28 08:43
also the leak likely happens with ALL variables, not only local variables

**Comment by Wealthyturtle** [comment] 2020-07-10 10:49
Closing in favor of #2337, to consolidate this issue.

**Closed by Wealthyturtle** 2020-07-10 10:49 UTC
Labels: bug
