### ISSUE TITLE
Console Error (on inventory click)

### ISSUE THREAD

**Issue by Anoniempje1234** [SkriptLang/Skript#2795] opened 2020-01-28 20:08 UTC
### Description

Sometimes, I got an error in the console. I think it has something to do with the inventory-click-event. When I reload the scripts, I don't get an error.
### Steps to Reproduce

Use the inventory click event? I think? I don't get it always.
### Expected Behavior

I shouldn't get an error, right?
### Errors / Screenshots

https://gist.github.com/Anoniempje1234/bd4cebfeae23b8c2a37eb807b2439e64

### Server Information
* **Server version/platform:**       Paper 1.15.2 (more details in console error)
* **Skript version:**                2.5-alpha1

**Comment by iOshawott** [comment] 2020-01-30 16:48
maybe try to update skquery?

**Comment by Wealthyturtle** [comment] 2020-02-01 02:24
SkQuery isn't mentioned in the stacktrace though... can anyone else replicate this issue?

**Comment by iOshawott** [comment] 2020-02-02 14:18
> SkQuery isn't mentioned in the stacktrace though... can anyone else replicate this issue?

".... [20:22:48 ERROR]: #!#! Here is full list of them:
.... [20:22:48 ERROR]: #!#! SkQuery v4.1.1"

isn't?

**Comment by bensku** [comment] 2020-02-03 12:45
Please run the server with JVM argument -ea and post any errors that might occur here. I suspect this issue is caused by SkQuery creating inventory slots without inventories, but some obscure part of Skript might also be doing this.

**Comment by Nicofisi** [comment] 2020-03-02 16:36
Hey @Anoniempje1234, are you still here?

**Comment by Jayderp** [comment] 2020-03-22 02:11
@Wealthyturtle I think it'd be time to close this error has OP hasn't replied in almost 2 months

**Closed** 2020-03-22 02:49 UTC
Labels: waiting for reply
