### ISSUE TITLE
Bukkit plugin

### ISSUE THREAD

**Issue by zaipod** [SkriptLang/Skript#4332] opened 2021-09-14 22:09 UTC
### Suggestion

Hello, can you update the Skript plugin on Bukkit?

### Why?

Because I need it for aternos

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by WeeskyBDW** [comment] 2021-09-14 22:14
See https://github.com/SkriptLang/Skript/issues/3550#issuecomment-728826328

**Comment by TPGamesNL** [comment] 2021-09-15 06:51
If you mean making Skript work on CraftBukkit, the answer is no.
If you mean publish Skript on dev.bukkit.org, this is a duplicate of https://github.com/SkriptLang/Skript/issues/3550 / https://github.com/SkriptLang/Skript/issues/3678

**Closed by TPGamesNL** 2021-09-15 06:51 UTC
