### ISSUE TITLE
Crop Harvesting

### ISSUE THREAD

**Issue by Skyy2K** [SkriptLang/Skript#5487] opened 2023-03-02 16:35 UTC
### Skript/Server Version

```markdown
[16:28:38 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:28:38 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[16:28:38 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[16:28:38 INFO]: [Skript] Server Version: git-Paper-81 (MC: 1.19)
[16:28:38 INFO]: [Skript] Skript Version: 2.6.4
[16:28:38 INFO]: [Skript] Installed Skript Addons: 
[16:28:38 INFO]: [Skript]  - SkBee v2.7.6 (https://github.com/ShaneBeee/SkBee)
[16:28:38 INFO]: [Skript] Installed dependencies: 
[16:28:38 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

I am currently creating a farming server with Skript.
Now, when testing my farming script, it turned out to be **NOT** what I expected.
Skript apparently now thinks `ripe wheat plant` is also `wheat item`? (Or any wheat plant stage)

I have provided screenshots as per below.

### Expected Behavior

Skript is not meant to proceed the `if` statement (code shown below) for a `wheat item` or wheat seeds as it is not a `ripe wheat plant`.

### Steps to Reproduce

After finishing my code, which is provided below, I break a 2 wheat plants: a fully grown wheat plant, and a wheat seed. After doing so, it broadcasts saying both of them are a ripe wheat plant, even though one is not.

### Errors or Screenshots

<img width="325" alt="image" src="https://user-images.githubusercontent.com/110974688/222491390-b00c5cb2-1e6d-4ceb-b2a8-3c060c6c19dd.png">

### Other

Code:
```js
on break:
	broadcast "&7Broken: &r%event-block%"
	if event-block is ripe wheat plant:
		broadcast "&aThis is a ripe wheat plant."
	else:
		broadcast "&cThis is not a ripe wheat plant!"
```

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2023-08-21 10:53
Duplicate of #4582

**Closed** 2023-08-27 17:55 UTC
Labels: bug, priority: low, aliases
