### ISSUE TITLE
parameters fiel

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2479] opened 2019-09-23 17:14 UTC
[01:09:10 WARN]: [Skript] Skript's parameters field could not be resolved. Class proxies will not work.

**Comment by Blueyescat** [comment] 2019-09-23 17:16
Duplicate of https://github.com/SkriptLang/Skript/issues/2436, please close this issue.

skript-mirror needs to fix that problem, but it won't break anything you are currently using.

**Closed** 2019-09-24 20:34 UTC
