### ISSUE TITLE
Issue with SKILLS+ plugin and FAWE WorldEdit

### ISSUE THREAD

**Issue by CaoTrongThang** [SkriptLang/Skript#2799] opened 2020-01-31 10:37 UTC
My server is running on PaperSpigot 1.15.2 latest version (86)
Using Skript 2.5

I get this issue when loading skills + and FAWE WorldEdit plugin.

FAWE WorldEdit: https://pastebin.com/z2aTT4Qk
Skills+: https://pastebin.com/6c8GkMm7

**Comment by ShaneBeee** [comment] 2020-01-31 23:05
Duplicate of #2794 
Duplicate of #2737

**Closed by ShaneBeee** 2020-01-31 23:05 UTC
Labels: duplicate
