### ISSUE TITLE
Spawn reasons doesn't work

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2632] opened 2019-11-09 08:46 UTC
```
on spawn of iron golem:
	spawn reason is village defense
	send "&k" to "rudde" parsed as player
```

https://i.imgur.com/yitJKIW.png

**Comment by ShaneBeee** [comment] 2019-11-09 08:47
Duplicate of #2186

**Closed by ShaneBeee** 2019-11-09 08:47 UTC
