### ISSUE TITLE
Size of list variable is not as expected

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3506] opened 2020-10-30 20:45 UTC
### Description

This bug if *it called a bug* has been in Skript for a very long time ever since I was using 2.2-dev36,
using `size of {_list-var::*}` should return how many indexes in that list var but it doesn't! look at the example below, probably the broken thing is the list variable system

### Steps to Reproduce

```
on chat:
    # Test 1
    add "test1" to {_list-var::*}
    add "test2" to {_list-var::*}
    add "test3" to {_list-var::*}
    broadcast "%size of {_list-var::*}%"

    # Test 2
    add "sub1" to {_list-var::test2::*}
    add "sub3" to {_list-var::test2::*}
    broadcast "%size of {_list-var::*}%"

    # Test 3
    set {_list-var::test3::sub1} to "test1"
    set {_list-var::test3::sub2} to "test2"
    broadcast "%size of {_list-var::*}%"

    # Check
    broadcast "%{_list-var::*}%"

    # Check 2
    loop {_list-var::*}:
        broadcast "&a%loop-value%"

    # Test 4
    add player to {_list-var2::*}
    broadcast "&b%size of {_list-var2::*}%"
    
    loop {_list-var2::*}:
        set {_list-var2::%loop-value%::balance} to 10
        set {_list-var2::%loop-value%::kills} to 2
        broadcast "&c%size of {_list-var2::%loop-value%::*}%"

    broadcast "&b%size of {_list-var2::*}%"
    broadcast "&b%size of {_list-var2::%player%::*}%"

    # Last test
    add player to {_list-var3::*}
    broadcast "&e%size of {_list-var3::*}%"
    add "test" to {_list-var3::%player%::child1::child2::child3::child4::*}
    broadcast "&e%size of {_list-var3::*}%"
```

### Expected Behavior

At `Test 1` it should broadcast `3` and it did as expected
At `Test 2` it should broadcast `3` but it broadcast `4` as I think it may have considered the second `test2` as a new index not as an existent one 
At `Test 3` it should broadcast `3` but it broadcast `5` probably same as `Test 2`
At `Check` it says that it has two `<none>` values which is probably the duplicate of `test2` and `test3`
At `Check 2` it looped only real values and didn't read the `<none>` values
At `Test 4` tried to debug this more and tested using setting the child using `%loop-value%` and the same bug occurred
At `Last test` tried to debug this even more by adding multiple children to see if that matters but seems it doesn't

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/20037329/97754109-998bf100-1aff-11eb-8dbb-58db4bcd6991.png)

None.

### Server Information
* **Server version/platform:** 
* **Skript version:** 
![image](https://user-images.githubusercontent.com/20037329/97754403-2040ce00-1b00-11eb-96b7-d7a96cb9f266.png)

### Additional Context

I tried to use global variables and this is what I found in `variables.csv`
```
list-var::1, string, 80057465737431
list-var::2, string, 80057465737432
list-var::3, string, 80057465737433
list-var::test2::1, string, 800473756231
list-var::test2::2, string, 800473756233
list-var::test3::sub1, string, 80057465737431
list-var::test3::sub2, string, 80057465737432
list-var2::1, offlineplayer, 82046E616D65208009536B726970744465760475756964800455554944820C6C656173745369674269747304B304686BD30007C10B6D6F737453696742697473040AC0B83AACB94C85
list-var2::skriptdev::balance, long, 000000000000000A
list-var2::skriptdev::kills, long, 0000000000000002
list-var3::1, offlineplayer, 82046E616D65208009536B726970744465760475756964800455554944820C6C656173745369674269747304B304686BD30007C10B6D6F737453696742697473040AC0B83AACB94C85
list-var3::skriptdev::child1::child2::child3::child4::1, string, 800474657374
```
There are duplicates of the indexes that have been used, both have the same value

**Comment by Sorbon-CH** [comment] 2020-10-30 22:05
That's not a bug, you just don't understand how lists work.

**Comment by TheBentoBox** [comment] 2020-10-30 22:20
I'll leave it to the devs to respond but I agree this all looks like it's working exactly as expected.

> At Test 2 it should broadcast 3 but it broadcast 4 as I think it may have considered the second test2 as a new index not as an existent one
At Test 3 it should broadcast 3 but it broadcast 5 probably same as Test 2
At Check it says that it has two <none> values which is probably the duplicate of test2 and test3
At Check 2 it looped only real values and didn't read the <none> values
At Test 4 tried to debug this more and tested using setting the child using %loop-value% and the same bug occurred

Sub-lists do exist in the main list, but there's no index to represent them, so when you broadcast the list you're seeing `<none>`s which represent the sub-lists with no properly "set" index in the main list. After you added everything, why should it broadcast 3 when there's more than 3 things in this list? At that moment the list contains 3 objects and 2 sub-lists, so naturally the size will broadcast as 5. However, `loop` doesn't iterate over sub-lists, so yes, when looping the list you will see the 3 values contained directly in the main list. I'm not sure what other behavior would be expected.

> At Last test tried to debug this even more by adding multiple children to see if that matters but seems it doesn't

Not sure why this should matter either. It's the exact same thing, you've ended up with one list which contains one element and then one sub-list, so it contains two things.

##

The only possible true "bug" I see here is that when outputting the list it'd be best if it said something more useful rather than `<none>` when containing a sub-list; perhaps it could say something like `list <list index>`, e.g. in your case the output would've been "test1, test2, test3, list test2 and list test3" rather than the two `<none>`s at the end. Otherwise this all seems correct.

**Comment by AyhamAl-Ali** [comment] 2020-10-31 02:41
> That's not a bug, you just don't understand how lists work.
> 
> Index and Value are 2 different things
> at Test 1, you set the index "1" to value "test2"
> 
> at Test 2, you add the index "test2", that's why the output is 4, not 3, test it with `send "%indices of {_list-var::*}%"`
> 
> at Test 3, you added the index "test3"
> 
> `{_list-var::test2}` is not set, but `{_list-var::test2::1}` is, that's why you get `<none>` for it, if you were to test for the sub list, you'd see the values.
> 
> at your second check, it does not send you anything, because there is nothing to send

Good explanation, thank you. However, how about if I want to set the value of list index `test1 without it being added again while it is already added? so when used `add "test1" to {_list-var::*}` now `test1` should be added, when I do `set {_list-var::test1} to "value"` it should add another `test1` it is already there, why not just override the value of it?



> I'll leave it to the devs to respond but I agree this all looks like it's working exactly as expected.
> 
> > At Test 2 it should broadcast 3 but it broadcast 4 as I think it may have considered the second test2 as a new index not as an existent one
> > At Test 3 it should broadcast 3 but it broadcast 5 probably same as Test 2
> > At Check it says that it has two  values which is probably the duplicate of test2 and test3
> > At Check 2 it looped only real values and didn't read the  values
> > At Test 4 tried to debug this more and tested using setting the child using %loop-value% and the same bug occurred
> 
> Sub-lists do exist in the main list, but there's no index to represent them, so when you broadcast the list you're seeing `<none>`s which represent the sub-lists with no properly "set" index in the main list. After you added everything, why should it broadcast 3 when there's more than 3 things in this list? At that moment the list contains 3 objects and 2 sub-lists, so naturally the size will broadcast as 5. However, `loop` doesn't iterate over sub-lists, so yes, when looping the list you will see the 3 values contained directly in the main list. I'm not sure what other behavior would be expected.
> 
> > At Last test tried to debug this even more by adding multiple children to see if that matters but seems it doesn't
> 
> Not sure why this should matter either. It's the exact same thing, you've ended up with one list which contains one element and then one sub-list, so it contains two things.
> 
> The only possible true "bug" I see here is that when outputting the list it'd be best if it said something more useful rather than `<none>` when containing a sub-list; perhaps it could say something like `list <list index>`, e.g. in your case the output would've been "test1, test2, test3, list test2 and list test3" rather than the two `<none>`s at the end. Otherwise this all seems correct.

Another good explanation, as I said above I thought that when setting an existent index it shouldn't add it again, it should just override it that what I was expecting.

because right now I made a small function that will give me the expected size of list instead of counting the `<none>` with them by using
```
function sizeOf(var: text) :: object:
    loop {%{_var}%::*}:
        add 1 to {_n}
    return {_n}
``` 
which works as expected, not counting the <none> values or the indexes that are duplicated

**Closed** 2020-11-13 14:10 UTC
