### ISSUE TITLE
Can't get lore or name of item that only exists in variable

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#1309] opened 2018-06-13 12:57 UTC
set {test} to ice named "test item"
set {_w} to "%{test}'s name%"
{_w} = \<none\>

give ice named "test item" to player
set {test} to player's tool
set {_w} to "%{test}'s name%"
{_w} = "test item"

in skstuff
set {test} to ice with nbt "{display:{Name:""test item""}}"
set {_w} to {test}'s name
{_w}="test item"

**Comment by Nicofisi** [comment] 2018-08-01 00:32
*Probably* related to https://github.com/SkriptLang/Skript/issues/1287#issuecomment-406381386, but checking whether an issue was caused by *that* issue is always time consuming. The best thing would be obviously to fix that issue and then check whether everything that was referenced to it still occurs

**Comment by Nicofisi** [comment] 2018-08-27 18:56
Okay nevermind this is not related to #1287 since this broadcasts null too:
```
    broadcast "%(ice named ""test item"")'s name%"
```

**Comment by Blueyescat** [comment] 2018-11-05 14:38
```vb
set {test} to ice named "test item"
set {_w} to "%{test}'s name%"
```
This code still returns `<none>` but the code @Nicofisi sent works fine on 1.13.2 with 2.3-beta1.

**Comment by ShaneBeee** [comment] 2020-09-23 08:12
I just tested this issue using Paper version git-Paper-202 (MC: 1.16.3) and Skript 2.5-beta4,
this issue seems to have been fixed along the way somewhere.

Closing as it seems to be fixed.
If anyone here is still having the issue, please say so and we ca re-open it.

**Closed by ShaneBeee** 2020-09-23 08:12 UTC
Labels: bug, needs-testing, priority: medium
