### ISSUE TITLE
Problem with the plugin

### ISSUE THREAD

**Issue by Blox61** [SkriptLang/Skript#2553] opened 2019-10-11 18:55 UTC
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:51:16] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:51:16] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:51:16] [Server thread/ERROR]: #!#! Here is full list of them:
[20:51:16] [Server thread/ERROR]: #!#! SkQuery 
[20:51:16] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:51:16] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:51:16] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:51:16] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:51:16] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:51:16] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Stack trace:
[20:51:16] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:64)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.SheepData.init(SheepData.java:1)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.getData(EntityData.java:507)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.EntityData.fromClass(EntityData.java:523)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprSpawnerType.<clinit>(ExprSpawnerType.java:63)
[20:51:16] [Server thread/ERROR]: #!#!     at java.lang.Class.forName0(Native Method)
[20:51:16] [Server thread/ERROR]: #!#!     at java.lang.Class.forName(Class.java:348)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[20:51:16] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Version Information:
[20:51:16] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[20:51:16] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:51:16] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[20:51:16] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[20:51:16] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[20:51:16] [Server thread/ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[20:51:16] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-62-generic
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Server platform: Paper
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Current node: null
[20:51:16] [Server thread/ERROR]: #!#! Current item: null
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Thread: Server thread
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Language: english
[20:51:16] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! End of Error.
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:51:16] [Server thread/ERROR]: #!#! Skript's class ch.njol.skript.expressions.ExprSpawnerType generated an exception while loading
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[20:51:16] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:51:16] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:51:16] [Server thread/ERROR]: #!#! Here is full list of them:
[20:51:16] [Server thread/ERROR]: #!#! SkQuery 
[20:51:16] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:51:16] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:51:16] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:51:16] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:51:16] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:51:16] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Stack trace:
[20:51:16] [Server thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[20:51:16] [Server thread/ERROR]: #!#! java.lang.Exception: ch.njol.skript.util.EmptyStacktraceException
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1546)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1414)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:112)
[20:51:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[20:51:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[20:51:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[20:51:16] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:51:16] [Server thread/ERROR]: #!#! Caused by: ch.njol.skript.util.EmptyStacktraceException
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Version Information:
[20:51:16] [Server thread/ERROR]: #!#!   Skript: 2.4-beta8 (latest)
[20:51:16] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[20:51:16] [Server thread/ERROR]: #!#!     Date: 2019-09-29
[20:51:16] [Server thread/ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[20:51:16] [Server thread/ERROR]: #!#!   Minecraft: 1.14.4
[20:51:16] [Server thread/ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[20:51:16] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.15.0-62-generic
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Server platform: Paper
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Current node: null
[20:51:16] [Server thread/ERROR]: #!#! Current item: null
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Thread: Server thread
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! Language: english
[20:51:16] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[20:51:16] [Server thread/ERROR]: #!#! 
[20:51:16] [Server thread/ERROR]: #!#! End of Error.
[20:51:16] [Server thread/ERROR]: #!#!

**Comment by ShaneBeee** [comment] 2019-10-11 18:56
Duplicate of #2487

**Closed by ShaneBeee** 2019-10-11 18:56 UTC
