### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by MangoTangoMan12** [SkriptLang/Skript#2997] opened 2020-05-19 11:58 UTC
The question I asked got closed so im reposting. Does anybody know what this means?

Link:
https://pastebin.com/raw/t8FDQhkW

If you know, and/or know how to solve it, comment. Thank you!

**Comment by Pikachu920** [comment] 2020-05-19 13:25
Duplicate of #2996

Please discuss your issue there and we can reopen it if it's truly not a duplicate of #2945

**Closed by Pikachu920** 2020-05-19 13:25 UTC
