### ISSUE TITLE
Item Variables will not load when upgrade from 2.5.3 to 2.6 (2)

### ISSUE THREAD

**Issue by NCSV** [SkriptLang/Skript#4475] opened 2021-12-22 12:48 UTC
### Skript/Server Version

```
i have same problems with #4457
when i re-insert item, it worked, but after a certain period of time, it is not recognized again.
```

### Bug Description

![2021-12-22_21 45 51](https://user-images.githubusercontent.com/25452835/147094940-223af851-d2b4-4269-9ea4-d324fab3ebd5.png)
![2021-12-22_21 46 07](https://user-images.githubusercontent.com/25452835/147094963-567385fa-6a93-427a-b9e9-815a447b56df.png)

i made cook skript (put in ingredients in each slot, can exchange food.)
it works well 2.5.3 but when i updated 2.6.0, it's broken.
when i re-insert item, it worked, but after a certain period of time, it is not recognized again.

### Expected Behavior

Convert as needed, or load as it did before.

### Steps to Reproduce

can it make reproduce recognize items well?

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-12-22 12:49
If you have the same problem as another issue, please comment under that issue instead of opening a new issue.

Duplicate of #4457

**Closed by TPGamesNL** 2021-12-22 12:49 UTC
