### ISSUE TITLE
Inventory's name is <none>

### ISSUE THREAD

**Issue by det-kimflight** [SkriptLang/Skript#2315] opened 2019-07-30 07:38 UTC
It is problem when I use inventory click event

this is my script.

on inventory click:
    send "inventory name : %player's current inventory's name%" to player

when I click some inventory's item then send message to me like this
"inventory name : < none>"

but, I set the inventory's name to by using skript.

And, this is about my environment
1. server-version
spigot 1.14.2

2. skript-version
2.4 beta

3. Skript-Addons
skUtilities, skRayFall, SkQuery

4. Another Plugins
CoreProtect, LuckPerms, WorldEdit, Multiverse-Core, WorldGuard, GreifPrevention

What is wrong? 'player's current inventory's name' is expression using without addons?

**Comment by ShaneBeee** [comment] 2019-07-30 08:33
This has already been reported, and the Skript dev team already know about it. It's an issue with Spigot removing the method used for this in 1.14, and a new way needs to be created.

**Comment by bensku** [comment] 2019-08-04 10:32
Duplicate of #2069.

**Closed by bensku** 2019-08-04 10:32 UTC
