### ISSUE TITLE
Error with function optional list argument

### ISSUE THREAD

**Issue by tob-4** [SkriptLang/Skript#4269] opened 2021-08-11 01:52 UTC
### Skript/Server Version

```
[16:02:43 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:02:43 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[16:02:43 INFO]: [Skript] Server Version: git-Tuinity-"dc9d19c" (MC: 1.17.1)
[16:02:43 INFO]: [Skript] Skript Version: 2.6-beta2
[16:02:43 INFO]: [Skript] Installed Skript Addons:
```

### Bug Description

A severe error is caused when creating an optional list argument in a function.

### Expected Behavior

The function should've broadcasted "test".

### Steps to Reproduce

First, create any function with an optional list argument.

```
function test(arg: objects = <none>):
	broadcast "test"
```

Second, call the function.

```
command /test:
	trigger:
		test()
```

This will create a severe error without fail.

### Errors or Screenshots

https://paste.gg/p/anonymous/e43284238f7c467287c4d7d8721cabee

### Other

It took me a while to narrow down what was causing the error. Glad that I can help get this fixed sooner.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-08-11 08:39
Duplicate of #4049
Thank you for reporting tho!

**Closed by TPGamesNL** 2021-08-11 08:39 UTC
