### ISSUE TITLE
Set target not working properly

### ISSUE THREAD

**Issue by CobraTran** [SkriptLang/Skript#5782] opened 2023-07-01 06:56 UTC
### Skript/Server Version

```markdown
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Server Version: git-Paper-549 (MC: 1.19.4)
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Installed Skript Addons: None
[15:48:34] [Render thread/INFO]: [System] [CHAT] [Skript] Installed dependencies: None
```

### Bug Description

Setting an entity's target to (x) somewhat works but returns errors in the console and lines after are not registered.

### Expected Behavior

No errors when setting an entity's target and lines after function normally.

### Steps to Reproduce

Example:
every 1 second:
	loop all entities:
		loop-entity is an iron golem
		set {_p} to nearest player to loop-entity
		set loop-entity's target to {_p}
		broadcast "hello"

If `set loop-entity's target to {_p}` is included, iron golem will target player but `broadcast "hello"` will not get executed.  Error will also appear on console.

If `set loop-entity's target to {_p}` is removed, `broadcast "hello"` will work normally.

This was also tested with other entities but setting a target still causes errors.

### Errors or Screenshots

[06:53:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[06:53:19] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[06:53:19] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[06:53:19] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Stack trace:
[06:53:19] [Server thread/ERROR]: #!#! java.lang.UnsupportedOperationException
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.util.SimpleExpression.change(SimpleExpression.java:238)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.expressions.ExprTarget.change(ExprTarget.java:130)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:121)
[06:53:19] [Server thread/ERROR]: #!#!     at Skript-2.7.0-beta3.jar//ch.njol.skript.events.EvtPeriodical.lambda$postLoad$0(EvtPeriodical.java:80)
[06:53:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[06:53:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[06:53:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[06:53:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[06:53:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[06:53:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[06:53:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[06:53:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Version Information:
[06:53:19] [Server thread/ERROR]: #!#!   Skript: 2.7.0-beta3
[06:53:19] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[06:53:19] [Server thread/ERROR]: #!#!     Date: 03:18:03.366646700
[06:53:19] [Server thread/ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[06:53:19] [Server thread/ERROR]: #!#!   Minecraft: 1.19.4
[06:53:19] [Server thread/ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
[06:53:19] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.19.0-43-generic
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Server platform: Paper
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Current node: null
[06:53:19] [Server thread/ERROR]: #!#! Current item: set target of (loop-entity >> ch.njol.skript.classes.data.DefaultConverters$$Lambda$6937/0x000000080243f300@61af1bc1: ConverterInfo{from=interface org.bukkit.entity.Entity,to=interface org.bukkit.entity.LivingEntity,converter=ch.njol.skript.classes.data.DefaultConverters$$Lambda$6937/0x000000080243f300@61af1bc1,flag=0}) to {_p} (as org.bukkit.entity.LivingEntity)
[06:53:19] [Server thread/ERROR]: #!#! Current trigger: every 1 second (every 1 second) (1.sk, line 1)
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Thread: Server thread
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! Language: english
[06:53:19] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[06:53:19] [Server thread/ERROR]: #!#! 
[06:53:19] [Server thread/ERROR]: #!#! End of Error.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2023-07-01 07:04
Should be a duplicate of #5761

**Comment by AyhamAl-Ali** [comment] 2023-07-01 07:52
Duplicate of #5761

**Closed by AyhamAl-Ali** 2023-07-01 07:52 UTC
