### ISSUE TITLE
On player move and on any move work the same

### ISSUE THREAD

**Issue by WhoCutTheCheese** [SkriptLang/Skript#5319] opened 2023-01-04 11:12 UTC
### Skript/Server Version

```markdown
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[Skript] Server Version: git-Paper-215 (MC: 1.19.2)
[Skript] Skript Version: 2.6.4
[Skript] Installed Skript Addons: 
[Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[Skript]  - Skellett v2.0.8 (https://forums.skunity.com/resources/skellett.24/)
[Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[Skript]  - skRayFall v1.9.28 (https://sk.rayfall.net/)
[Skript]  - SkQuery v4.1.7
[Skript]  - SkBee v2.6.3 (https://github.com/ShaneBeee/SkBee)
[Skript] Installed dependencies: 
[Skript]  - Vault v1.7.3-b131
[Skript]  - WorldGuard v7.0.8-beta-01+cbb2ba7
```

### Bug Description

In the skript docs, it labels how the `on any move` event and the `on player move` event are different.
![image](https://user-images.githubusercontent.com/71863841/210540441-cd95aab1-c6f3-405d-9ce2-03b99ad11270.png)
^ skripthub.net
![image](https://user-images.githubusercontent.com/71863841/210541389-583f7530-d4c5-4f15-a4c2-3bc4e933272b.png)
^ skriptlang.org
Right above it shows how it will not be triggered when a player moves orientation, and yet when I use it, it will still run when someone moves orientation.

https://youtu.be/sDFAeEkWr-8
The video above shows that the `on player move` even still being called when I rotate my head.

### Expected Behavior

When you rotate your head the even should not be being called. This should only happen with `on any move` event.
The `on any move` event works fine, it's the `on player move` that is broken.

### Steps to Reproduce

Create a skript file
use the `on player move` event
`on player move:`
`    send "a" to player`
Will sometimes still be triggered when a player moves their head, in my specific case it triggers every time I move my head.

### Errors or Screenshots

https://youtu.be/sDFAeEkWr-8

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment] 2023-01-04 15:21
I can reproduce, but it only calls the event once after moving the head, not constantly while moving head. The reason is because for some reason the future location gets updated by 2 decimal points.

This is indeed not Skript's fault as this is what Spigot/Paper returns as the value.

For developers: I even attempted to use Paper's `PlayerMoveEvent#hasChangedPosition` and it has the same outcome.

What you can do is ignore the first event calling. Here is a script example:
```vb
on script unload:
	delete {temp::*}

on quit:
	delete {temp::player::%player%::*}

command /spawn:
	trigger:
		if {temp::player::%player%::teleport} is set:
			message "You are already teleporting to spawn"
			stop
		set {temp::player::%player%::teleport} to false
		message "you're teleporting to spawn, don't move!"
		wait 5 seconds
		{temp::player::%player%::teleport} is set
		delete {temp::player::%player%::teleport}
		teleport player to spawn of player's world
		message "&aTeleported to the spawn of the world"

on player move:
	if {temp::player::%player%::teleport} is false:
		set {temp::player::%player%::teleport} to true
		stop
	# Ignores the first event calling.
	{temp::player::%player%::teleport} is true
	delete {temp::player::%player%::teleport}
	message "&cCancelled teleportation"
```
Or better yet, you can use a while loop which is a better implementation
```vb
command /spawn:
	trigger:
		if {temp::player::%player%::teleport} is set:
			message "You are already teleporting to spawn"
			stop
		message "you're teleporting to spawn, don't move!"
		set {temp::player::%player%::teleport} to now
		set {_location} to player's location
		while difference between {temp::player::%player%::teleport} and now is less than 5 seconds:
			wait a tick
			distance between {_location} and player's location is greater than 0
			delete {temp::player::%player%::teleport}
			message "&cCancelled teleportation"
			stop
		{temp::player::%player%::teleport} is set
		delete {temp::player::%player%::teleport}
		teleport player to spawn of player's world
		message "&aTeleported to the spawn of the world"
```

**Comment by Moderocky** [comment] 2024-04-13 07:40
If this is what the server implementation provides us then I'm going to close it. If anything it sounds like a bug/inconsistency that should be fixed upstream, and not something we ought to address ourselves. If the player hasn't changed position then their position shouldn't have changed.

If we tried to build specific support around this oddity then it's likely to cause even more issues down the line, especially if it creates needless overhead that slows down the server.

I don't mind if somebody wants to change the documentation note for the syntax, though, if this is going to be a long-term concern.

**Closed by Moderocky** 2024-04-13 07:40 UTC
Labels: server issue
