### ISSUE TITLE
Files not Reloaded on Start or Restart.

### ISSUE THREAD

**Issue by iCodeDreamsMC** [SkriptLang/Skript#2719] opened 2019-12-22 19:11 UTC
All my skript files dont get reloaded on restart. Well some do but my commands file didnt. I can manually reload it fine and it all works. but never got reloaded on restart. Any ideas?

**Comment by iCodeDreamsMC** [comment] 2019-12-22 19:11
I use the Holiday update 1.15

**Comment by iCodeDreamsMC** [comment] 2019-12-22 21:10
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!
22.12 16:02:29 [Server] ERROR [Skript] Invalid function call to a function that does not exist yet. Be careful when using functions in 'script load' events!

**Comment by iCodeDreamsMC** [comment] 2019-12-22 21:11
my functions are in `functions.sk` and my on load event is in a file that starts with the letter `L` so idk why it doenst exist yet?

**Comment by bensku** [comment] 2019-12-22 22:23
Files starting with capital letters may be loaded before the ones that do not. Try if changing this helps.

**Comment by iCodeDreamsMC** [comment] 2019-12-22 23:01
I renamed it with capital F and all the otehrs are lower case. still has the ERROR in console when restarting server

**Comment by Wealthyturtle** [comment] 2019-12-22 23:15
Could you shrink all your scripts to see which script(s) are causing the issue?

**Comment by Wealthyturtle** [comment] 2019-12-23 08:41
Actually, I seem to be able to replicate this issue on Skript 2.4.1. Will try and post steps to reproduce.

**Comment by Wealthyturtle** [comment] 2019-12-23 09:41
@bensku Not entirely sure if this is the same issue, but I did find a similar issue:

1) Make a script named 'a.sk' that has:
```
function a():
    broadcast "a() called" #Doesn't matter what happens in the function
```

2) Make a script named 'b.sk' that has:
```
on script load:
    a()
```

3) Start up a server running with Skript 2.4.1

4) Run the command ``/sk reload a`` and you should get this error:
```
The function 'a' was deleted or renamed, but is still used in other script(s). These will continue to use the old version of the function until Skript restarts. (b.sk, line 2: a()')
```
(Note that a() is still called properly, just this error will occur when attempting to reload 'a.sk' for the first time manually)

After doing some binary search, this seems to have been introduced in Skript 2.4-beta6. Hopefully this is useful.

**Comment by iCodeDreamsMC** [comment] 2019-12-25 05:13
Any new news?

**Comment by iOshawott** [comment] 2019-12-25 08:25
Wealthyturtle u say beta-6? Maybe it's the reason why I'm still on beta-5, which is the most stable for me.
 
Waiting to fix this and problem with removing items and I'll update : d

**Comment by nopeless** [comment] 2019-12-26 14:35
You just need to reload the skripts twice iirc

**Comment by Wealthyturtle** [comment] 2019-12-26 14:58
> You just need to reload the skripts twice iirc

Still a bug, regardless.

**Comment by iCodeDreamsMC** [comment] 2019-12-27 17:44
So is it considered a bug now? xD **LOL**

**Comment by iCodeDreamsMC** [comment] 2019-12-29 21:05
Also my skripts dont reload correctly i changed the file saved closed reopened and it is saved correctly but /sk reload isnt reloading it cause the message is the same as before.

**Comment by iCodeDreamsMC** [comment] 2019-12-29 21:05
No errors in game nor in console

**Comment by TPGamesNL** [comment] 2021-06-12 14:10
I cannot replicate this, it has most likely been fixed in https://github.com/SkriptLang/Skript/pull/3841

**Closed by TPGamesNL** 2021-06-12 14:10 UTC
Labels: needs testing
