### ISSUE TITLE
Event-Values in docs

### ISSUE THREAD

**Issue by ShaneBeee** [SkriptLang/Skript#6376] opened 2024-01-30 16:54 UTC
### Suggestion

I would like to suggest the addition of event-values in docs.
Similar to SkriptHub:
<img width="1061" alt="Screenshot 2024-01-30 at 8 54 08 AM" src="https://github.com/SkriptLang/Skript/assets/20008482/06327756-924d-4298-968d-269d71a16bc5">

### Why?

This would help Skripters understand which event-values are available in an event.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment] 2024-01-30 17:03
See #5690. I suppose this is a duplicate of https://github.com/SkriptLang/skript-docs/issues/9, but it might be worth keeping here to prevent others from making more duplicates. not sure

**Comment by ShaneBeee** [comment] 2024-01-30 17:03
Yeah, I just found that and was about to close this haha.

**Closed** 2024-01-30 17:03 UTC
Labels: duplicate, documentation
