### ISSUE TITLE
Incompatibility issue with 2.5 beta4 and WolvSK

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#3385] opened 2020-09-18 08:35 UTC
### Description

Whenever I use cooldown-related syntax in WolvSK with expressions, it fails to load the script. example: create cooldown "test%player%" for a second
### Steps to Reproduce

use WolvSK addon and use 
create cooldown "test%player%" for a second 
in your script
### Expected Behavior

To keep loading the scripts correctly, this worked well on 2.5 beta3, while I know that addon compatibility isn't priority - I think it is important to not create backwards incompatible Skript versions

### Errors / Screenshots

some of the stacktraces:
https://pastebin.com/raw/9Mq6Z995

### Server Information
* **Server version/platform:** 1.12.2 Paper
* **Skript version:**  2.5beta4

### Additional Context

I can fix this issue myself if a code change is needed in the addon.

**Comment by ShaneBeee** [comment] 2020-09-18 08:38
There is literally nothing we can do regarding an addon.

**Comment by Govindass** [comment] 2020-09-18 08:39
> 
> 
> There is literally nothing we can do regarding an addon.

well some of the change in this version created an incompatibility - there's likely something that can be done about it

**Comment by ShaneBeee** [comment] 2020-09-18 08:40
Looking at the error, the issue is from the addon, and based on said error, I see nothing we can do on our end to fix it.

**Comment by Govindass** [comment] 2020-09-18 08:41
> 
> 
> Looking at the error, the issue is from the addon, and based on said error, I see nothing we can do on our end to fix it.

anything that I could do to fix it at the addon's code side? it worked perfectly on all skript versions I've used until 2.5 beta4.

**Comment by ShaneBeee** [comment] 2020-09-18 08:42
not a clue, I have no clue what happens in addons. The past few commits haven't changed any code that could break an addon. They mainly been internal fixes to our expressions.

Im closing this issue, as its not a Skript issue, as can be seen in the error.

**Closed by ShaneBeee** 2020-09-18 08:42 UTC

**Comment by Govindass** [comment] 2020-09-18 08:44
line 32 on which it errors:
```
			time = (Expression<Timespan>) expr[1];
```

**Comment by Govindass** [comment] 2020-09-18 09:34
I tried using WolvSK on a empty test server and I had no issues with beta4 even if using the same version of WolvSK, then I updated WolvSK and had no issues on my main server - one of the weirdest problems I've ran into as the logic is like same and Skript didn't really change things that could affect it, must've been something load-order related as soft dependencies changed.
