### ISSUE TITLE
Skript doesn't support 1.15.2

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2860] opened 2020-03-14 10:09 UTC
### Description
Loading Skript 2.5-alpha2 does not work on Paper 1.15.2

### Steps to Reproduce
Use paper 1.15.2 as your server architecture and try to run the latest version of Skript.

### Expected Behavior
No errors.

### Errors / Screenshots
https://hastebin.com/xaveporoze.php

### Server Information
* **Server version/platform:**   [Paper version git-Paper-133 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)](https://papermc.io/api/v1/paper/1.15.2/133/download)
   
* **Skript version:** Skript 2.5-alpha2

**Comment by ShaneBeee** [comment] 2020-03-14 10:17
Duplicate of #2752

**Closed by ShaneBeee** 2020-03-14 10:17 UTC
