### ISSUE TITLE
Skript loading error 

### ISSUE THREAD

**Issue by Tojefin** [SkriptLang/Skript#2791] opened 2020-01-25 15:21 UTC
https://pastebin.com/raw/2GuQ6gbT

Spigot 1.12.2
Skript 2.4.1 and 2.5
Dont have other plugin
Scripts is default 
Launch bat file:  java -Xms1024M -Xmx1024M -jar minecraft_server.jar nogui

![image](https://user-images.githubusercontent.com/39239196/73123275-ad6e5980-3fa7-11ea-834c-a3023936c90e.png)

**Comment by TPGamesNL** [comment] 2020-01-25 17:31
Duplicate of #2752

**Closed** 2020-01-25 20:03 UTC
Labels: duplicate
