### ISSUE TITLE
On Inventory Click Event

### ISSUE THREAD

**Issue by RedSmileyFace** [SkriptLang/Skript#4142] opened 2021-06-30 21:21 UTC
### Description

**The `on inventory click:` event does not trigger unless the clicked slot is 0-8 (Hotbar slots.)**

### Steps to Reproduce
**By pasting the below skript, you will see that the word "Triggered" only is sent when you:

1. Open your Inventory
2. Click Hotbar Slots**

```vbs
on inventory click:
    send "Triggered" to all players
```

**__Additionally__, if you open a "non-player inventory" such as a GUI, the remaining 27 inventory slots now trigger the event while the "above GUI" does not trigger if you click the slots.**

### Expected Behavior

**All 36 inventory slots and all GUI slots (including armor and shield slots) should trigger the event. Using the %event-slot% event value, you should be able to see the slot ID as you click them! EVERY slot should trigger the event, not just Hotbar slots.**

### Errors / Screenshots
**_Not Applicable_**

### Server Information
```
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-66 (MC: 1.17)
[Skript] Skript Version: 2.6-beta1
[Skript] Installed Skript Addons:
[Skript]  - skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders)
[Skript]  - skript-gui v1.3-alpha1 (https://github.com/APickledWalrus/skript-gui)
[Skript]  - Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[Skript]  - skript-yaml v1.4
[Skript]  - MorkazSk v1.2
[Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[Skript]  - Vixio v2.0.7 (http://vixio.space)
[Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[Skript]  - SkQuery v4.1.5
[Skript]  - SkriptJSON v1.0.0
[Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
[Skript]  - skLib v1.1.0 (https://github.com/WheezyGold7931/skLib/)
```
### Additional Context

**_Not Applicable_**

**Comment by TPGamesNL** [comment] 2021-07-01 09:34
I can not replicate this. What gamemode are you in? Are you clicking on items or empty slots? Is there anything in your cursor slot?

**Comment by RedSmileyFace** [comment] 2021-07-02 04:20
At the time, creative (Although now tested again, gamemode has 0 effect.). Empty slots and slots with items in it both do not trigger. Nothing in cursor slot. 1.17 Newest Skript (Pre) Release all details provided above for server version. 

This wasn't an issue in 1.16.5 without the 2.6 beta's so I am wondering if its a version that broke it now.


My friend Lubcubs will comment more on the issue. This was made on his behalf.

**Comment by lubcubsgaming** [comment] 2021-07-02 04:23
I can confirm, game mode has no effect. Survival, creative, adventure. Nothing in curser slot when clicking. 
And clicking on a slot in a virtual gui with an item, or an empty slot does not show anything.  

However, it seems to work in the survival, in all inventory slots, but not in virtual gui slots.
In creative mode, it does not work when clicking on an empty slot, but it works when clicking on a slot with an item in it while in the player inventory, but not a virtual gui.

**Comment by RedSmileyFace** [comment] 2021-07-02 04:38
It is a skript-gui issue. It seems to only happen when in a skript-gui! I tested with a vanilla skript gui and it works although any gui created with skript-gui does not work! Let me know if that is do to a change with skripts inventory click event or if I should contact skript-gui about this. Thanks.

**Comment by FranKusmiruk** [comment] 2021-07-02 04:46
Closing since as per the last comment, this seems to be an issue with skript-gui and not Skript itself. You can create a ticket in [skript-gui's issue tracker](https://github.com/APickledWalrus/skript-gui/issues/).

**Closed by FranKusmiruk** 2021-07-02 04:46 UTC
Labels: waiting for reply

**Comment by lubcubsgaming** [comment] 2021-07-02 04:49
I mean there is still some sort of bug there. In creative game mode, clicking on an empty slot, yields no output. And in survival, clicking on an empty slot, yields an output. So there is an inconsistency. But yes, our main problem is not skript dependent.

**Comment by FranKusmiruk** [comment] 2021-07-02 04:52
> I mean there is still some sort of bug there. In creative game mode, clicking on an empty slot, yields no output. And in survival, clicking on an empty slot, yields an output. So there is an inconsistency. But yes, our main problem is not skript dependent.

that is a client limitation as far I am aware, the client only sends a packet when picking up or dropping/placing an item in a creative inventory, it doesn't send a click event when clicking in categories either as that's completely client-sided. So, this is more of a "feature" (Mojang, go figure) rather than a bug per say, not much we can do about that.
