### ISSUE TITLE
"Outdated" docs?

### ISSUE THREAD

**Issue by MaPaJe** [SkriptLang/Skript#2705] opened 2019-12-18 09:50 UTC
### Description
Not able to get past information of sneaking 

### Steps to Reproduce
on sneak toggle:
	player was sneaking
	push the player upwards at speed 0.5

### Expected Behavior
I could get past tense of sneak

### Errors / Screenshots
https://gyazo.com/e5fa37b10df1d8ed1b44431b73c801d1
https://skriptlang.github.io/Skript/events.html#sneak_toggle

### Server Information
* **Server version/platform: 1.15.1 & 1.14.4**       
* **Skript version: 2.4**

**Comment by APickledWalrus** [comment] 2019-12-18 11:53
Being able to use “was sneaking” would be nice. For now, use “is/is not sneaking” to determine this.

**Comment by MaPaJe** [comment] 2019-12-18 12:45
I need to use it together with "on advancement open:" which can be accessed with "L" but is sneaking will always return "False"

**Comment by ShaneBeee** [comment] 2019-12-22 23:57
This isn't a docs issue, this is an issue with past/future event-values, which has already been reported.

Duplicate of #671

**Comment by TheLimeGlass** [comment] 2020-07-16 00:38
This issue actually isn't related to #671

The syntax just isn't a thing. TimeStates only work on expressions and event-values.

`sneaking` is not a literal, expression or event-value.

What would be cool is creating time state conditions just like expressions though.

**Closed** 2021-08-30 20:42 UTC
Labels: priority: lowest, documentation, completed
