### ISSUE TITLE
Vehicle steering

### ISSUE THREAD

**Issue by 5mmx** [SkriptLang/Skript#7223] opened 2024-11-21 14:49 UTC
### Suggestion

Might be useful to add syntax to detect when a player is attempting to steer a vehicle, which means being able to intercept when a player is using WASD or space bar while on top of a vehicle.

### Why?

While there currently is a way to create, delete and do other things in regards to vehicles, there is currently no way to detect steering. This could be useful for a variety of applications, for example to make "custom vehicles" though invisible armor stands (by making a player ride it though existing syntax). There is no other way to achieve this at the moment as add-ons that used to provide such functionality are now discontinued and not working anymore.

### Other

Please note that this is different from an entity move event. While an entity move event could be used to replace some of the things you would be able to do with a vehicle steering event, it would not allow for example an armor stand moving.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Fusezion** [comment] 2024-11-21 14:59
This to a degree or probably fully implemented in #7190 the vehicle steer event doesn't exactly exist and I believe is likely handled via packets in other addons something skript will likely never interact with on their end unless an api is created by bukkit or paper. 

So this should be something possible in the future and you could test it now via an artifact of that pr and a paper/spigot 1.21.3 release granted these are both still mildly unstable

**Comment by erenkarakal** [comment] 2024-11-21 15:00
Duplicate of #6620
It seems Paper still didn't add the steer event.

**Closed by erenkarakal** 2024-11-21 15:00 UTC
