### ISSUE TITLE
WG support issue

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#2959] opened 2020-05-03 05:20 UTC
### Description
Skript seems don't suppot WG 7.0.2

### Steps to Reproduce
When server starts

### Expected Behavior
WG should be supported

### Errors / Screenshots
[13:16:45 WARN]: [Skript] Loaded class com.boydti.fawe.FaweAPI from WorldEdit v1.15-164;5cc7a09 which is not a depend, softdepend or loadbefore of this plugin.
[13:16:45 ERROR]: [Skript] An error occurred while trying to enable support for FAWE WorldGuard 7. WorldGuard region support has been disabled!
[13:16:45 ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard

### Server Information
* **Server version/platform:**      Latest verison of paper 1.15.2
* **Skript version:**                2.5 alpha3

**Comment by ShaneBeee** [comment] 2020-05-12 09:56
Duplicate of #2674

**Closed by ShaneBeee** 2020-05-12 09:56 UTC
