### ISSUE TITLE
Bug about database storage items

### ISSUE THREAD

**Issue by xbxymax** [SkriptLang/Skript#2169] opened 2019-06-17 11:08 UTC
It's still about data values, so I've written everything down here
https://paste.ubuntu.com/p/2SRZK8VMzm/

**Comment by xbxymax** [comment] 2019-07-03 19:07
111111

**Comment by TheBentoBox** [comment] 2019-07-03 19:21
Please do not spam just because your issue isn't getting the attention you desire.

**Comment by bensku** [comment] 2019-07-10 17:20
Duplicate of #2111. Thanks for test case, though!

**Closed by bensku** 2019-07-10 17:20 UTC
