### ISSUE TITLE
On drop

### ISSUE THREAD

**Issue by TLOvO** [SkriptLang/Skript#4927] opened 2022-07-21 01:49 UTC
### Skript/Server Version

```markdown
SKript Version 2.6.3
server Version 1.18.2paperspigot
```

### Bug Description

On drop
It will trigger On left Click

When I drop item
It will  execute code of On left Click
sorry about my engilsh

### Expected Behavior

trigger on left click

### Steps to Reproduce

On drop:
  cancel event
On left click:
   send "11111" to player
When i drop
it send 11111 to me???

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-07-21 07:29
Duplicate of #2731

**Closed by AyhamAl-Ali** 2022-07-21 07:29 UTC
