### ISSUE TITLE
Skript command bug

### ISSUE THREAD

**Issue by Lennord** [SkriptLang/Skript#2985] opened 2020-05-15 10:42 UTC
Hello, I have a bug in the Skript plugin, because when I do a reload or turn on the server, and its tells me on the console "/skript help" when I execute all the commands of the Skript plugin! Please correct this problem...

Version Minecraft; 1.15.2
Version Skript: 2.5-alpha3
Plugin: skBee, skQuery,skRayfall and Skript

Console error : https://pastebin.com/9sTX1HZK

**Comment by ShaneBeee** [comment] 2020-05-15 10:43
Duplicate of #2752

**Closed by ShaneBeee** 2020-05-15 10:43 UTC
