### ISSUE TITLE
On Consume Event Repeating when canceled and same item in hand

### ISSUE THREAD

**Issue by MrEnxo** [SkriptLang/Skript#3486] opened 2020-10-22 14:44 UTC
### Description
When I Eat my custom food and get to full hunger bar it repeats the on consume event

### Steps to Reproduce
```vb
on consume:
	if tag "CustomItem" of nbt of event-item is "Worm":
		send "test"
		cancel event
		remove 1 of event-item from player's inventory
		add 1 to player's food bar
		stop
```
Reproduce my code. Just cancel the event remove 1 of event-item add 1 to food bar and stop.

### Expected Behavior
It should only do it once

### Errors / Screenshots
no Errors or screenshots I could record but im lazy

### Server Information
Its minehut skript dont know if that changes much 

### Additional Context
This is really annoying for custom servers on minehut with skript

**Comment by ShaneBeee** [comment] 2020-10-26 08:33
Can not reproduce

As you can see in the pic, "test" is sent once, and my stack went from 64 -> 63
<img width="966" alt="Screen Shot 2020-10-26 at 1 32 09 AM" src="https://user-images.githubusercontent.com/20008482/97150296-24996f80-172b-11eb-81fa-80fe762dcab4.png">


Since you are not using an official version of Skript, and also you are using an outdated version of Skript, Im going to go ahead and close this.

If you can reproduce this on our version of Skript, and not Minehut's, as well as an up-to-date version, we can re-open this issue and investigate further.

**Closed by ShaneBeee** 2020-10-26 08:33 UTC

**Comment by OoLunar** [comment] 2021-04-10 07:01
They could've managed to get a repro of https://github.com/PaperMC/Paper/issues/4682
