### ISSUE TITLE
cant return uuid of mob

### ISSUE THREAD

**Issue by TommyFoxs** [SkriptLang/Skript#5193] opened 2022-11-05 16:22 UTC
### Skript/Server Version

```markdown
Server Version: git-Paper-372 (MC: 1.18)
Skript Version: 2.6.3 (latest)
```

### Bug Description

When spawning a mob with a section instead of an effect (Spawn is an effect and a section) and then returning the uuid in a function it for some reason doesn't return an uuid.

### Expected Behavior

It's supposed to return the uuid of the mob.

### Steps to Reproduce

Using this code here shows that when using a section it doesn't return an uuid.
```
command /testuuid:
	trigger:
		broadcast "uuid of mob: %sendUuid(player)%"
		broadcast "uuid of mob2: %sendUuid2(player)%"

function sendUuid(p: player) :: text:
	spawn a zombie at {_p}: zombie at {_p}:
		set {_uuid} to uuid of entity
	return {_uuid}

function sendUuid2(p: player) :: text:
	spawn a zombie at {_p}
	set {_uuid} to uuid of last spawned zombie
	return {_uuid}
```
![image](https://user-images.githubusercontent.com/81250379/200129520-9890b978-83ce-4102-9d47-1cb259dbc061.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by UnderscoreTud** [comment] 2022-11-05 17:24
This is not a bug, it's because when using the section, you're editing the mob's properties *before* it's actually spawned, meaning there's no uuid or an instance assigned to that entity yet. What you could do is you return the uuid after it's spawned.

**Closed** 2022-11-05 17:42 UTC
