### ISSUE TITLE
Parsing issue with the split expression

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2647] opened 2019-11-13 07:40 UTC
### Description
There is a parsing issue with the split expression, that seems to only occur when a string literal is used in place of a variable.

### Steps to Reproduce
```
function a():
    set {_s} to "" #Fix parse problem
    set {_r::*} to "test" split at {_s}
```
The above code will not throw any errors during parsing, while
```
function a():
    set {_r::*} to "test" split at ""
```
will cause a parse error.

### Expected Behavior

For no parse error to be thrown

### Errors / Screenshots

`` {_r::*} can't be set to '"test" split at ""' because the latter is not an object``

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta10

### Additional Context

N/A

**Comment by Matocolotoe** [comment] 2019-11-13 08:55
Can confirm

**Comment by FranKusmiruk** [comment] 2019-11-13 21:11
Duplicate of #709

**Closed by FranKusmiruk** 2019-11-13 21:11 UTC
Labels: bug, priority: low

**Comment by Wealthyturtle** [comment] 2019-11-14 00:35
Oops my bad
