### ISSUE TITLE
NPE from setting variable to drops & ClassCastException: CreatureSpawnEvent > ProjectileLaunchEvent

### ISSUE THREAD

**Issue by staridiot** [SkriptLang/Skript#4350] opened 2021-10-08 06:12 UTC
### Skript/Server Version

```
[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-Paper-318 (MC: 1.17.1)
[Skript] Skript Version: 2.6-beta2
[Skript] Installed Skript Addons:
[Skript]  - MorkazSk v1.2
[Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
```

### NullPointerException
This error occurs very infrequently, I can't find any rhyme or reason for it. It seems to be because I have modified load outs of various mobs when they spawn. I also have the loot reduced by 50%, one of these things is likely causing it to fail.
[Error here](https://pastebin.com/Dq4JiMcy)

### ClassCastException
This one happens quite frequently when spawning a bunch of mobs with a command block. Seems to be from setting the off hand tool of a mob.
[Error here](https://pastebin.com/6CZifwLa)

### NullPointerException
When this error occurs, the variable never gets set to the drops which can cause issues.

### ClassCastException
Unlikely to happen in regular use, but it still happened and probably shouldn't.

### NullPointerException
Honestly can't tell you for sure. I believe it's partially because I modified the armor and tools of the mobs when they spawned and have the drops modified when they die. I can't seem to get this to happen without those two things. Even with those things, it's very inconsistent.

### ClassCastException
Seems to be caused by setting the off hand tool of a mob when it spawns, then spawning a boat load of said mob.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-10-09 11:44
The CCE is probably a duplicate of #3499.

The NPE can be fixed by adding a Objects::nonNull to the stream in ExprDrops (even though I don't know why the list contains a null value in the first place)

**Comment by TPGamesNL** [comment] 2021-10-30 16:51
Actually I am going to close this, because the remaining issue (the NPE) is a plugin issue (or maybe server issue), because I don't think the drops list in a death event should contain null values, and looking at your script and the exception, it looks like the event was called with the null value in the list (or added to it before the event was passed to Skript)

**Closed by TPGamesNL** 2021-10-30 16:51 UTC
Labels: bug, priority: low
