### ISSUE TITLE
Functions not updating in other scripts

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4001] opened 2021-05-13 19:12 UTC
### Description

When using a function from another script and that function gets updated and it's script has been reloaded, other scripts must reload it keep up with the changes otherwise they will be using the old version of that function.

### Steps to Reproduce

- Create 2 scripts
- Create any function in the first script and put some debug statements in
- With the second script, use that function in someway ex. a command
- Update the function code in the 1st script and reload it
- Test the same command u used in the 2nd script (without reloading the 2nd script)
- It will send the old function actions/code (unless reloaded the 2nd script)

**Example Code**
```
#! test1.sk:

function test():
	broadcast "1"

command /t1:
	trigger:
		test()


#! test2.sk

command /t2:
	trigger:
		test()


# Test both, both should print "1"
# Now update test function to broadcast "12"
# Reload test1.sk
# /t1 will broadcast "12"
# /t2 will broadcast "1" (unless you reload test2.sk)
```

### Expected Behavior

Update the function code for all scripts

### Errors / Screenshots

None

### Server Information
* **Server version/platform:**  `Paper 1.16.5-b89788a`
* **Skript version:**  `2.5.3`

### Additional Context

None

**Comment by TPGamesNL** [comment] 2021-05-13 20:50
Duplicate of https://github.com/SkriptLang/Skript/issues/3660

**Closed by TPGamesNL** 2021-05-13 20:50 UTC
