### ISSUE TITLE
Easier parsing

### ISSUE THREAD

**Issue by 24GDude** [SkriptLang/Skript#5162] opened 2022-10-13 21:21 UTC
### Suggestion

Create a parse effect instead of having to set an object to that object parsed as whatever, for example:

`parse {_var} as item` or `parse {_var} as direction`

### Why?

It looks better :)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment] 2022-10-14 02:10
Duplicate of #3561

**Closed by AyhamAl-Ali** 2022-10-14 02:10 UTC
