### ISSUE TITLE
Spigot/Bukkit

### ISSUE THREAD

**Issue by MinetopiaFan135794** [SkriptLang/Skript#3576] opened 2020-11-27 15:54 UTC
Is it possible to make this plugin to upload to dev.bukkit.org or Spigot.orgs

**Comment by Romitou** [comment] 2020-11-27 15:57
Duplicate of #3550 :
> That page on Bukkit is owned by Njol, and has no affiliation with us.

**Closed** 2020-11-28 20:34 UTC
