### ISSUE TITLE
Executing a command over and over duplicates the messages.

### ISSUE THREAD

**Issue by Alderheart** [SkriptLang/Skript#2301] opened 2019-07-25 19:28 UTC
### Description

Whenever I execute a command over and over, the variables and strings in the messages just duplicate more and more every time.

### Steps to Reproduce

```
command /health <player>:
	description: Check another player's conditions
	usage: /health <player>
	trigger:
		message "&a&l&m--------[&r&6&l %arg 1% &a&l&m]--------"
		message "&7Health: &f%arg 1's health%"
		message "&7Hunger: &f%arg 1's hunger%"
		message "&7Exhaustion: &f%{exhaustion.%arg 1%}%"
		message "&7Thirst&f: &f%{thirst.%arg 1%}%"
```

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/53315508/61902786-e0e50400-aef0-11e9-96c5-bc6066823929.png)

### Server Information
* **Server version/platform:**       1.14.4, spigot
* **Skript version:**                2.4-beta3

**Comment by Matocolotoe** [comment] 2019-07-25 19:49
Duplicate of #2279

**Closed** 2019-07-25 20:28 UTC
Labels: duplicate
