### ISSUE TITLE
skript bug (CRash)

### ISSUE THREAD

**Issue by monkey00000** [SkriptLang/Skript#2704] opened 2019-12-17 22:58 UTC
Description
Server crashes when on rightclick event item is removed during that event

Steps to Reproduce
Remove item from player when right-click event is fired

Expected Behavior
You know

Errors / Screenshots
https://img.onl/Gwe9a1

**Comment by ShaneBeee** [comment] 2019-12-17 22:59
This is an issue with Spigot not Skript, Im pretty sure it has already been reported but I cant find the issue.

You need to add at least a 1 tick wait before removing an item from a player in a click event.

**Comment by ShaneBeee** [comment] 2019-12-17 23:02
Duplicate of #2143

**Closed by ShaneBeee** 2019-12-17 23:02 UTC
