### ISSUE TITLE
Uncolored expression removes unused format symbols

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#2713] opened 2019-12-21 01:51 UTC
### Description
Just as the title says

### Steps to Reproduce
```
command /test:
    trigger:
        
        set {_text} to "Something & Something"
        send {_text}
        set {_text} to uncolored {_text}
        send {_text}
```

### Expected Behavior
The &-symbol should not be removed

### Errors / Screenshots
No errors

### Server Information
* **Server version/platform:**      paper 1.14.4
* **Skript version:**                2.4

**Comment by Wealthyturtle** [comment] 2019-12-22 01:19
Can confirm this issue. I did a bunch of investigating and it also seems to remove < and > symbols used in JSON formatting.

Here's a simplified test script:
```
command /f <string>:
    trigger:
        broadcast arg-1
        broadcast uncolored arg-1
```

**Comment by nopeless** [comment] 2019-12-22 03:59
@Wealthyturtle 
do you think skript needs a
uncolored
unstyled
unformatted
expression?
because uncolored also removes style codes which might be unexpected for a lot of players

**Comment by Wealthyturtle** [comment] 2019-12-22 04:14
Perhaps.

**Comment by Govindass** [comment] 2019-12-22 07:23
This change would be really nice, it's kinda disturbing my cross-server chat system, replacing & <> which are often used in normal usage, such as telling people to do /friend add <player>

**Comment by jaylawl** [comment] 2019-12-22 15:26
This used to work perfectly fine before, i'd rather call this a bug than an enhancement :|

**Comment by FranKusmiruk** [comment] 2019-12-24 11:18
@jaylawl unless my memory fails me, the uncolored expression has always removed the color symbols. Please tell me with what release (excluding dev ones), it wasn't this way.

**Comment by jaylawl** [comment] 2020-01-01 19:52
I'm sure that it used to work until 2.3.6, which is the version i upgraded to 2.4 from, @FranKusmiruk . Unfortunately i cannot remember what i used this for and in what way.

In any case: a standalone `&` symbol is not a formatting/coloring symbol or at least shouldn't be interpreted as such.

**Comment by Wealthyturtle** [comment] 2020-01-08 15:19
https://github.com/SkriptLang/Skript/blob/8f1981dbd31df2f9c7ed8954d44c5c5c24d314e3/src/main/java/ch/njol/skript/util/chat/ChatMessages.java#L505-L506 is the cause of this issue.

**Comment by jaylawl** [comment] 2020-01-11 13:50
https://papermc.io/javadocs/paper/1.14/org/bukkit/ChatColor.html#stripColor-java.lang.String-

I've just been messing about with this and it returns &'s properly if not involved in a color-code

**Comment by bensku** [comment] 2020-01-11 14:54
As stated in code comment, *everything* is stripped to protect against bugs in Skript's chat formatting system. This is not as critical as it was before #2215, and could potentially be removed.

**Comment by AyhamAl-Ali** [comment] 2021-09-07 00:25
Same as #3787

**Comment by TPGamesNL** [comment] 2021-09-07 12:40
Closing in favour of #3787

**Closed by TPGamesNL** 2021-09-07 12:40 UTC
Labels: enhancement, priority: low
