### ISSUE TITLE
Set line   | doesn't work on: bamboo/cherry sign |   and   | hanging´s: crimson warped |

### ISSUE THREAD

**Issue by yzz17** [SkriptLang/Skript#6553] opened 2024-04-12 03:39 UTC
### Skript/Server Version

```markdown
Skript 2.8.4
Purpur 1.20.4 #2169 // spigot
```

### Bug Description

on leftclick on sign:
	set line 3 to "test"
on leftclick on hanging sign:
	set line 3 to "test"

### Expected Behavior

set test to line 3

### Steps to Reproduce

It's a simple bug, it must be because the material isn't registered or something like that / I tried with the other materials and no problems

### Errors or Screenshots

![image](https://github.com/SkriptLang/Skript/assets/13352920/c61a107c-35a7-4a24-b965-e4b4b1b2213e)

### Other

I still use signs to access arenas and game modes. I know, it's old school but I love it

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2024-04-12 11:31
Duplicate of #6220

**Closed by AyhamAl-Ali** 2024-04-12 11:31 UTC
Labels: bug, priority: low, aliases
