### ISSUE TITLE
1.13 not working?

### ISSUE THREAD

**Issue by bolleboor** [SkriptLang/Skript#1753] opened 2018-12-16 11:27 UTC
I'm trying to start my server, but skript is not loading in 1.13

Upgrade your server to 1.13+

I just expected it work because the where as update to make it work.

https://gist.github.com/bolleboor/d525e1bb69280adda3b0a221312f9be7 <- full console log

### Server Information
* **Server version/platform:**  1.13+     
* **Skript version:**  Skript 2.3 beta 4

**Comment by bensku** [comment] 2018-12-16 12:10
Duplicate of #1697. Variable database updates are bugged.

**Closed by bensku** 2018-12-16 12:10 UTC
