### ISSUE TITLE
Bug: Worldguard and Worldedit support (doesn't work)

### ISSUE THREAD

**Issue by TheIronMinerLv** [SkriptLang/Skript#1698] opened 2018-11-19 13:42 UTC
Hello, I'll be short and simple.

Today I compiled Skript and took the [newest Worldedit and Worldguard builds](http://builds.enginehub.org/). Started the server and I got such error:

`[15:39:48 ERROR]: [Skript] WorldEdit you're using is not compatible with Skript. Disabling WorldGuard support!`
`[15:39:48 ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard`

I'm using Spigot 1.13.2, with, as compiled today, Skript 2.3-beta2.

**Comment by TheBentoBox** [comment] 2018-11-19 14:02
I can confirm this, noticed it last night as well but hadn't gotten a chance to make an issue or verify with anyone else.

**Comment by TheBentoBox** [comment] 2018-11-19 14:03
(Marking high priority in case it's not user error on our parts because it breaks all of the heavily used WG syntaxes).

**Comment by ham1255** [comment] 2018-11-24 12:31
please add support for older versions as well because i use skript beta2 in 1.12.2 and worldedit 7.0.0 does not work

**Comment by TheBentoBox** [comment] 2018-11-28 15:08
Should be fixed as of 2.3-beta3.

**Closed by TheBentoBox** 2018-11-28 15:08 UTC
Labels: bug, priority: high
