### ISSUE TITLE
Functions throw error when reloaded in subfolders

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#2461] opened 2019-09-18 09:10 UTC
### Description

if I put a script with function in a subfolder, for example "gs" and do /skript reload gs/script
it will throw error that a function with that name is already loaded in gs/script even if I am reloading the gs/script
### Steps to Reproduce

reload a script in subfolder which has a function
### Expected Behavior

expected to not throw error and reload properly
### Server Information
* **Server version/platform:** 1.12.2 paper       
* **Skript version:** 2.4-beta7                

### Additional Context

same happens if I use /skript disable on it and then enable

**Comment by bluelhf** [comment] 2019-09-18 12:15
Can reproduce with Paper 1.14.4 and Skript 2.4-beta7. Low priority bug seems appropriate.

**Comment by Govindass** [comment] 2019-09-18 12:40
kinda big for me as I use folders a lot and now I can't reload these functions without restarting the server

**Comment by Wealthyturtle** [comment] 2019-09-18 13:44
Out of curiosity, can you replicate this on Skript 2.4-beta5?

**Comment by SpinKnight** [comment] 2019-09-19 14:12
> Can reproduce with Paper 1.14.4 and Skript 2.4-beta7. Low priority bug seems appropriate.

This is actually a pretty big bug, as it causes functions not to update properly and it sometimes requires a server restart for it to work.

**Comment by SpinKnight** [comment] 2019-09-19 14:19
Also, when reloading all scripts, if an error occures, like "function doesn't exist", just because it wasn't loaded yet, even though you put it in a folder called __lib which is the top one, therefore should be loaded first, it prevents all of the other scripts to reload and just stops the reloading right there. This will result in you needing to restart the server.

**Comment by Wealthyturtle** [comment] 2019-09-23 09:57
Seems to be a regression of the recent function changes, this doesn't occur for commands

**Comment by bluelhf** [comment] 2019-10-10 07:39
Since the priority was reassessed, I don't think 2.4 should be released without a fix for this.

**Comment by APickledWalrus** [comment] 2019-10-10 10:18
This could be related, but when calling a function in a different script then one the function was created in, it causes an error when reloading the function’s code script stating something like, “the function was moved or has been deleted. it will no longer work on next restart,” even if the function has had no changes to it

**Comment by bluelhf** [comment] 2019-10-10 10:22
@APickledWalrus That's caused by the other script using an old version of the function, but yes it'd be nice to 'give' the other script(s) an updated version of the function when the script reloads

**Comment by APickledWalrus** [comment] 2019-10-10 10:24
ah okay. Good to know

**Comment by Matocolotoe** [comment] 2019-10-10 11:34
It should be a warning an not an error though

**Comment by bluelhf** [comment] 2019-10-10 12:06
@Matocolotoe It's an error, that could be something to change..

**Comment by bluelhf** [comment] 2019-10-10 20:05
:D ty for completionnn :)

**Closed** 2019-10-15 14:02 UTC
Labels: bug, completed, priority: medium
