### ISSUE TITLE
Is this a mistake or is it bug?

### ISSUE THREAD

**Issue by bonjourkemal** [SkriptLang/Skript#2254] opened 2019-07-16 07:27 UTC
```
[10:22:05] [Server thread/INFO]: [Skript] Loading variables...
[10:22:06] [Server thread/ERROR]: [Skript] 217 log handlers were not stopped properly! (at ch.njol.skript.registrations.Classes.parse(Classes.java:470)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:580)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 2 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1602)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1496)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 914 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:563)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 29 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:874)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 18 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1588)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 250 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:253)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
[10:22:06] [Server thread/ERROR]: [Skript] 9 log handlers were not stopped properly! (at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:708)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```

**Comment by bonjourkemal** [comment] 2019-07-16 07:33
Skript version: Skript 2.4-alpha4
Server version: 1.14.3

**Comment by TPGamesNL** [comment] 2019-07-16 09:23
This is caused by skript-mirror 1.0.0 or below. Use the 2.0 snapshot to fix this.

**Comment by bonjourkemal** [comment] 2019-07-16 09:49
Can you send me a link?

**Comment by TPGamesNL** [comment] 2019-07-16 10:29
[skript-mirror-2.0.0-SNAPSHOT.zip](https://github.com/SkriptLang/Skript/files/3396649/skript-mirror-2.0.0-SNAPSHOT.zip)
should work

**Comment by bonjourkemal** [comment] 2019-07-16 13:27
Solved, thanks!

**Comment by Blueyescat** [comment] 2019-07-16 13:28
close the issue please ^^

**Closed** 2019-07-16 13:28 UTC
