### ISSUE TITLE
cant remove from victim or attacker's inventory

### ISSUE THREAD

**Issue by madebygood** [SkriptLang/Skript#5990] opened 2023-09-10 19:37 UTC
### Skript/Server Version

```markdown
skript : 2.7
server : 1.20.1 paper
```

### Bug Description

on death of player:
 remove 1 of {item} from victim's inventory
 
 it doesnt work

### Expected Behavior

.

### Steps to Reproduce

.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2023-09-10 19:39
Duplicate of #5755

**Closed by AyhamAl-Ali** 2023-09-10 19:39 UTC

**Comment by madebygood** [comment] 2023-09-10 19:44
> Duplicate of #5755

Isn't this a bug?

So how should I modify the code?

help.

**Comment by AyhamAl-Ali** [comment] 2023-09-10 19:56
You can download this Skript version from the PR that fixed the issue [here](https://github.com/SkriptLang/Skript/suites/14249176787/artifacts/800286168)

**Comment by madebygood** [comment] 2023-09-10 20:03
> You can download this Skript version from the PR that fixed the issue [here](https://github.com/SkriptLang/Skript/suites/14249176787/artifacts/800286168)

![image](https://github.com/SkriptLang/Skript/assets/43653581/f34e8d21-6272-4dcb-90e4-ba9966c4de42)

Thank you for answer.

However, since the version of the PR in question is quite old, various errors have not been corrected.

Is it possible to use the latest 2.7.0 version with PR?

If it's bothersome, just tell me how to do it and I'll do it.

**Comment by madebygood** [comment] 2023-11-15 16:19
> i feel like this isn't a bug

Why do you think so?

Codes such as removing 50% of items from Victim's inventory do not work.

Skript should be able to implement these features.

**Comment by madebygood** [comment] 2023-11-15 16:30
> please see [#5755 (comment)](https://github.com/SkriptLang/Skript/issues/5755#issuecomment-1603433841)

You should be able to process inventory on death regardless of whether KeepInventory is allowed or not.

Why delete a well-used feature when you should be able to enable users to use it as needed?

Also, it is not recognized in worlds where keep inventory is set to true.

**Comment by TheLividX** [comment] 2023-11-15 16:32
> > please see [#5755 (comment)](https://github.com/SkriptLang/Skript/issues/5755#issuecomment-1603433841)
> 
> You should be able to process inventory on death regardless of whether KeepInventory is allowed or not.
> 
> Why delete a well-used feature when you should be able to enable users to use it as needed?
> 
> Also, it is not recognized in worlds where keep inventory is set to true.

I could maybe be wrong, do you have a source to back up this information?

**Comment by sovdeeth** [comment] 2023-11-15 17:01
> > You can download this Skript version from the PR that fixed the issue [here](https://github.com/SkriptLang/Skript/suites/14249176787/artifacts/800286168)
> 
> Any good news?
> 
> Has it not been resolved yet?

Yes, this has been fixed in #6171 and should be in 2.7.3.
