### ISSUE TITLE
Error while using location function

### ISSUE THREAD

**Issue by ModcoLocko** [SkriptLang/Skript#3308] opened 2020-08-15 00:43 UTC
Description
when using location(55, 7, 8) i get a error and the command doesnt work

Steps to Reproduce
Here is my exact script
command /test:
	trigger:
		send "Sent"
		location(55, 7, 8)

Expected Behavior
it should have told the player Sent, and teleport them to 55, 7, 8

Errors / Screenshots
https://docs.google.com/document/d/1UkqsNjbttuEB8hOBIW-zENI_yWxtexv6P6IbfVCkWIU/edit?usp=sharing

Server version/platform: Paper
Skript version: 2.5-beta2

I probably didn't format this very well and am sorry about that

**Comment by ShaneBeee** [comment] 2020-08-15 00:45
Duplicate of #1465

**Closed by ShaneBeee** 2020-08-15 00:45 UTC
