### ISSUE TITLE
I want to get a vehicle from 'on vehicle' event.

### ISSUE THREAD

**Issue by vhone** [SkriptLang/Skript#4328] opened 2021-09-12 16:54 UTC
### Suggestion

In 'on vehicle enter' and 'on mount' events, I can receive a vehicle as 'vehicle of player'.
However, in the 'on vehicle (create|destroy|damage)' event, there seems to be no way to get the vehicle.

In the 'create' event, the event-entity receives nothing.
In 'destroy' and 'damage' events, event-entity receives event-player.

This can be obtained simply by using the event.getVehicle() method with the reflect addon.
I wish I could get this from event-entity.

### Why?

I don't want to use the reflect addon, I just want to use this with vanilla scripts.

### Other

nothing

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment] 2021-09-12 20:45
Seems like `event-vehicle` isn't a thing in Skript since there is no class info for it and `event-entity` is used for both the rider and the vehicle which conflicts with each other. (maybe someone else know more about this?)

I'm currently working on a PR to implement vehicle and rider expressions with more vehicle events

**Comment by TPGamesNL** [comment] 2021-09-19 10:45
Duplicate of https://github.com/SkriptLang/Skript/issues/1337

**Closed by TPGamesNL** 2021-09-19 10:45 UTC
