### ISSUE TITLE
1.18 Skript  can't use "{}" and "İ" on message script

### ISSUE THREAD

**Issue by PaxYT** [SkriptLang/Skript#4468] opened 2021-12-19 16:30 UTC
### Skript/Server Version

```
command /test:
    trigger:
        message "{İ}" to player
```

### Bug Description

not working.
When you use only 'İ' it says *Can't understand*
When you use only "{}" no errors but not working (i  already tried "{{}}"

### Expected Behavior

it supposed to work like on old versions of skript.

### Steps to Reproduce

i didn't do anything.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-12-19 16:34
Duplicate of https://github.com/SkriptLang/Skript/issues/4465

**Closed by TPGamesNL** 2021-12-19 16:34 UTC

**Comment by PaxYT** [comment] 2021-12-19 16:57
> Duplicate of #4465

Are you stupid? I just re-send my 'bug report' message because no one replied so #4465 is duplicate of mine #4455
