### ISSUE TITLE
/skript help all teh time

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [SkriptLang/Skript#3011] opened 2020-05-27 04:19 UTC
### Description
Says /skript help when doing /sk or /skript (subcmd)

### Steps to Reproduce
download a version with latest relez and then uh u turn ur server to paper/spigot

### Expected Behavior
Show all the menu and help and all that.

### Errors / Screenshots
I coundn't get screenshots cuz its locked.
https://pastebin.com/dXyrRzew

### Server Information
* **Server version/platform:**       [08:15:59 INFO]: This server is running CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[08:15:59 INFO]: You are 2 version(s) behind

* **Skript version:**                 2.4.1

**Comment by Romitou** [comment] 2020-05-27 06:12
Duplicate of #2752

**Comment by ThisIsACoolBoy** [comment] 2020-05-27 06:21
That thread help me but I don’t understand what they are saying.

**Comment by Wealthyturtle** [comment] 2020-05-27 07:25
Try using 64-bit Java or Java 11, basically. We don't exactly know what's the cause, but it's due to Java in some way.

**Closed by Wealthyturtle** 2020-05-27 07:25 UTC

**Comment by ThisIsACoolBoy** [comment] 2020-05-28 11:25
![image](https://user-images.githubusercontent.com/48828036/83135804-734cca00-a0f7-11ea-8dd2-e0e170f6fe46.png)

**Comment by ThisIsACoolBoy** [comment] 2020-05-28 14:50
using 64-bit java and still not working.

**Comment by ThisIsACoolBoy** [comment] 2020-05-28 14:53
![image](https://user-images.githubusercontent.com/48828036/83157239-6ab6bc80-a114-11ea-967b-b437e8a3b58b.png)
Looks weird. Doesn't work on my game but for console it does :/

**Comment by ThisIsACoolBoy** [comment] 2020-05-28 14:54
oh i was wrong XD 
![image](https://user-images.githubusercontent.com/48828036/83157436-a487c300-a114-11ea-8d29-e43b034cd5f6.png)

**Comment by ThisIsACoolBoy** [comment] 2020-05-28 14:54
ty for the help WealthyTurtle

**Comment by ShaneBeee** [comment] 2020-05-28 17:55
@ThisIsACoolBoy As I mentioned in the other issue, please stop spamming replies in this issue tracker. People here do not appreciate getting multiple emails/notifications for the same person in the same issue. Edit your messages if need be.

I condensed your FIVE messages into one message.
