### ISSUE TITLE
Skript claiming server is running on 32-bit java and coming with errors

### ISSUE THREAD

**Issue by markaabo** [SkriptLang/Skript#4210] opened 2021-07-21 09:55 UTC
### Skript/Server Version

```
[11:49:14 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:49:14 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[11:49:14 INFO]: [Skript] Server Version: git-Paper-119 (MC: 1.17.1)
[11:49:14 INFO]: [Skript] Skript Version: 2.5.3
[11:49:14 INFO]: [Skript] Installed Skript Addons:
[11:49:14 INFO]: [Skript]  - skript-yaml v1.3.2
[11:49:14 INFO]: [Skript]  - skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect)
[11:49:14 INFO]: [Skript]  - Vixio v2.0.8 (http://vixio.space)
```

### Bug Description

I just installed Skript, and it comes up with this message: 
`[11:46:13 WARN]: [Skript] You are currently using 32-bit Java. This may result in a StackOverflowError when loading aliases.
[11:46:13 WARN]: [Skript] Please update to 64-bit Java to remove this warning.` 

even tho i am using AdoptOpenJDK Java 16 64-bit, i tried reinstalling Java 16 being sure to install the 64-bit version but Skript still claims its 32-bit :(

### Expected Behavior

Skript should be running on 64-bit Java 16 not 32-bit

### Steps to Reproduce

Install AdoptOpenJDK Java 16 64-bit
Setup a Paper server with Skript
Startup the server

### Errors or Screenshots

```
[11:46:12 INFO]: [Skript] Enabling Skript v2.5.3
[11:46:13 WARN]: [Skript] You are currently using 32-bit Java. This may result in a StackOverflowError when loading aliases.
[11:46:13 WARN]: [Skript] Please update to 64-bit Java to remove this warning.
[11:46:14 INFO]: [Skript] You're currently running the latest stable version of Skript.
[11:46:14 ERROR]: [Skript] Parsing block state [level=0] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[11:46:14 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=0]
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData$$Lambda$4892/0x0000000043420678.apply(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2239)
[11:46:14 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1802)
[11:46:14 WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases$$Lambda$4904/0x00000000433c3528.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda$353/0x0000000000000000.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[11:46:14 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[11:46:14 WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:46:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[11:46:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x0000000048a70860.run(Unknown Source)
[11:46:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
[11:46:14 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[11:46:14 ERROR]: [Skript] Parsing block state [level=1] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[11:46:14 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=1]
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData$$Lambda$4892/0x0000000043420678.apply(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2239)
[11:46:14 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1802)
[11:46:14 WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases$$Lambda$4904/0x00000000433c3528.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda$353/0x0000000000000000.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[11:46:14 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[11:46:14 WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:46:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[11:46:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x0000000048a70860.run(Unknown Source)
[11:46:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
[11:46:14 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[11:46:14 ERROR]: [Skript] Parsing block state [level=2] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[11:46:14 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=2]
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData$$Lambda$4892/0x0000000043420678.apply(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2239)
[11:46:14 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1802)
[11:46:14 WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases$$Lambda$4904/0x00000000433c3528.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda$353/0x0000000000000000.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[11:46:14 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[11:46:14 WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:46:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[11:46:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x0000000048a70860.run(Unknown Source)
[11:46:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
[11:46:14 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[11:46:14 ERROR]: [Skript] Parsing block state [level=3] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[11:46:14 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=3]
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData$$Lambda$4892/0x0000000043420678.apply(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2239)
[11:46:14 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1802)
[11:46:14 WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases$$Lambda$4904/0x00000000433c3528.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda$353/0x0000000000000000.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[11:46:14 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[11:46:14 WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:46:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[11:46:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x0000000048a70860.run(Unknown Source)
[11:46:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
[11:46:14 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[11:46:14 ERROR]: [Skript] Parsing block state [level=3] failed! (brewing.sk, line 80: {cauldron level} cauldron¦s = minecraft:cauldron')
[11:46:14 WARN]: java.lang.IllegalArgumentException: Could not parse data: minecraft:cauldron[level=3]
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.createNewData(CraftBlockData.java:550)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.lambda$newData$1(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData$$Lambda$4892/0x0000000043420678.apply(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createBlockData(CraftServer.java:2239)
[11:46:14 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1802)
[11:46:14 WARN]:        at ch.njol.skript.bukkitutil.block.NewBlockCompat.createBlockValues(NewBlockCompat.java:357)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:277)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:702)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:602)
[11:46:14 WARN]:        at ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:120)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:496)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:482)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.lambda$1(Aliases.java:465)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases$$Lambda$4904/0x00000000433c3528.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink$$Lambda$353/0x0000000000000000.accept(Unknown Source)
[11:46:14 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:46:14 WARN]:        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:498)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:46:14 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:46:14 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
[11:46:14 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:458)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:424)
[11:46:14 WARN]:        at ch.njol.skript.aliases.Aliases.load(Aliases.java:396)
[11:46:14 WARN]:        at ch.njol.skript.Skript.onEnable(Skript.java:403)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:46:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:46:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[11:46:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[11:46:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:46:14 WARN]:        at net.minecraft.server.MinecraftServer$$Lambda$3679/0x0000000048a70860.run(Unknown Source)
[11:46:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:853)
[11:46:14 WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:cauldron does not have property 'level' at position 19: ...:cauldron[<--[HERE]
[11:46:18 ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]¦s = minecraft:grass_path')
[11:46:18 ERROR]: [Skript] Minecraft id minecraft:grass_path is not valid (decoration.sk, line 416: grass path [block]¦s = minecraft:grass_path')
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-07-21 10:10
Try to double check if the 64-bit Java version is currently in-use using `echo $JAVA_HOME` and `java --version` on your linux system

**Comment by TPGamesNL** [comment] 2021-07-21 10:11
The 32-bit thing is a duplicate of #3805, the error is because you're using 2.5.3, which isn't supported on 1.17. Use the latest release (2.6-beta2): https://github.com/SkriptLang/Skript/releases

**Closed by TPGamesNL** 2021-07-21 10:11 UTC
