### ISSUE TITLE
disappearing signs in gui

### ISSUE THREAD

**Issue by Mitek2612** [SkriptLang/Skript#5731] opened 2023-06-04 01:47 UTC
### Skript/Server Version

```markdown
[03:39:38 INFO]: 7[6Skript7] rSkript's aliases can be found here: 3https://github.com/SkriptLang/skript-aliases
[03:39:38 INFO]: 7[6Skript7] rSkript's documentation can be found here: 3https://docs.skriptlang.org/
[03:39:38 INFO]: 7[6Skript7] rSkript's tutorials can be found here: 3https://docs.skriptlang.org/tutorials
[03:39:38 INFO]: 7[6Skript7] rServer Version: 3git-Paper-545 (MC: 1.19.4)
[03:39:38 INFO]: 7[6Skript7] rSkript Version: 32.7.0-beta2 (skriptlang-github)
[03:39:38 INFO]: 7[6Skript7] rInstalled Skript Addons: 3None
[03:39:38 INFO]: 7[6Skript7] rInstalled dependencies: 3None
```

### Bug Description

when i use signs in gui signs starts disappear

### Expected Behavior

open gui  with sign but one time there is sign next time there are not sign

### Steps to Reproduce

`set slot 3 of {_chest} to oak sign named "&aWymień bloki"`
 just use set slot with command open

### Errors or Screenshots

![Zrzut ekranu 2023-06-04 034636](https://github.com/SkriptLang/Skript/assets/117837382/4f8e5c3e-5293-41db-9e68-11b144d7c23e)
![Zrzut ekranu 2023-06-04 034606](https://github.com/SkriptLang/Skript/assets/117837382/ab9eb6fa-996d-4f43-9071-b4775451ec90)
![Zrzut ekranu 2023-06-04 034621](https://github.com/SkriptLang/Skript/assets/117837382/de573f00-ffda-4f85-b7ab-e2ebba53ecd7)

### Other

when i use other item everything is okay

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment] 2023-06-04 04:28
Duplicate of #5586 I believe

**Comment by AyhamAl-Ali** [comment] 2023-06-04 06:28
@Mitek2612 
Can you provide your current code use to demonstraight this issue, so we can double check of it's a duplicate of the issue Walrus mentioned above or something else.

**Closed** 2023-06-04 06:41 UTC
Labels: duplicate

**Comment by Mitek2612** [comment] 2023-06-04 10:53
> @Mitek2612 Can you provide your current code used to demonstrate this issue, so we can double check of it's a duplicate of the issue Walrus mentioned above or something else.

`command /wymiana:
    trigger:
        set {_chest} to a new chest inventory with 1 row named "Wymiana"
        set slot 0 of {_chest} to black stained glass pane named "&8&l_"
        loop 1*9 times:
            set slot (loop-number - 1) of {_chest} to black glass pane named "&8&l_"
        set slot 3 of {_chest} to ender chest named "&aWymień bloki"
        set slot 5 of {_chest} to ender chest named "&aWymień Punkty"
        open {_chest} to player

    

on inventory click:
    name of event-inventory is "Wymiana"
    cancel event
    if index of event-slot is 3:
        set {_cobble} to "%number of cobblestone in the player's inventory%" parsed as integer
        if %{_cobble}% is greater than 0:
            send "Nie masz wymienialnych blokow w eq"
        else:
            set {punkty.%player%} to "%number of cobblestone in the player's inventory%" parsed as integer
            remove all cobblestone from player's inventory
            send "Masz %{punkty.%player%}% punktów wymiany" to player
`

**Comment by jurajplayercze** [comment] 2023-06-17 17:21
You have to use full name of item. If you hold the item you want (for example oak wood sign), you have to type it, because signs have more variants like wall sign etc. 

![image](https://github.com/SkriptLang/Skript/assets/83863655/7f81ae0c-be34-42a8-b4c0-64a5e97f5b73)

![image](https://github.com/SkriptLang/Skript/assets/83863655/f06647e2-521a-43af-85cf-457c0a6de543)

It can't put wall sign in guy, so it will set it to air instead
