### ISSUE TITLE
Location variable that are in the plots world generated by plot squared plugin failed to load

### ISSUE THREAD

**Issue by MKMMM** [SkriptLang/Skript#3955] opened 2021-05-08 15:51 UTC
**So this code works normally, but when I restarted the server it just say that it failed to load the variable**
**This is what it said in the console:**
```
[22:46:18 INFO]: [Skript] Loading variables...
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! ===!!!=== Skript variable load error ===!!!===
[22:46:18 ERROR]: #!#! Unable to load (all) variables:
[22:46:18 ERROR]: #!#! 1 variable could not be loaded!
[22:46:18 ERROR]: #!#! Affected variables: test::1
```
**This is my code:**
```
every 2 second:
  drop 1 grass block 1 meter above {test::*}

on place of grass block:
  add event-block's location to {test::*}
on break of grass block:
  remove event-block's location from {test::*}
```

**Comment by TPGamesNL** [comment] 2021-05-08 16:03
More info needed:
- Skript version (did you change it recently?)
- Server version (did you change it recently?)
- Database configuration (did you change it recently?)

**Comment by MKMMM** [comment] 2021-05-08 16:37
My skript version is 2.5.3
My server version is 1.16.5
and I didn't change or do anything about Databaase configuration

**Comment by TPGamesNL** [comment] 2021-05-08 17:16
I cannot reproduce. Did this show up once, or are you able to reproduce it again?

**Comment by ShaneBeee** [comment] 2021-05-08 19:25
1) I believe this issue has already been created. I may be wrong
2) I believe this is caused by the Plot plugin loading AFTER Skript, therefor the plot world has not loaded yet, and the variable therefor can not load an unknown world/location.

**Comment by MKMMM** [comment] 2021-05-09 01:09
Yes the second one is true skript does load before the plot plugin
```
[08:05:11 INFO]: [WorldEdit] Loading WorldEdit v7.2.5+57d5ac9
[08:05:11 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89
q.worldedit.extension.platform.PlatformManager@2b2df0cf]
[08:05:11 INFO]: [Skript] Loading Skript v2.5.3
[08:05:11 INFO]: [PlotSquared] Loading PlotSquared v4.4.495
[08:05:11 INFO]: [TuSKe] Loading TuSKe v1.8.2
[08:05:11 INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:05:11 INFO]: [WorldEdit] Enabling WorldEdit v7.2.5+57d5ac9
[08:05:11 INFO]: WEPIF: Using the Bukkit Permissions API.
[08:05:11 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_16_R3 as the Bukkit adapter
[08:05:12 INFO]: [PlotSquared] Enabling PlotSquared v4.4.495
[08:05:12 INFO]: Version is PlotSquared-4.4
[08:05:12 INFO]: [P2] PlotSquared is using online UUIDs
[08:05:12 INFO]: PlotSquared Scripting Test
[08:05:12 INFO]: [P2] PlotSquared hooked into WorldEdit.
[08:05:12 INFO]: [P2] PlotSquared is now enabled
[08:05:12 INFO]: [P2] Metrics enabled.
```
Is there any way I can change the order that the plugins load?
If yes then this issue will be solved

**Comment by TPGamesNL** [comment] 2021-05-09 08:40
In that case you should edit the plugin jar (either Skript or PlotSquared) to make Skript load after PlotSquared, see https://www.spigotmc.org/wiki/plugin-yml/

**Comment by TPGamesNL** [comment] 2021-05-09 08:41
Also, duplicate of https://github.com/SkriptLang/Skript/issues/1144

**Closed by TPGamesNL** 2021-05-09 08:41 UTC
Labels: waiting for reply
