### ISSUE TITLE
Skulls doesn't work

### ISSUE THREAD

**Issue by imflitch** [SkriptLang/Skript#1736] opened 2018-12-07 13:32 UTC
When using "skull of player", it doesnt work. I tried with a variable parsed as a player and also with offline player, it doesnt work, no errors and no head?

Its when i use format slot xxxxxx in a gui.

**Comment by Pikachu920** [comment] 2018-12-07 13:35
Duplicate of #1738

**Closed** 2018-12-07 13:35 UTC
