### ISSUE TITLE
Error with loop-value in functions

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#3868] opened 2021-03-30 04:58 UTC
```vb
function getClosestNumberIndex(number: number, numbers: numbers) :: number:
	loop {_numbers::*}:
		add 1 to {_loop}
		if {_closest} is not set:
			set {_difference} to difference between loop-value and {_number}
			set {_closest} to loop-value
			set {_return} to {_loop}
			continue
		difference between {_closest} and {_number} is less than {_difference}
		set {_difference} to difference between loop-value and {_number}
		set {_closest} to loop-value
		set {_return} to {_loop}
	return {_return}
```
```
[22:55:41 ERROR]: #!#! Stack trace:
[22:55:41 ERROR]: #!#! java.lang.NullPointerException
[22:55:41 ERROR]: #!#!     at java.lang.Class.isAssignableFrom(Native Method)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:512)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:65)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1067)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:45)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:146)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:650)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[22:55:41 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[22:55:41 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:55:41 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:55:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[22:55:41 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772)
[22:55:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452)
[22:55:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
[22:55:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328)
[22:55:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116)
[22:55:41 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[22:55:41 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! Version Information:
[22:55:41 ERROR]: #!#!   Skript: 2.5.3 (latest)
[22:55:41 ERROR]: #!#!     Flavor: skriptlang-github
[22:55:41 ERROR]: #!#!     Date: 2020-12-11
[22:55:41 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[22:55:41 ERROR]: #!#!   Minecraft: 1.16.5
[22:55:41 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[22:55:41 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! Server platform: Paper
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! Current node: set {_difference} to difference between loop-value and {_number} (d.sk, line 12)
[22:55:41 ERROR]: #!#! Current item: null
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! Thread: Server thread
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! Language: english
[22:55:41 ERROR]: #!#! Link parse mode: DISABLED
[22:55:41 ERROR]: #!#!
[22:55:41 ERROR]: #!#! End of Error.
```

**Comment by TheLimeGlass** [comment] 2021-03-30 04:58
changing loop-value to loop-number fixes, but still error bad.

**Comment by TPGamesNL** [comment] 2021-03-30 07:59
Duplicate of #575 / #661 / #994 / #1001 / #2302

**Closed by TPGamesNL** 2021-03-30 07:59 UTC
