### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by hubertlagwskyyy** [SkriptLang/Skript#4301] opened 2021-08-23 09:34 UTC
### Skript/Server Version

[Skript] Severe Error:
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:21:02] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:21:02] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[11:21:02] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Stack trace:
[11:21:02] [Server thread/ERROR]: #!#! java.nio.file.FileSystemException: C:\Users\Admin\Desktop\McServers\server1.17.1\plugins\zipfstmp14712288765829386933.tmp: Proces nie mo┐e uzyskaŠ dostŕpu do pliku, poniewa┐ jest on u┐ywany przez inny proces
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.nio.file.Files.deleteIfExists(Files.java:1185)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.nio.file.Files.copy(Files.java:3132)
[11:21:02] [Server thread/ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getTempPathForEntry(ZipFileSystem.java:1132)
[11:21:02] [Server thread/ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.newFileChannel(ZipFileSystem.java:1014)
[11:21:02] [Server thread/ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipPath.newFileChannel(ZipPath.java:872)
[11:21:02] [Server thread/ERROR]: #!#!     at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileChannel(ZipFileSystemProvider.java:254)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.config.Config.<init>(Config.java:117)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:497)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:481)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:474)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:439)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.aliases.Aliases.load(Aliases.java:395)
[11:21:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:434)
[11:21:02] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:21:02] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[11:21:02] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[11:21:02] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511)
[11:21:02] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425)
[11:21:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619)
[11:21:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
[11:21:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
[11:21:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[11:21:02] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Version Information:
[11:21:02] [Server thread/ERROR]: #!#!   Skript: 2.6-beta2
[11:21:02] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:21:02] [Server thread/ERROR]: #!#!     Date: 08:57:41.422360
[11:21:02] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[11:21:02] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
[11:21:02] [Server thread/ERROR]: #!#!   Java: 16.0.2 (Java HotSpot(TM) 64-Bit Server VM 16.0.2+7-67)
[11:21:02] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Server platform: Spigot
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Current node: null
[11:21:02] [Server thread/ERROR]: #!#! Current item: null
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Thread: Server thread
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! Language: english
[11:21:02] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: #!#! End of Error.
[11:21:02] [Server thread/ERROR]: #!#!
[11:21:02] [Server thread/ERROR]: Error occurred while enabling Skript v2.6-beta2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ch.njol.skript.Skript.onEnable(Skript.java:460) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: type stationary water not found
        at ch.njol.skript.aliases.Aliases.javaItemType(Aliases.java:574) ~[?:?]
        at ch.njol.skript.classes.data.BukkitEventValues.<clinit>(BukkitEventValues.java:319) ~[?:?]
        ... 11 more
[11:21:02] [Server thread/INFO]: [ShopChest] Enabling ShopChest v1.13-SNAPSHOT
[11:21:02] [Server thread/WARN]: [ShopChest] Server version not officially supported: v1_17_R1!
[11:21:02] [Server thread/WARN]: [ShopChest] Plugin may still work, but more errors are expected!
[11:21:02] [ForkJoinPool.commonPool-worker-19/INFO]: [Skript] You're currently running the latest stable version of Skript.

### Bug Description

prosze pomozcie

### Expected Behavior

qe

### Steps to Reproduce

qe

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```
qe

### Other

qe

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-08-23 09:39
Duplicate of https://github.com/SkriptLang/Skript/issues/3124

**Closed by TPGamesNL** 2021-08-23 09:39 UTC
