### ISSUE TITLE
On Drop not working!

### ISSUE THREAD

**Issue by XfedeX** [SkriptLang/Skript#3883] opened 2021-04-07 15:09 UTC
### Description
This is my simple and small code:
```
on drop:
	send "debug drop"
every 1 second:
	broadcast "Skript works but not the Drop event!"
```

It gives no error but it doesnt run!
### Steps to reproduce
Make a new skript and paste the code in it.
Reload skripts.
### Skript version
latest.
### Skript addons:
SkQuery
ThatPackedAddon
### Server version
Paper 1.16.5

**Comment by TheDGOfficial** [comment] 2021-04-07 15:14
Write actual version number from /version Skript, not latest. Together with a Paper build number if needed. I can't test or confirm this right now but do you tried it with broadcast instead of send? Broadcast should be used generally when debugging because it sends to console, all players, and such. Not just the event-player or all players.

Try without add-ons too and restart the server. I guess something like this just can't be missed, the 2.5.3 is months old; though that can be a bad thing it is also a good thing, i.e. it is stable. If this started happening now, it can be caused by changes to Paper/Spigot or such.

**Comment by ShaneBeee** [comment] 2021-04-07 18:35
also try `send "debug drop" to player`
I believe in some events where an entity is present, Skript tries to send the message to the entity, and not to the player.

**Comment by TPGamesNL** [comment] 2021-04-08 08:28
Duplicate of https://github.com/SkriptLang/Skript/issues/3883

**Closed by TPGamesNL** 2021-04-08 08:28 UTC
