### ISSUE TITLE
BUG: Item type parse effect does not work

### ISSUE THREAD

**Issue by CHarcoalToast** [SkriptLang/Skript#1850] opened 2019-01-26 20:07 UTC
### Description
When you use the effect command `!give yellow glass pane to player`, it gives you a yellow glass pane.
But if you use `!give "yellow glass pane" parsed as item to player`, it gives a white glass pane. This issue is exactly the same with every color, and other items with different data values like dyes.
Also only happens when I upgraded from 2.2-dev37c to latest 2.3.2 release.

### Expected Behavior
To fix this issue ASAP

### Errors / Screenshots
See attached files
![bugskript](https://user-images.githubusercontent.com/38397639/51792205-5411f580-21ae-11e9-8e4b-b2cf83efd7ae.PNG)

### Server Information
* **Server version/platform:**       1.11.2
* **Skript version:**                2.3.2 (latest release)

**Comment by BlightedBlue** [comment] 2019-01-26 20:21
Works fine in 1.13.2. Seems to be an issue with aliases between server versions?

**Comment by TheBentoBox** [comment] 2019-01-26 20:52
If doing it without parsing gives the correct item then the alias correct. It's probably the parsing expression not handling data values appropriately. There are a number of known issues with versions below 1.13 essentially ignoring data values on aliases.

**Comment by TheBentoBox** [comment] 2019-01-26 20:52
I'm also marking as medium prio because these data value bugs can be pretty problematic with no great way to work around them. This is not an issue on 1.13.

**Comment by CHarcoalToast** [comment] 2019-01-26 21:10
Yeah I'm working with skript-yaml, so I have to use that parse expression. Hopefully this gets fixed soon...

**Comment by Snow-Pyon** [comment] 2019-01-27 02:48
The issue isn't with the parse expression itself since it doesn't do anything special to modify items. This is just an alias issue with 1.12, so, probably a duplicate.

And for the record, `To fix this issue ASAP` isn't an expected behavior.

**Comment by Snow-Pyon** [comment] 2019-01-27 03:56
The thing is that you shouldn't be allowed to parse as material/itemstack at all, as only itemtype is used in Skript. We might have to talk about removing the type so this kind of issues don't happen.

**Comment by Snow-Pyon** [comment] 2019-01-27 13:00
> That seems like an explanation to many issues I've had in the past, I'd say have Skript warn users about parsing as item but not necessarily remove it.

What I meant is that `"whatever" parsed as item` should try to parse it as an itemtype and not an itemstsack, it is currently not that way and thus, that kind of issues happen.

**Closed** 2019-02-03 11:56 UTC
Labels: bug, completed, priority: medium
