### ISSUE TITLE
(Bug) False negatives when player's tool is air/not set

### ISSUE THREAD

**Issue by MovesLikeJaeger** [SkriptLang/Skript#4407] opened 2021-11-04 03:51 UTC
### Skript/Server Version

Skript 2.6 (Official Release)
Paper 1.17

### Bug Description

![image](https://user-images.githubusercontent.com/75779721/140254685-c788fcb5-fc52-4617-a669-a8b4c8b53da5.png)

Same thing happens with *if player's tool is set/not set*
The photo shows everything ya need to know :D

### Expected Behavior

Definitely something funky going on here (This may be related to my last opened issue, but I figured it was still worth mentioning as it is considerably different).

### Steps to Reproduce

N/A

### Errors or Screenshots

N/A

### Other

Worth mentioning that this may be related to #4403 

Thanks for all your work guys!

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-11-04 08:55
I don't see the issue, assuming you're holding dirt for all the effect commands
![image](https://user-images.githubusercontent.com/29547183/140285295-06077e25-3844-4f46-b200-55b9dcb49d47.png)

**Comment by MovesLikeJaeger** [comment] 2021-11-04 08:58
The one you circled wouldn't have broadcasted if the players hand was air, but it did. 
Sorry for the confusion, I could have explaimed better

> I don't see the issue, assuming you're holding dirt for all the effect commands ![image](https://user-images.githubusercontent.com/29547183/140285295-06077e25-3844-4f46-b200-55b9dcb49d47.png)

**Comment by TPGamesNL** [comment] 2021-11-04 10:57
I can confirm in 2.6, but not on the master branch, so this was most likely fixed in https://github.com/SkriptLang/Skript/pull/4162

**Comment by MovesLikeJaeger** [comment] 2021-11-04 11:09
> I can confirm in 2.6, but not on the master branch, so this was most likely fixed in #4162
> 
> PS, `player's tool is set` always returns true, whether you're holding air or not

Good to hear. Thanks. 

I also meant
if player's tool is not set
As that would not pass condition when holding nothing. I'd assume that's also fixed with the issue you mentioned though?

**Comment by TPGamesNL** [comment] 2021-11-04 11:10
No, that's intended, because you're holding air

**Closed** 2022-01-26 05:29 UTC
Labels: bug, completed
