### ISSUE TITLE
Skript's clickable Chat Command leads to server kick

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#3594] opened 2020-12-01 14:53 UTC
Getting kicked when clicking on chat to execute a command (see example below)

### Steps to Reproduce
Skript code:
send formatted "<command:/broadcast &6TEST&7!!!>CLICK" to player

### Expected Behavior
Not being kicked from the server

### Errors / Screenshots
Kicked from server (Illegal character in chat)
https://i.imgur.com/uwRBDO7.png

### Server Information
* **Server version/platform:** This server is running Tuinity version git-Tuinity-"957a2ef" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
* **Skript version:** Skript: 2.5.2 (latest)

**Comment by Pikachu920** [comment] 2020-12-01 21:25
I think this is because the client is actually sending §6 and not &6 and I believe Spigot considers § to be an illegal character. Does it work if you remove the color codes? Not sure how to workaround/fix this one without editing the code for the broadcast command.

**Comment by juradev** [comment] 2020-12-02 13:47
> I think this is because the client is actually sending §6 and not &6 and I believe Spigot considers § to be an illegal character. Does it work if you remove the color codes? Not sure how to workaround/fix this one without editing the code for the broadcast command.

It works if I remove the color codes. But it does not matter which command I use there. As soon as there are color codes, it kicks me from the server.

**Comment by bloggy** [comment] 2020-12-02 13:48
It works if I remove the color codes. But it does not matter which command I use there. As soon as there are color codes, it kicks me from the server.

**Comment by Pikachu920** [comment] 2020-12-02 18:40
what happens if you don't send it formatted?

**Comment by bloggy** [comment] 2020-12-07 13:06
without the formated it will just write the command syntax in the chat (instead of replacing it with a clickable command)

**Comment by bloggy** [comment] 2021-01-28 14:58
What about this issue? It literally breaks the clickable chat stuff in skript.

**Comment by TheLimeGlass** [comment] 2023-08-03 06:34
@bloggy Cannot replicate anymore. Is this still valid? This may be because of third party server software.

**Comment by Moderocky** [comment] 2024-04-13 07:04
I'm going to close this, since there has been no more input on it.
I'm almost certain the cause was the colour codes used in the tooltip are being evaluated to the illegal `§` character that the client isn't permitted to send, but this isn't something we're really able to do anything about.

**Closed by Moderocky** 2024-04-13 07:04 UTC
Labels: cannot reproduce, server issue
