### ISSUE TITLE
1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1542))

### ISSUE THREAD

**Issue by Brok3nmindd** [SkriptLang/Skript#3574] opened 2020-11-27 10:26 UTC
[Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1500)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

**Comment by ShaneBeee** [comment] 2020-11-27 10:28
Closing for 2 reasons:

1) You deleted the issue template, so there is no viable information here.

2) This error is generally caused by running an outdated version of Skript-mirror. Please upgrade to either Skript-mirror 2.0.0 or Skript-reflect (a maintained and updated fork of Skript-mirror)

**Closed by ShaneBeee** 2020-11-27 10:28 UTC
