### ISSUE TITLE
ExprEntity not being considered a default expression

### ISSUE THREAD

**Issue by Eryk1983S** [SkriptLang/Skript#1182] opened 2018-04-10 18:45 UTC
**Engine:** Spigot 1.12.2.-R.0.1-SNAPSHOT
**Skript-Version:** 2.2. dev34

**Problem:**
Error: "the level of the player does not have a past state"

**Used script:**
_on level change:
	player's level after is bigger than player's level before
	send "Control-message: Your experience level has increased" to the player_

**Description:**
I want to block the possibility of gaining level under some conditions (these make no problems). The manual (https://bensku.github.io/Skript/expressions.html#ExprTimeState) says, I should use the expression "Former/Future State", that is meant to use expecially for the event "on level change" (see the link). The expression "player's level" seems to be correct (https://bensku.github.io/Skript/expressions.html#ExprLevel). And the error-message says clearly, that the level hasn't a past state, but according to the manual it should have.

**Request:**
Please fix the bug or tell me, if I do something wrong.

**Comment by TheLimeGlass** [comment] 2018-04-11 13:24
Past/Future states are really something that should be re-written. They hardly work well and could be really beneficial when in use. Also I don't think Addon developers can use it as I tried before and they wern't working correctly, and I don't think anyone aside from Njol in Skript actually properly use them due to this. I made an issue about this a long time ago https://github.com/bensku/Skript/issues/671

**Comment by TheBentoBox** [comment] 2018-04-11 15:41
Not sure whether to label as bug or enhancement but I can confirm that I've never really had any luck with using past/future states in most scenarios and as such it has never seemed like they work properly. They could probably use a revisit/refactor at some point.

**Comment by TheLimeGlass** [comment] 2018-04-11 15:43
This one is an enhancement to the player level past state, but I think past/future states only work for event-values as that's the only part where it's visible, expressions have the setTime() but it's never used.

https://github.com/bensku/Skript/issues/671 is the bugged information about this issue I feel.

**Comment by Snow-Pyon** [comment] 2018-07-15 08:38
Okay, after digging up a bit, found out that the reason why `future level of player` doesn't work is that `player` isn't marked as default expression (ExprEntity) but `future level of event-player` works because it is a default expression (ExprEventExpression). 

Overriding `isDefault` in `ExprEntity` and returning true should be good enough to fix it.

**Closed** 2018-07-16 16:12 UTC
Labels: bug, priority: low
