### ISSUE TITLE
RedstoneOre Unrecognizable 

### ISSUE THREAD

**Issue by Sodies** [SkriptLang/Skript#2083] opened 2019-05-21 07:32 UTC
### Description
Redstone Ore unrecognize in the latest version of skript

### Steps to Reproduce
```
on break:
  if event-block is redstone ore:
    send "hi"
```
no error but doesn't work

### Expected Behavior
it'

### Server Information
1.12.2            1.12.2
2.3.6 Skript

**Comment by TheBentoBox** [comment] 2019-05-21 13:11
Duplicate of #1974 which should already be fixed in the 2.4 alpha releases.

**Closed by TheBentoBox** 2019-05-21 13:11 UTC
