### ISSUE TITLE
Call to getSingle() on a non-single expression in EffPlaySound

### ISSUE THREAD

**Issue by waiching514** [SkriptLang/Skript#1876] opened 2019-02-06 00:05 UTC
remove item from player hand not work

> on rightclick:
> 	if the name of the tool of the player contains "&7$500":
> 		execute console command "/eco give %player% 500"
> 		remove 1 paper from the player's tool

on any movement error: https://pastebin.com/CP9XAfwj   

>on any movement:
> 	player's world is "RPG":
> 		if "%region at player%" contains "rpgtpspawn":
> 			teleport the player to the world's spawn point

* **Skript version: 2.3.3**           
* **server version: spigot 1.13.2**

**Comment by DevilishDante** [comment] 2019-02-06 08:02
mhhh why in ur error link there are
[ERROR] #!#! Version Information: 
[ERROR] #!#! Skript: 2.3.2
and not 2.3.3 :o

**Comment by BlightedBlue** [comment] 2019-02-06 09:20
> mhhh why in ur error link there are
> [ERROR] #!#! Version Information:
> [ERROR] #!#! Skript: 2.3.2
> and not 2.3.3 :o

2.3.3 shows up as 2.3.2 inside the server.
You didn't give us the actual play sound line, which is causing your issue in the first place.

Couldn't replicate "not work" with removing paper from player's tool. Works fine in Spigot 1.13.2, Skript 2.3.1

I request this issue be closed as there is seemingly nothing wrong, and the stacktrace seems to have nothing to do with Skript in itself. (You're using skRayFall, which is overriding your play sound effect.

**Comment by bensku** [comment] 2019-02-08 19:50
We need a script that can be used to reproduce this without addons.

**Comment by Blueyescat** [comment] 2019-03-03 14:22
No response and probably duplicate of https://github.com/SkriptLang/Skript/issues/1812.

**Closed** 2019-06-09 18:53 UTC
Labels: needs more info
