### ISSUE TITLE
Leftclick and Drop events trigger Bug

### ISSUE THREAD

**Issue by TeddyC400** [SkriptLang/Skript#2731] opened 2019-12-28 21:00 UTC
### Description
When using "on leftclick" and "on drop" events, they both trigger if you attempt to drop an item while facing the air/sky.

### Steps to Reproduce
Write a simple code like the following:
```
on leftclick:
	broadcast "leftclick"

on drop:
	broadcast "drop"
```

Hold an item then drop it WHILE facing the air/sky. You will notice that both events are triggered. Only the "on drop" event gets triggered if the user faces the block.

### Expected Behavior
The code should have only triggered the "on drop" event if dropping an item, regardless if the user is facing the air or anything else.

### Errors / Screenshots
No errors.

### Server Information
* **Server version/platform:**       Spigot 1.15.1
* **Skript version:**                2.4.1

### Additional Context
Either this is a Bukkit/Spigot bug or something happened with the Skript internal code itself.

**Comment by nopeless** [comment] 2019-12-30 09:16
using
paper 1.14.4 186
plugins
Skript, Sk-NBeet, skript-mirror, worldedit-bukkit-7.0.1, worldguard-bukkit-7.0.1
code
```

on drop:
	broadcast "drop"
on leftclick:
	broadcast "leftclick"```
the behavior does not happen to me

**Comment by WhiteC4** [comment] 2019-12-31 02:25
> using
> paper 1.14.4 186
> plugins
> Skript, Sk-NBeet, skript-mirror, worldedit-bukkit-7.0.1, worldguard-bukkit-7.0.1
> code
> 
> ```
> 
> on drop:
> 	broadcast "drop"
> on leftclick:
> 	broadcast "leftclick"
> ```
> 
> the behavior does not happen to me

Seems like it's because you're using paper spigot, not default spigot. Going to edit my post to clarify that I am using default spigot for the server.

**Comment by Wealthyturtle** [comment] 2019-12-31 14:12
> > using
> > paper 1.14.4 186
> > plugins
> > Skript, Sk-NBeet, skript-mirror, worldedit-bukkit-7.0.1, worldguard-bukkit-7.0.1
> > code
> > ```
> > 
> > on drop:
> > 	broadcast "drop"
> > on leftclick:
> > 	broadcast "leftclick"
> > ```
> > 
> > 
> > the behavior does not happen to me
> 
> Seems like it's because you're using paper spigot, not default spigot. Going to edit my post to clarify that I am using default spigot for the server.

Can you replicate this issue in Spigot 1.14.4 or Paper 1.14.4? If you can't then it's very likely a Spigot issue in 1.15.1

**Comment by ShaneBeee** [comment] 2020-01-03 08:59
This is 100% a Spigot/CB issue. 
I have reported it to Spigot, hopefully they will fix it soon.

**Comment by ShaneBeee** [comment] 2020-01-04 06:55
Ok so update:
- Reported this to SpigotMC. md_5 quickly closed it and marked it as a duplicate of another issues.

Long story short, Bukkit's playerInteractEvent for LEFT_CLICK_AIR is just a hacky way of listening to the arm swing packet. Since 1.15 added arm swing animations for a lot of things (including dropping an item) that is why the click event is getting called. Im sure we can try find a hacky way to fix this, but its going to take a bit of work.

**Comment by bensku** [comment] 2020-01-11 17:19
@ShaneBeee Could you link the issue you made here for reference?

**Comment by ShaneBeee** [comment] 2020-01-11 20:40
This is the issue I created:
https://hub.spigotmc.org/jira/browse/PLUG-370?filter=-2

Which was closed and referenced as a duplicate of:
https://hub.spigotmc.org/jira/browse/SPIGOT-5435

Which was closed and marked as invalid

**Comment by TheLimeGlass** [comment] 2023-05-05 05:29
Cannot replicate

**Comment by TheLimeGlass** [comment] 2023-05-05 07:43
We can't even fix this for legacy versions. Closing this.

**Closed by TheLimeGlass** 2023-05-05 07:43 UTC
Labels: enhancement, priority: lowest, server issue, legacy versions
