### ISSUE TITLE
on spawn event throws console error

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#3522] opened 2020-11-06 13:22 UTC
### Description
Console error:
https://pastebin.com/2UvWVv5p

### Steps to Reproduce
Script:
```
on spawn:
	if "%spawning reason%" contains "drowned":
		cancel event
	if event-entity is drowned:
		if spawn reason is natural:
			cancel event
```

### Expected Behavior
No error  (works in 1.15.2)

### Server Information
This server is running Tuinity version git-Tuinity-"083e162" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[Skript] Loading Skript v2.5.1

**Comment by ShaneBeee** [comment] 2020-11-06 13:26
Duplicate of #3499

**Closed by ShaneBeee** 2020-11-06 13:26 UTC
