### ISSUE TITLE
Parsing block state error on startup

### ISSUE THREAD

**Issue by GapiCer** [SkriptLang/Skript#4097] opened 2021-06-22 11:45 UTC
### Description
Every time on startup this error is shown: https://pastebin.com/NQ46tkJT

### Steps to Reproduce
I'm using paper 31 1.17, removed all plugins besides Skript and SkQuery and this happens.

### Expected Behavior
Hopefully no errors on startup

### Errors / Screenshots
https://pastebin.com/NQ46tkJT

### Server Information
Paper version git-Paper-"ae95311" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
* **Skript version:** Skript version 2.5.3

### Additional Context
Not a big deal since it works perfectly otherwise, just thought I should post this here. Great plugin btw.

**Comment by TPGamesNL** [comment] 2021-06-22 11:48
Duplicate of https://github.com/SkriptLang/Skript/issues/4082

**Closed by TPGamesNL** 2021-06-22 11:48 UTC
