### ISSUE TITLE
Bug with Item Types

### ISSUE THREAD

**Issue by bloggy** [SkriptLang/Skript#2983] opened 2020-05-14 14:14 UTC
the event-block in this script is a sign next to a default chest...

```
		loop blocks in radius 1 around event-block:
			broadcast "1) %type of loop-value%"

```

**output is:**
air
air
westward chest

But it should be:
air
air
chest

Because "westward chest" is not a valid spigot item type.
- Loading Skript v2.5-alpha3

**Comment by ShaneBeee** [comment] 2020-05-14 19:44
> Because "westward chest" is not a valid spigot item type.

it has nothing to do with Spigot, its a Skript alias.

**Comment by ShaneBeee** [comment] 2020-05-14 21:37
Closing this as I see no issue here. It appears to be working as intended.

**Closed by ShaneBeee** 2020-05-14 21:37 UTC
