### ISSUE TITLE
Difference expression not working with literals since the latest version

### ISSUE THREAD

**Issue by khlfkk** [SkriptLang/Skript#1201] opened 2018-04-20 20:42 UTC
```
#
# This script is a template for commands which have a cooldown.
# I will add a more intuitive way of handling cooldowns/countdowns in the future,
# But for now please use something like this.
# Make sure that you do not use delays for cooldowns as they stop when the server stops.
#

# This command allows each player to get infinite cakes
# but the command has a cooldown of one minute (per player)
command /cake:
	description: Recieve a cake, but you can only do this once per minute!
	permission: cake.is_a_lie
	executable by: players
	trigger:
		# stores how long it's been since the player last used this command
		set {_waited} to difference between {cake.%player%.lastused} and now
		# checks whether the player has used the command within the last minute
		if {_waited} is less than a minute:
			message "You have to wait %difference between a minute and {_waited}% before you can use this command again!"
			stop
		
		# some condition which sould not start the cooldown
		# (if the player doesn't get the cake he should be able to use the command again immediately)
		player doesn't have space for a cake:
			message "You do not have enough space in your inventory to hold the cake!"
			stop
			
		# do the action of the command
		give a cake to the player
		
		# and finally start the cooldown
		set {cake.%player%.lastused} to now
```

The demo skript is getting fail in Dev 35 build. 
Error image: https://i.imgur.com/mdnT4hU.png

**Comment by Pikachu920** [comment] 2018-04-20 23:13
The demo scripts should be rewritten anyways. they're not actually good examples.

**Comment by Snow-Pyon** [comment] 2018-04-21 01:02
@Pikachu920 is correct. There is even a rather new cooldown system that was implemented, making that example kind of pointless (the example is fine since that's the way you do cooldowns for other things, but having it in a command is just pointless with what I already said above).

**Comment by khlfkk** [comment] 2018-04-21 13:49
if there have a new tech for cooldown in script will be great .

**Comment by HYPExMon5ter** [comment] 2018-04-21 13:55
Might rewrite a few of the example scripts tonight.

**Comment by khlfkk** [comment] 2018-04-21 14:00
@HYPExMon5ter thanks for your support, i can use Dev 35 to test since most of my script with cooldown and all broken so far

**Comment by Blueyescat** [comment] 2018-04-22 07:30
You should see the issue before that ^^

The difference expression doesn't work when you enter timespans as literals on dev35.

Can't understand:
```vb
difference between 2 seconds and 1 minute
difference between (2 seconds) and (1 minute)
difference between 2 seconds and {_timespan}
```
Works:
```vb
difference between {_timespan1} and {_timespan2}
```

**Comment by khlfkk** [comment] 2018-04-22 13:07
@Blueyescat how to store the command cooldown to SQLite/CSV?

**Comment by TheBentoBox** [comment] 2018-04-22 18:16
The example scripts not working is definitely not a good look and is important to people learning how to use Skript for the first time. There is now a PR open which updates the example scripts so this should be fixed in the next release.

**Comment by khlfkk** [comment] 2018-04-22 18:24
@TheBentoBox Thanks for support, yup, we will wait the next month release .

**Comment by TheBentoBox** [comment] 2018-05-02 02:09
Also just want to note that I can confirm this on my test server using the latest release and it's a fairly serious issue. Makes using `difference between` in many ways you'd normally want to impossible. Should definitely be prioritized for next release (perhaps a bugfix release as dev35c along with anything else high priority such as the function type safety Pika just reported).

**Comment by TheLimeGlass** [comment] 2018-05-03 08:30
Referencing a similar issue https://github.com/bensku/Skript/issues/575

**Comment by bensku** [comment] 2018-09-05 14:42
The script in original post appears to be working now.

**Closed by bensku** 2018-09-05 14:42 UTC
Labels: bug, priority: medium
