### ISSUE TITLE
Update inventory effect

### ISSUE THREAD

**Issue by kill05** [SkriptLang/Skript#3755] opened 2021-02-16 16:23 UTC
Hi, in some cases, because of problems with bukkit/spigot, inventory doesn't update correctly. In my case it was a problem with setting the result slot. With skript-mirror I've used player.updateInventory() and it worked fine, but I thought it could be useful on vanilla skript.

Details on the method can be found here (last one on the list):
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html

Thanks for reading!

**Comment by TheDGOfficial** [comment] 2021-02-16 21:34
Yes, several addons provide this but if they don’t use
PlayerUtils#updateInventory(Player) method, it will be somewhat buggy.

It can be added to vanilla Skript, you right.

**Comment by TPGamesNL** [comment] 2021-03-27 09:51
@kill05 Could you provide in which scenario you require this effect, since Skript should do this automatically

**Comment by Wafffidooe** [comment] 2021-03-27 17:16
(I know I wasn't the one asked... but)
I think this would be useful when having displayed timers in GUIs... they don't update automatically unless the inventory is reopened

**Comment by TPGamesNL** [comment] 2021-03-27 17:25
> (I know I wasn't the one asked... but)
> I think this would be useful when having displayed timers in GUIs... they don't update automatically unless the inventory is reopened

@Wafffidooe Can you show the code for this so we can try to reproduce this?

**Comment by Wafffidooe** [comment] 2021-03-27 18:17
My 1.12.2 FTP server is down at the moment. But I recall experiencing that the inventory wouldn't update unless reopened. Since it's down, I was only able to bring you a code from my server's 1.8 "lifetime"... but it's practically the same code I use on 1.12.2 (just a bit downgraded). Here you go:
`function rewardstimeformat(p: player, n: number, m: number, t: text):
	set {_dr%{_n}%} to difference between {dr%{_n}%claimed::%{_p}%} and now 
	set {_dr%{_n}%remaining} to "%difference between {_dr%{_n}%} and 86400 seconds%" parsed as timespan
	set {_formatteddr%{_n}%} to "%{_dr%{_n}%remaining}%"
	replace all "hours" and "hour" with "t" in {_formatteddr%{_n}%}
	replace all "minutes" and "minute" with "m" in {_formatteddr%{_n}%}
	replace all "seconds" and "second" with "s" in {_formatteddr%{_n}%}
	replace all "and" with "og" in {_formatteddr%{_n}%}
	replace all "day" with "dag" in {_formatteddr%{_n}%}
	if difference between {dr%{_n}%claimed::%{_p}%} and now is less than 86400 seconds:
		set slot {_m} of {_p}'s current inventory to minecart item named "&cDaglig BelÃ¸nning" with lore "&cDu har allerede taget denne belÃ¸nning!||&cDu kan tage denne belÃ¸ning igen om:||&c%{_formatteddr%{_n}%}%"
	else:
		set slot {_m} of {_p}'s current inventory to storage minecart named "&aDaglig BelÃ¸nning %{_t}%" with lore "||&7Gratis daglig belÃ¸nning!||||&eKlik her for at tage denne belÃ¸nning."

function RewardsGUI(p: player):
	open chest with 4 rows named "&8The Delivery Man" to {_p}
	set slots (integers from 0 to 9) of {_p}'s current inventory to gray glass pane named "&7"
	set slots (integers from 17 to 18) of {_p}'s current inventory to gray glass pane named "&7"
	set slots (integers from 26 to 35) of {_p}'s current inventory to gray glass pane named "&7"
	set slot 31 of {_p}'s current inventory to arrow named "&aLuk Menuen"
	rewardstimeformat({_p}, 1, 10, "")
	if {_p} has permission "Vip", "Vip+", "Mvp", "Mvp+", "Mvp++" or "Other":
		rewardstimeformat({_p}, 2, 11, "&a[VIP]")
	else:
		set slot 11 of {_p}'s current inventory to minecart named "&aDaglig BelÃ¸nning &a[VIP]" with lore "||&7Gratis daglig belÃ¸nning!||||&eKræver &a[VIP]&e."
	if {_p} has permission "Vip+", "Mvp", "Mvp+", "Mvp++" or "Other":
		rewardstimeformat({_p}, 3, 12, "&a[VIP&c+&a]")
	else:
		set slot 12 of {_p}'s current inventory to minecart named "&aDaglig BelÃ¸nning &a[VIP&c+&a]" with lore "||&7Gratis daglig belÃ¸nning!||||&eKræver &a[VIP&c+&a]&e."

function reward(p: player, n: number):
	wait 3 ticks
	set {_dr%{_n}%} to difference between {dr%{_n}%claimed::%{_p}%} and now 
	if {_dr%{_n}%} is less than 86400 seconds:
		stop
	send "&aDu har modtaget din daglige belÃ¸nning!" to {_p}
	set {_dailyreward} to a random integer between 1 and 3
	if {_dailyreward} is 1:
		give {_p} 1 raw fish
	if {_dailyreward} is 2:
		give {_p} 1 cooked fish
	if {_dailyreward} is 3:
		give {_p} 1 clownfish
	set {dr%{_n}%claimed::%{_p}%} to now
	close {_p}'s inventory
	wait 2 ticks
	RewardsGUI({_p})`
	(I'm not sure if it's copying the code correctly... haven't really used this code-box as much here on Github)

**Comment by TPGamesNL** [comment] 2021-03-28 09:35
I cannot reproduce it with that code (I ran `RewardsGUI(me)`, worked fine)

**Comment by Wafffidooe** [comment] 2021-03-28 09:50
Did you try on a 1.12.2 server too? Weird...

**Comment by TPGamesNL** [comment] 2021-03-28 10:25
Just tried that too, couldn't replicate on there either

**Comment by Wafffidooe** [comment] 2021-03-28 10:41
I don't know if it could mean anything that I use Spigot and not PaperSpigot..

**Comment by TPGamesNL** [comment] 2021-03-28 11:00
Still cannot replicate it with that

**Comment by TPGamesNL** [comment] 2021-03-30 08:04
@Wafffidooe and I resolved his issue in DMs, but it wasn't related to this issue

**Comment by TPGamesNL** [comment] 2021-05-10 07:47
Closing, see https://github.com/SkriptLang/Skript/pull/3856#issuecomment-836313928

**Closed by TPGamesNL** 2021-05-10 07:47 UTC
Labels: PR Available, enhancement, priority: low
