### ISSUE TITLE
On break of wheat and skull. Extreme error in aliases /:

### ISSUE THREAD

**Issue by INTmAker** [SkriptLang/Skript#2408] opened 2019-08-31 09:14 UTC
### Description
Wrong aliases "all wheat stages" and "skull item"!

### Code used for debug
`
on break:
	send "%event-block%"
`
### Expected Behavior
It should say "skull item" not "SKULL" same with wheat it should say "ripe wheat" not "CROPS"

### Errors / Screenshots
No console errors. 
![image](https://user-images.githubusercontent.com/52136414/64061854-4018f100-cbe0-11e9-83d0-ce96c9aadae9.png)

### Server Information
* **Server version/platform: Spigot 1.12.2**       
* **Skript version: 2.4-beta5**

**Comment by INTmAker** [comment] 2019-08-31 09:15
Thank me later developers Xd.

**Comment by TPGamesNL** [comment] 2019-08-31 09:31
Duplicate of https://github.com/SkriptLang/Skript/issues/2394

**Comment by TheBentoBox** [comment] 2019-08-31 21:08
> Thank me later developers Xd.

Not only is this a duplicate, but it's a duplicate of your own bug report...

**Closed by TheBentoBox** 2019-08-31 21:08 UTC

**Comment by INTmAker** [comment] 2019-09-02 20:05
when will they fix your mistake. And it's not a duplicate because it's a different version of the script!

**Comment by ShaneBeee** [comment] 2019-09-02 20:57
Different Skript versions do no matter, not only is this a duplicate of #2394 which you made, its also a duplicate of another issue you made #2294 

These same 3 issues you created are also the same as #2244, #1990 
I believe there are a few more issues all related to this same bug, its a bug in Skript for 1.9->1.12.2 where the aliases are not matching properly to some materials in the materials.json file.

**Comment by TheBentoBox** [comment] 2019-09-02 21:47
Thanks for the list Shane, I've updated #2394 to be a bit more descriptive of the problem (via a better title and a comment from me) and will close the others in favor of that one.

**Comment by ShaneBeee** [comment] 2019-09-02 21:50
> Thanks for the list Shane, I've updated #2394 to be a bit more descriptive of the problem (via a better title and a comment from me) and will close the others in favor of that one.

You're welcome, and thank you for updating that 👍
