### ISSUE TITLE
Flipped Boolean Expression

### ISSUE THREAD

**Issue by lostsucks** [SkriptLang/Skript#7039] opened 2024-09-05 16:12 UTC
### Suggestion

It would be pretty useful to add syntax in which you can flip a boolean. 
The expression would be: `(!|flipped )%boolean%`
It could also be used as an effect: `flip %boolean%`

Example: `set player's fly state to !player's fly state`

### Why?

This feature would greatly help some people & help with compressing some scripts! 
I personally made this in my own addon and it helped compress some scripts.

### Other

It's based off the Java syntax, in which you can for example do `if (!message.exists) { return null; }` (if message does not exist, return null)

I'm not sure if this exists in skript-reflect but either way it would be pretty useful.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by APickledWalrus** [comment] 2024-09-05 16:13
Handled in a more Skript-friendly way in https://github.com/SkriptLang/Skript/pull/4154

**Comment by Moderocky** [comment] 2024-09-05 16:14
Duplicate of #5386, we also have `not ...`

**Closed by Moderocky** 2024-09-05 16:14 UTC
Labels: enhancement, PR available
