### ISSUE TITLE
On right click:

### ISSUE THREAD

**Issue by EazyFTW** [SkriptLang/Skript#988] opened 2017-11-28 23:23 UTC
Description: On right click is not working with entities.
Addons: I have the basic ones, but it happens w/ out any addons.
Errors: None.
MC Version: 1.12.2/1.12
Sample Code:

```
on rightclick on an armor stand:
    send "%clicked entity%"
```
```
on rightclick on an entity:
    send "%clicked entity%"
```

```
on rightclick:
    send "%clicked entity%"
```

**Comment by pattonga** [comment] 2017-12-01 12:50
Hmm try

on rightclick:
    Victim “entity”
    send “%clicked entity%”

I am not used to English translation you may need to add a little bit to the victim line but should work

**Comment by EazyFTW** [comment] 2017-12-01 16:12
You don't get it. Right clicking doesn't detect the entity.

**Comment by melinstagibson** [comment] 2017-12-01 16:25
code?

Am 01.12.2017 17:12 schrieb "EazyFTW" <notifications@github.com>:

**Comment by melinstagibson** [comment] 2017-12-01 16:28
did you try to broadcast it instead?

also target entity should work as workaround

**Comment by EazyFTW** [comment] 2017-12-01 16:30
Broadcasting does nothing.

**Comment by EazyFTW** [comment] 2017-12-01 16:30
Because it doesn't detect the entity. It cancels the event on right click.

**Comment by EazyFTW** [comment] 2017-12-01 16:30
Because there is no block and no entity so it doesn't trigger.

**Comment by bensku** [comment] 2017-12-02 10:45
Click events on armor stands are not supported at the moment. I tried adding them at one point, but events were still not reliably fired by Spigot. Maybe I'll try again at some point...

**Comment by EazyFTW** [comment] 2017-12-02 16:05
It's not just armor stands. It didn't work on Villagers and other mobs I tried.

**Comment by bensku** [comment] 2017-12-02 21:57
Oh. That is weird. Are you running Paper or Spigot?

**Comment by EazyFTW** [comment] 2017-12-02 21:57
Spigot, MC 1.12.

**Comment by Pikachu920** [comment] 2017-12-03 01:40
I also tested this and can confirm the issue

**Comment by MisterBasic** [comment] 2017-12-03 06:37
maybe try target entity:

```
on right click:
    send "%target entity%"
```

**Comment by xXAndrew28Xx** [comment] 2017-12-10 16:09
Can not reproduce with a villager
![image](https://user-images.githubusercontent.com/9660418/33806749-33a9daee-dd92-11e7-84b8-f55dcc0f0d1e.png)

**Comment by Snow-Pyon** [comment] 2018-02-11 22:43
Couldn't reproduce either, closing.

**Comment by aeonlamb** [comment] 2018-10-18 00:54
This is happening on skript 2.3 beta1. "on [right] click on [any entity]" does not detect the click event. Using paper 1.13.1

**Comment by Nicofisi** [comment] 2018-10-18 05:34
What entity did you try with?

**Comment by ShaneBeee** [comment] 2018-10-18 18:51
I can confirm this.
```
on right click:
    send "&aCLICK WORKED"
```
does not get fired when clicking on any entity, including my test subjects, a sheep, a rabbit, and a villager. 
Clicking on a block works just fine, but it appears that entities aren't triggering this event.

**Comment by Nicofisi** [comment] 2018-10-18 19:10
Not sure whether we shouldn't perhaps create a separate issue but whatever lol

**Comment by ShaneBeee** [comment] 2018-10-18 19:16
I just did an update to my findings, If you dont add "to player" to the end of the message, it won't send anything.

**Comment by ShaneBeee** [comment] 2018-10-18 19:31
More findings
```
on rightclick on entity:
	send "&aTEST: %event-entity%" to player

on rightclick:
	send "&aTEST: %event-entity%" to player
```
So the first one, if I click on a sheep, it sends "Test: sheep"
The second one, if I click on a block it sends "Test: ShaneBee"
so my guess, is with the first one, if you dont send the message to the player, its trying to send the message to the sheep, and well, I can't tell if the sheep is getting the message ;)

**Comment by ShaneBeee** [comment] 2019-11-08 22:13
I just wanted to update and see where we are at with this issue?

Using Paper 1.14.4 (209) and Skript 2.4-beta9 I see no issue.

![Screen Shot 2019-11-08 at 2 11 06 PM](https://user-images.githubusercontent.com/20008482/68514131-bc0f6500-0231-11ea-9921-ed4a1f46694f.png)

As you can see in the image the code is firing when I click the armor stand.

As I mentioned in a previous comment in this thread, sending a message without defining player will not send a message to the player as it appears to be attempting to send to the event-entity. 
Im not sure if that is the issue or not here, because the actual click event itself is working, the issue is with whom we are sending the message to.

**Comment by APickledWalrus** [comment] 2020-01-01 21:24
This issue should be closed now as the actual issue is with the message effect defaulting to event-entity instead of event-player.

**Closed** 2020-01-02 01:11 UTC
