### ISSUE TITLE
Incorrect on place cancel event with item frame

### ISSUE THREAD

**Issue by Sonlein** [SkriptLang/Skript#3525] opened 2020-11-06 22:28 UTC
### Description
cancel event doesnt work correctly on item frame
unlike blocks, player doesnt get his item back
```
on place of chest:
    cancel event
```
if player placing chest, its disappear and player get his chest back
### Steps to Reproduce
```
on place of item frame:
    cancel event
```

### Expected Behavior
item frame should be returned to player

### Server Information
* **Server version/platform:** spigot 1.16.1
* **Skript version:** 2.5.1

**Comment by ShaneBeee** [comment] 2020-11-06 22:29
I recommend using the right click event, since item frames are not blocks.

**Comment by Sonlein** [comment] 2020-11-06 22:31
> I recommend using the right click event, since item frames are not blocks.

how i can detect which side of the block did the player click on to then frame it?

**Comment by ShaneBeee** [comment] 2020-11-06 22:45
Ok originally I marked this as a bug, but technically it is not a bug. 

The "on place" event actually is called for 3 different events, one of which being the hanging event. 
Based on how this works, this seems more like a Spigot issue, since the server is not giving back the player the item.
Maybe this should be reported to Spigot.

When events are cancelled, the server (ie: Spigot/Paper) handles what happens), therefor there isn't much Skript can do here.

I recommend just writing a line of code to give the player back the item.

**Comment by ShaneBeee** [comment] 2020-11-06 22:51
Update:
Tested this using a java plugin. This is indeed an issue with Spigot/Paper. Im not sure if they will consider it a bug or not.

Closing as this is not a Skript issue.

**Closed by ShaneBeee** 2020-11-06 22:51 UTC
