### ISSUE TITLE
Set list to list (set {a::*} to {b::*}) does not behave as expected

### ISSUE THREAD

**Issue by nopeless** [SkriptLang/Skript#2717] opened 2019-12-22 03:50 UTC
### Description

when setting a list variable to another list variable, (from now on, `set {a::*} to {b::*}`) the values of `{b::*}`(the order of values when you loop `{b::*}`) gets written into `{a::*}` with the index of the numerical order

this is a representation of what is happening
`clear {a::*}`
`set {_i} to 0`
`loop {b::*}:`
`    add 1 to {_i}`
`    set {a::%{_i}%} to loop-value`

what I suggest should be the case
`clear {a::*}`
`loop {b::*}:`
`    set {a::%loop-index%} to loop-value`

### Steps to Reproduce

try setting any list to a non-numerical index list

the simplest way to reproduce
`!set {a::hi} to 10`
`!set {a::*} to {a::*}`
`!send "%{a::hi}%" # returns <none>`
`!send "%{a::1}%" # returns 10`
### Expected Behavior

the targeted list should retain the indexes
### Errors / Screenshots

no errors

### Server Information
* **Server version/platform:**       1.14.4
* **Skript version:**                2.4 beta 10

### Additional Context

this is not a request for functions being able to return lists with non-numerical string indexes(a common request by people) as it is under the acceptable range of "weird feature"
but setting a list to another is very counter-intuitive and I suggest to change this behavior

**Comment by Wealthyturtle** [comment] 2019-12-22 04:15
Duplicate of #2322

**Closed by Wealthyturtle** 2019-12-22 04:15 UTC
