### ISSUE TITLE
error

### ISSUE THREAD

**Issue by haveadooday** [SkriptLang/Skript#3602] opened 2020-12-04 04:08 UTC
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! [Skript] Severe Error:
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Something went horribly wrong with Skript.
[13:07:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[13:07:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[13:07:58 ERROR]: #!#! Here is full list of them:
[13:07:58 ERROR]: #!#! skRayFall v1.9.23 (https://sk.rayfall.net/) skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.3 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[13:07:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[13:07:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[13:07:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[13:07:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[13:07:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[13:07:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Stack trace:
[13:07:58 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
[13:07:58 ERROR]: #!#!     at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:79)
[13:07:58 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:335)
[13:07:58 ERROR]: #!#!     at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:154)
[13:07:58 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:173)
[13:07:58 ERROR]: #!#!     at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:249)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.serialize(Classes.java:706)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:529)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.variables.Variables.serialize(Variables.java:522)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:533)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:365)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.variables.Variables.setVariable(Variables.java:356)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.Variable.set(Variable.java:440)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.Variable.change(Variable.java:500)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:282)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.hooks.regions.events.EvtRegionBorder.callEvent(EvtRegionBorder.java:136)
[13:07:58 ERROR]: #!#!     at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:165)
[13:07:58 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:07:58 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:07:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:711)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:07:58 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[13:07:58 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[13:07:58 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[13:07:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Version Information:
[13:07:58 ERROR]: #!#!   Skript: 2.5.2 (latest)
[13:07:58 ERROR]: #!#!     Flavor: skriptlang-github
[13:07:58 ERROR]: #!#!     Date: 2020-11-28
[13:07:58 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[13:07:58 ERROR]: #!#!   Minecraft: 1.12.2
[13:07:58 ERROR]: #!#!   Java: 1.8.0_271 (Java HotSpot(TM) 64-Bit Server VM 25.271-b09)
[13:07:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Server platform: Paper
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Current node: null
[13:07:58 ERROR]: #!#! Current item: set {Region::%the UUID of the player%}(as java.lang.Object) to the region
[13:07:58 ERROR]: #!#! Current trigger: region enter (enter of a region) (지역 채팅.sk, line 8)
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Thread: Server thread
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! Language: english
[13:07:58 ERROR]: #!#! Link parse mode: DISABLED
[13:07:58 ERROR]: #!#!
[13:07:58 ERROR]: #!#! End of Error.
[13:07:58 ERROR]: #!#!

**Comment by ShaneBeee** [comment] 2020-12-04 04:32
Duplicate of #3203

**Closed by ShaneBeee** 2020-12-04 04:32 UTC
