### ISSUE TITLE
Push effect is delayed

### ISSUE THREAD

**Issue by Misio12320** [SkriptLang/Skript#3434] opened 2020-10-04 19:33 UTC
### Description
The push effect is delayed.

### Steps to Reproduce
jump into void from a high y with high speed.

### Expected Behavior
I've should be pushed instantly not with delay and not teleported x times into the location but once.

code:
```
on enter region "void":
    push player upwards with speed 5.0 
    cancel event 
    wait 2.5 real seconds 
    teleport player to location (-1.5), (66), (-1.5) in (world "void")
```

### Server Information
[Skript] Server Version: git-Paper-211 (MC: 1.16.3)
[Skript] Skript Version: 2.5
[Skript] Installed Skript Addons:
[Skript] - Skent v1.9
[Skript] - SK-NBeeT v2.10.0 (https://github.com/ShaneBeee/Sk-NBeeT)
[Skript] - skUtilities v0.9.2 (https://tim740.github.io/)
[Skript] - SkQuery v4.1.3
[Skript] - SharpSK v1.6.3

**Comment by ShaneBeee** [comment] 2020-10-05 00:05
From my understanding of how this works, and looking at the code, there is no delay in the push effect.
I believe the issue is with the region enter event.

Since WorldGuard does not have events, Skript has had to makeshift an event using the player movement event, and checking all regions at the player's location.
That said, depending on the amount of regions, it can take the server time to process this, which can result in a small delay.

I do not believe this is something we can fix.
I will mark this as "dev needed" to get the opinion of the other devs.

**Comment by APickledWalrus** [comment] 2020-10-05 14:59
How long is this delay?

**Comment by Misio12320** [comment] 2020-10-05 15:50
Have a look at the video: https://youtu.be/PpUlxEpbZEQ
I have also reproduced this same at Paper 1.15.2-here's video: https://youtu.be/c5J9oPM-Hes
The versions is:
Minecraft 1.15.2 - Paper-348
Skript v2.5-alpha3 with addons:
SkQuery v3.6.5
skript-mirror v2.0.0-SNAPSHOT
TuSKe v1.8.2
SharpSK v1.6.3
skript-npc v0.1.2*

**Comment by APickledWalrus** [comment] 2020-10-05 16:02
What happens if you don't cancel the event.

**Comment by Misio12320** [comment] 2020-10-05 16:32
At 1.15.2: The player die from hit the ground (under the region is a barrier) but with god mode it works instantly. 
At 1.16.3: This same.

**Comment by APickledWalrus** [comment] 2020-10-05 16:32
> 
> 
> At 1.15.2: The player die from hit the ground (under the region is a barrier) but with god mode it works instantly.
> At 1.16.3: This same.

I think you need to cancel the event and THEN push the user up

**Comment by Misio12320** [comment] 2020-10-05 16:40
Have a look at the vid how it would look like (1.16.3):  https://youtu.be/uATWdAFRMpQ
And at 1.15.2:  https://youtu.be/uuxCzZEkGJg
code:
`on enter region "void":
	cancel event
	push player upwards with speed 5.0
	wait 2.5 real seconds
	teleport player to location (-1.5), (66), (-1.5) in (world "void")`

**Comment by APickledWalrus** [comment] 2020-10-05 16:50
> 
> 
> Have a look at the vid how it would look like (1.16.3): https://youtu.be/uATWdAFRMpQ
> And at 1.15.2: https://youtu.be/uuxCzZEkGJg
> code:
> `on enter region "void": cancel event push player upwards with speed 5.0 wait 2.5 real seconds teleport player to location (-1.5), (66), (-1.5) in (world "void")`

What if you try
```
on enter region "void":
    cancel event
    wait 1 tick
    push player upwards with speed 5.0 
    wait 2.5 real seconds 
    teleport player to location (-1.5), (66), (-1.5) in (world "void")
```

The region events can be a little glitchy if you don't delay from what I have experienced in the past. This *might* not make a difference though.

**Comment by Misio12320** [comment] 2020-10-05 19:46
Hm, good bypass. Seems to be fixed but I still does not understand why it cannot be like in 1.15.2 without tick

**Comment by APickledWalrus** [comment] 2020-10-05 20:27
I don't think this can be fixed by us. This is just a result of Skript having to create it's own event I believe. Maybe in the future, once a cleanup of the hook system is completed, this will work better. For now though, I'm closing this and labeling it accordingly.

**Closed by APickledWalrus** 2020-10-05 20:27 UTC
Labels: dev needed, investigating

**Comment by Misio12320** [comment] 2020-10-13 17:13
> This _might_ not make a difference though.

@APickledWalrus I have just tested this today again and when player spam space then the push just bug. More than 1 is again.
