### ISSUE TITLE
Skript fails to start on 1.21 - Unrecognized item LAVA_CAULDRON

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#6796] opened 2024-06-17 21:06 UTC
### Skript/Server Version

Info gathered on Spigot 1.21 on same server, since Skript failed on Paper
```
>skript info
[14:05:48] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[14:05:48] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[14:05:48] [Server thread/INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[14:05:48] [Server thread/INFO]: [Skript] Server Version: 4219-Spigot-146439e-3f8e416 (MC: 1.21)
[14:05:48] [Server thread/INFO]: [Skript] Skript Version: 2.8.7 (skriptlang-github)
[14:05:48] [Server thread/INFO]: [Skript] Installed Skript Addons: None
[14:05:48] [Server thread/INFO]: [Skript] Installed dependencies: 
[14:05:48] [Server thread/INFO]: [Skript]  - Vault v1.7.3-b131
[14:05:48] [Server thread/INFO]: [Skript]  - WorldGuard v7.0.11-SNAPSHOT+2276-2bd426b
```

### Bug Description

On server start-up, errors and Skript disabled

### Expected Behavior

Clean start-up

### Steps to Reproduce

- Update to Paper 1.21-1
- Start server
- Read console/log

Skript 2.8.7 works fine with Spigot 1.21-4219 (and previous)

### Errors or Screenshots

```
[13:44:51] [Server thread/INFO]: [Skript] Enabling Skript v2.8.7
[13:44:52] [Server thread/INFO]: [Skript] The updater is disabled, so a check for the latest version of Skript was not performed.
[13:44:53] [Server thread/ERROR]: Error occurred while enabling Skript v2.8.7 (Is it up to date?)
java.lang.IllegalArgumentException: LAVA_CAULDRON isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:137) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesProvider.addAlias(AliasesProvider.java:307) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadSingleAlias(AliasesParser.java:705) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.loadAlias(AliasesParser.java:614) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.AliasesParser.load(AliasesParser.java:121) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:506) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:492) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.lambda$loadDirectory$1(Aliases.java:475) ~[Skript-2.8.7.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597) ~[?:?]
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:557) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadDirectory(Aliases.java:468) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.loadInternal(Aliases.java:433) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.aliases.Aliases.load(Aliases.java:389) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.Skript.onEnable(Skript.java:508) ~[Skript-2.8.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[13:44:53] [Server thread/INFO]: [Skript] Disabling Skript v2.8.7
[13:44:53] [Server thread/ERROR]: Error occurred while disabling Skript v2.8.7
java.lang.ExceptionInInitializerError: null
        at Skript-2.8.7.jar/ch.njol.skript.Skript.beforeDisable(Skript.java:1192) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.Skript.onDisable(Skript.java:1204) ~[Skript-2.8.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: ch.njol.skript.SkriptAPIException: Registration can only be done during plugin initialization
        at Skript-2.8.7.jar/ch.njol.skript.Skript.checkAcceptRegistrations(Skript.java:1299) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.Skript.registerEvent(Skript.java:1501) ~[Skript-2.8.7.jar:?]
        at Skript-2.8.7.jar/ch.njol.skript.events.EvtSkript.<clinit>(EvtSkript.java:39) ~[Skript-2.8.7.jar:?]
        ... 17 more
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by APickledWalrus** [comment] 2024-06-17 22:02
It looks like this issue has caught up to us again. This will require a likely extensive rework of the aliases system. I'll hopefully have some further details to share soon.

**Comment by APickledWalrus** [comment] 2024-06-18 05:12
This issue should be resolved in https://github.com/SkriptLang/Skript/pull/6798 (based on 2.8.7). However, it likely needs extensive testing and I'm not sure what kind of errors can be expected (if really any).

**Comment by SlimeDog** [comment] 2024-06-18 08:48
#6798 looks good on my admittedly-limited server

**Comment by SlimeDog** [comment] 2024-06-19 23:42
I can close this now, or should I wait until Skript 2.8.8 release?

**Comment by APickledWalrus** [comment] 2024-06-20 00:23
We can wait until it's in a release

**Comment by tylermasci16** [comment] 2024-06-25 17:15
Can reproduce

**Closed** 2024-07-14 03:52 UTC
Labels: bug, priority: critical, completed, core task
