### ISSUE TITLE
loop objects

### ISSUE THREAD

**Issue by Adawasda** [SkriptLang/Skript#7238] opened 2024-12-03 13:02 UTC
### Suggestion

`loop %objects% as %variable%`or `loop %objects% and store in %variable%`
My english is not good enough sorry.
Read more in `why?`

### Why?

I searched a lot, but I never found it.
My idea is to simplify loops, sometimes expressions like loop-value-2, loop-value-5, etc. can be confusing and sometimes it is more difficult to read the code.
And if you add syntax by type: `loop %objects% as %some local variable%` or `loop %objects%. in %variable%` This will help make the code cleaner, and I've seen it a lot in different languages.
Variable will be deleted after looping is over.
Like:
![image](https://github.com/user-attachments/assets/8b4196c8-1bdf-4dfd-9cc1-e50f29e5431d)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Adawasda** [comment] 2024-12-03 13:04
Ye i know you can store loop-value in var and use it but i have too much loops and sometimes i cannot read my code

**Comment by UnderscoreTud** [comment] 2024-12-03 13:16
Duplicate of https://github.com/SkriptLang/Skript/issues/6052

**Closed as not planned by UnderscoreTud** 2024-12-03 13:16 UTC
