### ISSUE TITLE
GraaVM Java Error

### ISSUE THREAD

**Issue by LiannOM** [SkriptLang/Skript#4416] opened 2021-11-10 11:29 UTC
### Skript/Server Version

1.17.1 Purpur, Latest Skript

### Bug Description

Skript doesnt want to load when using https://github.com/etil2jz/etil-minecraft-flags (errors)

### Expected Behavior

Skript plugin doesnt work and addons either

### Steps to Reproduce

Just use flags that i sent above (enterprise edition) on purpur 1.17.1

### Errors or Screenshots

https://pastebin.com/1tTCM2jc

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-11-10 12:43
It looks like your aliases failed to load, can you send your server's startup log?

**Comment by LiannOM** [comment] 2021-11-10 12:53
It only happens when i use GraaVM on normal java it works well idk why:

i uploaded logs on my server because pastebin or any other hostings doesnt allow such huge files:

https://ocelotmc.pl/logs.txt

**Comment by TPGamesNL** [comment] 2021-11-10 13:05
Can you send a screenshot of your plugins/Skript directory, from your file explorer / FTP client?

**Comment by LiannOM** [comment] 2021-11-10 13:29
![Bittern713cffa63-5c74-4a21-9553-845019271536](https://user-images.githubusercontent.com/82086199/141121924-0e8767ec-ce5b-4082-92d4-5865178827fb.png)

**Comment by AyhamAl-Ali** [comment] 2021-11-10 13:32
> [12:25:57 ERROR]: #!#! Java: 17.0.1 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-jvmci-21.3-b05)

Is Java 17 supported by skript? did you test the normal Java 17 or was it Java 16?

**Comment by LiannOM** [comment] 2021-11-10 13:33
```java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

**Comment by AyhamAl-Ali** [comment] 2021-11-10 13:35
Can you try the JDK 11 based version? 

Link: https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.3.0
![image](https://user-images.githubusercontent.com/20037329/141122740-3a3fb5c2-3396-46d3-ba91-cb2342ae738b.png)

**Comment by LiannOM** [comment] 2021-11-10 13:36
yeah i will try it but does minecraft 1.17.1 need java 16+?

**Comment by AyhamAl-Ali** [comment] 2021-11-10 13:38
Ah yea I think 1.16 requires Java 16+ however try it if you can

**Comment by LiannOM** [comment] 2021-11-10 13:40
i think it wont work on 1.17+ with java 11

**Comment by LiannOM** [comment] 2021-11-10 13:42
```Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.incubator.vector not found
DAEMON
 Running post-execution steps```

**Comment by TPGamesNL** [comment] 2021-11-10 13:58
Can you try removing ` -Dfile.encoding=UTF-8` from your options?

**Comment by LiannOM** [comment] 2021-11-10 14:02
> Can you try removing ` -Dfile.encoding=UTF-8` from your options?

still doesnt work
![image](https://user-images.githubusercontent.com/82086199/141126890-e0589b71-eb1e-41da-bc34-f949135e16c0.png)

**Comment by TPGamesNL** [comment] 2021-11-10 14:30
Can you send your startup log again after removing that option?

**Comment by AyhamAl-Ali** [comment] 2021-11-10 14:37
Could you maybe try to delete the whole Skript folder and let it regenerate again? also without addons maybe

**Comment by TPGamesNL** [comment] 2021-11-10 14:39
Can you try redownloading the Skript jar file and using it?

**Comment by TPGamesNL** [comment] 2021-11-11 19:44
Can confirm on GraalVM, but only on Enterprise edition, not Community edition. Tested on both Java 11 and Java 17 versions, both produced the issue. The startup arguments are not the problem, without them I can still replicate the issue on versions mentioned above. The weird characters in the log isn't the issue, that's Notepad++'s fault (the latest.log files open with the wrong encoding).

After some debugging, it seems that *some* aliases aren't properly loaded, which causes the next aliases (which depend on the previous ones, e.g. `any granite = raw granite, polished granite`) to error. To make this even more interesting (/ frustrating), when I attach my debugger and go step by step, the bug does not occur anymore (for that single alias I'm doing stepping through, the rest still go wrong). I'll do more (probably old-fashioned) debugging later

**Comment by LiannOM** [comment] 2021-11-11 21:10
Thanks mate hope it will get resolved.

czw., 11 lis 2021, 20:44 użytkownik TPGamesNL ***@***.***>
napisał:

**Comment by TPGamesNL** [comment] 2021-11-17 14:14
This is an issue with GraalVM Enterprise edition. I've reported it to them, you can follow it at https://github.com/oracle/graal/issues/4022. TL;DR `String#indexOf(int)`, which Skript uses to determine where the `¦` character is when parsing aliases (among others), doesn't always work.

When loading an alias such as `[raw] granite¦s = minecraft:granite`, it should convert the name `[raw] granite¦s` into its single and plural form, `raw granite` and `raw granites`. It does this in `AliasesParser#getAliasPlural` with https://github.com/SkriptLang/Skript/blob/537a6984d6b0e6e6d64fe63058049f6c101c101a/src/main/java/ch/njol/skript/aliases/AliasesParser.java#L627-L632
Because the `String#indexOf(int)` method can return `-1` when it shouldn't, it'll return the input string for the single and plural forms, which will include the `¦`. This means the it will be registered under the alias `raw granite¦s`, while the `¦s` part should have been filtered out already. Because aliases depend on the previous aliases, e.g. `any granite¦s = raw granite, polished granite`, this would error, as `raw granite` is not registered because of the bug.

@LiannOM Temporary workarounds for this include switching to GraalVM's Community edition, or using `-Dgraal.CompilerConfiguration=community` to use the community version of Graal's JIT (although some of your startup args may not work with these). Otherwise, you can wait for a new release of GraalVM Enterprise.

As this is not caused by Skript, I'm closing this issue.

**Closed by TPGamesNL** 2021-11-17 14:14 UTC
Labels: investigating
