### ISSUE TITLE
Problem With Hex Codes

### ISSUE THREAD

**Issue by SebyHas** [SkriptLang/Skript#4535] opened 2022-01-27 11:44 UTC
### Skript/Server Version

```
[12:35:52 INFO]: [Skript] Server Version: git-Paper-170 (MC: 1.18.1)
[12:35:52 INFO]: [Skript] Skript Version: 2.6.1
[12:35:52 INFO]: [Skript] Installed Skript Addons:
[12:35:52 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[12:35:52 INFO]: [Skript]  - SkQuery v4.1.6
[12:35:52 INFO]: [Skript]  - SkBee v1.14.1 (https://github.com/ShaneBeee/SkBee)
[12:35:52 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

I have a problem in new version (2.6.1), with hex colors.
I found this problem in formatted messages (send formatted ""), in normal messages working well.
I maked a test script to test it, in first screenshop you can see my first problem, and in second, the actual test with official minecraft wiki colors

### Expected Behavior

Well, I think it's already clear, to display the colors according to the hex code.
Here are same thing, but in version 2.6
![2022-01-27_12 47 55](https://user-images.githubusercontent.com/14328372/151353376-1d4dab2e-5955-4dd2-b760-d337dae8592e.png)

### Steps to Reproduce

```
command /test4:
	trigger:
		send formatted "&4DarkRed <##AA0000>DarkRed"
		send formatted "&cRed <##FF5555>Red"
		send formatted "&6Gold <##FFAA00>Gold"
		send formatted "&eYellow <##FFFF55>Yellow"
		send formatted "&2DarkGreen <##00AA00>DarkGreen"
		send formatted "&aGreen <##55FF55>Green"
		send formatted "&bAqua <##55FFFF>Aqua"
		send formatted "&3DarkAqua <##00AAAA>DarkAqua"
		send formatted "&1DarkBlue <##0000AA>DarkBlue"
		send formatted "&9Blue <##5555FF>Blue"
		send formatted "&dLightPurple <##FF55FF>LightPurple"
		send formatted "&5DarkPurple <##AA00AA>DarkPurple"
		send formatted "&fWhite <##FFFFFF>White"
		send formatted "&7Gray <##AAAAAA>Gray"
		send formatted "&8DarkGray <##555555>DarkGray"
		send formatted "&0Black <##000000>Black"
```

### Errors or Screenshots

![2 6 1 color problem](https://user-images.githubusercontent.com/14328372/151351697-fc6f9bd7-f13a-4516-924d-6f1d9ebe5080.png)
![2022-01-27_12 37 14](https://user-images.githubusercontent.com/14328372/151351740-c8c1b1be-7dbc-47bb-b598-a9513906f930.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-01-27 12:02
Duplicate of https://github.com/SkriptLang/Skript/issues/4527

**Closed by TPGamesNL** 2022-01-27 12:02 UTC
