### ISSUE TITLE
Startup Problem

### ISSUE THREAD

**Issue by Max0fficial** [SkriptLang/Skript#2746] opened 2020-01-05 14:26 UTC
### Description
Skript plugin won't start, even though everything has been updated to the latest version

### Errors / Screenshots
Error code -> https://pastebin.com/G3cuiVTv

### Server Information
* **Server version/platform:**       Paper Spigot version git-Paper-33 (MC: 1.15.1)
* **Skript version:**                Skript v2.4.1

**Comment by APickledWalrus** [comment] 2020-01-05 14:35
It looks like one of your scripts has a line that is too long for the parser to read. Try shortening some of your lines or increasing your stack size.

**Comment by Wealthyturtle** [comment] 2020-01-05 14:40
Duplicate of #1117, as APickledWalrus stated, try shortening extremely long lines in scripts (or use brackets)

**Closed by Wealthyturtle** 2020-01-05 14:40 UTC

**Comment by Max0fficial** [comment] 2020-01-05 15:09
> Duplicate of #1117, as APickledWalrus stated, try shortening extremely long lines in scripts (or use brackets)

currently I don't have any scripts uploaded (skripts folder is empty)

**Comment by ShaneBeee** [comment] 2020-01-05 21:23
Do you have any Skript addons installed?
I have seen a couple people with this error now, I believe its addon related, but I don't know which addon.

**Comment by Max0fficial** [comment] 2020-01-06 21:39
I don't have any addons installed
it's weird :|
