### ISSUE TITLE
Named expression returns an inventory when used with variables

### ISSUE THREAD

**Issue by Govindass** [SkriptLang/Skript#1138] opened 2018-03-05 07:49 UTC
console is full of errors like(they didn't appear in previous version):
```
[09:33:12] [Server thread/ERROR]: [Skript] '::blocks::146} named "&fDouble Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."' is not a valid item data (plotmenu.sk, line 387: player does not have {heads::blocks::146} named "&fDouble Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."')
[09:33:12] [Server thread/ERROR]: [Skript] '::blocks::146} named "&fDouble Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."' is not a valid item data (plotmenu.sk, line 388: give {heads::blocks::146} named "&fDouble Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture." to player')
[09:33:12] [Server thread/ERROR]: [Skript] '::blocks::145} named "&fDouble Red Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."' is not a valid item data (plotmenu.sk, line 393: player does not have {heads::blocks::145} named "&fDouble Red Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."')
[09:33:12] [Server thread/ERROR]: [Skript] '::blocks::145} named "&fDouble Red Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."' is not a valid item data (plotmenu.sk, line 394: give {heads::blocks::145} named "&fDouble Red Sandstone Slab(All sides)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture." to player')
[09:33:13] [Server thread/ERROR]: [Skript] '::mobs::101} named "&fEnder Crystal" with lore "&7You can place ender crystals!"' is not a valid item data (plotmenu.sk, line 426: set slot 3 of player's current inventory to {heads::mobs::101} named "&fEnder Crystal" with lore "&7You can place ender crystals!"')
[09:33:13] [Server thread/ERROR]: [Skript] '::blocks::130} named "&fRedstone Lamp (ON)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."' is not a valid item data (plotmenu.sk, line 428: set slot 5 of player's current inventory to {heads::blocks::130} named "&fRedstone Lamp (ON)" with lore "&cThis block places as a full block||&cHead is only used for inventory||&ctexture."')
```
so looks like it's something to-do with setting heads saved in variables.
I also noticed this happening with other blocks than heads, so might be not only head related

**Comment by Snow-Pyon** [comment] 2018-03-05 08:10
the with lore expression isn't from Skript, could you possibly try without it? Just to confirm it's a Skript issue.

**Comment by Govindass** [comment] 2018-03-06 15:08
looks like it's addon problem, but it worked in previous version, so that's unnice :(

**Comment by Blueyescat** [comment] 2018-03-06 19:22
Doesn't give an error for me with `PaperSpigot 1.12.2-R0.1-SNP`, `Skript 2.2-dev3`4 and `SkQuery 3.6.0-Lime`. You may have break something by mistake 😜

**Comment by Snow-Pyon** [comment] 2018-03-06 20:32
I'm closing this since it isn't a Skript issue and I can't reproduce it either. Open it again if it happens to be a Skript issue in the end.

**Comment by Govindass** [comment] 2018-03-07 06:45
here's the problem:
set slot 0 of player's inventory to {item} named "test" = can't understand
set slot 0 of player's inventory to iron ingot named "test" = can understand

variable is the problem, it works if not adding named or with lore.
you maybe tried to re-produce it wrongly

**Comment by Nicofisi** [comment] 2018-03-07 07:09
How do you set the {item}

**Comment by Govindass** [comment] 2018-03-07 07:14
set {item} to player's slot 0

giving the item fully works without adding any "named" things

**Comment by Blueyescat** [comment] 2018-03-07 11:21
Confirmed ✔️  Here are the details; it throws the following stacktrace **if the variable is set**: https://hastebin.com/ifudelajim.md

**Comment by Snow-Pyon** [comment] 2018-03-08 05:12
Looks like it's returning an inventory even when it should return an item, probably fixed for the next patch.

**Comment by TheLimeGlass** [comment] 2018-03-21 08:57
I just got a similar issue with unrelated reasons compared to this https://github.com/bensku/Skript/issues/1163

**Comment by xbxymax** [comment] 2018-04-23 15:25
I now use the code '{test} parsed as itemtype'.
But this is not the best. Is there any way to solve it?

**Comment by Pikachu920** [comment] 2018-05-02 00:30
details:
![image](https://user-images.githubusercontent.com/28607612/39499829-0a18964e-4d76-11e8-99ef-e5d06f94475a.png)

**Comment by bloggy** [comment] 2018-05-13 12:53
Please fix this asap, because it's hard to change all scripts only to change them again later when it is fixed. Also in some cases there is no workaround. Specially when you format a gui slot with an item from a variable :-(

**Comment by Snow-Pyon** [comment] 2018-05-18 12:27
@bloggy you just have to change the return type, so, you can use:
```
formt gui slot 0 with (random item out of {_variable}) named "whatever"
```

**Comment by bloggy** [comment] 2018-05-24 16:39
Does not work for me. Enchanten items in guis are broken (not showing up).

**Comment by Snow-Pyon** [comment] 2018-05-24 18:17
```
set {_test} to player's tool
make gui slot 1 of player with (random item out of {_test}) named "test"
```

**Comment by Pikachu920** [comment] 2018-05-27 00:28
Fixed (https://github.com/SkriptLang/Skript/commit/168f54498d05cc4611aceede15ed11394900cb97)

**Comment by bloggy** [comment] 2018-05-29 07:39
How can I use the fixed version?

**Comment by Snow-Pyon** [comment] 2018-05-29 10:13
You can't yet unless you compile it. You could look at the nightly builds repo and see if it ia there too.

Opened again since we close issues after a release with the fix is out.

**Comment by Blueyescat** [comment] 2018-06-04 19:16
@Snow-Pyon Can be closed now.

**Comment by TheBentoBox** [comment] 2018-06-04 20:08
Thanks @Blueyescat !

**Closed by TheBentoBox** 2018-06-04 20:08 UTC
Labels: bug, priority: medium
