### ISSUE TITLE
ExprTimePlayed doesn't work for an offline player in 1.13+

### ISSUE THREAD

**Issue by CarloDrift** [SkriptLang/Skript#3310] opened 2020-08-15 18:49 UTC
### Description
Before 1.13, it's normal that it doesn't work. But in 1.13+, it should. I use Skript 2.5-beta2.

**Comment by Romitou** [comment] 2020-08-15 18:50
I think it's related to #3298.

**Comment by ShaneBeee** [comment] 2020-08-15 18:54
Closing as duplicate of #3298

**Closed by ShaneBeee** 2020-08-15 18:54 UTC
