### ISSUE TITLE
Bug when trying to remove an item from a player within a function.

### ISSUE THREAD

**Issue by Blacksoul16** [SkriptLang/Skript#3231] opened 2020-07-27 04:11 UTC
### Description
When I want to remove 1 item from a player's inventory in a function using "{_p}'s tool" doesn't work, but "tool of {_p}" does.

### Steps to Reproduce
```
function test(p: player):
    remove 1 of tool of {_p} from {_p}'s inventory    ← Work
  #----- 
    remove 1 of {_p}'s tool from {_p}'s inventory    ← Doesn't work

on rightclick holding red dye:
    cancel event
    test(player)
```

### Expected Behavior
This should remove the item from the inventory, regardless of the expression used.

### Errors / Screenshots
https://pastebin.com/F0mnancm

### Server Information
* **Server version/platform:** git-Paper-243 (MC: 1.14.4)
* **Skript version:** 2.5-alpha5

### Additional Context
In alpha6 it also happens and with worse errors, like this #3185 .

**Comment by TPGamesNL** [comment] 2021-03-22 16:11
Duplicate of #3814

**Closed by TPGamesNL** 2021-03-22 16:11 UTC
