### ISSUE TITLE
Vector arifmetic

### ISSUE THREAD

**Issue by Lotzyprod** [SkriptLang/Skript#5108] opened 2022-09-21 02:18 UTC
### Suggestion

Please, allow to use vector arifmetic with not only %vector% ** %vector% but %vector% ** %number% or %number% ** %vector%

It exists in examples, but not implement in source code.

### Why?

because it will not allow me to write something like this:
```
set {_sin} to sin(180)
set {_vec} to vector(1,1,1)
set {_sin} to vector({_sin},{_sin},{_sin})
set {_vec} to {_vec} ** {_sin}
set {_vec2} to (1,1,1)
set {_vec} to {_vec} ++ {_vec2}
```
or
```
set {_sin} to sin(180)
set {_vec} to vector(1,1,1)
set {_vec} to vector((x of {_vec})*{_sin},(y of {_vec})*{_sin},(z of {_vec})*{_sin}) #more brackets for decrease parse time!!!!
```

### Other

Same thread
https://github.com/SkriptLang/Skript/issues/4253

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment] 2022-09-21 02:28
I don't think this should be added, personally. Vector arithmetic should stay as vector-vector, instead of adding scalars and adding confusion. The examples should be changed to reflect this, rather than the other way around.
If you want to scale a vector you can simply use the existing `vector length` expression:
```
set {_v} to vector(1,1,1)
set vector length of {_v} to (vector length of {_v}) * sin(180) + 1
```

**Comment by Lotzyprod** [comment] 2022-09-21 02:51
> I don't think this should be added, personally. Vector arithmetic should stay as vector-vector, instead of adding scalars and adding confusion. The examples should be changed to reflect this, rather than the other way around. If you want to scale a vector you can simply use the existing `vector length` expression:
> 
> ```
> set {_v} to vector(1,1,1)
> set vector length of {_v} to (vector length of {_v}) * sin(180) + 1
> ```

Lets invert vector with same method.
https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/main/java/ch/njol/skript/expressions/ExprVectorLength.java#L64

For first its not faster then vector.multiply()
For second specific of code of skript doesnt allow us to multiply vector length with values less than null

**Comment by AyhamAl-Ali** [comment] 2022-09-21 07:34
Duplicate of #4253

**Closed by AyhamAl-Ali** 2022-09-21 07:34 UTC
