### ISSUE TITLE
Getting Error In The Console While Having The Latest Version Of Skript On MC 1.16.1

### ISSUE THREAD

**Issue by Drainer2002** [SkriptLang/Skript#3227] opened 2020-07-26 17:09 UTC
### Description
I did download latest version of skript 2.5-alpha6(rev1) on MC 1.16.1 and getting errors in the console

### Steps to Reproduce
1. place Skript 2.5-alpha6(rev1) in the plugins folder
2. restart the server
3. getting errors in the console

### Expected Behavior
no errors in the console

### Errors / Screenshots
 
[20:02:47 INFO]: [Skript] A new version of Skript is available: 2.5-alpha6 (you're currently running 2.5-alpha6(rev1))
[20:02:47 INFO]: Download it at: <aqua><u><link:https://github.com/SkriptLang/Skript/releases/download/2.5-alpha6/Skript.jar>https://github.com/SkriptLang/Skript/releases/download/2.5-alpha6/Skript.jar
[20:02:56 ERROR]: Error occurred while enabling Skript v2.5-alpha6(rev1) (Is it up to date?)
java.lang.StackOverflowError: null
        at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_261]
        at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0

### Server Information
* **Server version/platform:**  1.16.1/paper
* **Skript version:**  Skript 2.5-alpha6(rev1)

**Comment by ShaneBeee** [comment] 2020-07-26 19:35
Duplicate of #2752

**Closed by ShaneBeee** 2020-07-26 19:35 UTC
