### ISSUE TITLE
Skript not saving variables

### ISSUE THREAD

**Issue by lidanthedev** [SkriptLang/Skript#3064] opened 2020-06-21 16:06 UTC
### Description
Skript Doesn't save variables after a little while the server was online 

### Steps to Reproduce
I added my config.sk and variables
[Skript.zip](https://github.com/SkriptLang/Skript/files/4809798/Skript.zip)

### Expected Behavior
It should save variables

### Errors / Screenshots
https://pastebin.com/QiZ02Qyj

### Additional Context
This problem happens to me for a long time and no one knows how to fix it

**Comment by Wealthyturtle** [comment] 2020-06-26 05:07
Everything looks good to me... not sure why this exception is being thrown.

**Comment by lidanthedev** [comment] 2020-06-27 12:27
is there any way to fix it?

**Comment by lidanthedev** [comment] 2020-07-04 20:01
did it god fixed cuz it's still happening to me

**Comment by TPGamesNL** [comment] 2021-03-18 08:23
Duplicate of https://github.com/SkriptLang/Skript/issues/3453.
In this case the second thread that's using log handlers is the variable saving thread.

**Closed by TPGamesNL** 2021-03-18 08:23 UTC
Labels: bug, dev needed

**Comment by startree236** [comment] 2021-05-31 11:36
Did you solve the problem?
I am also having the same error..

**Comment by TPGamesNL** [comment] 2021-05-31 13:26
> Did you solve the problem?
> I am also having the same error..

This issue has been fixed in 2.6-alpha1

**Comment by startree236** [comment] 2021-06-01 03:00
> > Did you solve the problem?
> > I am also having the same error..
> 
> This issue has been fixed in 2.6-alpha1

Thank you for answer!
World Guard did not work in version 1.12.2, is there any solution?

**Comment by TPGamesNL** [comment] 2021-06-01 09:49
> > > Did you solve the problem?
> > > I am also having the same error..
> > 
> > 
> > This issue has been fixed in 2.6-alpha1
> 
> Thank you for answer!
> World Guard did not work in version 1.12.2, is there any solution?

That is not related to this issue
