### ISSUE TITLE
is op is not working correctly

### ISSUE THREAD

**Issue by GrimEpp** [SkriptLang/Skript#1037] opened 2017-12-30 19:20 UTC
The condition is op is not working correctly.
When i do /checkop wich code is 
`command /checkop:
  trigger:
    loop all players:
      loop-player is op
      broadcast "%loop-player% is op"` just returns the name of the person even tho there is other people on that are op

**Comment by GrimEpp** [comment] 2017-12-30 19:25
Tested with 1.12.2 dev 32c

**Comment by TheBentoBox** [comment] 2018-01-02 03:47
Can anyone reproduce this?

**Comment by xXAndrew28Xx** [comment] 2018-01-07 00:35
I remember @TonyMaster21 having the same issue. I just reproduced it on 1.12.2.
![image](https://user-images.githubusercontent.com/9660418/34645364-68d5b970-f310-11e7-8e13-ca0bce447483.png)

**Comment by bensku** [comment] 2018-01-07 08:49
What permission plugin, if any, do you use?

**Comment by GrimEpp** [comment] 2018-01-07 10:24
None

**Comment by jaylawl** [comment] 2018-01-19 08:33
is op condition doesn't work for me either using paper spigot 1.12.1, skript dev32d and luck permissions as perm plugin. permission conditions working fine however

**Comment by Nicofisi** [comment] 2018-02-21 13:11
Is it still relevant? I'm not able to reproduce it with head on 462601b on latest Spigot version ` git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`:
```
>op Nicofisi
[13:56:49 INFO]: Opped Nicofisi
[13:56:57 INFO]: Nicofisi issued server command: /broadcastop
[13:56:57 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastop
[13:56:57 INFO]: Starting
[13:56:57 INFO]: Nicofisi is op
[13:56:57 INFO]: Done
[13:57:04 INFO]: Nicofisi issued server command: /deop Nicofisi
[13:57:04 INFO]: [Nicofisi: De-opped Nicofisi]
[13:57:08 INFO]: Nicofisi issued server command: /broadcastop
[13:57:08 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastop
[13:57:08 INFO]: Starting
[13:57:08 INFO]: Done
[13:57:25 INFO]: Nicofisi issued server command: /broadcastisop
[13:57:25 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastisop
[13:57:25 INFO]: not op
```
```
command /broadcastisop:
        trigger:
                if player is op:
                        broadcast "%player% is op"
                else:
                        broadcast "not op"

command /broadcastop:
        trigger:
                broadcast "Starting"
                loop all players:
                        loop-player is op
                        broadcast "%loop-player% is op"
                broadcast "Done"
```
Any special steps to reproduce?

**Comment by xXAndrew28Xx** [comment] 2018-02-21 13:22
On Wed, Feb 21, 2018 at 7:11 AM Nicofisi <notifications@github.com> wrote:

> Is it still relevant? I'm not able to reproduce it with head on 462601b
> <https://github.com/bensku/Skript/commit/462601b48427a872968ec6e9604e87b6feb133d9>
> on latest Spigot version git-Spigot-4bd94dc-fb414fe (MC: 1.12.2)
> (Implementing API version 1.12.2-R0.1-SNAPSHOT):
>
> >op Nicofisi
> [13:56:49 INFO]: Opped Nicofisi
> [13:56:57 INFO]: Nicofisi issued server command: /broadcastop
> [13:56:57 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastop
> [13:56:57 INFO]: Starting
> [13:56:57 INFO]: Nicofisi is op
> [13:56:57 INFO]: Done
> [13:57:04 INFO]: Nicofisi issued server command: /deop Nicofisi
> [13:57:04 INFO]: [Nicofisi: De-opped Nicofisi]
> [13:57:08 INFO]: Nicofisi issued server command: /broadcastop
> [13:57:08 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastop
> [13:57:08 INFO]: Starting
> [13:57:08 INFO]: Done
> [13:57:25 INFO]: Nicofisi issued server command: /broadcastisop
> [13:57:25 INFO]: Nicofisi [6cf7857f-2d7d-3cbd-8c22-511f4f93c8d1]: /broadcastisop
> [13:57:25 INFO]: not op
>
> command /broadcastisop:
>         trigger:
>                 if player is op:
>                         broadcast "%player% is op"
>                 else:
>                         broadcast "not op"
>
> command /broadcastop:
>         trigger:
>                 broadcast "Starting"
>                 loop all players:
>                         loop-player is op
>                         broadcast "%loop-player% is op"
>                 broadcast "Done"
>
> Any special steps to reproduce?
>
> —
>
Try multiple players, also try both online and offline mode.

**Comment by TheLimeGlass** [comment] 2018-04-04 19:12
I think this is user error. When a Spigot server is in offlinemode and it is of a Bungeecord network they should have the bungeecord option enabled and have ip_forward enabled in the Bungeecord configurations. This allows Bungeecord to accurately setup UUID's based off Mojang. If it's not setup correctly Spigot thinks it's a cracked server and thus Spigot will generate all the UUID's. UUID's are related to the Operator data which is why I feel this condition would be failing. A suggestion to fix this could be using offlineplayers within the syntax.

**Comment by GrimEpp** [comment] 2018-04-07 10:36
This error was produced on online mode

**Comment by xXAndrew28Xx** [comment] 2018-04-07 15:05
Also even if offline-mode did change the UUIDs to the non-correct ones (due to improper setup), it would still map 1 to 1 with players properly as long as they didn't change their name.

**Comment by Snow-Pyon** [comment] 2018-05-21 20:15
I've tested this and the only way I could reproduce it is with more than one player online in a loop.

**Comment by crzyBrown** [comment] 2018-06-21 18:25
I looked codes to 5 minute & debugged somewhere stuff. I found what problem is it.

The problem is; `is op` doesn't check loop-player, just checks onPlayerCommand events player. I'm not totally know this project codes (i mean idk for now, how to fix this) but i'm totally sure this is problem. Maybe this can help, if i found fix, i will send it as PR.

**Comment by crzyBrown** [comment] 2018-06-21 18:39
Oh i understand something too Njol's brain is like crazy, cuz of it uses compare instance to get is op or not, not checking player.isOp(). He controls player instance comparing... :/

The `is op` need to be redesigned. (Like a real condition class)

**Comment by SiebeDW** [comment] 2019-02-05 22:23
I think this should be closed. (referred to a merged PR and commits.)

**Comment by Nicofisi** [comment] 2019-02-05 22:46
Good point @SiebeDW, thanks!

**Comment by ShaneBeee** [comment] 2019-10-11 08:01
Fiddling around with this a little more, I came to a realization. The `is op` is being used incorrectly. The users here are using it as if it were a condition, where rather its comparing the player to operator entity class, therefor it should be used like "is an op"

when testing, if I use a simple command:
```vb
command /test:
    trigger:
        loop all players:
            send "Player: %loop-player% - UUID: %uuid of loop-player%"
                if loop-player is op:
                    send "&aOP"
                else:
                    send "&cNOT OP"
```
If I run in game, it says I'm op, if I run from console, it says I'm not op.
If I change the line `if loop-player is op` to `if loop-player is an op` it works in both console and in game.

saying `if player is op` is the equivalent of saying `if entity is skeleton` where we should be doing `if entity is a skeleton`

The same thing happens with this case:
```vb
command /test:
    trigger:
        loop all entities:
            if loop-entity is villager:
                send "&aVILLAGER"
```
(run from console) using `is villager` returns no villagers, if I use `is a villager` it returns 2 villagers

That said, I'm not sure if I could classify this as a bug. I would say maybe we should add an `if %player% is op` condition, which would check if the player has operator status vs checking if the player is an op entity.

**Comment by TPGamesNL** [comment] 2021-08-11 12:47
Duplicate of #1798

**Closed by TPGamesNL** 2021-08-11 12:47 UTC
Labels: bug, priority: low
