### ISSUE TITLE
Suggestion - upload skript to spigotmc

### ISSUE THREAD

**Issue by SzczurekYT** [SkriptLang/Skript#3770] opened 2021-02-23 06:47 UTC
I'm suggesting uploading plugin also to spigotmc.org. Why? There is free server hosting and it allow only plugins from spigotmc.org and bukkit.org. Uploading this to spigot will allow me and other server owners who like skript using it on aternos.

**Comment by TPGamesNL** [comment] 2021-02-23 09:38
Duplicate of https://github.com/SkriptLang/Skript/issues/3550

**Closed by TPGamesNL** 2021-02-23 09:38 UTC

**Comment by TheDGOfficial** [comment] 2021-02-23 09:52
Also see #3678, which is still open (as an issue and discussion not locked)
and both Njol and bensku commented.
