### ISSUE TITLE
Issue with teleporting entity to a location

### ISSUE THREAD

**Issue by RiverThrough** [SkriptLang/Skript#974] opened 2017-11-16 04:47 UTC
hello I have an issue after switching to Dev32b from dev25

```
function DespawnPet(e: entity , p: player):
	if {_p} is set:
		set {_uuid} to uuid of {_p}
		delete {x_activepet::%{_uuid}%}
	wait 5 ticks
	teleport {_e} to 400 blocks above {_e}
	wait 1 tick
	kill {_e}
```

I have this function to despawn a pet, it use to work fine on dev25 but now I get the following error:
https://i.imgur.com/geAPxnx.png

so the problem is the line
```teleport {_e} to 400 blocks above {_e}```

I have tried a few other variations such as:
```teleport {_e} to location at 400 blocks above {_e}```
and a few more but I haven't found any that work. Is there a new way to do this? Or is this possibly a bug?

**Comment by Pikachu920** [comment] 2017-11-16 06:22
that should work but for now you can do
```
set {_l} to location of {_e}
add 400 to x-loc of {_l}
teleport {_e} to {_l}
```
although i dont see why you dont just use
```
delete {_e}
```

**Comment by RiverThrough** [comment] 2017-11-16 07:44
If I remember correctly when I kill/despawn an entity with skript the player sees and hears the animal die, to combat this and make it so it would appear as if the animal would seemingly disappear I decided to teleport it away and then kill it, I handle clearing/preventing the drops in a separate part of the code but overall that was my goal

As for your suggested solution I did consider doing that but I guess I'm just a bit annoyed that I have to turn my 1 line code into 2 or 3 lines of code when the code worked perfectly before, obviously the function is super easy to fix but I have dozens more lines like these scattered throughout my scripts, I figured the change might have been unintentional so I thought it would be a good idea to bring it up here, if it's not unintentional I'll just go through my scripts and deal with it but it would be nice to have the functionality working as before if it is indeed a bug or an unintended change

Here are two other similar lines that previously worked just fine, just in case it helps to find a possible issue
```set {_loc} to location 2 blocks above player```
```teleport {_pet} to location 2 blocks horizontally behind player```

**Comment by Pikachu920** [comment] 2017-11-16 08:51
That only happens if you use the kill effect. Now that I think about it, because of another skript bug (or rather overlook in this case) you have to use skript-mirror to do `{_e}.remove();` if you would like to delete a entity stored in a variable without any death sound/animation

**Comment by RiverThrough** [comment] 2017-11-16 21:26
Thanks! tried that out and it seems to do the trick

**Comment by TheBentoBox** [comment] 2017-11-17 13:50
I don't think it's intentional. Syntaxes should always remain backward compatible unless there's a really good reason or a need to make a breaking change.

Also, this thread makes me think it's about time we get a `remove %entity%` effect in vanilla Skript that calls the entity's remove() method (or perhaps the `delete` changer on an entity should be made to do that). It's never made much sense that we have to teleport living entities into the void to "delete" them.

**Comment by Pikachu920** [comment] 2017-11-18 05:23
The only intentionally changed syntax that I can think of is the hashing expression

**Comment by Nicofisi** [comment] 2018-07-20 10:58
Since ExprLocation accepts `%directions%`:
```
"[the] (location|position) %directions% [%location%]"
```
they need to be separated by commas (this works):
```vb
command /hi:
	trigger:
		set {_e} to player
		teleport {_e} to location (at, 400 blocks above) {_e}
```
The better question  is not why it doesn't work, it's why it did work?

**Comment by Pikachu920** [comment] 2018-07-20 19:15
could be as it has a similar issue with strings

**Comment by TheLimeGlass** [comment] 2018-08-25 09:41
Related? https://github.com/SkriptLang/Skript/issues/828

**Comment by TPGamesNL** [comment] 2021-06-15 10:23
Duplicate of #828, every correct example works if you replace blocks with meters

**Closed by TPGamesNL** 2021-06-15 10:23 UTC
Labels: bug, needs testing, priority: low
