### ISSUE TITLE
Crash on push player's vehicle

### ISSUE THREAD

**Issue by Florenthz** [SkriptLang/Skript#5086] opened 2022-09-07 00:01 UTC
### Skript/Server Version

```markdown
Skript: v2.6.3
SkQuery: v4.1.7
Skellet: 2.0.7
SkRayFall: v.1.1
```

### Bug Description

Hi there, this is my first post, sorry for my wrong english...

```pyon rightclick with coal:
    if player is riding a minecart:
        push player's vehicle in horizontal direction of player at speed 10
        remove 1 coal from player's held item
```

When I do click with the coal on a minecart, servers crashes, this is the log:

```log
06.09 23:49:57 [Server] Server thread/ERROR Encountered an unexpected exception
06.09 23:49:57 [Server] INFO java.lang.AssertionError: TRAP
06.09 23:49:57 [Server] INFO at net.minecraft.world.item.ItemStack.P(ItemStack.java:194) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.world.item.ItemStack.e(ItemStack.java:1190) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:453) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1724) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1106) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1017) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
06.09 23:49:57 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
06.09 23:49:58 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2022-09-06_23.49.58-server.txt
```

### Expected Behavior

I dont know

### Steps to Reproduce

I wrote and it did not work

### Other

HI

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by bluelhf** [comment] 2022-09-07 08:31
This error is probably not caused by Skript. The relevant stack trace is from Minecraft's code: the issue is likely either with Spigot or with Minecraft itself.

**Comment by AyhamAl-Ali** [comment] 2022-09-07 08:57
Duplicate of #2143

**Closed by AyhamAl-Ali** 2022-09-07 08:57 UTC
