### ISSUE TITLE
Lore contains

### ISSUE THREAD

**Issue by MrScopes** [SkriptLang/Skript#1363] opened 2018-07-10 18:05 UTC
I've been working with a custom enchanter, but this dosen't seem to work:
    **if line 1 of lore of {_p}'s held item does not contain "Explosive":**

There are no errors, it just dosen't properly register.

**Comment by MrScopes** [comment] 2018-07-10 18:05
function enchExplosive(p: player):
	{_p} is holding a diamond pickaxe
	if line 1 of lore of {_p}'s held item is " &b(!) &3Explosive &bV":
		send " &3&lEvolve &8➟ &7That enchantment is already at the maximum level." to {_p}
	else:
		if {evolve.tokens::%{_p}%} is less than 5:
			send " &3&lEvolve &8➟ &7You don't have enough tokens." to {_p}
		else:
			send " &3&lEvolve &8➟ &7You upgraded your &3Explosive &7enchantment." to {_p}
			subtract 5 from {evolve.tokens::%{_p}%}
			make {_p} execute command "/sb update"
			if line 1 of lore of {_p}'s held item does not contain "Explosive":
				set line 1 of lore of {_p}'s tool to " &b(!) &3Explosive &bI"
			else if line 1 of lore of {_p}'s held item is " &b(!) &3Explosive &bI":
				set line 1 of lore of {_p}'s tool to " &b(!) &3Explosive &bII"
			else if line 1 of lore of {_p}'s held item is " &b(!) &3Explosive &bII":
				set line 1 of lore of {_p}'s tool to " &b(!) &3Explosive &bIII"
			else if line 1 of lore of {_p}'s held item is " &b(!) &3Explosive &bIII":
				set line 1 of lore of {_p}'s tool to " &b(!) &3Explosive &bIV"
			else if line 1 of lore of {_p}'s held item is " &b(!) &3Explosive &bIV":
				set line 1 of lore of {_p}'s tool to " &b(!) &3Explosive &bV"

**Comment by MrScopes** [comment] 2018-07-10 18:05
Ofc there are tabs in there

**Comment by jaylawl** [comment] 2018-07-10 20:08
have you tried `broadcast line 1 of lore of {_p}'s held item`? Always good to try and output.

**Comment by TheBentoBox** [comment] 2018-07-16 13:11
I haven't confirmed this but if it is truly an issue it may be the same as what's described in #1287 since there seems to be some issues with function parameters at the moment.

**Comment by TheBentoBox** [comment] 2018-07-19 12:58
Closing this to move discussions to #1287 and because it's been reported as non-reproducible by someone else anyways.

**Closed by TheBentoBox** 2018-07-19 12:58 UTC

**Comment by Nicofisi** [comment] 2018-07-19 18:58
Can't reproduce with the following script:
```vb
command /test:
    trigger:
        set {_x} to player
        if line 1 of lore of {_x}'s held item contains "o":
            message "yes"
        else:
            message "no"
```
nor with the following one:
```vb
command /hi:
    trigger:
        fun(player)

function fun(x: player):
    if line 1 of lore of {_x}'s held item contains "o":
        message "yes" to {_x}
    else:
        message "no" to {_x}
```
whilewith an item name with lore `o hi` in hand
