### ISSUE TITLE
Skript error 

### ISSUE THREAD

**Issue by qtt509** [SkriptLang/Skript#2683] opened 2019-12-11 06:35 UTC
What is causing this error?

MC - 1.12.2 Paper
Skript - 2.4

![1](https://user-images.githubusercontent.com/58448722/70597507-e63ab500-1c2b-11ea-8353-93a9d339a099.PNG)

**Comment by ShaneBeee** [comment] 2019-12-11 06:37
Duplicate of #2678 

I believe you were already answered on this. This isn't a bug, this is an issue with your code.

**Comment by qtt509** [comment] 2019-12-11 06:40
> Duplicate of #2678
> 
> I believe you were already answered on this. This isn't a bug, this is an issue with your code.

There is no error when opening the server.
However, I get an error only when loading with the / sk command.
Is it a bucket problem?

**Comment by ShaneBeee** [comment] 2019-12-11 06:42
Not really sure, you have provided next to no information. 
You even deleted the template we provide for you to fill in, to help us triage the issue.

My guess is you're trying to parse too much code at once. Maybe a really large script file or a long line.

I recommend trying to debug yourself, try to find out which script file is causing the issue and go from there.

**Closed** 2019-12-11 06:43 UTC
Labels: duplicate

**Comment by qtt509** [comment] 2019-12-11 06:49
> Not really sure, you have provided next to no information.
> You even deleted the template we provide for you to fill in, to help us triage the issue.
> 
> My guess is you're trying to parse too much code at once. Maybe a really large script file or a long line.
> 
> I recommend trying to debug yourself, try to find out which script file is causing the issue and go from there.

All functions work normally.
Can I ignore the error in this case?

**Comment by Wealthyturtle** [comment] 2019-12-11 09:24
You are free to ignore the error, although if it becomes an issue and your server doesn't start up due to Paper killing the server after it exceeds 60 seconds then you may want to dig further.

**Comment by TheDGOfficial** [comment] 2019-12-13 03:53
You should not use `/sk reload all`, if you want to reload all scripts use `/sk reload scripts`, if you want to reload some script use `/sk reload <script name with or without the .sk extension>`, but sure it should be classified as a warning, not an error. You can ignore it safely. It means your server is not ticked/freezed for 10 seconds, its normal when (re)loading long scripts.

**Comment by qtt509** [comment] 2019-12-13 03:54
> You are free to ignore the error, although if it becomes an issue and your server doesn't start up due to Paper killing the server after it exceeds 60 seconds then you may want to dig further.

Thank you for answer

**Comment by qtt509** [comment] 2019-12-13 03:55
> You should not use `/sk reload all`, if you want to reload all scripts use `/sk reload scripts`, if you want to reload some script use `/sk reload <script name with or without the .sk extension>`, but sure it should be classified as a warning, not an error. You can ignore it safely. It means your server is not ticked/freezed for 10 seconds, its normal when (re)loading long scripts.

Thank you for answer
