### ISSUE TITLE
Skript not loading properly on 1.21

### ISSUE THREAD

**Issue by Laukage** [SkriptLang/Skript#6808] opened 2024-06-22 19:41 UTC
### Skript/Server Version

```markdown
Skript does not load, but version is 2.8.7
```

### Bug Description

Skript fails to load on Paper/Purpur 1.21

### Expected Behavior

That it loads properly

### Steps to Reproduce

Install latest build from paper or purpor along with skript.

### Errors or Screenshots

https://gist.github.com/Laukage/6ef8eab4018f118d85f962efc9730a35

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Asleeepp** [comment] 2024-06-22 19:47
duplicate of https://github.com/SkriptLang/Skript/issues/6796
see https://github.com/SkriptLang/Skript/pull/6798 for a in development build of Skript that loads on 1.21

**Closed** 2024-06-30 09:57 UTC
