### ISSUE TITLE
can't set first 1 charracter

### ISSUE THREAD

**Issue by Mikimoka** [SkriptLang/Skript#3595] opened 2020-12-01 22:37 UTC
### Description
severy error on loading skript or reloading that skript file
### Steps to Reproduce
```
command /testi <text>:
  trigger: 
    set {_jeptesti} to the first 1 characters of arg 1   
```

### Expected Behavior
not to give error and it should set first character of arg 1 to local variable... this used to work in earlier version Skript 2.5.1

### Errors / Screenshots

```
[23:34:05 INFO]: [Skript] Reloading test.sk...
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! [Skript] Severe Error:
[23:34:05 ERROR]: #!#! Could not load viive.sk
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Something went horribly wrong with Skript.
[23:34:05 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:34:05 ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[23:34:05 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Stack trace:
[23:34:05 ERROR]: #!#! java.lang.NullPointerException
[23:34:05 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSubstring.isSingle(ExprSubstring.java:108)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:249)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:486)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:636)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:464)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.reloadScript(ScriptLoader.java:976)
[23:34:05 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[23:34:05 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:34:05 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:34:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
[23:34:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764)
[23:34:05 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[23:34:05 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[23:34:05 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212)
[23:34:05 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
[23:34:05 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:34:05 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Version Information:
[23:34:05 ERROR]: #!#!   Skript: 2.5.2
[23:34:05 ERROR]: #!#!     Flavor: skriptlang-github
[23:34:05 ERROR]: #!#!     Date: 2020-11-28
[23:34:05 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[23:34:05 ERROR]: #!#!   Minecraft: 1.16.4
[23:34:05 ERROR]: #!#!   Java: 1.8.0_222 (OpenJDK 64-Bit Server VM 25.222-b10)
[23:34:05 ERROR]: #!#!   OS: Linux amd64 4.19-ovh-xxxx-std-ipv6-64
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Server platform: Paper
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Current node: set {_jeptesti} to the first 1 characters of arg 1 (test.sk, line 8)
[23:34:05 ERROR]: #!#! Current item: null
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Thread: Server thread
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! Language: english
[23:34:05 ERROR]: #!#! Link parse mode: DISABLED
[23:34:05 ERROR]: #!#!
[23:34:05 ERROR]: #!#! End of Error.
```

### Server Information
* **Server version/platform: Paper spigot / Minecraft 1.16.4 
* **Skript version:  Skript 2.5.2 i

**Comment by ShaneBeee** [comment] 2020-12-01 22:38
Duplicate of #3585

**Closed by ShaneBeee** 2020-12-01 22:38 UTC
