### ISSUE TITLE
Long loading time with "on command"

### ISSUE THREAD

**Issue by Lennord** [SkriptLang/Skript#4494] opened 2022-01-11 16:41 UTC
### Skript/Server Version

Skript: 2.6 Skript Github and 2.6 Skript version in discord (for support 1.18/1.18.1)
Server version: Paper 1.17.1 (and the same for any version that works in 2.6 all versions...)
Skript addon: None

### Bug Description

When I do the example code, it loads me much longer than the previous version of skript (2.5.3) while I am in 2.6 all versions, there is no error but there is an error when the server crash in red with the Paper in message (but this error I believe comes from Paper but not from Skript).
Last year, when the official version of 2.6 was released, I already contacted you for this type of problem but I tried your solutions but it does not change (it reduces the lag a bit, especially with the brackets but this does not change much).
Hope this bug will be fixed successfully.
Good luck !

### Expected Behavior

In the previous version of skript (2.5.3), normally it would load faster but since 2.6 all versions it loads much faster.
So normally it shouldn't be long like this.

### Steps to Reproduce

Code:

Example 1:

```
on command:
    if sender is a player:
        if player's world is "world":
            if command is not "[COMMAND]":
                send "Error !" to player
                stop
```

Example 2:

```
on command:
    if sender is a player:
        if player's world is "world":
            if command is not "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or "[COMMAND]": (...)
                send "Error !" to player
                stop
```

Example 3:

```
on join:
    set {variableslist::*} to "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or "[COMMAND]" (...)

on command:
    if sender is a player:
        if player's world is "world":
            if command is not {variableslist::*}:
                send "Error !" to player
                stop
```

Example 4:

```
on command:
    if sender is a player:
        if player's world is "world":
            if command is not "[COMMAND]" or "[COMMAND]" or "[COMMAND]" or ("[COMMAND]" or "[COMMAND]" or "[COMMAND]") or "[COMMAND]" or "[COMMAND]": (...)
                send "Error !" to player
                stop
```

### Errors or Screenshots

No error with Skript error !

Error with Server Crash Paper (bug for Paper, is advertissement Long loading time server load:
https://pastebin.com/Vduz7ptL

### Other

Your skript plugin is wonderful even if it is not too powerful but it can do wonderful things that we can not do in Java (or almost).

Have a good day or a good evening !

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-01-11 17:34
Can you put your code in blocks like these:
\```
code here
\```

This'll make it so your code keeps its indentation and it's easier to read:
```
on join:
    test stuff
```

**Comment by Lennord** [comment] 2022-01-11 17:38
> Can you put your code in blocks like these: ``` code here ```
> 
> This'll make it so your code keeps its indentation and it's easier to read:
> 
> ```
> on join:
>     test stuff
> ```


There it's done.

**Comment by TPGamesNL** [comment] 2022-01-11 18:04
Duplicate of https://github.com/SkriptLang/Skript/issues/4025

I recommend distributing the values over multiple lines, for example:
```
on load:
	set {list::*} to "command 1", "command 2" and "command 3"
	add "command 4", "command 5" and "command 6" to {list::*}
```

**Closed by TPGamesNL** 2022-01-11 18:04 UTC

**Comment by TPGamesNL** [comment] 2022-01-11 18:21
You can use `if {list::*} contains command:` or `if {list::*} does not contain command:`

**Comment by Lennord** [comment] 2022-01-11 18:24
> You can use `if {list::*} contains command:` or `if {list::*} does not contain command:`

Thank you very much for your help, thanks to you I could continue my projects in skript...
Have a good evening !
