### ISSUE TITLE
Global Functions Broken (v2.5.2)

### ISSUE THREAD

**Issue by Baezor1** [SkriptLang/Skript#3611] opened 2020-12-06 06:23 UTC
### Description

Global functions are completely broken. When using a large number of functions between files, everything breaks.

### Steps to Reproduce

1. Create a file and make a function.
2. Try to use that function repeatedly in other files. (Errors show up sometimes on reload!)

### Expected Behavior

Global functions should work across all scripts.

### Errors / Screenshots

![Screen Shot 2020-12-06 at 12 18 25 AM](https://user-images.githubusercontent.com/64096464/101273154-91efe580-3758-11eb-844c-c445eb134283.png)
^ This fills the console.

### Server Information
* **Server version/platform:**  Paper (ver. Paper-288) 1.16.4
* **Skript version:**  2.5.2

### Additional Context

This is VERY similar to an issue that happened on Minehut. The person responsible for maintaining the Minehut fork had to fix this same issue. Minehut's fork also doesn't have this issue!

**Comment by ShaneBeee** [comment] 2020-12-06 07:21
Closing due to:
1) the issue this user was having was an underling issue caused by -> #3585 
2) the issue present here is just user error, but this user didn't have incorrect code it was just caused from the other issue.

**Closed by ShaneBeee** 2020-12-06 07:21 UTC
