### ISSUE TITLE
Proposal to change the vehicle enter event 

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#1450] opened 2018-08-07 10:55 UTC
Hi, i think that arguments in the event "on vehicle enter" are a bit weird and without any logics :

https://skripthub.net/docs/?id=1064

```
on vehicle enter:
    broadcast "%passenger of event-entity% /// %event-entity%"
    event-entity is a minecart or a boat
    passenger of event-entity is not a player
    cancel event
```

cause of : 
*  "passenger of event-entity" would said that the passenger is already in the vehicle BUT the event is cancelable so it's not logic !

** "event-entity" return the vehicle and not the entity which try to enter in the vehicle.

*** in 1.11.2+ there is multiple passengers in a vehicle, so it's not possible to detect witch new entity try to enter in the vehicle with a simple expresion.

**I suggest to change expressions with :**
event-vehicle / vehicle
event-entity (=the entity wich try to enter in the vehicle)
all passengers of [event-]vehicle (=entities wich are already in the vehicle BUT without event-entity)

```
on vehicle enter:
    broadcast "%event-entity% /// %event-vehicle%"
    vehicle is a minecart or a boat
    event-entity is not a player
    cancel event
```

**Comment by Snow-Pyon** [comment] 2018-08-18 11:38
In fact, it should have been like this but Njol (or whoever implemented it) kinda messed up the things with event values, as you can see on #1337.

**Comment by Wealthyturtle** [comment] 2020-07-10 07:57
Marking as duplicate of #1337

**Closed** 2020-07-10 07:57 UTC
Labels: enhancement, priority: lowest
