### ISSUE TITLE
Spawn <mob type> issue

### ISSUE THREAD

**Issue by idealwolf** [SkriptLang/Skript#3386] opened 2020-09-19 00:57 UTC
### Description
When i try to spawn multiple mobs at the same time i get spammed with this error at my console and sometimes the server crashes

on damage issue:
 when i use the event on damage it spams errors and stop the server

### Steps to Reproduce
```vb
command skele2:
	trigger:
		spawn a skeleton at player
		set display name of last spawned skeleton to "&6[T2] Skeleton"
		set max health of last spawned skeleton to 24
		equip last spawned skeleton with leather helmet
		equip last spawned skeleton with iron chestplate
		equip last spawned skeleton with iron boots
		enchant tool of last spawned skeleton with power 2
		enchant tool of last spawned skeleton with flame 1
```

```vb
on damage:
    victim is a zombie
    send "lol" 
```

### Expected Behavior
It should fill the console with errors and lag a but and sometimes the server restarts / crashes

### Errors / Screenshots
None in game only in console

https://pastebin.com/ZtSckTCH

for the second one: https://pastebin.com/V62S68aS

### Server Information
* **Server version/platform:** 1.12.2 / Paper Spigot -1618
* **Skript version:** 2.5-beta-2

**Comment by ShaneBeee** [comment] 2020-09-19 22:40
I just tested using Skript 2.5-beta4 and paper git-Paper-1618 (MC: 1.12.2),
no console errors.

Outcome:
<img width="966" alt="Screen Shot 2020-09-19 at 3 38 44 PM" src="https://user-images.githubusercontent.com/20008482/93690541-4baab480-fa8e-11ea-8d82-b7ea3ae735ab.png">


I can not replicate this issue. Can you please try replicate this on beta4

**Comment by idealwolf** [comment] 2020-09-19 22:51
I did and the mob spawning is working but the on damage is still not working it just fills my console with errors

**Comment by ShaneBeee** [comment] 2020-09-21 00:39
I could not reproduce that either.

code:
```vb
on damage:
	if victim is a zombie:
		send "Zombie" to all players
```
<img width="966" alt="Screen Shot 2020-09-20 at 5 38 25 PM" src="https://user-images.githubusercontent.com/20008482/93725951-24c0b100-fb68-11ea-9742-e945b79876da.png">

no console errors
message sends, nothing wrong from what I can see.

**Comment by Govindass** [comment] 2020-09-21 09:51
I recommend trying to update to 2.5beta4

**Comment by ShaneBeee** [comment] 2020-09-23 09:18
Closing due to can not replicate this error.

My assumption is its a plugin conflict of some kind.

**Closed by ShaneBeee** 2020-09-23 09:18 UTC
Labels: waiting for reply
