### ISSUE TITLE
Spiggot

### ISSUE THREAD

**Issue by SirAquapyr0** [SkriptLang/Skript#2226] opened 2019-07-03 18:55 UTC
I know that it has already been asked but it's been a year and nothing changed.
Will it be post as verified on spigot so aternos users can use it ?

**Comment by ShaneBeee** [comment] 2019-07-03 19:38
Duplicate of #1475

**Comment by TheBentoBox** [comment] 2019-07-03 19:45
If you know there's already an open issue for something, don't post another one.

**Closed by TheBentoBox** 2019-07-03 19:45 UTC
