### ISSUE TITLE
Right click event returns type of targeted block

### ISSUE THREAD

**Issue by rudde0** [SkriptLang/Skript#2879] opened 2020-03-25 15:00 UTC
### Description
I was testing my codes which I wrote on Skript 2.4 and I realized event-item's changed as targeted block.

### Steps to Reproduce
```
on right click:
	broadcast "%event-item%"
```

### Expected Behavior
It should return the player's hand or off hand

### Errors / Screenshots
http://prntscr.com/rmlbvw

### Server Information
* **Server version/platform:**       Paper Build 143 (MC 1.15.2)
* **Skript version:**                2.5-alpha1

### Additional Context
event-item was fine on Skript 2.4.1

**Comment by ShaneBeee** [comment] 2020-03-25 20:53
Duplicate of #2771

**Closed by ShaneBeee** 2020-03-25 20:53 UTC
