### ISSUE TITLE
Skript Sound Error

### ISSUE THREAD

**Issue by Techno3600** [SkriptLang/Skript#1399] opened 2018-07-20 14:02 UTC
I'm on the latest version of Skript now. Still errors, it's not Skellet because I've disabled its sound effect.

https://pastebin.com/KS3H7Jpk

Thanks
Techno

**Comment by Nicofisi** [comment] 2018-07-20 14:08
Code please

**Comment by Techno3600** [comment] 2018-07-20 14:14
https://pastebin.com/zHQdGBVQ

**Comment by Techno3600** [comment] 2018-07-20 14:16
After a restart, it works fine, but then it starts glitching later into the server's life.

**Comment by Techno3600** [comment] 2018-07-20 16:11
Thanks, but has the issue been processed?

**Comment by Techno3600** [comment] 2018-07-21 00:09
This should definitely be in a hotfix, it's a really pressing issue on my server. Almost all of my scripts are based around this effect. Whenever it errors the whole script stops working.

**Comment by Snow-Pyon** [comment] 2018-07-21 01:41
We can't do anything without information. Can you provide an example code that could cause this? What verbose level do you have in your config.sk?

**Comment by Techno3600** [comment] 2018-07-21 01:53
I’ll  set it to maximum level and make it error.

**Comment by Nicofisi** [comment] 2018-07-21 10:41
It isn't supposed to work actually. The play sound effect accepts only one location:
https://github.com/SkriptLang/Skript/blob/c3febaedb89a7ed00223bcceb44971951f06f011/src/main/java/ch/njol/skript/effects/EffPlaySound.java#L48
and you do "at all players"
```
 play sound "block.note.pling" at all players for all players
```
It shouldn't even parse I think (why does it?)

**Comment by Techno3600** [comment] 2018-07-21 13:30
Well that should be supported in the next update.

**Comment by Techno3600** [comment] 2018-07-21 13:31
Oh I see, I think it only errors when there’s more than one player online, let me check.

**Comment by Techno3600** [comment] 2018-07-21 13:43
Okay, here's the level of output at level "debug"

https://gist.github.com/Techno3600/767608bb1b4e78ef15da1c58a3974f88

**Comment by Snow-Pyon** [comment] 2018-07-21 23:01
The issue is actually an user-error but it shouldn't throw this stacktrace nor even parse at all. Closing since there's an issue open about this already.

For now, do:
```vb
loop all players:
  play sound "block.note.pling" at player
```
and it should work,

**Closed by Snow-Pyon** 2018-07-21 23:01 UTC
