### ISSUE TITLE
NotSerializableException for CraftMetaItem 

### ISSUE THREAD

**Issue by TPGamesNL** [SkriptLang/Skript#3185] opened 2020-07-21 15:30 UTC
### Description
A `NotSerializableException` is thrown whenever an item is saved to a global variable.

### Steps to Reproduce
```
command /err:
	trigger:
		set {stone} to stone
```

### Expected Behavior
No errors obviously

### Errors / Screenshots
https://pastebin.com/P4W9BmaK

### Server Information
* **Server version/platform:** 1.15.2 (paper-379)
* **Skript version:** 2.5-alpha6

### Additional Context
None

**Comment by Pikachu920** [comment] 2020-07-21 15:36
@APickledWalrus

**Comment by APickledWalrus** [comment] 2020-07-21 15:50
Hey, does this occur every time you run the command? If so, does it occur with items that have names, enchantments, or etc.?

**Comment by TPGamesNL** [comment] 2020-07-21 15:52
Yes, everything the command is run and I also tried with a named item, same error. I haven't tried with enchantments.

**Comment by APickledWalrus** [comment] 2020-07-21 15:57
Okay, I am going to investigate if this occurs on other versions.

**Comment by APickledWalrus** [comment] 2020-07-21 17:09
Can someone confirm whether this issue is present on alpha5?

**Comment by TPGamesNL** [comment] 2020-07-21 17:12
This issue is not present on alpha5

**Comment by Romitou** [comment] 2020-07-21 18:30
I can confirm this issue only with 2.5-alpha6 on Paper 1.15.2.

**Comment by APickledWalrus** [comment] 2020-07-22 15:35
The cause of this issue has been found, it just needs to be patched.

**Comment by APickledWalrus** [comment] 2020-07-25 20:38
Going to downgrade this since it doesn't affect the current release. It **must** be fixed for the next release though.

**Comment by ShaneBeee** [comment] 2020-08-06 19:35
Marking this as completed and closing. 
Im not sure why this was missed but it was fixed in 2.5-beta1

**Closed by ShaneBeee** 2020-08-06 19:35 UTC
Labels: bug, completed, priority: high

**Comment by TPGamesNL** [comment] 2020-08-28 17:57
Why exactly was this closed? I know that this specific case is no longer present in the latest release, but the underlying issue with Yggdrasil's serializer is still present.
