### ISSUE TITLE
On Inventory Click

### ISSUE THREAD

**Issue by Norbiros** [SkriptLang/Skript#4352] opened 2021-10-08 14:31 UTC
### Skript/Server Version

```
[16:20:40 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:20:40 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[16:20:40 INFO]: [Skript] Server Version: git-Paper-92 (MC: 1.17.1)
[16:20:40 INFO]: [Skript] Skript Version: 2.6-beta3
[16:20:40 INFO]: [Skript] Installed Skript Addons:
[16:20:40 INFO]: [Skript]  - DiSky v2.1 (https://disky.itsthesky.info/)
[16:20:40 INFO]: [Skript]  - skUtilities v0.9.2 (https://tim740.github.io/)
[16:20:40 INFO]: [Skript]  - SkQuery v4.1.5
[16:20:40 INFO]: [Skript]  - SkBee v1.11.3 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

Cancel event in On Inventory Click didn't work for me. While spaming i can move and pickup and place items into chest. 
I want to add my average ping is 70, tps is 20 so it can't be lag problem.

### Expected Behavior

It must cancel event

### Steps to Reproduce

It happend in 2 ways:

1. When i spam click and move mouse between 2 slots
2. When i click on slot, drag mouse while pulling it. Then item shows in first slot

### Errors or Screenshots

```
https://cdn.discordapp.com/attachments/138027100593455104/896035803627667466/Screencast_from_08.10.2021_160652.webm
```

### Other

It is in some kind, something like bug #3744.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-10-08 15:28
Yea this is a duplicate of #3744. The inventory click event is not called when you drag items. Even if it is a single pixel over a single slot with an item amount of 1, it still calls the drag event instead of the click event.

**Closed as completed by TPGamesNL** 2021-10-08 15:28 UTC
