### ISSUE TITLE
Skript internal error on command

### ISSUE THREAD

**Issue by TheJappie27** [SkriptLang/Skript#5526] opened 2023-03-16 07:39 UTC
### Skript/Server Version

```markdown
sk info
[07:35:18 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[07:35:18 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[07:35:18 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[07:35:18 INFO]: [Skript] Server Version: git-Paper-446 (MC: 1.19.3)
[07:35:18 INFO]: [Skript] Skript Version: 2.7.0-beta1 (skriptlang-github)
[07:35:18 INFO]: [Skript] Installed Skript Addons: 
[07:35:18 INFO]: [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[07:35:18 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[07:35:18 INFO]: [Skript]  - DiSky v4.11.0
[07:35:18 INFO]: [Skript]  - SkBee v2.7.7-for-Skript-2.7.0-beta1 (https://github.com/ShaneBeee/SkBee)
[07:35:18 INFO]: [Skript] Installed dependencies: 
[07:35:18 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

So i have a command that sets a variable to true (sounds pretty basic to me), but when i execute it i get a huge error (see down below). Posted this in the SkUnity discord server and got told to make an issue out of this since someone higher up should take a look at it. I don't have any issues with other variables, just this one that's broken

### Expected Behavior

It was supposed to just set a variable to true to toggle between normal chat and a staff chat for all staff members

### Steps to Reproduce

```
command /staffchat [<text>]:
	permission: dangeruse.staffchat
	aliases: sc, staffc, schat
	trigger:
		if arg 1 isn't set:
			if {dangeruse::staffchat::%player's uuid%} isn't set:
				set {dangeruse::staffchat::%player's uuid%} to true
				send "{@prefix} &aYou &a&lENABLED &aStaffchat"
			else:
				delete {dangeruse::staffchat::%player's uuid%}
				send "{@prefix} &aYou &c&lDISABLED &aStaffchat"
		else:
			send "{@staffprefix} &7| &r%player's prefix% &r&e%player's displayname% {@chat_sign} %{dangeruse::chatcolor::%player%}%%arg-1%"
```

This is the code that's acting weird.

### Errors or Screenshots

[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! [Skript] Severe Error:
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Something went horribly wrong with Skript.
[07:19:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[07:19:08 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[07:19:08 ERROR]: #!#! Here is full list of them:
[07:19:08 ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders) skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui) DiSky v4.11.0 SkBee v2.7.7-for-Skript-2.7.0-beta1 (https://github.com/ShaneBeee/SkBee) 
[07:19:08 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[07:19:08 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[07:19:08 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[07:19:08 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[07:19:08 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[07:19:08 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Stack trace:
[07:19:08 ERROR]: #!#! java.util.NoSuchElementException
[07:19:08 ERROR]: #!#!     at java.base/java.util.ArrayDeque.getFirst(ArrayDeque.java:402)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.structures.StructVariables$DefaultVariables.add(StructVariables.java:100)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.VariableString.toString(VariableString.java:551)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.set(Variable.java:497)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Variable.change(Variable.java:553)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.effects.EffChange.execute(EffChange.java:280)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Effect.run(Effect.java:50)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:312)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:277)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:282)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands.handleCommand(Commands.java:193)
[07:19:08 ERROR]: #!#!     at Skript-2.7.0-beta1.jar//ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:152)
[07:19:08 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[07:19:08 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[07:19:08 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:19:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[07:19:08 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[07:19:08 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2264)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[07:19:08 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[07:19:08 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[07:19:08 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[07:19:08 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[07:19:08 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[07:19:08 ERROR]: #!#!     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[07:19:08 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[07:19:08 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Version Information:
[07:19:08 ERROR]: #!#!   Skript: 2.7.0-beta1 (latest)
[07:19:08 ERROR]: #!#!     Flavor: skriptlang-github
[07:19:08 ERROR]: #!#!     Date: 20:28:50.750636200
[07:19:08 ERROR]: #!#!   Bukkit: 1.19.3-R0.1-SNAPSHOT
[07:19:08 ERROR]: #!#!   Minecraft: 1.19.3
[07:19:08 ERROR]: #!#!   Java: 17.0.6 (OpenJDK 64-Bit Server VM 17.0.6+10)
[07:19:08 ERROR]: #!#!   OS: Linux amd64 5.15.0-46-generic
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Server platform: Paper
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Current node: null
[07:19:08 ERROR]: #!#! Current item: set {dangeruse::staffchat::%the UUID of the player%} (as java.lang.Object) to [[boolean:true]]
[07:19:08 ERROR]: #!#! Current trigger: command /staffchat (simple event) (moderation.sk, line 48)
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Thread: Server thread
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! Language: english
[07:19:08 ERROR]: #!#! Link parse mode: STRICT
[07:19:08 ERROR]: #!#! 
[07:19:08 ERROR]: #!#! End of Error.
[07:19:08 ERROR]: #!#! 

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2023-03-16 07:41
Are you using default variables?
Sounds like a duplicate of #5510

**Closed** 2023-03-16 10:41 UTC
Labels: duplicate

**Comment by AyhamAl-Ali** [comment] 2023-03-16 15:04
> The variable causing the issue is not being set in any variable section

It's the same internal code/concept causing it that's why it's a duplicate
