### ISSUE TITLE
Alias bug: fire block cannot be checked

### ISSUE THREAD

**Issue by TwinkleToes777** [SkriptLang/Skript#5497] opened 2023-03-08 13:23 UTC
### Skript/Server Version

```markdown
[14:20:40 INFO]: §7[§6Skript§7]§r Server Version: §3git-Purpur-1171 (MC: 1.16.5)
[14:20:40 INFO]: §7[§6Skript§7]§r Skript Version: §32.6.4
[14:20:40 INFO]: §7[§6Skript§7]§r Installed Skript Addons: §3
[14:20:40 INFO]: §7[§6Skript§7]§r  - skript-yaml v1.4
[14:20:40 INFO]: §7[§6Skript§7]§r  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[14:20:40 INFO]: §7[§6Skript§7]§r  - SkBee v1.15.2 (https://github.com/ShaneBeee/SkBee)
[14:20:40 INFO]: §7[§6Skript§7]§r  - Skore v2.0.1
[14:20:40 INFO]: §7[§6Skript§7]§r  - Skript-Packet v2.1.1 (www.github.com/Anarchick/skript-packet)
[14:20:40 INFO]: §7[§6Skript§7]§r  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[14:20:40 INFO]: §7[§6Skript§7]§r  - skDragon v0.17.5
[14:20:40 INFO]: §7[§6Skript§7]§r  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[14:20:40 INFO]: §7[§6Skript§7]§r  - SkQuery v4.1.6
[14:20:40 INFO]: §7[§6Skript§7]§r  - SkriptJSON v1.0.0
[14:20:40 INFO]: §7[§6Skript§7]§r  - SkJade v1.4.2 (https://www.github.com/Ankoki-Dev/SkJade)
[14:20:40 INFO]: §7[§6Skript§7]§r Installed dependencies: §3
[14:20:40 INFO]: §7[§6Skript§7]§r  - Vault v1.7.3-b131
[14:20:40 INFO]: §7[§6Skript§7]§r  - WorldGuard v7.0.5+3827266
```

### Bug Description

if block at {_loc} is fire:

throws error that fire is a visual effect? how to check for fire? I tried "fire block"

### Expected Behavior

before I updated from 2.6.1 to 2.6.4 it worked, now fire is a visual effect

### Steps to Reproduce

reload a script with:
on join:
block at player is fire

### Errors or Screenshots

Can't compare a block with a visual effect

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment] 2023-03-09 00:57
Duplicate of #4769
Have you tried using `fire block`?

**Comment by TheLimeGlass** [comment] 2023-03-09 13:22
Found and fixed the issue in an upcoming pull request.

### Issue description
Essentially if an expression is an unparsed literal, you convert it to Object.class or use the defending literal utils class, this will allow that UnparsedLiteral to now be a proper literal. Well that also solidifies it's value now. So CondCompare was doing this and Skript picked VisualEffect each time for fire and not even comparators can save that because a block nor itemtype can be converted to a visual effect and vice versa. So I fixed it so it doesn't do this but rather check the context it's comparing against, and attempt to convert to something it can compare and convert to. So for example in this issue, Skript should be converting a block to an itemtype and then also ensuring the UnparsedLiteral is parsed as an ItemType.

**Closed** 2023-06-06 04:51 UTC
Labels: bug, priority: low, completed
