### ISSUE TITLE
Can't use the letter "İ"

### ISSUE THREAD

**Issue by UsainSrht** [SkriptLang/Skript#4465] opened 2021-12-15 13:16 UTC
### Skript/Server Version

![image](https://user-images.githubusercontent.com/59025999/146193015-cc9fa998-5cd2-452e-8e0b-f0bc86cc607a.png)

Skript 1.18 version shared by ShaneBee on SkUnity discord.

### Bug Description

Skript gives error at lines that contains "İ"

### Expected Behavior

no errors

### Steps to Reproduce

just use some code that contains "İ"

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/59025999/146193186-c2039bc0-ee2a-493e-97f1-d6c46b665ff2.png)

### Other

I've tried doubling the "İ" but it doesn't work
And it was working fine at normal 2.6 version

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-12-15 13:28
Addon Issue (Disky) check the solution here: https://github.com/SkriptLang/Skript/issues/4462#issuecomment-992424020

**Comment by UsainSrht** [comment] 2021-12-15 13:35
> Probably addon issue (Disky) check the solution here: [#4462 (comment)](https://github.com/SkriptLang/Skript/issues/4462#issuecomment-992424020) not sure if it will work with you since you have Disky v2.2

It's not the issue
![image](https://user-images.githubusercontent.com/59025999/146196177-5891fd09-9940-4948-b3c4-ca3c55955895.png)

**Comment by UsainSrht** [comment] 2021-12-15 13:40
It wasn't giving error when I was using normal 2.6

**Comment by TPGamesNL** [comment] 2021-12-15 14:03
Can confirm, medium prio since it's not present in a release (an official one, that is).

**Comment by Pikachu920** [comment] 2021-12-18 03:36
maybe as part of a fix for this we can add a test for parsing less common strings like this

**Comment by PaxYT** [comment] 2021-12-19 17:02
This post is duplicate of #4455 !

**Comment by TPGamesNL** [comment] 2021-12-19 17:03
> This post is duplicate of #4455 !

@PaxYT It doesn't matter which is a duplicate of which, it's just about an **issue** (not discussion, they're only for feature requests) being open

**Closed** 2022-01-26 05:29 UTC
Labels: bug, priority: medium, completed
