### ISSUE TITLE
Suggest: Adding PlaceholderAPI placeholders suuport to Skript

### ISSUE THREAD

**Issue by iTzAyhamHD** [SkriptLang/Skript#1425] opened 2018-07-29 16:16 UTC
Some people can't use Skellett in shared hosting so it would be great to add support to PlaceholderAPI placeholders in Skript it self.

Thanks.

**Comment by supertassu** [comment] 2018-07-29 16:30
Duplicate of #644

**Closed** 2018-07-29 19:47 UTC
Labels: duplicate

**Comment by Snow-Pyon** [comment] 2018-07-31 03:10
@TheLimeGlass there is no need to be rude about it. The issue is closed and the fact that someone uses whatever host they want doesn't mean they can't ask for a feature to be in Skript.

**Comment by TheLimeGlass** [comment] 2018-07-31 12:27
Free hosts limit what plugins are allowed on their server. Don't use a free host.

**Comment by Blueyescat** [comment] 2018-07-31 15:59
@TheLimeGlass serveromat doesn't limit plugins or something
