### ISSUE TITLE
Message Formatted Can't Handle Special Characters

### ISSUE THREAD

**Issue by Plutoren** [SkriptLang/Skript#3002] opened 2020-05-22 08:16 UTC
### Description
Certain characters cause the `<tooltip>` syntax to melt into a small puddle of uselessness.  

### Steps to Reproduce
Here's a very simple example:
`message formatted "<tooltip:Te$t>test"`
The issue is caused by the $ symbol. When reloading a skript with this syntax a console error appears. Notably a command using this syntax will become an unknown command. https://pastebin.com/raw/JP1YRRrB

You might be thinking "Just add a \ in front of the $" and you'd be right, this does prevent the reload error from happening, however when you actually go to send the message it fails and throws pretty much the same error. https://pastebin.com/raw/STdPYFka

Now you might be thinking "Just use a temp variable and call `<tooltip:%{_text}%>test`" but alas this does not help. https://pastebin.com/raw/4rawNd6d 

### Expected Behavior
The tooltip would send without errors and include the $ symbol when hovering over the message.

### Errors / Screenshots
(Linked above)
https://pastebin.com/raw/JP1YRRrB
https://pastebin.com/raw/STdPYFka
https://pastebin.com/raw/4rawNd6d 

### Server Information
Server: Paper-301 (1.15.2)
Skript: 2.5-alpha3

### Additional Context
I've done some other testing that would lead me to believe there are is likely other symbols that cause issues with the tooltip syntax but more testing is needed.

**Comment by Govindass** [comment] 2020-05-22 12:23
I've already reported this issue earlier, thus this is duplicate of https://github.com/SkriptLang/Skript/issues/2706

**Comment by Wealthyturtle** [comment] 2020-05-25 07:35
Closing as this has been reported before.

**Closed by Wealthyturtle** 2020-05-25 07:35 UTC
