### ISSUE TITLE
Unusable Anvil GUI

### ISSUE THREAD

**Issue by Lightspeedz** [SkriptLang/Skript#4586] opened 2022-02-10 06:27 UTC
### Skript/Server Version

[13:30:26 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[13:30:26 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[13:30:26 INFO]: [Skript] Server Version: 3417-Spigot-862678e-1eeba6a (MC: 1.18.1)
[13:30:26 INFO]: [Skript] Skript Version: 2.6.1
[13:30:26 INFO]: [Skript] Installed Skript Addons: 
[13:30:26 INFO]: [Skript]  - Skacket v1.0.8
[13:30:26 INFO]: [Skript]  - SkWaze v3.0.5
[13:30:26 INFO]: [Skript]  - Skellett v2.0.2 (https://forums.skunity.com/resources/skellett.24/)
[13:30:26 INFO]: [Skript]  - Tablisknu v1.0 (tlatoani.us/tablisknu)
[13:30:26 INFO]: [Skript]  - skDragon v0.18
[13:30:26 INFO]: [Skript]  - skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect)
[13:30:26 INFO]: [Skript]  - skRayFall v1.9.26 (https://sk.rayfall.net/)
[13:30:26 INFO]: [Skript]  - SkQuery v4.1.6
[13:30:26 INFO]: [Skript]  - SkBee v1.14.2 (https://github.com/ShaneBeee/SkBee)
[13:30:26 INFO]: [Skript]  - SkJade v1.4 (https://www.github.com/Ankoki-Dev/SkJade)
[13:30:26 INFO]: [Skript]  - Skript-Packet v2.0.1 (www.github.com/Anarchick/skript-packet)
[13:30:26 INFO]: [Skript]  - skript-holo v1.0.2 (https://github.com/Blueyescat/skript-holo)
[13:30:26 INFO]: [Skript] Installed dependencies: None

### Bug Description

The anvil GUI created by using "open anvil inventory" is not usable in 1.18.1. The GUI is different from the one after clicking an actual anvil. (I guess the anvil GUI is from the previous versions)

### Expected Behavior

An usable anvil GUI like the one after clicking an actual anvil.

### Steps to Reproduce

Typing "!open anvil inventory to me" in game.

### Errors or Screenshots

![skript open anvil inventory](https://user-images.githubusercontent.com/99382928/153349905-01c38783-fa06-439f-8640-753736e8733d.png)
![clicking an actual anvil](https://user-images.githubusercontent.com/99382928/153349909-4228fd8f-2217-4d95-98c2-e49655b4d6f0.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2022-02-10 13:18
Duplicate of https://github.com/SkriptLang/Skript/issues/3035 / https://github.com/SkriptLang/Skript/issues/41

**Closed by TPGamesNL** 2022-02-10 13:18 UTC
