### ISSUE TITLE
Skript broken on 1.18.1

### ISSUE THREAD

**Issue by Cerquaas** [SkriptLang/Skript#4479] opened 2021-12-24 14:27 UTC
### Skript/Server Version

```
2.6 (I can't even load skript so I can run /skript info.)
Server is 1.18.1
```

### Bug Description

I recently updated my server to 1.18(.1) and I get this error when running Skript. It doesn't create a folder, doesn't appear in the plugins list, and gives an error in console. This is extremely annoying as Skript is a crucial part of my server. Skript works perfectly fine with my 1.17.1 test server.

### Expected Behavior

Skript was supposed to load, create a folder and allow me execute commands and load scripts.

### Steps to Reproduce

I started my 1.18.1 Spigot server with Skript 2.7.

### Errors or Screenshots

```
[09:22:42] [Server thread/ERROR]: Could not load 'plugins\Skript (4).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3375-Spigot-8965a50-319ca70]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.isRunning()
	at ch.njol.skript.Skript.<clinit>(Skript.java:1050) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 7 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.isRunning()
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at ch.njol.skript.Skript.<clinit>(Skript.java:1048) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 7 more
```

### Other

The only other plugin I have on the server is WorldEdit.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-12-24 14:32
Duplicate of https://github.com/SkriptLang/Skript/issues/4466

**Closed by TPGamesNL** 2021-12-24 14:32 UTC
