### ISSUE TITLE
Inventory slot cant be set to a variable anymore.

### ISSUE THREAD

**Issue by L3v3lup** [SkriptLang/Skript#3357] opened 2020-08-31 16:24 UTC
### Description
Since Beta Update #3, an inventory slot cant be set to a variable anymore.

### Steps to Reproduce
Code:
```
command /test:
	trigger:
		open hopper inventory to player
		set {_value} to "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjIyMWRhNDQxOGJkM2JmYjQyZWI2NGQyYWI0MjljNjFkZWNiOGY0YmY3ZDRjZmI3N2ExNjJiZTNkY2IwYjkyNyJ9fX0"
		set {_skull} to skull from skin with value {_value} signature ""
		set slot 2 of player's current inventory to {_skull} named "&2&lVotelinks des Servers" with lore "&7&oDieses Item kann angeklickt werden," and "&7&oum den Link im Chat zu öffnen."
```

### Expected Behavior
-

### Errors / Screenshots
```
[17:55:46] [Server thread/ERROR]: [Skript] {_skull} named "Votelinks des Servers" is not an item type (Essentials.sk, line 68: set slot 2 of {_p}'s current inventory to {_skull} named "&2&lVotelinks des Servers" with lore "&7&oDieses Item kann angeklickt werden," and "&7&oum den Link im Chat zu öffnen."')
```

### Server Information
* **Server version/platform:** git-Paper-174 / MC 1.16.2
* **Skript version:** Skript 2.5-beta3

### Additional Context
Broke in the latest update (beta 3)

**Comment by vhone** [comment] 2020-09-02 12:59
It works correctly when I write down the item name directly, but I get an error when I use variables.

```
command /test1:
	trigger:
		set {_item} to white stained glass
		set slot 5 of chest inventory with 6 rows to {_item} named "item"
		
		# a slot can't be set to {_item} named "item" because the latter is neither an item type nor an item stack


command /test2:
	trigger:
		set slot 5 of chest inventory with 6 rows to white stained glass named "item"
		
		# non error
```

**Comment by Romitou** [comment] 2020-09-02 13:00
Related to #3347

**Comment by ShaneBeee** [comment] 2020-09-03 22:36
Closing as duplicate of #3347

**Closed by ShaneBeee** 2020-09-03 22:36 UTC
