### ISSUE TITLE
2.6.1 breaks colourising strings / chat with hex colour codes expanded from variables

### ISSUE THREAD

**Issue by Shirk** [SkriptLang/Skript#4680] opened 2022-03-20 20:16 UTC
### Skript/Server Version

```markdown
[Skript] Server Version: git-Paper-73 (MC: 1.18.1)
[Skript] Skript Version: 2.6.1
[Skript] Installed Skript Addons:
[Skript] - skript-yaml v1.3.2
[Skript] Installed dependencies:
[Skript] - Vault v1.7.3-b131
[Skript] - WorldGuard v7.0.6+1cff55f
```

### Bug Description

In previous version of Skript (tested on the same system as posted in Skript/Server Version but with Skript 2.6.0) it worked just fine to use a variable containing a hex-value as string (like, `##aabb00`) in combination with `coloured` to create a valid coloured string. This does only apply to hex values, named colour behave as expected.

So this would work and produce a chat prompt with the player name coloured as expected:

```
function get_colour_string() :: text:
    return "##112233"

on chat:
    set {_colour} to coloured "<%get_colour_string()%>"
    set chat format to "<%{_colour}[player]§r> [message]"
```

In 2.6.0 it produces the chat prompt `"<NameOfThePlayer_in_colour> Message"`
In 2.6.1 it produces the chat prompt  `"<<##112233>##112233NameOfThePlayer> Message"`

### Expected Behavior

`coloured` should colourise any string with named colours and hex codes regardless if they are expanded from a variable or not.

### Steps to Reproduce

Try this sample code:

```
function get_colour_string() :: text:
    return "##112233"

on chat:
    set {_colour} to coloured "<%get_colour_string()%>"
    set chat format to "<%{_colour}[player]§r> [message]"
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-03-20 21:59
Duplicate of #4527

**Closed by AyhamAl-Ali** 2022-03-20 21:59 UTC
