### ISSUE TITLE
Log handlers were not stopped properly, causing variables to not save.

### ISSUE THREAD

**Issue by W0lfyZRex** [SkriptLang/Skript#4047] opened 2021-06-01 12:18 UTC
### Description
I've been getting log handler errors at random times and that causes my server to just hang on shutdown when the "Unloading Skript" line appears, I have to kill it and restart it, it also doesn't save variables at all after the error happens.

### Steps to Reproduce
I do not know what causes it, it says something about parsing? The goal of this issue is for me to know where it comes from.

### Expected Behavior
This error should not happen at all and my variables should get saved

### Errors / Screenshots
![image](https://user-images.githubusercontent.com/66094336/120321754-f6dd6000-c2e3-11eb-9592-bc2f8b90def8.png)
![image](https://user-images.githubusercontent.com/66094336/120321833-0ceb2080-c2e4-11eb-965e-03f13507e780.png)
![image](https://user-images.githubusercontent.com/66094336/120322261-7e2ad380-c2e4-11eb-8309-a329ff7b9bee.png)

### Server Information
* **Server version/platform:** Spigot 1.8.8
* **Skript version:** 2.5.3 (Matocolotoe's retro-compatibility fork, already tried to submit an issue on there but the error doesnt seem to be because of that so I'm sending here as well)

(btw a lot of people say it's because of skript-mirror 1.0 but I don't even have skript-mirror)

**Comment by TPGamesNL** [comment] 2021-06-01 12:47
Duplicate of https://github.com/SkriptLang/Skript/issues/3453 / https://github.com/SkriptLang/Skript/issues/3064, fixed in 2.6-alpha1

**Closed by TPGamesNL** 2021-06-01 12:47 UTC

**Comment by W0lfyZRex** [comment] 2021-06-01 12:58
Cool but that's kind of a fatal error that I can't fix until Matocolotoe releases a 2.6 retro-compatible version of Skript.
It literally makes it so variables do not save and you're just saying a casual "fixed in 2.6-alpha1" while I'm depressed because of the fact that a lot of people's xp and shit don't save (including things that can cost irl money)

**Comment by TPGamesNL** [comment] 2021-06-01 13:00
> Cool but that's kind of a fatal error that I can't fix until Matocolotoe releases a 2.6 retro-compatible version of Skript.
> It literally makes it so variables do not save and you're just saying a casual "fixed in 2.6-alpha1" while I'm depressed because of the fact that a lot of people's xp and shit don't save (including things that can cost irl money)

You're definitely not going to get that fixed complaining on this version of Skript, while you're not even using it

**Comment by W0lfyZRex** [comment] 2021-06-01 13:08
How am I supposed to use Skript 2.6-alpha1 when it's not compatible with 1.8? I don't get it

**Comment by TPGamesNL** [comment] 2021-06-01 13:09
You can't, we don't support 1.8. My point is, why would you complain here? We don't support your version (MC or Skript)

**Comment by W0lfyZRex** [comment] 2021-06-01 13:10
I'm using a special updated fork of SkriptLang/Skript which is made to work on 1.8, this error will keep happening until the owner of the repo releases a 1.8 compatible Skript 2.6

**Comment by TPGamesNL** [comment] 2021-06-01 13:10
> I'm using a special updated fork of SkriptLang/Skript which is made to work on 1.8, this error will keep happening until the owner of the repo releases a 1.8 compatible Skript 2.6

Exactly, so WHY COMPLAIN HERE if you're using a fork?

**Comment by W0lfyZRex** [comment] 2021-06-01 13:11
BECAUSE I'VE ALREADY COMPLAINED ON THE 1.8 REPO AND SINCE EVERYTHING THAT THAT FORK DOES IS JUST ADAPT TO 1.8, I THOUGHT IT WAS A NATIVE SKRIPT ISSUE SINCE THE CODE IS FROM THIS REPO
