### ISSUE TITLE
Uncolored text if there's a color code before

### ISSUE THREAD

**Issue by Matocolotoe** [SkriptLang/Skript#2277] opened 2019-07-21 14:22 UTC
### Description

When putting a color code before some colored text, the text actually becomes uncolored

### Steps to Reproduce

```
command /test <text>:
    trigger:
        send "&b%colored arg%"
```

`/test &aHello !` gives `Hello !` in aqua (`&b`)

### Expected Behavior

The text should be green

### Errors / Screenshots

N/A

### Server Information
* **Server version/platform:** any      
* **Skript version:** 2.4-beta3

**Comment by Kuass** [comment] 2019-08-01 19:40
Same symptoms! Quick fix request!

**Comment by bensku** [comment] 2019-08-04 10:50
Quick fix is unlikely, I'm currently too busy.

**Comment by bensku** [comment] 2019-08-04 10:55
Likely fixed in beta4.

**Comment by Matocolotoe** [comment] 2019-08-04 22:08
Problem is still there in beta5

**Comment by Wealthyturtle** [comment] 2019-08-07 02:39
I'm unable to replicate this issue? Used your skript and tried running ```/test &aHello !```, it yielded
![image](https://user-images.githubusercontent.com/19924575/62590568-69a36d00-b8ff-11e9-8bc3-d67ed30bf151.png)

Similarly, tested with ```/test &ctest``` and it yielded 
![image](https://user-images.githubusercontent.com/19924575/62590591-7627c580-b8ff-11e9-8989-fe0b5716f53e.png)

No aqua or discoloration of text (tested in Skript 2.4-beta5, Spigot 1.14.4)

**Comment by Matocolotoe** [comment] 2019-08-07 17:39
```
function chat(p: player, t: text):
    hasrank(player, "Admin"):
        set {_t} to colored {_t}
    loop all players:
        hasrank(player, "Staff")
        send "&b[Staff] %{_p}% &f: &b%{_t}%" to loop-player
```
Running `chat(player, "&cTest")` gives "Test" in aqua

**Comment by Matocolotoe** [comment] 2019-09-03 15:26
@bensku @Wealthyturtle This issue also happens when using `send colored`
btw `hasrank(player, string)` returns a boolean

**Comment by SiebeDW** [comment] 2019-09-06 16:56
I can not reproduce this on 1.12.2.

I get this:
![image](https://user-images.githubusercontent.com/29002908/64445460-d5cbe900-d0d6-11e9-9d8a-5bc39244f027.png)

Using this code:
![image](https://user-images.githubusercontent.com/29002908/64445394-b208a300-d0d6-11e9-9d16-6ded9521e31c.png)

Skript Version: 2.4-beta7

**Comment by Matocolotoe** [comment] 2019-09-06 17:09
It only happens for me when the text parameter is a command argument

**Comment by Wealthyturtle** [comment] 2019-12-22 02:25
Unable to replicate on Skript 2.4, Paper 1.14.4
```
function hasrank(p: player, s: string) :: boolean:
    return true #For testing purposes

function chat(p: player, t: text):
    hasrank({_p}, "Admin")
    set {_t} to colored {_t}
    loop all players:
        hasrank(loop-player, "Staff")
        send "&b[Staff] %{_p}% &f: &b%{_t}%" to loop-player

command /t1 <string>:
    trigger:
        chat(player, arg-1)

command /t2 <string>:
    trigger:
        chat(player, colored arg-1)
```
^ That's my modified version of the code.

I ran a test with ``/t1 &cTest``, ``/t2 &cTest`` as well as ``!chat(player, "&cTest")`` using the Skript command effects, and all returned a red ``Test``, not blue.

Re-open a new issue if you can replicate this on Skript 2.4 without any addons, since I really can't replicate this issue and others can't as well.

**Closed by Wealthyturtle** 2019-12-22 02:25 UTC
Labels: bug, priority: low
