### ISSUE TITLE
Formatted Hex

### ISSUE THREAD

**Issue by TravelerHere** [SkriptLang/Skript#4758] opened 2022-05-17 09:52 UTC
### Skript/Server Version

```markdown
[09:45:54 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[09:45:54 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[09:45:54 INFO]: [Skript] Server Version: git-Paper-177 (MC: 1.18.1)
[09:45:54 INFO]: [Skript] Skript Version: 2.6.1
[09:45:54 INFO]: [Skript] Installed Skript Addons: 
[09:45:54 INFO]: [Skript]  - SkBee v1.15.3 (https://github.com/ShaneBeee/SkBee)
[09:45:54 INFO]: [Skript] Installed dependencies: 
[09:45:54 INFO]: [Skript]  - Vault v1.7.3-b131
[09:45:54 INFO]: [Skript]  - WorldGuard v7.0.7+216b061
```

### Bug Description

Hex color not working in "send formatted" or "broadcast formatted".

### Expected Behavior

Hex color existing, something like that.

### Steps to Reproduce

`command /broadcast <string>:`
`permission: cmd.broadcast`
`trigger:`
`  broadcast formatted arg-1`

(Argument is "<tooltip:tooltiptxt><#23afcf>Yow")

(It just looks better) It appears as only white instead of something like cyan.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TravelerHere** [comment] 2022-05-17 11:53
well looks like i was wrong, F

**Comment by APickledWalrus** [comment] 2022-05-17 16:46
Duplicate of:
- https://github.com/SkriptLang/Skript/issues/4527

**Closed by APickledWalrus** 2022-05-17 16:46 UTC
