### ISSUE TITLE
Upload Skript to Spigot or Paper website

### ISSUE THREAD

**Issue by ScadeBlock** [SkriptLang/Skript#6111] opened 2023-10-09 10:26 UTC
### Suggestion

Upload Skript to Spigot(https://spigotmc.org/) or Paper(https://papermc.io/) website

### Why?

Because it's easier to reachs to many people that don't know SkriptLang, also it can be add into Aternos

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment] 2023-10-09 10:36
Duplicate of #3678 and #5627.

**Closed by Moderocky** 2023-10-09 10:36 UTC
