### ISSUE TITLE
Chunk Loading in Skript causes very long time to process.

### ISSUE THREAD

**Issue by Fiopon** [SkriptLang/Skript#5293] opened 2022-12-29 19:32 UTC
### Skript/Server Version

```markdown
[19:22:10 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[19:22:10 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[19:22:10 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[19:22:10 INFO]: [Skript] Server Version: git-Paper-362 (MC: 1.19.3)
[19:22:10 INFO]: [Skript] Skript Version: 2.6.4
[19:22:10 INFO]: [Skript] Installed Skript Addons: 
[19:22:10 INFO]: [Skript]  - SkBee v2.6.2 (https://github.com/ShaneBeee/SkBee)
[19:22:10 INFO]: [Skript]  - Khoryl v1.0.6
[19:22:10 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

A simple skript, which only gets leashed entities when a player teleports and then teleports the entities to the players new location, causes the server to take a long time to process. This only happens when reloading the skript or starting the server. I believe it may have something to do with the chunk loading used to ensure mobs get teleported reliably, as when the chunk loading code is removed it doesn't take nearly a minute to reload. Interestingly, when a player does teleport with leashed mobs, the server handles it with no problem.

### Expected Behavior

It shouldn't take nearly a minute for this simple skript to process.

### Steps to Reproduce

Server Version: Paper-362
Server OS: Linux (Unsure on specifics)
Server Plugins: DiscordSRV-Build-1.26.0, Geyser-Spigot, floodgate-spigot, InvisibleItemFrames-1.3.0, itemswapperplugin-0.0.1-SNAPSHOT, Khoryl-1.0.6, LuckPerms-Bukkit-5.4.55, NoChatReports-Spigot-1.0.5, SkBee-2.6.2, Skript-2.6.4, Vivecraft_Spigot_Extensions, voicechat-bukkit-1.19.3-2.3.21
Server RAM: 8GB
Skript Causing Issues: https://gist.github.com/Fiopon/663190a1fa5d1077dadc9d385699b3e8

### Errors or Screenshots

https://gist.github.com/Fiopon/a34f8d053242af235d48cfd000d3bfae

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by TheLimeGlass** [comment] 2022-12-29 19:36
Can you provide the script that you're reloading?

**Comment by TheLimeGlass** [comment] 2022-12-29 19:40
Do note that chunk loading when teleporting is done asynchronously when paper is installed, so there shouldn't be any thread hauling unless you only have 1 thread system or privileges for the server.

**Comment by Fiopon** [comment] 2022-12-29 21:15
Skript is included in Steps to Reproduce section

**Comment by TheLimeGlass** [comment] 2022-12-30 18:20
Cannot reproduce.

Skript doesn't have a load chunk syntax. The syntax isn't even valid for SkBee?
SkBee fails to load on 2.7 so I couldn't test if 2.7 fixes it.
The script provided doesn't work with SkBee installed on Skript 2.6.4, I couldn't even get the syntax to work
```
(load|:unload) chunk at %number%,[ ]%number% (in|of) [world] %world% [ticket:with ticket]
(load|:unload) %chunks% [ticket:with ticket] 

load chunk at x coordinate of {_loc}, z coordinate of {_loc} in world of {_loc} with ticket
load chunk at {_loc} with ticket
```
@ShaneBeee

**Comment by TheLimeGlass** [comment] 2022-12-30 18:21
Closing after reviewed or in a few days.

**Comment by ShaneBeee** [comment] 2022-12-30 23:47
This isn't an SkBee issue, this has to do with the amount of expressions in the location function:
```vb
load chunk chunk at location(x coordinate of {_loc}, y coordinate of {_loc}, z coordinate of {_loc}, world "%world of {_loc}%") with ticket
```
I copy/pasted the code, and used
```vb
load chunk at {_loc} with ticket
```
and it parsed correctly, and very quickly!

**Comment by Fiopon** [comment] 2022-12-31 01:21
Thats so strange, I originally tried that exact line and I was told it couldn't understand.

**Comment by TheLimeGlass** [comment] 2022-12-31 14:05
SkBee issue or duplicate of https://github.com/SkriptLang/Skript/pull/5133

**Closed by TheLimeGlass** 2022-12-31 14:05 UTC
Labels: addon related
