### ISSUE TITLE
skript cannot understand "loop-entitiy"

### ISSUE THREAD

**Issue by kenkencw** [SkriptLang/Skript#3004] opened 2020-05-22 13:20 UTC
### Description

skript cannot understand "loop-entitiy" in a loop

### Steps to Reproduce

```
loop entities in radius 3 of player's location:
	set {_e} to loop-entity
```
or
```
	kill loop-entity
```

### Expected Behavior

i need to catch the entities to do further actions

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/63932383/82671220-0fe31800-9c71-11ea-849d-9143eb5d2e34.png)

### Server Information
* **Server version/platform:**       git-Paper-282 (MC: 1.15.2)
* **Skript version:**                2.5-alpha3

**Comment by TheBentoBox** [comment] 2020-05-22 18:48
Duplicate of #946.

For now. just do `of player` in those cases rather than `of player's location`

**Closed by TheBentoBox** 2020-05-22 18:48 UTC
