### ISSUE TITLE
PlayerMoveEvent error

### ISSUE THREAD

**Issue by arts7493** [SkriptLang/Skript#3081] opened 2020-06-26 09:30 UTC
### Description
[17:24:42] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Skript v2.4.1
java.lang.NullPointerException: null
	at ch.njol.skript.events.EvtMoveOn$1.execute(EvtMoveOn.java:90) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1153) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Expected Behavior
idk

### Server Information
* **Server version/platform:**       paper 372
* **Skript version:**                2.4.1

**Comment by Hexivoid** [comment] 2020-06-27 19:40
You don't know what was/you expected to occur and provided no information on when the error occurred or how to replicate it?

**Comment by Runakai1** [comment] 2020-06-27 19:43
> You don't know what was/you expected to occur and provided no information on when the error occurred or how to replicate it?


I think he just gets it when loading. He's just confused why it's occuring so "idk" suits very well

**Comment by Wealthyturtle** [comment] 2020-06-28 02:06
Needs more information, specifically in how to replicate. Is it a start up error? Is it caused by something in game? Plugins?

**Comment by arts7493** [comment] 2020-06-28 23:18
sometimes cause that error
i think problem is this event
on region enter or on region exit

**Comment by Wealthyturtle** [comment] 2020-06-29 00:53
Script?

**Comment by Misio12320** [comment] 2020-07-23 22:45
28 days still no answer. Time to close?
Whats the time max with no answer? 14 days or 31?

**Comment by ShaneBeee** [comment] 2020-10-02 05:48
closing due to lack of information.

**Closed by ShaneBeee** 2020-10-02 05:48 UTC
Labels: waiting for reply
