### ISSUE TITLE
Multiple expressions broken when working with/parsing as "item" instead of "item type"

### ISSUE THREAD

**Issue by ham1255** [SkriptLang/Skript#1592] opened 2018-10-10 12:08 UTC
set {_item} to "Redstone block" parsed as item

**Comment by ham1255** [comment] 2018-10-10 12:08
![image](https://user-images.githubusercontent.com/34905970/46735246-b948e600-cca6-11e8-8e15-1344be11160c.png)
this befour i name it to redstone block.

**Comment by ham1255** [comment] 2018-10-10 12:10
that code with redstone dust set {_item} to "Redstone dust" parsed as item
![image](https://user-images.githubusercontent.com/34905970/46735333-fdd48180-cca6-11e8-9817-55f594e8a44b.png)

**Comment by Nicofisi** [comment] 2018-10-10 13:02
What Skript version?

**Comment by ham1255** [comment] 2018-10-10 13:13
alpha5

**Comment by TheBentoBox** [comment] 2018-10-10 13:17
Doesn't look like an aliases issues, [see here](https://github.com/SkriptLang/skript-aliases/blob/5de4f9ab7fe7cd852485ee71a57077ac70ece2ed/redstone.sk#L4). Unless the aliases parser isn't handling the plurality very well.

**Comment by ham1255** [comment] 2018-10-10 13:20
Yeah i guess soo

**Comment by ham1255** [comment] 2018-10-10 13:20
**Redstone block**

**Comment by ham1255** [comment] 2018-10-10 13:39
@TheBentoBox then is there fix?

**Comment by TheBentoBox** [comment] 2018-10-10 13:49
Not immediately, I need someone else to confirm this or to be able to test it myself later today.

**Comment by carrymeonbedwars** [comment] 2018-10-10 16:35
I can confrim this broken for me too

I tried to give it to player but the player didnt got the item

**Comment by TheBentoBox** [comment] 2018-10-10 16:46
I imagine there are other items this is an issue with as well (it's probably not isolated to specifically redstone blocks) so this needs to be looked into and addressed.

**Comment by ShaneBeee** [comment] 2018-10-10 21:09
I can confirm this as well, and I think I know why.
"redstone block" isnt an item, its an item type

```
command /test:
	trigger:
		set {_item} to "diamond sword" parsed as item
		give player 1 of {_item}
		send "PARSED ITEM"
		wait 1 second
		set {_itemtype} to "diamond sword" parsed as itemtype
		give player 1 of {_itemtype}
		send "PARSED ITEM TYPE"
		wait 1 second
		give player 1 diamond sword
		send "DIRECT ITEM"
```
With this example, the parsed as item, gave me nothing
parsed as item type gave me the diamond sword

**Comment by TheBentoBox** [comment] 2018-10-11 02:09
Updated title because I've also found this to be the case with the `raw name of %item types%` expression. Doing `send "%raw name of tool%"` doesn't work while holding anything, it just returns `<none>`, you have to do `raw name of type of tool`. It's almost as if some default converter from item stack to item type is broken.

**Comment by TheBentoBox** [comment] 2018-10-11 02:09
Also moving to high priority since this likely affects a number of expressions.

**Comment by TheBentoBox** [comment] 2018-10-11 02:32
Actually, the issue with `raw name` is more complex. It's not working for a number of blocks at all even when using `type of`, e.g. looking at a grass block and running `send "%raw name of type of target block%"` sends `<none>` as does sending the raw name of your tool when holding a grass block. 

However, dirt works fine, but when doing it as a tool you still have to do `type of` for it to work; what I mean is, `send "%minecraft name of target block%"` works when looking at dirt (returns `minecraft:dirt`), but you have to do `send "%minecraft name of type of tool%"` to get it to work while *holding* dirt. I'm suspecting this has to do with whether or not the block has states, but it's hard to say; I also tested with sand (which has no states, like dirt) and it worked without `type of` for both the held and placed states. 

Really bizarre overall, it's not very clear what the consistent issue is that determines if it works. This may warrant a separate report but I somewhat suspect these issues have the same or similar root cause. Gonna add dev needed to see if this warrants separate issues and to get attention quickly since it seems to break a number of things in a hard to work around way.

**Comment by carrymeonbedwars** [comment] 2018-10-11 03:15
Wow because a redstone block wont set lol

**Comment by ham1255** [comment] 2018-10-11 08:32
@ShaneBeee I tried your code instead of that you got my server crashed after server ran out of ram wtfused 8000mb ram

**Comment by ham1255** [comment] 2018-10-11 10:07
And i tested older version of skript alpha1 to 4 and its exist

**Comment by bensku** [comment] 2018-10-11 12:53
Raw name bug most certainly did not apply to anything else, because it was in code that dealt with those names only.

**Comment by TheBentoBox** [comment] 2018-10-11 12:58
Ah ok, I thought it might be related since using `type of` changed my results. Good to see a fix for that one already, at least.

**Comment by ham1255** [comment] 2018-10-11 13:03
And what about parsed as item?

**Comment by bensku** [comment] 2018-10-11 19:32
There were serious issues with plurality mark parsing, which have now been fixed. However, in case of redstone blocks, aliases also have a problem.

@TheBentoBox Could you check that we do not have duplicate aliases? I may be able to make Skript more resistant to them, but they're still considered bugs in aliases.

**Comment by TheBentoBox** [comment] 2018-10-11 19:54
Yeah I can try to take a look as soon as I get a chance. There generally shouldn't be since things were built out of the redstone categories but there could be accidental overlap especially with stuff from merge requests.

**Comment by ham1255** [comment] 2018-10-13 08:02
Ok seems legit
and closing?

**Comment by Nicofisi** [comment] 2018-10-13 10:42
We close completed issues when a new Skript version is released :)

**Comment by ham1255** [comment] 2018-10-13 10:42
oof ok

**Comment by ham1255** [comment] 2018-10-13 10:43
i screwd up cause i am new to this github

**Comment by Nicofisi** [comment] 2018-10-13 10:43
thanks...

**Closed** 2018-10-13 13:18 UTC
Labels: bug, completed, priority: high
