### ISSUE TITLE
Unable to change default no permission message

### ISSUE THREAD

**Issue by thonkinator** [SkriptLang/Skript#4318] opened 2021-09-03 21:12 UTC
### Skript/Server Version

```
[21:02:53 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[21:02:53 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[21:02:53 INFO]: [Skript] Server Version: git-Paper-239 (MC: 1.17.1)
[21:02:53 INFO]: [Skript] Skript Version: 2.6-beta3
[21:02:53 INFO]: [Skript] Installed Skript Addons:
[21:02:53 INFO]: [Skript]  - SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee)
```

### Bug Description

I have this code in `/plugins/Skript/lang/english.lang`, but even after a restart, any Skript commands I use still have their default no permission message set to `You don't have the required permission to use this command` with no colors.
```
commands:
	no permission message: '&cYou do not have the required permissions to use this command.'
```

### Expected Behavior

The no permission message of Skript commands that don't have their no permission message explicitly set will use the no permission message `&cYou do not have the required permissions to use this command.`

### Steps to Reproduce

1. Make a server with Skript-2.6beta3 as one of the plugins.
2. Create a file at `/plugins/Skript/lang/english.lang` with the contents
```
commands:
	no permission message: '&cYou do not have the required permissions to use this command.'
```
and save the file.
3. Create any sort of Skript command without a permission message set. Make sure you don't have the permissions to execute the command.
4. Restart the server.
5. Test the command you made, and the no permission message will still be the default Skript one.

### Errors or Screenshots

There are no errors.

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-09-04 08:33
Duplicate of https://github.com/SkriptLang/Skript/issues/136

**Closed by TPGamesNL** 2021-09-04 08:33 UTC
