### ISSUE TITLE
Allow Conditions to be used as Expressions

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4746] opened 2022-04-29 08:33 UTC
### Suggestion

In Java, we can declare a boolean variable set to a boolean-return method:
```
boolean var = Player#isSneaking();
```
My suggestion is to carry this feature into Skript.

### Why?

This can be useful to simplify the work from using ternaries, we will be able to do this:
```
set {_var} to player's health >= 5  _This might need some pattern re-adjustment to sound more English-friendly_
send "%player can fly% .. %{_list::*} contains "String"%" to console
```
.. instead of this:
```
set {_var} to true if player's health >= 5, else false
send "%true if player can fly, else false% .. %true if {_list::*} contains "String", else false%"
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by Moderocky** [comment] 2022-04-29 10:24
If people are unhappy with the readability of using the condition as an expression directly (`set {var} to player can fly`) we could use `whether %condition%` as an alternative.
`set {var} to whether player can fly`

**Comment by AyhamAl-Ali** [comment] 2022-04-30 00:38
Duplicate of #2207

**Closed by AyhamAl-Ali** 2022-04-30 00:38 UTC
