### ISSUE TITLE
checking named items syntax broken in last beta

### ISSUE THREAD

**Issue by Leonardo-Fiori** [SkriptLang/Skript#3364] opened 2020-09-04 17:26 UTC
i used this line of code to check if player had X regular diamonds (that had no special name or lore):
`if arg-player has arg-number of diamonds named "":`

now, after updating to beta 3, i get this error on load of the script:
`the 1st argument of diamond named "" is not an item type (atm_diamond.sk, line 233: if arg-player has arg-number of diamonds named "":')`

### Server Information
* **Server version/platform:** git-Paper-184
* **Skript version:** Skript version 2.5-beta3

**Comment by Romitou** [comment] 2020-09-04 17:27
This problem has already been reported and completed (https://github.com/SkriptLang/Skript/issues/3347).

**Comment by Leonardo-Fiori** [comment] 2020-09-04 17:50
Where can I find a build for that?

**Comment by Romitou** [comment] 2020-09-04 17:52
You can find a Nightly Build [here](https://github.com/SkriptLang/Skript/actions/runs/229999658), fixing the problem or go to beta2 while waiting for beta4.

**Comment by ShaneBeee** [comment] 2020-09-04 19:05
Closing as duplicate of #3347

**Closed by ShaneBeee** 2020-09-04 19:05 UTC

**Comment by Leonardo-Fiori** [comment] 2020-09-07 15:19
Tested both nightly and beta 2, neither works.

```
if arg-player has arg-number of diamonds named "":
	remove arg-number of diamonds named "" from arg-player's inventory
	add {_worth} to arg-player's money
	... bla bla do stuff 😄 
```

https://giphy.com/gifs/ehOBHL0qObLzL5wqs4
