### ISSUE TITLE
Remove effect don't work properly

### ISSUE THREAD

**Issue by ruddeTR** [SkriptLang/Skript#2404] opened 2019-08-29 15:49 UTC
### Description
I've set my hotbar 0, 1 and 2 with two papers with nbt CustomItems:Summon_Skeleton_1/2/3 and I tried to remove them with function below. I attached two result belongs to Skript 2.3.7 and Skript 2.4-beta-5

### Expected Behavior
Remove just one in each hotbar. So Skript 2.3.7 works properly in that case.

### Errors / Screenshots
No errors in console.
Remove effect in Skript 2.4-beta-5: https://i.imgur.com/P0s2DD2.png
Remove effect in Skript 2.3.7: https://i.imgur.com/9qGhq9c.png

### Server Information
* **Server version/platform:** Paper 1.13.2 Build 643
* **Skript version:** Skript 2.4-beta-5 in first screenshot, Skript 2.3.7 in second screenshot

```
command /nbttest:
	trigger:
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_1""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_2""")
		removeNBTItem(player, 1, "CustomItems:""Summon_Skeleton_3""")
function removeNBTItem(p: player, a: number, nbt: text):
	broadcast " ", " "
	broadcast "&bSearching: %{_nbt}%"
	loop all items in {_p}'s inventory:
		broadcast " "
		nbt of loop-item contains {_nbt}
		broadcast "&cRemoved: %loop-item%(%{_a}%)"
		remove {_a} of loop-item from {_p}
		stop loop
```

**Comment by TheBentoBox** [comment] 2019-08-29 16:45
This is a duplicate of #2354 as it is caused by the same bug.

**Closed by TheBentoBox** 2019-08-29 16:45 UTC
