### ISSUE TITLE
[ERROR] TIMING_STACK_CORRUPTION

### ISSUE THREAD

**Issue by lucasboss45** [SkriptLang/Skript#3042] opened 2020-06-08 09:38 UTC
### Description

TIMING_STACK_CORRUPTION error

### Steps to Reproduce
Line that is supposedly causing the error

```
on right click with heart of the sea:
if item is a custom item with id "Protosphere":
[...]
```

### Expected Behavior
No error

### Errors / Screenshots

https://pastebin.com/kvxmHRc1

### Server Information
* **Server version/platform:** Paper-334 1.15.2
* **Skript version:** 2.4.1

**Comment by ShaneBeee** [comment] 2020-06-08 20:30
Duplicate of #2143

**Closed by ShaneBeee** 2020-06-08 20:30 UTC
