### ISSUE TITLE
"Target entity" does not return the correct entity.

### ISSUE THREAD

**Issue by Blacksoul16** [SkriptLang/Skript#3737] opened 2021-02-05 04:33 UTC
### Description
When I use "target entity" to refer to the entity on which my crosshair is positioned (in this case a zombie), having an item frame in front of the entity (practically on the ground) causes it to return the item frame instead of the entity itself.

### Steps to Reproduce
1. Place something like this and then stand on the gold block facing the zombie.
![bug](https://user-images.githubusercontent.com/31175013/106988925-b7e13880-674f-11eb-9db0-1aa90d572766.png)
2. Use this code and voilà.
```vbs
on rightclick holding stick:
   set {_omg} to player.getTargetEntity(60)
   set {_why} to player.getTargetBlock(60)
   broadcast "&8- &6Skript: &f%target entity% &7| &f%targeted block%"
   broadcast "&7&m                                                    "
   broadcast "&8- &6Skript-reflect: &f%{_omg}% &7| &f%{_why}%"
```

### Expected Behavior
It should return the same entity that Skript-reflect returns. And the same one that appears in the "Targeted Entity" section on the right side of F3.

### Errors / Screenshots
No errors in the console, but.
![bugp2](https://user-images.githubusercontent.com/31175013/106989357-c5e38900-6750-11eb-8ea7-e7ef88089d20.png)

### Server Information
* **Server version/platform:** git-Paper-409 (MC: 1.16.4)
* **Skript version:** 2.5.3

### Additional Context
I only have Skript-reflect.
![additional](https://user-images.githubusercontent.com/31175013/106989838-ca5c7180-6751-11eb-8f0c-042f2ac6805a.png)
Another thing that happened to me when testing this is that there are times when you right click on the entity and the code is executed twice, I don't know if it is another error, but it is a bit annoying.

**Comment by MarinoFTB** [comment] 2021-02-06 23:07
![image](https://user-images.githubusercontent.com/58314919/107131581-08839d80-68d8-11eb-9a28-008e3860ea36.png)
![image](https://user-images.githubusercontent.com/58314919/107131591-176a5000-68d8-11eb-94e3-0c8fc7bb765c.png)
Blue lines is the direction the mob/entity is facing and it's probably the reason why this happens

**Comment by TPGamesNL** [comment] 2021-02-20 19:10
Probably caused by [Utils.java#L122](https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/util/Utils.java#L122)

**Comment by TPGamesNL** [comment] 2021-02-21 11:54
Actually, I'll mark this as a duplicate of https://github.com/SkriptLang/Skript/issues/3675, since both are caused by the same issue

**Closed by TPGamesNL** 2021-02-21 11:54 UTC
Labels: bug, priority: medium
