### ISSUE TITLE
Functions such as floor, ceil, and round change large numbers to 9.223e18

### ISSUE THREAD

**Issue by Xicad** [SkriptLang/Skript#4425] opened 2021-11-16 07:08 UTC
### Skript/Server Version

![image](https://user-images.githubusercontent.com/65637689/141937168-cbbb139c-a6c9-43e5-a5d9-abe09830c2be.png)

### Bug Description

When using the floor, ceiling, or round functions on large numbers they will be reduced to 9.223e18 even though these numbers work normally for other operations like adding, subtracting, etc.

### Expected Behavior

The numbers would not be reduced

### Steps to Reproduce

```
command /test:
	trigger:
		broadcast "&7Floor Function"
		broadcast "%floor(1000000000000000000000000000000000000000000000000000000000000000000000000000)%"
		broadcast " "
		broadcast "&7Ceiling Function"
		broadcast "%ceil(1000000000000000000000000000000000000000000000000000000000000000000000000000)%"
		broadcast " "
		broadcast "&7Round Function"
		broadcast "%round(1000000000000000000000000000000000000000000000000000000000000000000000000000)%"
```

Run this script, see that it does not broadcast the correct number.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/65637689/141936873-756a53cd-e1d7-4419-81c2-f2aa990960e9.png)
![image](https://user-images.githubusercontent.com/65637689/141936893-38c0a6c8-9541-40f0-8f42-a8b8ddd14d60.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TheLimeGlass** [comment] 2021-11-22 15:22
The max value is the size of a Long which is 9,223,372,036,854,775,807.

I don't believe these numbers work normally in subtraction and addition.

This is not a bug, just a Long overflow because the program can only support so large of a number.

**Comment by TPGamesNL** [comment] 2021-11-22 17:52
This does work properly for addition and subtraction, as Skript falls back to Double parsing when Long parsing fails:
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/classes/data/JavaClasses.java#L72-L77

This doesn't work for rounding because Skript rounds by converting the number to a long, which has the aforementioned maximum value. 
1. We could call this intended behaviour, as we have to draw a line for number limits somewhere, and nine quintillion seems like a reasonable one.
2. We could switch to BigDecimal and BigInteger for default number parsing, and make arithmetic expressions and functions be able to handle these without the limits (they can currently handle the types, but will still have the limit).

I'd personally go for the first, as within the usage Skript is made for, I can't see why you'd need numbers this large. As LimeGlass also doesn't think this is a bug, I'm closing this.

**Closed by TPGamesNL** 2021-11-22 17:52 UTC
Labels: won't fix
