### ISSUE TITLE
Make function better

### ISSUE THREAD

**Issue by LowScarlet** [SkriptLang/Skript#4600] opened 2022-02-13 20:48 UTC
### Suggestion

Make the function even better by adding optional arguments
Example: (Python)
```py
def test(a="hello",b="world"):
    print(a,b)

test(b="python")
```
output = `hello python`

### Why?

This is very useful because it can minimize function arguments
Example problem:
```vb
function test(a: text, b: text):
  if {_a} is not set:
    set {_a} to "Hello"
  if {_b} is not set:
    set {_a} to "World"
  send "%{_a}% %{_b}%" to console

on load:
  test({_none}, "Skript") 
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by TeamArty** [comment] 2022-02-13 21:04
Doesn't this already exist?

```
function test(a: text = "Hello", b: text = "World"):
  broadcast "%{_a} %{_b}%"

on load:
  test({_none}, "World")

**Comment by LowScarlet** [comment] 2022-02-13 21:08
> Doesn't this already exist?
> 
> ```
> function test(a: text = "Hello", b: text = "World"):
>   broadcast "%{_a} %{_b}%"
> 
> on load:
>   test({_none}, "World")
>   
> ```

yes butttt, {_none} is annoying

**Comment by Pikachu920** [comment] 2022-02-13 22:14
based on your example it sounds like what you are really asking for is named parameters?

**Comment by LowScarlet** [comment] 2022-02-13 22:16
> test({_none}, "World")

yes
```vb
test(b="Skript")
```

**Comment by TPGamesNL** [comment] 2022-02-15 18:27
Duplicate of https://github.com/SkriptLang/Skript/issues/1185 / https://github.com/SkriptLang/Skript/issues/2993
Maybe not exactly, but close enough: no need to have 3 issues for optional arguments, overloading and named arguments

**Closed by TPGamesNL** 2022-02-15 18:27 UTC
