### ISSUE TITLE
Issue with new version of Skript (2.5.3) on Spigot 1.12.2

### ISSUE THREAD

**Issue by Leadervideo** [SkriptLang/Skript#3674] opened 2021-01-03 13:49 UTC
During server start i have that error all the time:

```
[14:44:57 ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1539)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]

[14:44:57 ERROR]: [Skript] 48 log handlers were not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1606)) [if you're a server admin and you see this message please file a bug report at https://github.com/bensku/skript/issues if there is not already one]
```

There's some fixes available for that?

**Comment by TheDGOfficial** [comment] 2021-01-03 17:10
This error is generally (if not always) caused by using skript-mirror 1.x. You have to use the new 2.x version to solve this.
https://skripttools.net/dl/skript-mirror+2.0.0-SNAPSHOT.jar

Replace the 2.x JAR with the one you have and you should be fine. The only breaking change is fields no longer require ! after them, so remove !'s from field accesses if necessary.

It is callsed a SNAPSHOT since it is not yet released by btk5h, but it should be fine and solve these errors you are getting.

And as a rule of thumb, DO NOT use add-ons if not necessary at all. There is a plenty of things you can do with vanilla Skript, some say only use skript-mirror and you can do all the things with Java style Skript code (via reflection), but since skript-mirror is a hacky way to accomplish this task and it uses reflection; it is slower and not supported. The Skript plugin is not meant for writing Java code directly.

Also the message in the error clearly says "file a bug report at <uri> **if there is  not already one**", even searching "Log handler" in issues, you can find all the duplicate issues with this question.

Perhaps Google or use the GitHub search before creating a new issue? I know the error message says create an issue but it also says if there is not already one.

Also you've deleted the template and didn't provide any information like your server version or Skript version/add-on versions; this issue is from skript-mirror and can be solved by using 2.x, but what if it was a different issue? You deleting the template would make this issue useless then.

**Comment by ShaneBeee** [comment] 2021-01-11 13:25
Closing. As DG stated, this is almost always caused by outdated Skript-mirror.

Please update, and if the issue persists, we can reopen this issue and investigate further.

**Closed by ShaneBeee** 2021-01-11 13:25 UTC

**Comment by Leadervideo** [comment] 2021-01-12 08:15
Yeah it's a problem with skript mirror... Thank you for the help

Il lun 11 gen 2021, 14:26 Shane Bee <notifications@github.com> ha scritto:
