### ISSUE TITLE
Player's Tool is ... Amount Parsing Issues

### ISSUE THREAD

**Issue by BenguMC** [SkriptLang/Skript#4488] opened 2022-01-02 04:06 UTC
### Skript/Server Version

```
Paper 1.17.2 - Skript 2.6
```

### Bug Description

Previously in 1.16.5 Skript builds you could use `if player's tool is {item-variable}` you could compare a singular value with a multiple value and it could output code... For instance, if I had a key item I could check with `if player's tool is {key-item}` then give the item no matter the amount of items I had in my hand. Now in the newest build, the code only continues if the amount matches on a one-to-one ratio... this breaks a ton of my work and I imagine countless other projects.

### Expected Behavior

The code `if player's tool is...` should be able to decipher varying item amounts and understand if the other factors outside of specific amounts are still a match.  

### Steps to Reproduce

```
on load:
     set {item-variable} to 1 of stone named "TEST"

on right click:
     if player's tool is {item-variable}:
          give player 1 of stone
```
First, right click with only one of the items set to the variable, then click with two or more of the items. The remainder of the code will only execute if the item amount is an exact match.

### Errors or Screenshots

```
No errors.
```

### Other

There is a workaround for this, but it breaks many projects... The current workaround I have found is to change `if player's tool is {item-variable}` to `if 1 of player's tool is {item-variable}`. Again, this is a major issue for many projects and should still be investigated, but if anyone else is having the issue, this may help you in the meantime. 

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by DelayedGaming** [comment] 2022-01-02 04:12
Go for `if 1 of player's tool is ....:`.

It will grab 1 of itemstack and use it for comparison.

**Comment by BenguMC** [comment] 2022-01-02 04:14
> 

Yeah, I mentioned that in the Other section, it is not a permanent fix to this issue however.

**Comment by APickledWalrus** [comment] 2022-01-02 05:01
Likely caused by https://github.com/SkriptLang/Skript/pull/3960

Another item comparison PR was merged after this one but it was merged after the release of 2.6. I don't think that PR will have fixed this issue, but I am not entirely sure. I recommend that someone test if this issue occurs on the latest master branch build (I will try to myself soon).

This issue is because ExprTool returns a slot and ItemType-Slot comparisons have been changed. This issue is more so an unintended side effect of the change. There is not currently any good way for a user to specify how an item comparison should work (e.g. whether stack size should be taken into account).

One option is to use the workaround listed above. Another option is to add another comparison condition, something like `%itemtype% is similar to %itemtype%` and stack size would not be taken into account. We have discussed ideas before as a team, but I don't think we ever decided on a specific method.

For now, I recommend using the workaround if possible.

**Comment by Jjman739** [comment] 2022-01-11 17:14
So it sounds like there are two ways this could go. Either you center on the idea that comapring stack size should be default, or center on the idea that it shouldn't.

If you center on comparing, you've got
```
# Stack size sensitive
player's tool is {key-item}:
    do stuff
```
and
```
# Stack size insensitive
1 of player's tool is 1 of {key-item}:
    do stuff
```
(Because maybe {key-item} is set dynamically by players who could be holding more than one at the time.)

Or if you center on not comparing, you've got
```
# Stack size sensitive
player's tool is {key-item}:
    itemstack size of player's tool is itemstack size of {key-item}
    do stuff
```
and
```
# Stack size insensitive
player's tool is {key-item}:
    do stuff
```
(I don't remember if amount is a viable alternative for itemstack size.)

So it looks to me like centering on comparing stack size is cleaner overall, but I would think use cases are probably worth considering. Some use cases I can think of for comparing items:
- **Keys** - Size insensitive (like in the vanilla implementation of locks for chests.)
- **Puzzles** - Size sensitive (like if the puzzle involves putting X cobblestone in a slot.)
- **Total inventory comparison** - Size sensitive (but you probably want to do deeper checks for NBT anyways.)
- **Checking if someone has contraband** - Size insensitive (bro, I got past the metal detector by carrying 6 iron instead of 1)
- **You must be holding a stick to do this** - Size insensitive (what do you mean, I'm holing 3 sticks)

I'm probably missing some relevant use cases, but I think all in all, the size insensitive cases are the simpler ones. Given that this is a programming language at least partially marketed towards beginners, I think it's better to avoid making the basic things harder to do.

There's also something to be said for bringing it closer in line with how pedantic "real" programming languages will be, so they're not caught totally unprepared. Though I think it's better to make it easier to enter so they're less likely to be discouraged early on.

**Comment by TheLimeGlass** [comment] 2023-03-10 06:35
Item comparison should match the amount.

**Closed by TheLimeGlass** 2023-03-10 06:35 UTC
Labels: priority: medium, up for debate
