### ISSUE TITLE
2.2-dev36 | has and doesn't have not working on functions

### ISSUE THREAD

**Issue by Sitieno14** [SkriptLang/Skript#1313] opened 2018-06-14 14:33 UTC
```
command /testfunction:
	trigger:
		testfunction(executor)

function testfunction(e: offline player):
	{_e} doesn't have tnt
	send "notnt" to {_e}
```
not returning value also if executor has tnt
the same for the opposite (has)

**Comment by Blueyescat** [comment] 2018-06-14 14:34
Duplicate of https://github.com/SkriptLang/Skript/issues/1287, also there is a workaround ^^

**Comment by Sitieno14** [comment] 2018-06-14 14:36
Don't need to return values ._.

**Comment by Sitieno14** [comment] 2018-06-14 14:37
This was just a testfunction, but in the real one where I also have this problem I won't split it in 1921482194215219581952189 functions that return a boolean so that I also have to manage the response to these boolean if true in all events where I use these 192418521952195912 functions xD

**Comment by Sitieno14** [comment] 2018-06-14 14:38
Really man, it must work, can bensku fix this in next version release soon please? c.c

**Comment by Blueyescat** [comment] 2018-06-14 14:52
🤦‍♀️ go to https://github.com/SkriptLang/Skript/issues/1287 and read

**Comment by Sitieno14** [comment] 2018-06-14 15:00
Readed, doesn't work.

**Comment by Blueyescat** [comment] 2018-06-14 15:50
Reading won't make it working, get my workaround there.

**Comment by Nicofisi** [comment] 2018-07-19 19:02
```vb
command /hi:
    trigger:
        set {_x} to player
        if {_x} has stone:
            message "yes"
        else:
            message "no"
```
The problem is that in `CondContains` [the container](https://github.com/SkriptLang/Skript/blob/b11c6e8a59f9546f217d0268599842a06c65b6f1/src/main/java/ch/njol/skript/conditions/CondContains.java#L103) is a `CraftPlayer`, aka it's neither an `Inventory` nor a `String` nor a `Variable`, and a default `return false;` at the end of the `check` method is executed

#1287 is unrelated since the syntax used here is `"%inventories% ha(s|ve) %itemtypes% [in [(the[ir]|his|her|its)] inventory]"` (no expressions that accept multipe types). I believe that it's this line that causes the issue:
https://github.com/SkriptLang/Skript/blob/b11c6e8a59f9546f217d0268599842a06c65b6f1/src/main/java/ch/njol/skript/conditions/CondContains.java#L70
There *is* an `Entity` -> `Inventory` converter, but I believe the above line causes it to be ignored

**Comment by TheBentoBox** [comment] 2018-07-19 19:08
Re-opened and labelled, thanks for the analysis Nico.

**Comment by SiebeDW** [comment] 2019-08-06 10:15
I think this is fixed? When i use the code of Nicofisi and do /hi without having stone i get "no".
When i have stone it says yes. So i think its fixed?

**Comment by ShaneBeee** [comment] 2020-08-18 08:13
Tested both Nico's command as well as Sitieno's command, both work.

Im guessing this was fixed somewhere along the line.

**Closed by ShaneBeee** 2020-08-18 08:13 UTC
Labels: bug, needs-testing, priority: medium
