### ISSUE TITLE
CondContains is ... crazy.

### ISSUE THREAD

**Issue by Alyanos22** [SkriptLang/Skript#6976] opened 2024-08-14 20:30 UTC
### Skript/Server Version

```markdown
.
```

### Bug Description

// if "test" contain "hihi"                   | true  | true 
// if "test" contains "hihi"                 | true  | true 
// if "test", "test1" contain "hihi"      | false | true
// if "test", "test1" contains "hihi"     | false | false

### Expected Behavior

Why is the variable "explicitSingle" true for ("if "test", "test1" contain "hihi"") - is that really wanted?

### Steps to Reproduce

reproduce in IntelliJ :)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Alyanos22** [comment] 2024-08-14 20:30
Code: `explicitSingle = matchedPattern == 2 && parseResult.mark != 1 || containers.isSingle();`

**Comment by Alyanos22** [comment] 2024-08-14 20:31
I just noticed that and wondered if its really explained when to use contain and when containS.
Because it seems to change something.

**Comment by sovdeeth** [comment] 2024-08-14 20:32
What's the issue here?

**Comment by Alyanos22** [comment] 2024-08-14 20:34
I just wonder for what the variable "explicitSingle" is, when it can be changed by adding an "s"...

**Comment by sovdeeth** [comment] 2024-08-14 20:35
`"abc", "bcd", "cde" contain "c" -> true`: checks if each of the strings contain another string
`"abc", "bcd", "cde" contains "c" -> false`: checks if the list of string contains a specific string

Closing as not a bug report or suggestion

**Comment by Alyanos22** [comment] 2024-08-14 20:35
Why is there a difference between using 
```
// if "test", "test1" contain "hihi" | true
// if "test", "test1" contains "hihi" | false
```?

I mean explicitSingle is true for a thing where it is NOT single ("test", "test1")

**Comment by Alyanos22** [comment] 2024-08-14 20:36
Oh, thanks for clarifiing.... Maybe that should be added to the docs

**Closed by sovdeeth** 2024-08-14 20:35 UTC

**Comment by Alyanos22** [comment] 2024-08-14 20:38
Sorry, but how can I just use java's "contains"?
E.g. List<String> list

list.contains("test")

**Comment by sovdeeth** [comment] 2024-08-14 20:39
![image](https://github.com/user-attachments/assets/5a898fdc-607a-4144-bcae-a086d39958a3)

**Comment by Alyanos22** [comment] 2024-08-14 20:39
"cde" contains "c".

**Comment by Alyanos22** [comment] 2024-08-14 20:40
How can I check if ONE or more of the list contains "c"? not all

**Comment by sovdeeth** [comment] 2024-08-14 20:40
But list.contains("c") would be false if given a list with "cde" in it

**Comment by sovdeeth** [comment] 2024-08-14 20:41
> How can I check if ONE or more of the list contains "c"? not all

This should really be done on the skunity discord, not here.
But you'd use `if "x", "y" or "z" contain "a"`

**Comment by Alyanos22** [comment] 2024-08-14 20:41
oh f i noticed, thanks
