### ISSUE TITLE
Replace text in lore

### ISSUE THREAD

**Issue by UzumakiYT** [SkriptLang/Skript#1618] opened 2018-10-20 01:20 UTC
```
command 1:
	trigger:
		set {_item} to stone
		set line 1 of the lore of {_item} to "Line"
		set line 2 of the lore of {_item} to "Line"
		give {_item} to player

```
https://image.ibb.co/noejT0/Untitled.png
```
command 2:
	trigger:
		set {_item} to stone 
		set line 1 of the lore of {_item} to "Line"
		set line 2 of the lore of {_item} to "Line"
		replace every "Line" in lore of {_item} with "NewLine"
		give {_item} to player	
```	
https://image.ibb.co/cstNFf/Untitled.png

**Comment by ShaneBeee** [comment] 2018-10-20 05:53
I just tested out your code, and I had no issue with it
```
command /test:
	trigger:
		set {_item} to stone 
		set line 1 of the lore of {_item} to "Line"
		set line 2 of the lore of {_item} to "Line"
		replace every "Line" in lore of {_item} with "NewLine"
		give {_item} to player	
```
All I did was change the name of the command.
![](https://i.imgur.com/q2dHUeK.png)
I would recommend stating which version of MC and which version of Skript you are using if you are having an issue!

**Comment by UzumakiYT** [comment] 2018-10-20 12:40
spigot 1.13.1, skript  2.3-beta1

**Comment by Snow-Pyon** [comment] 2018-10-30 08:04
Closing since I wasn't able to reproduce it nor it seems to be the case for someone else. Reopen if you find out this issue again with reproducible steps.

**Closed by Snow-Pyon** 2018-10-30 08:04 UTC
Labels: needs more info
