### ISSUE TITLE
Error message for double pound symbol

### ISSUE THREAD

**Issue by Fusezion** [SkriptLang/Skript#5181] opened 2022-10-26 17:14 UTC
### Suggestion

Update error message for using "#" inside strings *or maybe find a way to exclude comments while inside strings.
The current error message for when you do `"Stringy text #thingy"` isn't clear as it defaults to `"` *see image below \*taken from discord\**

### Why?

I believe the current error message leads to too many miss understandings in errors since you'll check `"` right away 
Since when you read it you'll think it should be like `""Stringy text #thingy""` which leads to a new error 

### Other

![image](https://user-images.githubusercontent.com/81952476/198090926-d324457b-aea1-4dd6-aa4c-34794b51449e.png)

While I'm not sure how hard it would be to make `#` excluded in strings I believe it's something that's better than simply making a new error message *but leads to breaking changes* Since when using hex codes we have to do `<##ff0000>` which isn't nice looking to new people in skript

### Agreement

- [x] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by TheLimeGlass** [comment] 2022-10-26 19:21
You have to double the pound symbol.

**Comment by Fusezion** [comment] 2022-10-27 00:36
> You have to double the pound symbol.

While true it's mostly the fact there's no error for invalid use of `#`. Most people new to skript don't understand the current error
and I believe it might be a good idea to see if we could remove the need of double pound and double percent symbols.

And if not then simply adding an error message for double pound is good since we already got one for percents and quotes

**Comment by sovdeeth** [comment] 2024-04-18 18:54
this is not a duplicate of #1211, 1211 is about comments starting with multiple #, not about a bad error message when forgetting to double # in a quoted string.

**Closed** 2024-07-14 03:52 UTC
Labels: enhancement, priority: lowest, completed
