### ISSUE TITLE
[horrible high priority bug] If player has played before: doesnt work if player has joined server for first time. needs to log out first

### ISSUE THREAD

**Issue by Dad3** [SkriptLang/Skript#1918] opened 2019-02-26 20:34 UTC
### Description

If you use "If player has played before:" it works fine unless the player has joined for the first time, it will not recognize this player as played before. The players need to log out at least once.
A fix for this is checking if player is online first, would be a double check though.
### Steps to Reproduce

command /check [offlineplayer>:
    if player has played before:
        work
    else
        doesnt work on first join
### Expected Behavior

I expect it to work on first join because if a player has joined before it means he played before. 
### Server Information
* **Server version/platform:**   [22:34:22 INFO]: Previous version: git-Paper-1593 (MC: 1.12.2)
[22:34:22 INFO]: Checking version, please wait...
[22:34:23 INFO]: You are 5 version(s) behind    
* **Skript version:**                
[22:34:18 INFO]: Skript version 2.3.3

**Comment by Hexivoid** [comment] 2019-02-26 22:09
Try with Skript 2.3.5?

**Comment by ShaneBeee** [comment] 2019-02-27 01:14
I could be wrong, but I believe this has nothing to do with Skript, this is an issue with the method from the BukkitAPI

**Comment by Pikachu920** [comment] 2019-02-27 01:22
but working around it is as easy as `return p.isOnline() || p.hasPlayedBefore()`. It's just a question of: should we?

**Comment by Nicofisi** [comment] 2019-02-27 09:16
I might misunderstand something completely but isn't the current behavior the whole point of the condition? To check whether this is not the first time the player is on the server?

**Comment by ShaneBeee** [comment] 2019-02-27 09:29
This doesn't really need to be re-written since you could easily just do 
```vb
command /check <offline player>:
	trigger:
		if arg-1 is online:
			send "Has played"
		else:
			if arg-1 has played before:
				send "Has played"
			else:
				send "Has NOT played"
```

**Comment by Dad3** [comment] 2019-02-27 18:43
In my opinion the expected behavior for `has played before` includes an online player and thus you should add pikachu's double check if there is no way around it. Otherwise the only way around for me personally is doing the whole script twice, checking first if player has played before, then else if online with the duplicated script. You can't use "or" in my case when I mess around with completed names

**Comment by Nicofisi** [comment] 2019-02-27 19:14
Oh, I see what you mean now, but that's not the point of the condition, it was originally intended to work as `on first join:`, like
```vb
on join:
    if player hasn't played before:
        send "Hey, welcome to our server for the first time!"
        give 5 potatoes to the player
```
that's why I couldn't get why you wanted it changed at all at first. 
Pretty sure there's even an example like that in the docs, so I'm against changing that honestly.

You could just make a function and use it everywhere :eyes:

**Comment by Hexivoid** [comment] 2019-02-27 19:34
You could use "on first join:" instead for your specific Skript.

**Comment by Dad3** [comment] 2019-02-27 19:39
> Oh, I see what you mean now, but that's not the point of the condition, it was originally intended to work as `on first join:`, like
> 
> ```vbnet
> on join:
>     if player hasn't played before:
>         send "Hey, welcome to our server for the first time!"
>         give 5 potatoes to the player
> ```
> 
> that's why I couldn't get why you wanted it changed at all at first.
> Pretty sure there's even an example like that in the docs, so I'm against changing that honestly.
> 
> You could just make a function and use it everywhere 👀

but there is `on first join` why would u ever use on join, if player hasnt played before. 

Also if this is a spigot problem, I will happily report it to the papermc devs. I am assuming it's because bukkit/spigot only saves this info on a log out.

**Comment by ShaneBeee** [comment] 2019-02-28 02:55
I wouldn't really call this a "spigot problem" since its not technically an issue.

The only time someone would really be using the hasPlayedBefore method, wouldn't be in a join event.
So when a player is joining, if they haven't played before, do something.
The only other time you would use it is checking an offline player.

If the player is currently online, there would be absolutely no need to check if they have played before. 

That being said, its not a BUG with Spigot, since you wouldn't check an ONLINE player to see if they have played before.

As for using this in Skript, you are talking about using it in a command, checking a player in a command if they have played before.
Simple solution:
```vb
command /check <offline player>:
	trigger:
		if arg-1 is online:
			send "Has played"
		else if arg-1 has played before:
			send "Has played"
		else:
			send "Has NOT played"
```

I really see no need to re-write this condition in script, since it perfectly matches how the BukkitAPI handles it, and there is absolutely nothing wrong with it.
The BukkitAPI is full of all sorts of things like this, they aren't "broken" per se, they just need to be handled properly in your code.

**Comment by Dad3** [comment] 2019-02-28 08:40
If that's the case it should be called hasLoggedOutBefore, because an online player did play in the past no matter how much you try to twist the words.

**Comment by ShaneBeee** [comment] 2019-02-28 08:45
If that's what you want to think sure.... but Spigot isn't going to change it for that reason.

If the player is online, they haven't PLAYED before, because PLAYED would indicate past tense, indicating the player has a past played session. 
Their current session is PLAYING, therefor their last session is non existent.

Its been `hasPlayerBefore()` since the dawn of Bukkit time (or whenever they added it) and no ones made a deal with it, because the devs know how to properly use it.

**Comment by Nicofisi** [comment] 2019-02-28 09:06
Don't want to be the one closing it, but just to note, I fully agree with @ShaneBeee

**Comment by Dad3** [comment] 2019-03-01 12:43
alright close the issue

**Comment by TheBentoBox** [comment] 2019-03-01 14:11
I see both sides but I don't think we should modify the behavior of syntaxes which are meant to essentially be direct mappings of the Bukkit API.

**Closed by TheBentoBox** 2019-03-01 14:11 UTC
