### ISSUE TITLE
NullPointer Error

### ISSUE THREAD

**Issue by PrtyBlk** [SkriptLang/Skript#3375] opened 2020-09-13 03:35 UTC
### Description
MAJOR ERROR

### Errors / Screenshots
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! [Skript] Severe Error:
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Something went horribly wrong with Skript.
12.09 23:33:51 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
12.09 23:33:51 [Server] ERROR #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
12.09 23:33:51 [Server] ERROR #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Stack trace:
12.09 23:33:51 [Server] ERROR #!#! java.lang.NullPointerException
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.util.slot.InventorySlot.getItem(InventorySlot.java:66)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.classes.data.DefaultComparators$4.compare(DefaultComparators.java:143)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.classes.data.DefaultComparators$4.compare(DefaultComparators.java:1)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.lambda$1(CondCompare.java:312)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:172)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleLiteral.check(SimpleLiteral.java:178)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.ExpressionList.check(ExpressionList.java:176)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.lambda$0(CondCompare.java:310)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:172)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:160)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:309)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:154)
12.09 23:33:51 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
12.09 23:33:51 [Server] ERROR #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
12.09 23:33:51 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.09 23:33:51 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
12.09 23:33:51 [Server] ERROR #!#!     at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
12.09 23:33:51 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Version Information:
12.09 23:33:51 [Server] ERROR #!#!   Skript: 2.5-beta3 (latest)
12.09 23:33:51 [Server] ERROR #!#!     Flavor: skriptlang-github
12.09 23:33:51 [Server] ERROR #!#!     Date: 2020-08-28
12.09 23:33:51 [Server] ERROR #!#!   Bukkit: 1.16.3-R0.1-SNAPSHOT
12.09 23:33:51 [Server] ERROR #!#!   Minecraft: 1.16.3
12.09 23:33:51 [Server] ERROR #!#!   Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
12.09 23:33:51 [Server] ERROR #!#!   OS: Linux amd64 4.4.232-1.el7.elrepo.x86_64
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Server platform: Paper
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Current node: null
12.09 23:33:51 [Server] ERROR #!#! Current item: event-slot is equal to ([[itemtype:wood shovel, stone shovel, gold shovel, iron shovel, diamond shovel, wood shovel, stone shovel, gold shovel, iron shovel, diamond shovel or netherite shovel]], [[itemtype:wood sword, stone sword, gold sword, iron sword, diamond sword, wood sword, stone sword, gold sword, iron sword, diamond sword or netherite sword]], [[itemtype:wood pickaxe, stone pickaxe, gold pickaxe, iron pickaxe, diamond pickaxe, wood pickaxe, stone pickaxe, gold pickaxe, iron pickaxe, diamond pickaxe or netherite pickaxe]], [[itemtype:wood axe, stone axe, gold axe, iron axe, diamond axe, wood axe, stone axe, gold axe, iron axe, diamond axe or netherite axe]], [[itemtype:bow]], [[itemtype:crossbow]], [[itemtype:elytra]], [[itemtype:trident]] or [[itemtype:wood hoe, stone hoe, gold hoe, iron hoe, diamond hoe, wood hoe, stone hoe, gold hoe, iron hoe, diamond hoe or netherite hoe]])[class ch.njol.skript.aliases.ItemType] (comparator: ch.njol.skript.classes.data.DefaultComparators$4@8259c87)
12.09 23:33:51 [Server] ERROR #!#! Current trigger: inventory click (dispense/spawn/drop/craft/pickup/consume/break/despawn/merge) (tool_levels.sk, line 266)
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Thread: Server thread
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! Language: english
12.09 23:33:51 [Server] ERROR #!#! Link parse mode: DISABLED
12.09 23:33:51 [Server] ERROR #!#! 
12.09 23:33:51 [Server] ERROR #!#! End of Error.
12.09 23:33:51 [Server] ERROR #!#! 

### Server Information
Server Version: 1.16.3 (Paper v195)
Skript Version: newest

**Comment by ShaneBeee** [comment] 2020-09-13 06:18
Closing due to lack of info, and possible duplicate of #3359 
My guess is its the same error which was caused by clicking outside of the inventory.

For future reference, please fill in the template, so we at least have something to work with. 
"Steps to reproduce" would be helpful, so we can attempt to reproduce this error. There could be a million cases for an error, and you have given us zero info outside of the error.
Also for future reference: `Skript Version: newest` <-- "newest" is NOT a version. As you can see in the error, the version is: `Skript: 2.5-beta3 (latest)`

**Closed by ShaneBeee** 2020-09-13 06:18 UTC
