### ISSUE TITLE
on tab complete event

### ISSUE THREAD

**Issue by HYPExMon5ter** [SkriptLang/Skript#2374] opened 2019-08-15 03:34 UTC
Add a `on tab complete` event, like the one in MundoSk. Mundo is splitting into different addons and none of them currently have this, and I feel this would fit good in vanilla skript.

**Comment by PanGargamel** [comment] 2019-08-15 14:41
As far as I remember, SkQuery supports implementing tab completers (but there's still no `on tab complete` event).

**Comment by bensku** [comment] 2019-08-17 15:18
Duplicate of #1600.

**Closed** 2019-08-17 15:18 UTC
Labels: duplicate

**Comment by HYPExMon5ter** [comment] 2019-08-17 15:46
This isn’t really a duplicate, both are valid. Other issue is specifically for having it add player’s names as tab completions automatically, this is adding an event for cancelling, removing, and adding your own completions.
