### ISSUE TITLE
Delete %type% %object%

### ISSUE THREAD

**Issue by kill05** [SkriptLang/Skript#4039] opened 2021-05-27 21:39 UTC
The delete syntax should be reworked a bit to allow to specify what type you want to delete. It would be useful in applications such as:

"delete {_e}" deletes the variable, doesn't despawn the entity, while "delete entity {_e}" would despawn the entity but not delete the variable.

Im sure there are many other cases where this would be very useful. Thanks for reading! :)

**Comment by FranKusmiruk** [comment] 2021-05-28 01:28
duplicate of #2240

**Closed by FranKusmiruk** 2021-05-28 01:28 UTC
