### ISSUE TITLE
Can't pass end crystal to function as itemtype

### ISSUE THREAD

**Issue by PotatoIQ** [SkriptLang/Skript#4774] opened 2022-05-28 06:37 UTC
### Skript/Server Version

```markdown
28.05 06:18:16 [Server] INFO [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
28.05 06:18:16 [Server] INFO [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
28.05 06:18:16 [Server] INFO [Skript] Server Version: git-Paper-350 (MC: 1.18.2)
28.05 06:18:16 [Server] INFO [Skript] Skript Version: 2.6.2
28.05 06:18:16 [Server] INFO [Skript] Installed Skript Addons: 
28.05 06:18:16 [Server] INFO [Skript]  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
28.05 06:18:16 [Server] INFO [Skript]  - Floodgate-Skript v2.1
28.05 06:18:16 [Server] INFO [Skript]  - Skellett v2.0.3 (https://forums.skunity.com/resources/skellett.24/)
28.05 06:18:16 [Server] INFO [Skript]  - skRayFall v1.9.27 (https://sk.rayfall.net/)
28.05 06:18:16 [Server] INFO [Skript]  - SkBee v1.15.3 (https://github.com/ShaneBeee/SkBee)
28.05 06:18:16 [Server] INFO [Skript] Installed dependencies: 
28.05 06:18:16 [Server] INFO [Skript]  - SQLibrary v7.1
28.05 06:18:16 [Server] INFO [Skript]  - Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
28.05 06:18:16 [Server] INFO [Skript]  - WorldGuard v7.0.7+216b061
28.05 06:18:16 [Server] INFO [Skript]  - GriefPrevention v16.18
```

### Bug Description

```
stuff ...
    setGlowing(end crystal)
stuff ...

function setGlowing(item: itemtype) :: itemtype:
    enchant {_item} with (infinity if {_item} is not a bow, else (lure))
    return {_item} with enchant flags hidden
```
gives me the error:
```
the 1st argument given to the function 'setGlowing' is not of the required type item type. Check the correct order of the arguments and put lists into parentheses if appropriate (e.g. 'give(player, (iron ore and gold ore))'). Please note that storing the value in a variable and then using that variable as parameter will suppress this error, but it still won't work.
```
only for end crystals, works for other items in 2.6.2 used to work fine in 2.6.1 with same addons

### Expected Behavior

it should let me enchant the end crystal as item

### Steps to Reproduce

```
stuff ...
    setGlowing(end crystal)
stuff ...

function setGlowing(item: itemtype) :: itemtype:
    enchant {_item} with (infinity if {_item} is not a bow, else (lure))
    return {_item} with enchant flags hidden
```

### Errors or Screenshots

```
[Skript] Line 125: (toolsmenu.sk)
[05:54:58] [Server thread/INFO]:     The 1st argument given to the function 'setGlowing' is not of the required type item type. Check the correct order of the arguments and put lists into parentheses if appropriate (e.g. 'give(player, (iron ore and gold ore))'). Please note that storing the value in a variable and then using that variable as parameter will suppress this error, but it still won't work.
[05:54:58] [Server thread/INFO]:     Line: set slot 11 of metadata tag "ToolsMenu" of player to setGlowing(end crystal) named "&dToggle Effects" with lore "&7Manage different visual effects."
```

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment] 2022-05-28 07:09
Try `setGlowing("end crystal" parsed as item type)` as an alternative.
We all love when these names caused a conflict for representing different objects...

**Comment by bluelhf** [comment] 2022-05-28 10:22
Can reproduce on Skript 2.6.2, solved by using `end crystal item` instead of `end crystal`.

**Comment by AyhamAl-Ali** [comment] 2022-05-28 11:11
I think most of these itemtype issues might be related to #4649 as they wasn't occuring before 2.6.2 and that was the only aliases related commit AFAIK, probably applies to #4773 as well

**Comment by TPGamesNL** [comment] 2022-06-01 17:03
Duplicate of https://github.com/SkriptLang/Skript/issues/4769

**Closed by TPGamesNL** 2022-06-01 17:03 UTC
Labels: PR Available
