### ISSUE TITLE
Bug: cursor slot expression returns "cursor slot of player"

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1341] opened 2018-06-27 18:53 UTC
```
on inventory click:
    broadcast "%event-player's cursor slot%"
```
It seems to be the same under any circumstances. I have tried variations of the expression, like "event-player's cursor slot's item", but to no different results.
Always getting: https://snag.gy/N6GQwi.jpg

dev36, tested with and without add-ons on paper spigot 1.12.1

/edit:
if i use this:
```
on inventory click:
    set event-player's cursor slot to dirt
    broadcast "%event-player's cursor slot%"
```
it set's the *clicked* inventory slot to dirt

```
every second:
    loop all players:
        broadcast ".%loop-player's cursor slot's name%"
```
always returns < none >

**Comment by Snow-Pyon** [comment] 2018-06-27 21:54
duplicate of #1039.

**Closed by Snow-Pyon** 2018-06-27 21:54 UTC
