### ISSUE TITLE
Adding integer to integer doesn't return integer type

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#3542] opened 2020-11-14 21:54 UTC
### Description

when using `set {_var} to {_var} + 1` it doesn't return integer,
the issue is probably with the `+` math expression, because when using `{_var} + 1` in functions it throws a type error.

### Steps to Reproduce

```
function test(i: int):
	broadcast "%{_i}%"

on chat:
	set {_int} to 1
	test({_int}) # works well, prints 1

	set {_int} to {_int} + 1
	test({_int}) # prints nothing, no errors in console

	add 1 to {_int}
	test({_int}) # prints 3

	test({_int} + 1) # throws type error
```

### Expected Behavior

Adding integer to integer should return integer.

### Errors / Screenshots

![image](https://user-images.githubusercontent.com/20037329/99157742-65562a00-26d4-11eb-92fe-7420d8d3bc7d.png)

### Server Information
* **Server version/platform:** 
* **Skript version:** 
![image](https://user-images.githubusercontent.com/20037329/99157755-72731900-26d4-11eb-97b9-42b21b3ae862.png)

### Additional Context

Using this method works
`set {_int} to "%{_int} + 1%" parsed as int`

**Comment by ShaneBeee** [comment] 2020-11-15 00:03
It appears adding to it, makes it a double, which is odd.

```
> !set {i} to 1
[16:02:29 INFO]: executing 'set {i} to 1'
> !send "I: %{i}% : %{i}.getClass()%"
[16:02:41 INFO]: executing 'send "I: %{i}% : %{i}.getClass()%"'
[16:02:41 INFO]: I: 1 : class java.lang.Long
> !set {i} to {i} + 1
[16:02:49 INFO]: executing 'set {i} to {i} + 1'
> !send "I: %{i}% : %{i}.getClass()%"
[16:02:50 INFO]: executing 'send "I: %{i}% : %{i}.getClass()%"'
[16:02:50 INFO]: I: 2 : class java.lang.Double
> /

```
Will mark as a bug

**Comment by TPGamesNL** [comment] 2020-11-15 08:07
Is this not a duplicate of https://github.com/SkriptLang/Skript/issues/1602

**Comment by ShaneBeee** [comment] 2020-11-16 03:45
Closing as duplicate of #1602 as TPGamesNL pointed out.

**Closed by ShaneBeee** 2020-11-16 03:45 UTC
Labels: bug, priority: low
