### ISSUE TITLE
Set yector yaw not working

### ISSUE THREAD

**Issue by ZoomBug58** [SkriptLang/Skript#4186] opened 2021-07-14 02:49 UTC
### Skript/Server Version

Paper 1.17.1
Skript 2.6 beta2

### Bug Description

"Cant understand this condition"
Set vector yaw & pitch don't work.

### Expected Behavior

Was supposed to understand ;p

### Steps to Reproduce

```
command /pscan:
    trigger:
        set {_loc1} to player's location
        set {_loc2} to the location 3 blocks above the player
        set {_v} to vector between {_loc1} and {_loc2}
        set vector yaw of {_v} to 131
        set vector pitch of {_v} to -13
        send {_v}
```

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2021-07-14 06:15
It has been changed to only `yaw` and `pitch` instead of `vector yaw` in 2.6

**Comment by TPGamesNL** [comment] 2021-07-14 06:17
Duplicate of #4167

**Closed by TPGamesNL** 2021-07-14 06:17 UTC
