### ISSUE TITLE
Function Reload Bug with Parallel Loading

### ISSUE THREAD

**Issue by DelayedGaming** [SkriptLang/Skript#4799] opened 2022-06-11 06:12 UTC
### Skript/Server Version

```markdown
[07:53:10] [Server thread/INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[07:53:10] [Server thread/INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[07:53:10] [Server thread/INFO]: [Skript] Server Version: git-Paper-794 (MC: 1.16.5)
[07:53:10] [Server thread/INFO]: [Skript] Skript Version: 2.6.2
[07:53:10] [Server thread/INFO]: [Skript] Installed Skript Addons: 
[07:53:10] [Server thread/INFO]: [Skript]  - skript-yaml v1.4
[07:53:10] [Server thread/INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[07:53:10] [Server thread/INFO]: [Skript]  - reqn v1.3.0-alpha
[07:53:10] [Server thread/INFO]: [Skript]  - SkriptJSON v1.0.0
[07:53:10] [Server thread/INFO]: [Skript] Installed dependencies: None
```

### Bug Description

**With setting 'script loader thread size' to 1**, reloading an unmodified script containing a function will throw a `function name already exists` error. Furthermore, reloading the second time shows success without errors, but function does not recognize anymore, until you disable and enable the script manually.

### Expected Behavior

Reloads successfully without issues.

### Steps to Reproduce

1. Set `script loader thread size` to `1`, or higher
2. Create a new script with a function and any valid code belong to it
3. Reload the script (expected results: no errors, function can be used normally)
4. Reload the same script again (expected results: function already exist error -- function not recognized upon calling)
5. Reload the same script again (expected results: no errors, but function not recognized upon calling)

Disable and re-enable the same script will eliminate the issue, but reloading it again will take you back to the bug.

### Errors or Screenshots

![Screenshot_20220611-135029_Edge](https://user-images.githubusercontent.com/72163224/173175603-4f451a90-a0c8-4dd7-9c3e-a0025670228a.png)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-06-11 08:49
Duplicate of #4579

**Comment by TPGamesNL** [comment] 2022-06-11 08:58
Duplicate of https://github.com/SkriptLang/Skript/issues/4246

**Closed by TPGamesNL** 2022-06-11 08:58 UTC
