### ISSUE TITLE
Incoherent calculation issue

### ISSUE THREAD

**Issue by CarloDrift** [SkriptLang/Skript#3109] opened 2020-07-06 23:02 UTC
### To Reproduce
```
broadcast "%5 - 3 - 2%"
```

### Expected Behavior
I was expecting 0, but Skript chose 4.

### Server Information
* **Server version/platform:** Paper 1.15.2
* **Skript version:** Tried 2.4.1 and 2.5-alpha5

### Additional Context
There's obviously an issue of calculation priority. Probably because of the way Skript reads and interprets code, the calculation performed is `5 - (3 - 2)`.

**Comment by FranKusmiruk** [comment] 2020-07-06 23:05
Duplicate of #535. TL;DR: this isn't something we can easily solve so your best bet is to work it around by using parenthesis.

**Closed by FranKusmiruk** 2020-07-06 23:05 UTC
