### ISSUE TITLE
Error when stopping server

### ISSUE THREAD

**Issue by TUCAOEVER** [SkriptLang/Skript#3395] opened 2020-09-24 11:36 UTC
### Description
Error happens each time i stop the server

### Steps to Reproduce
type "/stop" to stop the server

### Expected Behavior
should be no error

### Errors / Screenshots

```
[19:33:09 ERROR]: Error occurred while disabling Skript v2.5-beta4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ch.njol.skript.entity.EntityData.getAll(EntityData.java:460) ~[?:?]
        at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:155) ~[?:?]
        at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:1) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101) ~[?:?]
        at ch.njol.skript.lang.util.SimpleExpression.iterator(SimpleExpression.java:313) ~[?:?]
        at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:189) ~[?:?]
        at ch.njol.skript.lang.Loop.walk(Loop.java:79) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.events.EvtScript.unregisterAll(EvtScript.java:75) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.removeAllTriggers(SkriptEventHandler.java:249) ~[?:?]
        at ch.njol.skript.Skript.disableScripts(Skript.java:978) ~[?:?]
        at ch.njol.skript.Skript.onDisable(Skript.java:1040) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:750) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1017) ~[patched_1.15.2.jar:git-Paper-384]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:534) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:192) ~[patched_1.15.2.jar:git-Paper-384]
        at ch.njol.skript.util.Task.schedule(Task.java:88) ~[?:?]
        at ch.njol.skript.util.Task.<init>(Task.java:53) ~[?:?]
        at ch.njol.skript.util.Task.<init>(Task.java:46) ~[?:?]
        at ch.njol.skript.bukkitutil.PlayerUtils$1.<init>(PlayerUtils.java:57) ~[?:?]
        at ch.njol.skript.bukkitutil.PlayerUtils.<clinit>(PlayerUtils.java:57) ~[?:?]
        ... 23 more
```

### Server Information
* **Server version/platform:** git-Paper-379 (MC: 1.15.2)
* **Skript version:** Skript version 2.5-beta4

**Comment by ShaneBeee** [comment] 2020-09-24 18:06
Duplicate of #993

**Closed by ShaneBeee** 2020-09-24 18:06 UTC
