### ISSUE TITLE
Skript is disabled on start eror 

### ISSUE THREAD

**Issue by yel-wishahy** [SkriptLang/Skript#3121] opened 2020-07-09 23:51 UTC
### Description
Every time server restart or I try to reload skript now, it does not work. I cannot find the source of the issue as I do not understand the error message sorry.

### Errors / Screenshots
[19:03:21] [Server thread/INFO]: [Skript] Enabling Skript v2.4.1
[19:03:21] [Server thread/ERROR]: Error occurred while enabling Skript v2.4.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148) ~[?:1.8.0_212]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137) ~[?:1.8.0_212]
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:402) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-372]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-372]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-372]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 974
	at ch.njol.skript.aliases.MaterialRegistry.<init>(MaterialRegistry.java:102) ~[?:?]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:79) ~[?:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:108) ~[?:?]
	... 11 more

### Server Information
* **Server version/platform:**       paper 1.15.2
* **Skript version:**               v.2.4.1

**Comment by FranKusmiruk** [comment] 2020-07-10 00:05
What version of Java are you using? Did you upgrade/downgrade the server by any chance? If so, you should delete the `materials.json` file in the `plugins/Skript` folder.

**Comment by yel-wishahy** [comment] 2020-07-10 00:21
I tried to go to 1.16, everything died, so i reverted back. Everything else works, just this, I'll try deleting that file.

**Comment by yel-wishahy** [comment] 2020-07-10 00:34
> If so, you should delete the `materials.json` file in the `plugins/Skript` folder.

It didn't work, also how do I check my java version :D

**Comment by Romitou** [comment] 2020-07-10 11:50
You can run `java -version` in your console.

**Comment by Wealthyturtle** [comment] 2020-08-16 10:54
Closing as duplicate of #2578

**Closed by Wealthyturtle** 2020-08-16 10:54 UTC
Labels: waiting for reply
