### ISSUE TITLE
loop 0 times: -> loop 2 times:

### ISSUE THREAD

**Issue by uiytt** [SkriptLang/Skript#1476] opened 2018-08-18 15:51 UTC
I'm in 1.12 and i have skript in dev 37c
i have this code : 
```
command /test:
	trigger:
		set {_t} to 0
		loop {_t} times:
			message "test"
```
when i do /test, it's sending me "test" 2 times instead of sending me nothing

**Comment by HYPExMon5ter** [comment] 2018-08-18 16:01
Duplicate of #1356

**Closed** 2018-08-18 16:04 UTC
Labels: duplicate
