### ISSUE TITLE
set {_stand} to armor stand - saves an item, not an entity

### ISSUE THREAD

**Issue by MadPanCake** [SkriptLang/Skript#5721] opened 2023-05-28 09:37 UTC
### Skript/Server Version

```markdown
[11:34:58 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[11:34:58 INFO]: [Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[11:34:58 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[11:34:58 INFO]: [Skript] Server Version: git-Paper-538 (MC: 1.19.4)
[11:34:58 INFO]: [Skript] Skript Version: 2.6.4
[11:34:58 INFO]: [Skript] Installed Skript Addons:
[11:34:58 INFO]: [Skript]  - skript-yaml v1.4
[11:34:58 INFO]: [Skript]  - SkBee v2.9.0 (https://github.com/ShaneBeee/SkBee)
[11:34:58 INFO]: [Skript] Installed dependencies: None
```

### Bug Description

Setting a variable to an armor stand actually sets it to an **item**, not the entity.
I'm trying to set a variable to armor stand, and then spawn it from the variable.

### Expected Behavior

An armor stand should spawn at my location after executing /as command.

### Steps to Reproduce

```
command /as:
    trigger:
        set {_stand} to armor stand
        spawn {_stand} at location of player
```

### Other

I think that it might be related to [#1631](https://github.com/SkriptLang/Skript/issues/1631)

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by DelayedGaming** [comment] 2023-05-28 10:25
This happens when different types has the same aliases.
Alternatively, you set a variable to a text which matches the object name at your discretion, and parse it as entity type.
```
set {_e} to "armor stand" parsed as entity type
spawn {_e} at player
```

**Comment by AyhamAl-Ali** [comment] 2023-05-28 11:35
The `a` trick might also work, try `set {_stand} to a armor stand`

**Comment by AyhamAl-Ali** [comment] 2023-05-28 11:38
Duplicate of #5497. There is a PR for this already #5503.

**Closed by AyhamAl-Ali** 2023-05-28 11:38 UTC
