### ISSUE TITLE
WorldGuard support

### ISSUE THREAD

**Issue by VozikCZE** [SkriptLang/Skript#3301] opened 2020-08-12 18:00 UTC
### Description

The newest version of worldguard doesn't work.
### Steps to Reproduce

1. Install the newest version of skript and newest worldguard with newest fawe.
2. Restart server.
### Expected Behavior

WorldGuard support should be enabled.
### Errors / Screenshots

`[19:21:01] [Server thread/ERROR]: [Skript] An error occurred while trying to enable support for FAWE WorldGuard 7. WorldGuard region support has been disabled!
[19:21:01] [Server thread/ERROR]: [Skript] Could not hook into WorldGuard. This can happen if Skript doesn't support the installed version of WorldGuard`

### Server Information
* **Server version/platform:** 1.16.1/Paper
* **Skript version:** 2.5-beta2

**Comment by Romitou** [comment] 2020-08-12 20:28
Skript doesn't support FAWE yet. You can find out more here: #2674

**Comment by ShaneBeee** [comment] 2020-08-13 05:43
Closing as duplicate of #2674

**Closed by ShaneBeee** 2020-08-13 05:43 UTC
