### ISSUE TITLE
Respawn anchor and bed explosions don't trigger on explode event.

### ISSUE THREAD

**Issue by GDudeUnderscore** [SkriptLang/Skript#5632] opened 2023-04-23 22:01 UTC
### Skript/Server Version

```markdown
[16:56:20 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[16:56:20 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[16:56:20 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[16:56:20 INFO]: [Skript] Server Version: git-Paper-518 (MC: 1.19.4)
[16:56:20 INFO]: [Skript] Skript Version: 2.6.4
[16:56:20 INFO]: [Skript] Installed Skript Addons:
[16:56:20 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[16:56:20 INFO]: [Skript]  - SkBee v2.8.4 (https://github.com/ShaneBeee/SkBee)
[16:56:20 INFO]: [Skript] Installed dependencies:
[16:56:20 INFO]: [Skript]  - Vault v1.7.3-b131
[16:56:20 INFO]: [Skript]  - GriefPrevention v16.18.1
```

### Bug Description

When using the on explode event in skript, and for instance, broadcasting a message like so:

```
on explode:
    broadcast yes
```

It doesn't trigger. Using TNT or a creeper does work though.

### Expected Behavior

It should've triggered the on explode event.

### Steps to Reproduce

Put the following into a script file:
```
on explode:
    broadcast yes
```

Try using a respawn anchor, a bed, a creeper and TNT.
You'll see that a creeper and TNT does trigger it, but respawn anchors and beds don't.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by Fusezion** [comment] 2023-04-23 22:07
This should be caused by the event skript supports rn there are 2 events block explosion and entity explosion

**Comment by GDudeUnderscore** [comment] 2023-04-23 22:09
The only events I can see in the docs are `on explosion prime:` and `on explode:`. (not counting on firework explode)

**Comment by Owehttamy** [comment] 2023-04-23 22:17
I can't find any basic solution to this problem either.

**Comment by sovdeeth** [comment] 2023-04-23 22:20
see #3990

**Comment by AyhamAl-Ali** [comment] 2023-04-23 23:15
Duplicate of #3759 Soon it will be completed hopefully

**Closed** 2023-04-23 23:15 UTC
Labels: duplicate
