### ISSUE TITLE
Concurrent functions and reload function case sensitive

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#3029] opened 2020-06-03 04:25 UTC
Nice... So I found out this stupid error
`The function 'insertName' was deleted or renamed, but is still used in other script(s). These will continue to use the old version of the function until Skript restarts.`
```
/sk reload Name
/sk reload name
```
Typing twice fixes it...
```
/sk reload Name
/sk reload Name
```
Clearly not checking case sensitivity when saving functions and keeping the script name reference.

Then this error happens when you run the function in concurrent
```
Could not pass event InventoryClickEvent to Skript v2.5-alpha1
java.lang.NoClassDefFoundError: Could not initialize class org.bukkit.event.server.BroadcastMessageEvent
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.broadcast(CraftServer.java:1353) ~[patched_1.15.2.jar:git-Paper-83]
        at org.bukkit.Bukkit.broadcast(Bukkit.java:783) ~[patched_1.15.2.jar:git-Paper-83]
        at ch.njol.skript.Skript.adminBroadcast(Skript.java:1713) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:95) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:57) ~[?:?]
        at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:92) ~[?:?]
        at ch.njol.skript.lang.function.Function.execute(Function.java:136) ~[?:?]
        at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:267) ~[?:?]
        at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53) ~[?:?]

INFINITE ERROR WHILE CONCURRENT RUNNING
```

```
function test(boolean: boolean = false):
    add 1 to {test}
    broadcast "test"
    if {test} is less than 1000:
        test()
on script load:
    clear {test}
    test()
```
This error with the concurrent I think only happens around 1000 concurrent loops, don't know if it's related to the reload naming.

**Comment by ThisIsACoolBoy** [comment] 2020-06-03 04:48
I think the problem is that if you included 'insertName' then i am sure thats outdated, plus you need to use a new way to find that out

**Comment by ThisIsACoolBoy** [comment] 2020-06-03 05:14
Oh i got it now. The skript thinks that is too much and giving a infinite value error. I think you need to increase your ram to fix this for sure.

**Comment by nfell2009** [comment] 2020-06-03 08:51
Duplicate of #2719. @Wealthyturtle comments on the bug with detail.

**Comment by ThisIsACoolBoy** [comment] 2020-06-03 12:23
I agree nfell

**Comment by ShaneBeee** [comment] 2020-06-03 19:17
Closing due to duplicate of #2719 as already stated.
On that note:
```
v2.5-alpha1
```
Why are you using alpha1, and why are you reporting a bug for alpha1?
I feel like you should know better, I also feel like you should know better to use the template.

**Closed by ShaneBeee** 2020-06-03 19:17 UTC
