### ISSUE TITLE
hide erros expression/effect

### ISSUE THREAD

**Issue by danielzinh** [SkriptLang/Skript#4038] opened 2021-05-27 11:29 UTC
A expression/effect to hide the erros of the condition, example:

if {has-addon} is set:
    hide all erros from this condition # Hide errors from that condition

Its a good idea to Skripters that want to use optionals addons to then skripts.

**Comment by TPGamesNL** [comment] 2021-05-27 11:31
Duplicate of https://github.com/SkriptLang/Skript/issues/1449

**Closed by TPGamesNL** 2021-05-27 11:31 UTC

**Comment by danielzinh** [comment] 2021-05-27 11:40
its not a duplicate, the example is only a example.

this effect is to hide the erros of the condition, not to see if contains a certain addon

**Comment by FranKusmiruk** [comment] 2021-05-27 11:46
@danielzinh we are planning on adding a `parse if` statement to allow what the linked issue and this issue are asking for, the linked issue just happens to mention addons as an example but you could use the given statement virtually for any kind of condition. Don't expect this anytime soon though.
