### ISSUE TITLE
check player online bug

### ISSUE THREAD

**Issue by jeff13401769** [SkriptLang/Skript#5190] opened 2022-11-04 18:58 UTC
### Skript/Server Version

```markdown
Skellett v2.0.7
skDragon v0.16
MorkazSk v1.3
skUtilities v0.9.2
skript-reflect v2.3
skRayFall v1.9.28
Vixio v2.0.9-pre5
SkQuery v4.1.7
SkBee v2.5.0
Ersatz v1.0
```

### Bug Description

I'm trying to make the command run to detect if the player is online, but it doesn't matter if the detection is online or not
Will not work

### Expected Behavior

Should stop when the player is not online

### Steps to Reproduce

here is my code
                    set {_p} to arg-2 parsed as offline players
                    if {_p} is online:
                        send "1" to player
                    if {_p} is offline:
                        send "2" to player
                    if {_p} isn't set:
                        send "3" to player
                    send "%type of {_p}%" to player
                    if {_p} is online:
                        if {guild.%{_p}%} isn't set:
                            if {guildInvite.%player%::%{_p}%} isn't set:
                                set {guildInvite.%player%::%{_p}%} to true
                                send "{@sysprefix} &a成功發送邀請給 &e%{_p}%." to player
                                send "{@sysprefix} &e%{_p}% &7有 &e{@invitetime} &7秒&e接受&7/&e拒絕" to player
                                send "&6[+]--------------------------[+]" to {_p}
                                send "" to {_p}
                                send "  &e%player% &7邀請你加入公會." to {_p}
                                send "" to {_p}
                                send formatted "  <tooltip:&a點擊接受><run command:/g accept %player%>&2[&a接受&2]<reset>  <tooltip:&c點擊拒絕><run command:/g deny %player%>&4[&c拒絕&4]<reset>" to {_p}
                                send "" to {_p}
                                send "&6[+]--------------------------[+]" to {_p}
                                wait {@invitetime} seconds
                                if {guildInvite.%player%::%{_p}%} is set:
                                    delete {guildInvite.%player%::%{_p}%}
                                    send "{@sysprefix} &c你發送給 &e%{_p}% 的公會邀請已過期!"
                                    stop
                            else:
                                send "{@sysprefix} &c你已邀請過該玩家! 若該玩家未收到邀請, 請等待邀請過期後再重新邀請"
                                stop
                        else:
                            send "{@sysprefix} &c該玩家當前已經擁有公會!"
                            stop
                    else:
                        send "{@sysprefix} &c該玩家不在線上或不存在"
                        stop

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/51765857/200054144-c199b45e-1b81-4b2b-8df3-3c56f623e688.png)

There are no error messages in the console

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2022-11-04 20:11
Duplicate of #4125 
It's due to Vixio addon.

**Closed by AyhamAl-Ali** 2022-11-04 20:11 UTC

**Comment by jeff13401769** [comment] 2022-11-04 20:26
thx
