### ISSUE TITLE
2.5.2 Subtext Expression error

### ISSUE THREAD

**Issue by Chsui** [SkriptLang/Skript#3599] opened 2020-12-03 14:08 UTC
```
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! [Skript] Severe Error:
[23:02:48 ERROR]: #!#! Could not load SW_Item.sk
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Something went horribly wrong with Skript.
[23:02:48 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[23:02:48 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:02:48 ERROR]: #!#! Here is full list of them:
[23:02:48 ERROR]: #!#! skript-reflect v2.1.0 (https://github.com/TPGamesNL/skript-reflect) skUtilities v0.9.2 (https://tim740.github.io/) Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/)
[23:02:48 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:02:48 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:02:48 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:02:48 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:02:48 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:02:48 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Stack trace:
[23:02:48 ERROR]: #!#! java.lang.NullPointerException
[23:02:48 ERROR]: #!#!     at ch.njol.skript.expressions.ExprSubstring.isSingle(ExprSubstring.java:108)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:249)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:65)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1067)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Conditional$1.<init>(Conditional.java:71)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:71)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1090)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[23:02:48 ERROR]: #!#!     at com.btk5h.skriptmirror.util.SkriptUtil.getItemsFromNode(SkriptUtil.java:55)
[23:02:48 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.expression.CustomExpressionSection.lambda$init$12(CustomExpressionSection.java:158)
[23:02:48 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.handleEntriesAndSections(CustomSyntaxSection.java:205)
[23:02:48 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.expression.CustomExpressionSection.init(CustomExpressionSection.java:128)
[23:02:48 ERROR]: #!#!     at com.btk5h.skriptmirror.skript.custom.CustomSyntaxSection.init(CustomSyntaxSection.java:176)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1263)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1234)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:669)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[23:02:48 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:601)
[23:02:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[23:02:48 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[23:02:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:949)
[23:02:48 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:02:48 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Version Information:
[23:02:48 ERROR]: #!#!   Skript: 2.5.2 (latest)
[23:02:48 ERROR]: #!#!     Flavor: skriptlang-github
[23:02:48 ERROR]: #!#!     Date: 2020-11-28
[23:02:48 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[23:02:48 ERROR]: #!#!   Minecraft: 1.16.4
[23:02:48 ERROR]: #!#!   Java: 1.8.0_261 (Java HotSpot(TM) 64-Bit Server VM 25.261-b12)
[23:02:48 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Server platform: Paper
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Current node: set {_color} to first 2 character of name of {_socket} (SW_Item.sk, line 1134)
[23:02:48 ERROR]: #!#! Current item: null
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Thread: Server thread
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! Language: english
[23:02:48 ERROR]: #!#! Link parse mode: STRICT
[23:02:48 ERROR]: #!#!
[23:02:48 ERROR]: #!#! End of Error.
[23:02:48 ERROR]: #!#!
```

Paper build275(1.16.4)

**Comment by ShaneBeee** [comment] 2020-12-03 21:01
This has already been reported and fixed.

Duplicate of #3585 
I suggest looking at other issues before posting to prevent duplicates.

**Closed by ShaneBeee** 2020-12-03 21:01 UTC
