### ISSUE TITLE
amount of item in inventory of player 

### ISSUE THREAD

**Issue by TIM31205** [SkriptLang/Skript#6120] opened 2023-10-14 13:43 UTC
### Skript/Server Version

```markdown
[20:35:54 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[20:35:54 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/[20:35:54 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[20:35:54 INFO]: [Skript] Server Version: git-Paper-233 (MC: 1.20.2)
[20:35:54 INFO]: [Skript] Skript Version: 2.7.1 (skriptlang-github)
[20:35:54 INFO]: [Skript] Installed Skript Addons:
[20:35:54 INFO]: [Skript]  - SkBee v2.18.3 (https://github.com/ShaneBeee/SkBee)
[20:35:54 INFO]: [Skript] Installed dependencies:
[20:35:54 INFO]: [Skript]  - Vault v1.7.3-b131
```

### Bug Description

I have found that in vanilla GUI within the `on inventory click:` context, when using `type of event-item` to obtain the type of the clicked item and store it in the variable {_item}, then using `set ... to amount of {_item} in inventory of player`, it won't detect items in the player's inventory, even though the output of {_item} is "cobblestone block," there is no issue. However, if I manually set the variable, there is no problem, for example: `set {_item} to cobblestone block`.

### Expected Behavior

It should display all of that item in the player's inventory.

### Steps to Reproduce

I have tried:
```
function shop(p: player):
	set metadata tag "shop" of {_p} to chest inventory with 6 row named "shop"
	set slot 10 of metadata tag "shop" of {_p} to cobblestone named "&r鵝卵石" with lore ...
```

```
on inventory click:
    event-inventory = (metadata tag "shop" of player):
```
`set {_n} to amount of event-item’s type in inventory of player`
and
```
set {_item} to type of event-item
set {_n} to amount of {_item} in inventory of player
```
Even though the player has cobblestone in their inventory, {_n} still displays as 0.

### Errors or Screenshots

No error message

### Other

```
set {_item} to type of event-item
set {_n} to amount of {_item} in inventory of player
```
Additionally, when I use it in Skript 2.6.4, it works as expected.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by sovdeeth** [comment] 2023-10-15 05:46
This is because `type of event-item` is a plain piece of cobblestone. When you use it in `amount of`, it's now checking for plain cobblestone, which does not match the named cobblestones you have. When you use `cobblestone block` literally, that's an alias for any kind of cobblestone, so it matches the named ones too.

Duplicate of #2142

**Closed** 2023-10-15 05:47 UTC
Labels: duplicate
