### ISSUE TITLE
Test enviroment stack trace

### ISSUE THREAD

**Issue by TheLimeGlass** [SkriptLang/Skript#4293] opened 2021-08-20 08:12 UTC
### Skript/Server Version

This is happening in the test Skript environment on all versions

### Bug Description

I'm assuming one of the test scripts is causing Skript to throw this error.

### Expected Behavior

Figure out if the error is critical because I think the test isn't even working.

### Steps to Reproduce

Running `gradlew skriptTest`

### Errors or Screenshots

```
Error occurred while disabling Skript v2.6-beta2 (Is it up to date?)
java.lang.AssertionError: diamond sword named BOB (class ch.njol.skript.aliases.ItemType) != diamond sword named BOB (class ch.njol.skript.aliases.ItemType): [89, 103, 103, 0, 0, 1, -128, 8, 105, 116, 101, 109, 116, 121, 112, 101, -122, 3, 97, 108, 108, 15, 0, 5, 116, 121, 112, 101, 115, -128, 9, 65, 114, 114, 97, 121, 76, 105, 115, 116, -127, 6, 118, 97, 108, 117, 101, 115, 48, -128, 6, 79, 98, 106, 101, 99, 116, -128, 1, -128, 11, 78, 101, 119, 73, 116, 101, 109, 68, 97, 116, 97, -121, 7, 105, 115, 65, 108, 105, 97, 115, 15, 0, 5, 112, 108, 97, 105, 110, 15, 0, 4, 109, 101, 116, 97, -128, 34, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 83, 101, 114, 105, 97, 108, 105, 122, 97, 98, 108, 101, 95, 73, 116, 101, 109, 77, 101, 116, 97, -127, 5, 118, 97, 108, 117, 101, 32, -128, 94, 118, 97, 108, 117, 101, 58, 10, 32, 32, 61, 61, 58, 32, 73, 116, 101, 109, 77, 101, 116, 97, 10, 32, 32, 109, 101, 116, 97, 45, 116, 121, 112, 101, 58, 32, 85, 78, 83, 80, 69, 67, 73, 70, 73, 67, 10, 32, 32, 100, 105, 115, 112, 108, 97, 121, 45, 110, 97, 109, 101, 58, 32, 66, 79, 66, 10, 32, 32, 108, 111, 114, 101, 58, 10, 32, 32, 45, 32, 76, 79, 82, 69, 49, 10, 32, 32, 45, 32, 76, 79, 82, 69, 50, 10, 9, 105, 116, 101, 109, 70, 108, 97, 103, 115, 3, 0, 0, 0, 2, 10, 105, 115, 65, 110, 121, 116, 104, 105, 110, 103, 15, 0, 2, 105, 100, 3, 0, 0, 0, -22, 8, 105, 116, 101, 109, 70, 111, 114, 109, 15, 0, 6, 97, 109, 111, 117, 110, 116, 3, 0, 0, 0, 1, 4, 105, 116, 101, 109, 0, 10, 103, 108, 111, 98, 97, 108, 77, 101, 116, 97, 0, 5, 98, 108, 111, 99, 107, 0]
        at ch.njol.skript.registrations.Classes.serialize(Classes.java:741) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:438) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:432) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:386) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.close(FlatFileStorage.java:339) ~[?:?]
        at ch.njol.skript.Skript.onDisable(Skript.java:1088) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.9.4.jar:git-Paper-773]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.disablePlugins(CraftServer.java:337) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.stop(MinecraftServer.java:458) [patched_1.9.4.jar:git-Paper-773]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:658) [patched_1.9.4.jar:git-Paper-773]
        at java.base/java.lang.Thread.run(Thread.java:831) [?:?]
```
I have also not made any test scripts for this error.

Test script involved in this error https://github.com/SkriptLang/Skript/blob/d09320866fa15bd6f2fc77b13f3e0cfd2c46ef36/src/test/skript/tests/regressions/3305-named%20inventory-item.sk

**Comment by TheLimeGlass** [comment] 2021-08-20 08:13
Also I can't run the skriptTestDev because of
```
* What went wrong:
Execution failed for task ':skriptTestDev'.
> Could not set unknown property 'standardInput' for task ':skriptTestDev' of type org.gradle.api.DefaultTask.
```

**Comment by TPGamesNL** [comment] 2021-08-20 09:37
Duplicate of https://github.com/SkriptLang/Skript/issues/3767, the stacktrace is probably caused by https://github.com/SkriptLang/Skript/issues/2111

The standardInput property thing isn't in #3767 yet, so you should comment there

**Closed by TPGamesNL** 2021-08-20 09:37 UTC
