### ISSUE TITLE
Stone slab doesn't have unique name

### ISSUE THREAD

**Issue by Eng1ner** [SkriptLang/Skript#4207] opened 2021-07-20 16:11 UTC
### Skript/Server Version

Server version: git-Paper-318 (MC: 1.16.4)
Skript version: 2.5.3

### Bug Description

When you trying to set variable to _stone slab_ (`set {_i} to stone slab`), you will get every type of stone slab (f.e. andesite slab, diorite slab etc.). So when you want to assign stone slab specifically, you can't do it. Theoretically you can do `set {_i} to minecraft:stone_slab`, but then it have some problems f.e. with giving it to player.

### Expected Behavior

`set {_i} to stone slab` - should assign stone slab _only_, without any other slabs.
`set {_i} to any stone slab` - should assign every type of stone slab

### Steps to Reproduce

^^

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-07-20 17:06
Duplicate of #4055

**Closed by TPGamesNL** 2021-07-20 17:06 UTC
