### ISSUE TITLE
Proper subcommands using static command arguments

### ISSUE THREAD

**Issue by honkling** [SkriptLang/Skript#4731] opened 2022-04-16 15:15 UTC
### Suggestion

Although not well known, Skript does allow people to write command arguments like the following:
```
command give me a <item>:
    trigger:
        give player arg-item
```
which would be executed as `/give me a cake`. This technology should be used to define proper command structures, for example:
```
command mines goto <offlineplayer>:
    trigger:
        teleport player to {mines::%arg-offlineplayer's uuid%}

command mines reset:
    trigger:
        delete world file for world of {mines::%player's uuid%}
```

Currently, when Skript comes across this code, it'll throw the following: `A command with the name /mines is already defined in mines.sk`. Skript should instead accept this code.

### Why?

It allows users to elegantly define a command structure and separate subcommands. It avoids long (and quite annoying) paragraphs of code like the following:
```
command mines <text> [<player>]:
    trigger:
        if arg-text is "goto":
            arg-offlineplayer is set
            teleport player to {mines::%arg-offlineplayer's uuid%}
        else if arg-text is "reset":
            delete world file for world of {mines::%player's uuid%}
```

### Other

If you're wondering how this could be implemented, I would suggest that Skript registers the `/mines` command, and then when the command is used, Skript would figure out which subcommand was called by using the user's provided arguments, and then run the code for that subcommand.

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment] 2022-04-16 17:10
It's true that Skript accepts such command syntax as explained [here](https://github.com/SkriptLang/Skript/pull/4653) though it doesn't mean the command label is `mines goto` or `mines reset`, the command label is `mines` and everything after the whitespace are command arguments therefore your idea's approach should not be done like this, it should be simply done within the same command section, regarding if it's possible or not.

**Comment by TPGamesNL** [comment] 2022-04-17 08:44
Duplicate of https://github.com/SkriptLang/Skript/issues/2809

Command arguments are converted to Skript patterns, therefore they allow many things Skript patterns have as well (though some things are restricted)

**Closed by TPGamesNL** 2022-04-17 08:44 UTC
