### ISSUE TITLE
Skript 2.5+

### ISSUE THREAD

**Issue by VemcziN** [SkriptLang/Skript#3950] opened 2021-05-07 20:07 UTC
Hello, I have probably detected a bug in the 2.5+ script that when the server is on version 1.12.2-1.16.5 and with viaversion plugins, players on version 1.8 when they have a box that can be opened with the right button when clicking on npc / player / animal doubles them open and removes two boxes and adds two drops. I checked on the lower version 2.2dev36 from matocolotoe, it normally works nicely and nothing doubles below the code I present such a box when we click it on npc it doubles and when in the air it normally opens 1 time

I apologize for my English but I wrote it with a google translator because I am from Poland

	
on right click:
	if player's tool is chest named "skrzynia":
		remove 1 chest named "skrzynia" from player
		send "dostales dirta" to player
		add 1 dirt to player

**Comment by TheDGOfficial** [comment] 2021-05-07 21:51
Shouldn't it be give 1 dirt to player instead of add? Didn't check source but anyway if it works it is doing a similar thing or even it is an alias in the code.

I did not understand much what you say, ViaVersion allows connecting newer versions not older versions. You are probably talking about ViaRewind or using another 1.8 compatible fork of 2.5, if it is the second case go report it on the fork's issue tracker.

If it is the first one and only happens on older clients that may also be not a Skript issue too, ViaRewind should translate everything automatically so Skript shouldn't need special code to handle them. In that case you should open an issue on the ViaRewind repo.

**Comment by VemcziN** [comment] 2021-05-07 22:07
My point is that when I have a spigot 1.12 engine and viaversion viabackwards plugin and the third one, I just forgot the name. then when players connect on the old version, for example 1.8.8, these errors appear with the fact that they drop from the box

**Comment by TPGamesNL** [comment] 2021-05-09 09:14
Duplicate of https://github.com/SkriptLang/Skript/issues/2148

**Closed by TPGamesNL** 2021-05-09 09:14 UTC
