### ISSUE TITLE
Invalid Addon Link in /skript info

### ISSUE THREAD

**Issue by hapily04** [SkriptLang/Skript#5936] opened 2023-08-24 23:31 UTC
### Skript/Server Version

```markdown
[23:31:12 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[23:31:12 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/
[23:31:12 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
[23:31:12 INFO]: [Skript] Server Version: git-Paper-550 (MC: 1.19.4)
[23:31:12 INFO]: [Skript] Skript Version: 2.7.0-beta3 (skriptlang-github)
[23:31:12 INFO]: [Skript] Installed Skript Addons: 
[23:31:12 INFO]: [Skript]  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
[23:31:12 INFO]: [Skript]  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
[23:31:12 INFO]: [Skript]  - SkBee v2.16.1 (https://github.com/ShaneBeee/SkBee)
[23:31:12 INFO]: [Skript]  - Skript-Advancements v1.5.6
[23:31:12 INFO]: [Skript] Installed dependencies: 
[23:31:12 INFO]: [Skript]  - Vault v1.7.3-b131
[23:31:12 INFO]: [Skript]  - WorldGuard v7.0.8+33cdb4a
```

### Bug Description

When you click the link to go to the addon's page, it has an extra ) for all addons
![image](https://github.com/SkriptLang/Skript/assets/87914807/afc699d1-ff15-4519-a0ca-667ccb93bc03)

### Expected Behavior

Shouldn't have the extra ) so people can properly go to the link

### Steps to Reproduce

/skript info and click on any of the addon links

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment] 2023-08-24 23:43
Duplicate of #5742

**Closed by AyhamAl-Ali** 2023-08-24 23:43 UTC
