### ISSUE TITLE
[SUGGESTION] Functions that return key & value

### ISSUE THREAD

**Issue by scheetposter** [SkriptLang/Skript#6548] opened 2024-04-10 12:11 UTC
### Suggestion

For functions to be able to return key&value of a list
Basically indices of a list
For example:
```
function returnStats(i: item) :: strings,integers:
    set {_nbt} to nbt of {_i}
    set {_stats::damage} to float tag "damage" of {_nbt}
    set {_stats::range} to float tag "range" of {_nbt}
    return {_stats::*}
```
then, it will return"
```
set {_return::*} to returnStats(player's tool)
loop {_return::*}:
    send "%loop-index%: %loop-value%" to player
```
output:
```
damage: x
range: y
```

### Why?

i understand u could probably to similar to this by probably storing the values in a string, then returning string and then splitting the string to get what u want but this is much easier and convenient

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by sovdeeth** [comment] 2024-04-10 12:39
Duplicate of https://github.com/SkriptLang/Skript/issues/3127

**Closed by sovdeeth** 2024-04-10 12:39 UTC
