### ISSUE TITLE
Critical Bug with List-Variables

### ISSUE THREAD

**Issue by Duetro** [SkriptLang/Skript#2022] opened 2019-04-24 13:28 UTC
### Description
Hi. We have found a huge Problem with List-Variables. Sometimes the last Variables don't get set.

### Steps to Reproduce
```
command /duetro_vartest:
    trigger:
        loop 10 times:
            delete {-bugtest::*}
            wait 0.5 seconds
            loop 1000 times:   
                add true to {-bugtest::*}
                chance of 1%
                wait a tick
            send "Size: %size of {-bugtest::*}%"   
            wait 0.5 seconds
```
Example Output: https://s.duetro.de/i/javaw_2019-04-24_15-24-44.png
_Note: More Variables are missing if there is a wait in between the adds!_

### Server Information
* **Server version/platform:** git-Paper-1606 (MC: 1.12.2)
* **Skript version:** 2.3.6

### Plugins
```
Plugins (46): ArmorStandEditor, BannerMaker, BKCommonLib, BuycraftX, Citizens, CrackShot, CrackShotPlus, CS-CoreLib, Essentials, EssentialsProtect, ForceResourcepacks, GMDE-Skript-AddOn, HeadDatabase, HolographicDisplays, LagMonitor, LightAPI, LightCleaner, LuckPerms, Magic, Multiverse-Core, MundoSK, NametagEdit, NoCheatPlus, Orebfuscator4, PacketWrapper, PlaceholderAPI, PremiumVanish, ProtocolLib, SK-NBeeT, skDragon, Skellett, SkQuery, skRayFall, Skript, skript-mirror, skUtilities, SQLibrary, TuSKe, UltraCosmetics, Vault, Votifier, WebAddon, WolvSK, WorldBorder, WorldEdit, WorldGuard
```

**Comment by TheBentoBox** [comment] 2019-04-24 13:45
What variable storage method do you use? CSV or a database?

I'd like to note that @Blueyescat has tested this and cannot reproduce, and even if we do find a way to reproduce it this "critical bug" is potentially just due to you trying to access variables which haven't fully been written to your database yet. You're creating a LOT of variables very fast here then accessing them immediately -- generally there is no reason to do this.

**Comment by Blueyescat** [comment] 2019-04-24 13:48
```md
> test
[16:45:12 WARN]: [Skript] Cannot write variables to the database 'default' at sufficient speed; server performance may suffer and many variables will be lost if the server crashes. (this warning will be repeated at most once every 10 seconds)
[16:45:13 INFO]: Size: 1000
[16:45:15 INFO]: Size: 1000
[16:45:16 INFO]: Size: 1000
[16:45:18 INFO]: Size: 1000
[16:45:19 INFO]: Size: 1000
[16:45:21 INFO]: Size: 1000
[16:45:22 INFO]: Size: 1000
[16:45:22 WARN]: [Skript] Cannot write variables to the database 'default' at sufficient speed; server performance may suffer and many variables will be lost if the server crashes. (this warning will be repeated at most once every 10 seconds)
[16:45:24 INFO]: Size: 1000
[16:45:25 INFO]: Size: 1000
[16:45:26 INFO]: Size: 1000
```

**Comment by Duetro** [comment] 2019-04-24 13:57
Hi, this happens when we save to MySQL or just to RAM (With the **-** prefix).
The Variables are even missing if we wait for one second and then check the size again

```
[15:51:56 INFO]: 1-OK: 1000
[15:51:57 INFO]: 2-OK: 1000
[15:51:57 INFO]: 1-OK: 1000
[15:51:58 INFO]: 2-OK: 1000
[15:51:59 INFO]: 1-OK: 1000
[15:52:00 INFO]: 2-OK: 1000
[15:52:00 INFO]: 1-Variables Missing! >> Size: 998
[15:52:01 INFO]: 2-Variables Missing! >> Size: 998
[15:52:02 INFO]: 1-OK: 1000
[15:52:03 INFO]: 2-OK: 1000
[15:52:04 INFO]: 1-OK: 1000
[15:52:05 INFO]: 2-OK: 1000
[15:52:06 INFO]: 1-OK: 1000
[15:52:07 INFO]: 2-OK: 1000
[15:52:07 INFO]: 1-OK: 1000
[15:52:08 INFO]: 2-OK: 1000
[15:52:09 INFO]: 1-OK: 1000
[15:52:10 INFO]: 2-OK: 1000
[15:52:10 INFO]: 1-OK: 1000
[15:52:11 INFO]: 2-OK: 1000
```

**Comment by Duetro** [comment] 2019-04-24 14:04
On the main server (currently ~90 players) this happens even more often: 
https://s.duetro.de/i/javaw_2019-04-24_16-03-31.png

**Comment by Blueyescat** [comment] 2019-04-24 14:10
So it might be some issue depending on the server resources. I'm trying with 60 tick delay...

**Comment by bensku** [comment] 2019-04-29 09:37
This could be a serious bug in MySQL variable storage. Unfortunately it has not exactly been maintained for a long time - there is no one who really *knows* how to work with it anymore.

**Comment by Blueyescat** [comment] 2019-04-29 14:21
@Duetro tried without saving to somewhere or saving to MySQL as he said above, and i tried with saving to CSV or without saving but couldn't reproduce. I think it might be related to RAM... `investigating` label would be good.

**Comment by TPGamesNL** [comment] 2021-05-08 14:58
This might've been caused by scripts running on other threads, because Skript's variable system doesn't support multiple threads using it

**Comment by Moderocky** [comment] 2024-04-12 15:27
I'm closing this since nobody else has reported the issue since and nobody has been able to reproduce it, so triage would be impossible.

**Closed by Moderocky** 2024-04-12 15:27 UTC
Labels: needs testing, variables, cannot reproduce
