### ISSUE TITLE
Local variables making RAM going to 0 (dev37c)

### ISSUE THREAD

**Issue by YellowZaki** [SkriptLang/Skript#1570] opened 2018-09-29 22:59 UTC
Yesterday I updated from a old version of skript to dev37c. 
Today I noticed huge lag spikes. Then I realised the RAM was reaching 0. When I start the server, the RAM starts decreasing slowly until 0mb when lag spikes occur.

I made a RAM Dump and I found that +90% of the RAM was because of skript, specifically it was about local variables.

**Comment by TheBentoBox** [comment] 2018-09-29 23:34
This doesn't really mean anything without us seeing how you're handling local variables in your scripts. I've never heard of anyone else having this issue so for all we know you're generating a ton of local variables with laggy, high frequency events.

**Comment by YellowZaki** [comment] 2018-09-30 00:06
I have been using Skript 2.2-dev29 for months and I hadn't have any problems. The ram issue comes from yesterday and the only changes I made yesterday on the server were updating Skript and SKQuery, I'll try downgrading SkQuery to see if something changes.

**Comment by bensku** [comment] 2018-09-30 09:01
Some old Skript versions do have memory leaks, but I didn't think dev37c was one of those. If it is, I wonder how *most* users have not noticed anything.

If this happens without addons, I could take a look at heap dump.

**Comment by YellowZaki** [comment] 2018-09-30 12:10
I attach some screenshots of the memory dump, if it helps.
![image](https://user-images.githubusercontent.com/13599841/46257456-5c854880-c4ba-11e8-8538-6dbf2ff913dc.png)
![image](https://user-images.githubusercontent.com/13599841/46257468-7e7ecb00-c4ba-11e8-9b13-6315a76e4e6a.png)
![image](https://user-images.githubusercontent.com/13599841/46257471-8b032380-c4ba-11e8-88de-8791a6cb6091.png)

**Comment by bensku** [comment] 2018-09-30 15:03
That bug should not exist on dev37b, are you sure it is that version? Might also be caused by addons, please try running without them and see if memory is still leaking.

**Comment by YellowZaki** [comment] 2018-10-04 22:28
The same thing happens without addons. But I have noticed something. 

On older skript versions, a large portion of RAM is occupied by local variables too. But when RAM goes down to ~50mb, it goes up to the max value again, instead of dropping to 0mb and lagging the server (dev37).

**Comment by Feerko** [comment] 2018-10-09 16:20
Hello,

@bensku i have a similar problem and i'm also using dev37c
<img width="809" alt="class" src="https://user-images.githubusercontent.com/16988054/46683077-8db6f480-cbef-11e8-95e1-459e80792f9b.png">
<img width="889" alt="leaks" src="https://user-images.githubusercontent.com/16988054/46683078-8db6f480-cbef-11e8-92ef-2579e4ade5c2.png">
<img width="653" alt="problem1" src="https://user-images.githubusercontent.com/16988054/46683079-8db6f480-cbef-11e8-941f-0d1d24d4a711.png">

the server has been on for 8 hours. variables.csv weighs 7mb while there are 150 people on the server. the server now uses 15gb of RAM.

```vbs
on join:
  send request to "xxxxx" #stats, coins, etc
  map json last response's body to {player::%player%::*}

on quit:
  delete {player::%player%::*}
```

**Comment by Feerko** [comment] 2018-10-09 16:58
Hmm, I have variables like this:
```
{player::%player%::level}
{player::%player%::stats::kills}
...
```
maybe `delete {player::%player%::*}`
doesn't remove {player::%player%::*::*} and that's the reason.

**Comment by Feerko** [comment] 2018-10-09 17:31
i think i found it
```vbs
function var():
  loop 100 times:
    loop 100 times:
      set {test::%loop-num-1%} to loop-num-1
      set {test::%loop-num-1%::%loop-num-2%} to random number between 11111111 and 99999999

command /test:
  trigger:
    loop 100 times:
      var()
      delete {test::*}
      wait 1 tick
```

**Comment by Feerko** [comment] 2018-10-09 18:32
@bensku What can I do with this? Within 2 hours my server consumes 10GB of RAM.

**Comment by bensku** [comment] 2018-10-09 18:48
@Feerko Iterate through lists before deleting and delete your "sublists" too.

In the other news, I identified a problem with periodical events causing local variables to slowly leak. It may fix this issue.

**Comment by TheBentoBox** [comment] 2018-10-09 18:56
> Iterate through lists before deleting and delete your "sublists" too.

Last I recalled, iterating over a list which contains sub-lists does not iterate over the indices representing those sub-lists, so this wouldn't work. Maybe my info is wrong or outdated, though.

**Comment by Feerko** [comment] 2018-10-09 19:02
Tried, doesn't work. RAM grows and grows. When the server reaches Xmx, the CPU usage drastically increases, tps drops a lot and a crash server.

Removing variables does not free RAM. I've tried everything.

**Comment by bensku** [comment] 2018-10-09 19:17
@TheBentoBox You can add non-list keys in addition to list keys, and then iterate over them.

Not tested, but something like
```vbs
function var():
  loop 100 times:
    set {test::%loop-num-1%} to loop-num-1
    loop 100 times:
      set {test::%loop-num-1%} to true
      set {test::%loop-num-1%::%loop-num-2%} to random number between 11111111 and 99999999

command /test:
  trigger:
    loop 100 times:
      var()
      loop {test::*}:
        delete {test::%loop-index%::*}
      delete {test::*}
      wait 1 tick
```

**Comment by Feerko** [comment] 2018-10-09 19:39
Same. 

```vbs
function var():
  loop 10000 times:
    set {test_%loop-num%} to random number between 111111 and 99999999999
    delete {test_%loop-num%}
    
command /test:
  trigger:
    loop 100 times:
      var()
      wait 1 tick
```
it also causes this issue. Deleting a variable does not free RAM?

**Comment by Feerko** [comment] 2018-10-09 23:01
Correction: issue exists for all variables. Tested with:
```vbs
function test(n: number=0):
  loop 10000 times:
    set {test_%{_n}%_%loop-num%} to random number between 11111111111 and 99999999999
  wait 1 tick
  loop 10000 times:
    delete {test_%{_n}%_%loop-num%}
  broadcast "[%{_n}%] %tps% - %difference between now and {now}%"
  wait 1 tick
  test({_n}+1)

command /test:
  trigger:
    set {now} to now
    test()
```

**Comment by Feerko** [comment] 2018-10-10 08:56
Ok, so I compiled dev37c, but I used WeakHashMap instead of HashMap in Variables. Works much better.

**Comment by bensku** [comment] 2018-10-13 13:16
New release is out. Could someone check if this still occurs?

**Comment by bensku** [comment] 2018-10-22 18:21
Closing in a few days unless someone still has this issue.

**Closed** 2018-10-29 17:15 UTC
Labels: bug, completed
