### ISSUE TITLE
Remove features.sk

### ISSUE THREAD

**Issue by Jayderp** [SkriptLang/Skript#2848] opened 2020-03-04 04:24 UTC
**features.sk** is a yet-to-be-implemeted file with no actual use at the moment.
I've seen people put scripts in features.sk multiple times, every time gets funnier.

It should be removed due to it being,
a. unused
b. confusing for new scripters

**Comment by ShaneBeee** [comment] 2020-03-04 04:27
Duplicate of #2769 

I know this isn't a direct duplicate but I feel the convo could be continued there.

I have yet to hear a single instance of anyone having issues with this file, and I talk to a LOT of people on skUnity's discord as well as Skript-Chat's discord.

**Comment by Jayderp** [comment] 2020-03-04 04:27
uncultured

**Closed by ShaneBeee** 2020-03-04 04:27 UTC
