### ISSUE TITLE
Right-click event is broken when you specify "with xxx"

### ISSUE THREAD

**Issue by iOshawott** [SkriptLang/Skript#1873] opened 2019-02-04 10:37 UTC
### Description

On rightclick event doesn't do what it needs to do when you specify item

### Steps to Reproduce

```
on rightclick with stick:
	if player's tool is stick named "&aPatyk":
		send "hejka" to player
command /patyk:
	trigger:
		add 1 stick named "&aPatyk" to player's inventory
command /sprawdzpatyka:
	trigger:
		if player's tool is stick named "&aPatyk":
			send "hejka" to player
```

### Expected Behavior

on rightclick should send "hejka" to player. It does when you type /sprawdzpatyka, but not on rightclick

It works when you change "on rightclick with stick" to "on rightclick" but on 2.3.2 it was possible to use first version

but anyway it doesn't works with off hand. I don't know how it should work with off hand but it doesn't. (maybe anyone can explain? I see nothing in docs about it but I would love to use it :-:)

### Errors / Screenshots

No errors

### Server Information
* **Server version/platform:**   paperclip-513
* **Skript version:**               2.3.3 (on 2.3.2 works perfectly!)

**Comment by iOshawott** [comment] 2019-02-04 15:39
@bensku both

**Comment by GermanMinerDE** [comment] 2019-02-05 12:31
Hey,

something else, which should be fixed with #1808 - but it isn't always.

**Skript:**
`on rightclick:
    send "Test"`

**Test**

- Wooden sword in off-tool, tool empty
- Clicking on an oak wooden door
- Message does not appear
- Message appears, when nothing is on off-tool

Skript 2.3.3
newest Paper 1.12.2

**Comment by bensku** [comment] 2019-02-08 19:38
@iOshawott Cannot reproduce. I suspect this was caused by #1871, since items were named.

**Comment by iOshawott** [comment] 2019-02-08 20:33
@bensku it works on 2.3.4! :) But how to use on rightclick event on off-hand? Still 
"if player's tool is ..." doesn't works with off-hand for me ; d

**Comment by TheBentoBox** [comment] 2019-02-08 21:33
If you want to check their offhand tool, use `if player's offhand tool is...`

**Comment by iOshawott** [comment] 2019-02-09 22:00
@TheBentoBox 
```
command /karta:
	trigger:
		add 1 paper named "&a&lZdrapka" with lore "&bLuty 2019" to player's inventory
on rightclick with paper:
	if player's offhand tool is paper named "&a&lZdrapka" with lore "&bLuty 2019":
		remove 1 paper named "&a&lZdrapka" with lore "&bLuty 2019" from player's inventory
		set {_v} to 1
		set {_f} to 2 or 1 or 3 or 9 or 7 or 4 or 8 or 5 or 6
	if player's tool is paper named "&a&lZdrapka" with lore "&bLuty 2019":
		remove 1 paper named "&a&lZdrapka" with lore "&bLuty 2019" from player's inventory
		set {_v} to 1
		set {_f} to 2 or 1 or 3 or 9 or 7 or 4 or 8 or 5 or 6
	if {_v} is 1:
		if {_f} is 1:
			add 1 paper of unbreaking 10 named "&b&lKarta Ferie" with lore "&91" to player's inventory
			send "&aZdrapałeś zdrapkę. To karta - &bFerie"
```
So... Why it doesn't work with off-hand? :v

**Comment by bensku** [comment] 2019-02-22 19:57
It seems that paper counts as usable item. Interesting...

**Closed** 2019-03-10 16:12 UTC
Labels: bug, completed
