### ISSUE TITLE
'remove %entity%' effect to call entity.remove()

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#977] opened 2017-11-17 13:52 UTC
Based on convo in #974.

Alternatively, the `delete` changer on an entity could be made to do this instead of needing a new effect; both options are just as good. I know this is already implemented for some entities where `kill`ing them calls their `remove()`, but it would be nice to have this option for all entities so you don't have to (for example) teleport living entities into the void to "remove" them without creating drops.

**Comment by TheLimeGlass** [comment] 2017-11-18 01:07
This used to work. It's a bug.

**Comment by Snow-Pyon** [comment] 2017-11-18 01:59
@TheLimeGlass that works, the issue is when you have an entity which is saved in a variable, it'll delete the variable instead of killing the entity.

And remove is already used by the change effect. That said, my suggestion is the following addition to the kill effect:
```
kill %entities% without drops #this would be matchedPattern #2
```
Of course using the Entity#remove method will do more than that but that's the first thing I came with.

**Comment by TheBentoBox** [comment] 2017-11-18 02:28
I could get behind that syntax: whatever works and makes sense is good by me. It's definitely a long-needed feature IMO.

**Comment by Pikachu920** [comment] 2017-11-18 05:21
I had the idea of having the syntax
```
%*classinfo% (from|[out] of) %objects%
```
and it would be used like this:
```
delete entity out of {_e}
```

**Comment by bensku** [comment] 2017-11-19 09:29
All good ideas. Maybe I could implement them all, too.

**Comment by Pikachu920** [comment] 2017-12-19 08:15
For now you can use this workaround: ![](https://cdn.discordapp.com/attachments/135877399391764480/392586595183624193/unknown.png)

**Comment by Wealthyturtle** [comment] 2019-12-15 03:28
Closing this in favor of #2240

**Closed by Wealthyturtle** 2019-12-15 03:28 UTC
Labels: enhancement, priority: low
