### ISSUE TITLE
Skript error on start-up

### ISSUE THREAD

**Issue by hostionou** [SkriptLang/Skript#2549] opened 2019-10-11 04:26 UTC
### Description
This happened when i was starting up my minecraft server. I was trying to use skript for the first time. (https://gist.github.com/hostionou/3a01d83f73e732ff155f41337b4d7128)

### Steps to Reproduce
Starting your server.

### Expected Behavior
Skript to start-up as it should.

### Errors / Screenshots
https://user-images.githubusercontent.com/56423591/66624333-8e88ba80-eba4-11e9-9f78-e867e58e40ec.PNG

**Comment by bluelhf** [comment] 2019-10-11 04:41
Looks like #2427 to me.

**Comment by Wealthyturtle** [comment] 2019-10-11 04:46
Duplicate of #2487. Thanks for posting, though

**Closed by Wealthyturtle** 2019-10-11 04:46 UTC
