### ISSUE TITLE
New 2.6 custom font does not works on title

### ISSUE THREAD

**Issue by Anarchick** [SkriptLang/Skript#4419] opened 2021-11-13 13:35 UTC
### Skript/Server Version

```
Skript 2.6
mc:  paper 1.17.1
```

### Bug Description

the new <font> chat parametter is not working on title.

### Expected Behavior

Replace font

### Steps to Reproduce

```hs
 # DOES NOT WORKS
send title "<font:alt>test" to player
send title formatted "<font:alt>test" to player

# WORKS
send "<font:alt>test" to player
send action bar "<font:alt>test" to player
/title @p title {"text":"test","font":"minecraft:alt"}
```

### Errors or Screenshots

```
Print LITERAL "<font:alt>test" on screen
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by TPGamesNL** [comment] 2021-11-14 10:51
Duplicate of https://github.com/SkriptLang/Skript/issues/3112

**Closed by TPGamesNL** 2021-11-14 10:51 UTC
