### ISSUE TITLE
just a litle issue causing lag spikes when a player joinning 

### ISSUE THREAD

**Issue by DevilishDante** [SkriptLang/Skript#723] opened 2017-07-12 15:27 UTC
hi i have a litle issue when i reload my sk and, i think he causing the lag spikes i've had when other player join on my server, just look

```
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:19:38] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[17:19:38] [Server thread/ERROR]: #!#! Used command: /sk reload TPCore
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[17:19:38] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[17:19:38] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[17:19:38] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[17:19:38] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[17:19:38] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[17:19:38] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! Stack trace:
[17:19:38] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[17:19:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:269)
[17:19:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:240)
[17:19:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:618)
[17:19:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:611)
[17:19:38] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[17:19:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:19:38] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[17:19:38] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:19:38] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:19:38] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[17:19:38] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! Version Information:
[17:19:38] [Server thread/ERROR]: #!#!   Skript: 2.2-dev28c
[17:19:38] [Server thread/ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[17:19:38] [Server thread/ERROR]: #!#!   Minecraft: 1.10.2
[17:19:38] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[17:19:38] [Server thread/ERROR]: #!#!   OS: Linux amd64 2.6.32-41-pve
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! Current node: null
[17:19:38] [Server thread/ERROR]: #!#! Current item: null
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! Thread: Server thread
[17:19:38] [Server thread/ERROR]: #!#! 
[17:19:38] [Server thread/ERROR]: #!#! End of Error.
[17:19:38] [Server thread/ERROR]: #!#! 
```

just here 
```
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[17:19:38] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
```

i'm not a pro but i found it strange ^^
and my skript make a latency when i type /sk reload all
but i try less multiverse and worldguard and i dont have lantency but i need them :/
thanks to read me, and good luck with your project :)

**Comment by DevilishDante** [comment] 2017-07-12 15:43
i'm tryied dev 29 and now i used dev28c

**Comment by JeepSmash** [comment] 2017-07-15 00:15
doing [ /sk reload all ] is probably not a good idea unless you only have less than 5 scripts.  The server (as far as gameplay is concerned) will essentially be slowed to a halt while skript is loading/parsing all of your scripts.  I have about 2 dozen running and that command would freeze my high end server for several minutes and cause disconnects.  Try reloading each script 1 by 1 to reduce the lag/latency that will be caused from issuing reloads.

The error above appears to me that skript had issues unloading scripts before trying to load them back again.  Again i would suggest trying 1 by 1 to see if a specific script is causing the issue or if its the reload command itself and if errors still persist maybe attempt /sk disable <script>  then /sk enable <script> to reload it that way

**Comment by bensku** [comment] 2017-07-16 11:27
I might be able to move parsing to one separate thread. It's not easy, but not as hard as using many threads at same moment would be.

**Comment by DevilishDante** [comment] 2017-07-16 14:31
hi, just i think multiverse or worldguard causing latency because whitout them ,i had no slowdown with my sk and more interesting without the conditions _'if player is in "worldname"'_ or _'if "%region at playet%" contains "regionname"'_ load with absolutely no latency, and good luck for solve all cause it's meticulous work :o

**Comment by TheBentoBox** [comment] 2017-07-16 23:32
@bensku moving script loading as a whole to a separate thread would be really incredible. As it stands, working with very large scripts is problematic on a live server since they freeze it up for multiple seconds constantly as you repeatedly reload them during iterations. Even though better script loading in general would be ideal, script loading being moved to its own thread would be a great QoL improvement.

**Comment by DevilishDante** [comment] 2017-07-17 03:22
@TheBentoBox  @bensku  hi, my skript "ModoCore" contain 1129 lines and he's reload instantly 
and he doesn't have world condition or région condition so maybe the large skript is not the cause?
maybe a skript with 1129 lines is not large? i don't know :c 
sorry for my poor english u.u

**Comment by bensku** [comment] 2017-07-19 09:02
Some scripts parse really fast, some... not so fast. Depends on patterns used.

**Comment by bensku** [comment] 2017-07-19 20:30
@TheBentoBox Working on it now. Right now causes numerous problems, but loads scripts - usually.

**Comment by TheBentoBox** [comment] 2017-07-22 23:04
Cheers @bensku. I'm sure some other devs in the community like Tuke would be open to helping with it or discussing it if need be, as I'm sure working on this mostly on your own can be overwhelming at times. Excited to see where this goes.

**Comment by TPGamesNL** [comment] 2021-03-26 18:38
Duplicate of https://github.com/SkriptLang/Skript/issues/884, fixed a long time ago

**Closed by TPGamesNL** 2021-03-26 18:38 UTC
Labels: enhancement, needs testing, priority: low
